### ISSUE TITLE
global name 'verifyssl' is not defined

### ISSUE THREAD

**Issue by justquick** [StackStorm/st2#1517]
when running 
`st2 run packs.install packs=ansible repo_url=https://github.com/StackStorm/st2contrib.git`

action output contains this error
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/python_action_wrapper.py", line 116, in <module>
    obj.run()
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/python_action_wrapper.py", line 61, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 23, in run
    abs_local_path = self._clone_repo(repo_url, branch=branch)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 40, in _clone_repo
    if not verifyssl:
NameError: global name 'verifyssl' is not defined
```
vagrant install
st2 0.9.1.18
Vagrant 1.7.2
VirtualBox 4.3.28

**Comment by Kami** [comment]
This has been fixed a while ago (#1450), but it looks like the fix hasn't been backported into the 0.9.x series yet.

I will make sure we backport the fix into 0.9.x ASAP. In the mean time, you can try it out using v0.10dev version where this should be fixed.

Sorry for the inconvenience and I will let you know once the fix has been backported.

**Comment by Kami** [comment]
@justquick Just wanted to let you know that v0.9.2 with this fix has been released.

You can install it on Ubuntu by using this script  - http://downloads.stackstorm.net/releases/st2/0.9.2/debs/st2_deploy.sh

**Comment by manasdk** [comment]
Closing as this is now fixed.
