### ISSUE TITLE
`ImportError: No module named db` when installing

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#1669]
When installing `st2_deploy.sh latest`, it fails with message:

```sh
...
==> chatops: Cloning into 'st2mistral'...
==> chatops: running develop
==> chatops: running egg_info
==> chatops: creating st2mistral.egg-info
==> chatops: writing pbr to st2mistral.egg-info/pbr.json
==> chatops: writing dependency_links to st2mistral.egg-info/dependency_links.txt
==> chatops: writing st2mistral.egg-info/PKG-INFO
==> chatops: writing top-level names to st2mistral.egg-info/top_level.txt
==> chatops: writing entry points to st2mistral.egg-info/entry_points.txt
==> chatops: [pbr] Processing SOURCES.txt
==> chatops: writing manifest file 'st2mistral.egg-info/SOURCES.txt'
==> chatops: [pbr] In git context, generating filelist from git
==> chatops: warning: no files found matching 'AUTHORS'
==> chatops: warning: no files found matching 'ChangeLog'
==> chatops: warning: no previously-included files found matching '.gitreview'
==> chatops: warning: no previously-included files matching '*.pyc' found anywhere in distribution
==> chatops: writing manifest file 'st2mistral.egg-info/SOURCES.txt'
==> chatops: running build_ext
==> chatops: Creating /opt/openstack/mistral/.venv/lib/python2.7/site-packages/st2mistral.egg-link (link to .)
==> chatops: Adding st2mistral 0.0.1.dev17 to easy-install.pth file
==> chatops:
==> chatops: Installed /etc/mistral/actions/st2mistral
==> chatops: Processing dependencies for st2mistral==0.0.1.dev17
==> chatops: Finished processing dependencies for st2mistral==0.0.1.dev17
==> chatops: Writing Mistral configuration file to /etc/mistral/mistral.conf...
==> chatops: Writing Mistral log configuration file to /etc/mistral/wf_trace_logging.conf...
==> chatops: Changing max connections for PostgreSQL...
==> chatops:  * Restarting PostgreSQL 9.3 database server
==> chatops:    ...done.
==> chatops: Setting up Mistral DB in PostgreSQL...
==> chatops: NOTICE:  database "mistral" does not exist, skipping
==> chatops: DROP DATABASE
==> chatops: NOTICE:  role "mistral" does not exist, skipping
==> chatops: DROP ROLE
==> chatops: CREATE ROLE
==> chatops: CREATE DATABASE
==> chatops: Creating and populating DB tables for Mistral...
==> chatops: Traceback (most recent call last):
==> chatops:   File "./tools/sync_db.py", line 17, in <module>
==> chatops:
==> chatops: from mistral.db.v2 import api as db_api
==> chatops:   File "/opt/openstack/mistral/mistral/db/v2/api.py", line 18, in <module>
==> chatops:
==> chatops: from oslo.db import api as db_api
==> chatops: ImportError
==> chatops: :
==> chatops: No module named db
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by armab** [comment]
Fixed by awesome @m4dcoder here: https://github.com/StackStorm/mistral/commit/44b223b98b8c1bcbbd1efb2d54ade993aacf5066

**Comment by Kami** [comment]
Yeah, this seems related to the oslo library namespace changes - https://github.com/StackStorm/st2/issues/1658

We need to make sure all of our dependencies are pinned and / or update all the code to use the latest version and replace "oslo." namespace with "oslo_".
