### ISSUE TITLE
Rules are not registered

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#1671]
#### Install `latest`
```
sudo ./st2_deploy.sh latest
# install hubot pack
st2 run packs.install packs=hubot register=all

st2 rule list
st2ctl reload --register-all
```

#### Result: 
```
Registering content...[flags = --register-all]
2015-06-29 23:39:11,253 INFO [-] Connecting to database "st2" @ "0.0.0.0:27017" as user "None".
2015-06-29 23:39:11,372 INFO [-] =========================================================
2015-06-29 23:39:11,373 INFO [-] ############## Registering sensors ######################
2015-06-29 23:39:11,374 INFO [-] =========================================================
2015-06-29 23:39:11,874 INFO [-] Registered 1 sensors.
2015-06-29 23:39:11,877 INFO [-] =========================================================
2015-06-29 23:39:11,878 INFO [-] ############## Registering actions ######################
2015-06-29 23:39:11,884 INFO [-] =========================================================
2015-06-29 23:39:15,451 INFO [-] Registered 58 actions.
2015-06-29 23:39:15,452 INFO [-] =========================================================
2015-06-29 23:39:15,452 INFO [-] ############## Registering rules ########################
2015-06-29 23:39:15,453 INFO [-] =========================================================
2015-06-29 23:39:15,474 ERROR [-] Failed registering rule from /opt/stackstorm/packs/hubot/rules/notify_hubot.yaml.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2reactor/bootstrap/rulesregistrar.py", line 105, in _register_rules_from_pack
    rule_db = RuleAPI.to_model(rule_api)
  File "/usr/lib/python2.7/dist-packages/st2common/models/api/rule.py", line 158, in to_model
    trigger_db = TriggerService.create_trigger_db_from_rule(rule)
  File "/usr/lib/python2.7/dist-packages/st2common/services/triggers.py", line 175, in create_trigger_db_from_rule
    'triggertype. Cannot create trigger: %s.' % (trigger_dict))
TriggerDoesNotExistException: A simple trigger should have been created when registering triggertype. Cannot create trigger: {'type': 'core.st2.generic.notifytr                  igger', 'parameters': {}, 'pack': 'core'}.
2015-06-29 23:39:15,477 INFO [-] Registered 0 rules.
2015-06-29 23:39:15,477 INFO [-] =========================================================
2015-06-29 23:39:15,477 INFO [-] ############## Registering aliases ######################
2015-06-29 23:39:15,477 INFO [-] =========================================================
2015-06-29 23:39:15,594 INFO [-] Registered 13 aliases.
2015-06-29 23:39:15,595 INFO [-] =========================================================
2015-06-29 23:39:15,596 INFO [-] ############## Registering policy types #################
2015-06-29 23:39:15,596 INFO [-] =========================================================
2015-06-29 23:39:15,623 INFO [-] Registered 2 policy types.
2015-06-29 23:39:15,625 INFO [-] =========================================================
2015-06-29 23:39:15,625 INFO [-] ############## Registering policies #####################
2015-06-29 23:39:15,626 INFO [-] =========================================================
2015-06-29 23:39:15,626 INFO [-] Registered 0 policies.
##### st2 components status #####
st2actionrunner PID: 18843
st2actionrunner PID: 18844
st2actionrunner PID: 18845
st2actionrunner PID: 18846
st2actionrunner PID: 18847
st2actionrunner PID: 18848
st2actionrunner PID: 18849
st2actionrunner PID: 18850
st2actionrunner PID: 18851
st2actionrunner PID: 18852
st2api PID: 18854
st2auth PID: 18853
st2sensorcontainer PID: 23859
st2rulesengine PID: 18858
mistral PID: 18865
mistral PID: 18907
mistral PID: 18914
st2web PID: 18871
st2resultstracker PID: 18856
st2notifier PID: 18857
```

#### for `st2_deploy.sh stable`:
```
st2 run packs.install packs=hubot
st2ctl reload --register-all
Registering content...[flags = --register-all]
2015-06-30 00:22:59,864 INFO [-] Connecting to database "st2" @ "0.0.0.0:27017" as user "None".
2015-06-30 00:22:59,968 INFO [-] =========================================================
2015-06-30 00:22:59,970 INFO [-] ############## Registering sensors ######################
2015-06-30 00:22:59,971 INFO [-] =========================================================
2015-06-30 00:23:00,356 INFO [-] Registered 1 sensors.
2015-06-30 00:23:00,357 INFO [-] =========================================================
2015-06-30 00:23:00,357 INFO [-] ############## Registering actions ######################
2015-06-30 00:23:00,358 INFO [-] =========================================================
2015-06-30 00:23:03,322 INFO [-] Registered 58 actions.
2015-06-30 00:23:03,324 INFO [-] =========================================================
2015-06-30 00:23:03,325 INFO [-] ############## Registering rules ########################
2015-06-30 00:23:03,325 INFO [-] =========================================================
2015-06-30 00:23:03,364 ERROR [-] Conflict while trying to save in DB.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2common/persistence/base.py", line 83, in add_or_update
    model_object = cls._get_impl().add_or_update(model_object)
  File "/usr/lib/python2.7/dist-packages/st2common/models/db/__init__.py", line 131, in add_or_update
    instance.save()
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 286, in save
    raise NotUniqueError(message % unicode(err))
NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error index: st2.rule_d_b.$name_1  dup key: { : "chatops.notify_hubot" })
2015-06-30 00:23:03,368 ERROR [-] Failed to create rule chatops.notify_hubot.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2reactor/bootstrap/rulesregistrar.py", line 136, in _register_rules_from_pack
    rule_db = Rule.add_or_update(rule_db)
  File "/usr/lib/python2.7/dist-packages/st2common/persistence/base.py", line 90, in add_or_update
    raise StackStormDBObjectConflictError(str(e), conflict_id)
StackStormDBObjectConflictError: Tried to save duplicate unique keys (E11000 duplicate key error index: st2.rule_d_b.$name_1  dup key: { : "chatops.notify_hubot" })
2015-06-30 00:23:03,370 INFO [-] Registered 2 rules.
2015-06-30 00:23:03,370 INFO [-] =========================================================
2015-06-30 00:23:03,370 INFO [-] ############## Registering aliases ######################
2015-06-30 00:23:03,371 INFO [-] =========================================================
2015-06-30 00:23:03,476 INFO [-] Registered 13 aliases.
2015-06-30 00:23:03,476 INFO [-] =========================================================
2015-06-30 00:23:03,477 INFO [-] ############## Registering policy types #################
2015-06-30 00:23:03,478 INFO [-] =========================================================
2015-06-30 00:23:03,503 INFO [-] Registered 2 policy types.
2015-06-30 00:23:03,503 INFO [-] =========================================================
2015-06-30 00:23:03,503 INFO [-] ############## Registering policies #####################
2015-06-30 00:23:03,504 INFO [-] =========================================================
2015-06-30 00:23:03,504 INFO [-] Registered 0 policies.
##### st2 components status #####
st2actionrunner PID: 19408
st2actionrunner PID: 19409
st2actionrunner PID: 19410
st2actionrunner PID: 19411
st2actionrunner PID: 19412
st2actionrunner PID: 19413
st2actionrunner PID: 19414
st2actionrunner PID: 19415
st2actionrunner PID: 19416
st2actionrunner PID: 19417
st2api PID: 19419
st2auth PID: 19418
st2sensorcontainer PID: 20655
st2rulesengine PID: 19423
mistral PID: 19430
st2web PID: 19435
st2resultstracker PID: 19421
st2notifier PID: 19422
```
-----

Used this Vagrant to reproduce (hubot rule was absent):
https://github.com/armab/showcase-ansible-chatops

**Comment by armab** [comment]
Could be related to https://github.com/StackStorm/st2/issues/1669, pip dependency problems we experienced today.

**Comment by DoriftoShoes** [comment]
I get the duplicate error but I the rule gets registered for me properly. (This is on stable).

```
vagrant@stabletest:~$ st2 run packs.install packs=hubot
...............
id: 5591ff1535da2f49600e1c27
action.ref: packs.install
status: succeeded
start_timestamp: 2015-06-30T02:29:41.047899Z
end_timestamp: 2015-06-30T02:30:09.509719Z
+--------------------------+-----------+--------------------------+-------------------------+-------------------------------+
| id                       | status    | task                     | action                  | start_timestamp               |
+--------------------------+-----------+--------------------------+-------------------------+-------------------------------+
| 5591ff1535da2f4958824468 | succeeded | download                 | packs.download          | Tue, 30 Jun 2015 02:29:41 UTC |
| 5591ff2335da2f495882446a | succeeded | virtualenv_prerun        | packs.virtualenv_prerun | Tue, 30 Jun 2015 02:29:55 UTC |
| 5591ff2435da2f495882446c | succeeded | setup_virtualenv         | packs.setup_virtualenv  | Tue, 30 Jun 2015 02:29:56 UTC |
| 5591ff2d35da2f495882446e | succeeded | reload                   | packs.load              | Tue, 30 Jun 2015 02:30:05 UTC |
| 5591ff2f35da2f4958824470 | succeeded | restart-sensor-container | packs.restart_component | Tue, 30 Jun 2015 02:30:07 UTC |
+--------------------------+-----------+--------------------------+-------------------------+-------------------------------+
vagrant@stabletest:~$ st2ctl reload --register-all
Registering content...[flags = --register-all]
2015-06-30 02:30:15,511 INFO [-] Connecting to database "st2" @ "0.0.0.0:27017" as user "None".
2015-06-30 02:30:15,559 INFO [-] =========================================================
2015-06-30 02:30:15,559 INFO [-] ############## Registering sensors ######################
2015-06-30 02:30:15,560 INFO [-] =========================================================
2015-06-30 02:30:15,691 INFO [-] Registered 1 sensors.
2015-06-30 02:30:15,692 INFO [-] =========================================================
2015-06-30 02:30:15,695 INFO [-] ############## Registering actions ######################
2015-06-30 02:30:15,695 INFO [-] =========================================================
2015-06-30 02:30:16,403 INFO [-] Registered 43 actions.
2015-06-30 02:30:16,404 INFO [-] =========================================================
2015-06-30 02:30:16,404 INFO [-] ############## Registering rules ########################
2015-06-30 02:30:16,405 INFO [-] =========================================================
2015-06-30 02:30:16,422 ERROR [-] Conflict while trying to save in DB.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2common/persistence/base.py", line 83, in add_or_update
    model_object = cls._get_impl().add_or_update(model_object)
  File "/usr/lib/python2.7/dist-packages/st2common/models/db/__init__.py", line 131, in add_or_update
    instance.save()
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 286, in save
    raise NotUniqueError(message % unicode(err))
NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error index: st2.rule_d_b.$name_1  dup key: { : "chatops.notify_hubot" })
2015-06-30 02:30:16,428 ERROR [-] Failed to create rule chatops.notify_hubot.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2reactor/bootstrap/rulesregistrar.py", line 136, in _register_rules_from_pack
    rule_db = Rule.add_or_update(rule_db)
  File "/usr/lib/python2.7/dist-packages/st2common/persistence/base.py", line 90, in add_or_update
    raise StackStormDBObjectConflictError(str(e), conflict_id)
StackStormDBObjectConflictError: Tried to save duplicate unique keys (E11000 duplicate key error index: st2.rule_d_b.$name_1  dup key: { : "chatops.notify_hubot" })
2015-06-30 02:30:16,429 INFO [-] Registered 2 rules.
2015-06-30 02:30:16,430 INFO [-] =========================================================
2015-06-30 02:30:16,430 INFO [-] ############## Registering aliases ######################
2015-06-30 02:30:16,430 INFO [-] =========================================================
2015-06-30 02:30:16,434 INFO [-] ActionAlias /opt/stackstorm/packs/hubot/aliases/branch.yaml not found. Creating new one.
2015-06-30 02:30:16,438 INFO [-] ActionAlias /opt/stackstorm/packs/hubot/aliases/deploy.yaml not found. Creating new one.
2015-06-30 02:30:16,445 INFO [-] ActionAlias /opt/stackstorm/packs/hubot/aliases/restart.yaml not found. Creating new one.
2015-06-30 02:30:16,449 INFO [-] ActionAlias /opt/stackstorm/packs/packs/aliases/pack_deploy.yaml not found. Creating new one.
2015-06-30 02:30:16,453 INFO [-] ActionAlias /opt/stackstorm/packs/packs/aliases/pack_info.yaml not found. Creating new one.
2015-06-30 02:30:16,454 INFO [-] Registered 5 aliases.
2015-06-30 02:30:16,455 INFO [-] =========================================================
2015-06-30 02:30:16,455 INFO [-] ############## Registering policy types #################
2015-06-30 02:30:16,456 INFO [-] =========================================================
2015-06-30 02:30:16,465 INFO [-] Registered 2 policy types.
2015-06-30 02:30:16,465 INFO [-] =========================================================
2015-06-30 02:30:16,466 INFO [-] ############## Registering policies #####################
2015-06-30 02:30:16,466 INFO [-] =========================================================
2015-06-30 02:30:16,467 INFO [-] Registered 0 policies.
##### st2 components status #####
st2actionrunner PID: 18773
st2actionrunner PID: 18774
st2actionrunner PID: 18775
st2actionrunner PID: 18776
st2actionrunner PID: 18777
st2actionrunner PID: 18778
st2actionrunner PID: 18779
st2actionrunner PID: 18780
st2actionrunner PID: 18781
st2actionrunner PID: 18782
st2api PID: 18784
st2auth PID: 18783
st2sensorcontainer PID: 19317
st2rulesengine PID: 18788
mistral PID: 18795
st2web PID: 18799
st2resultstracker PID: 18786
st2notifier PID: 18787
vagrant@stabletest:~$ st2 rule list
+---------------------------+------+----------------------+---------------------------------------------+
| ref                       | pack | name                 | description                                 |
+---------------------------+------+----------------------+---------------------------------------------+
| core.chatops.notify_hubot | core | chatops.notify_hubot | Notification rule to send messages to Hubot |
+---------------------------+------+----------------------+---------------------------------------------+
vagrant@stabletest:~$ dpkg -l | grep st2
ii  python-st2client                     0.11.3.10-1                      all          CLI and python client library for the StackStorm (st2) autom
ii  st2actions                           0.11.3-10                        amd64        ST2 ActionRunner
ii  st2api                               0.11.3-10                        amd64        ST2 API
ii  st2auth                              0.11.3-10                        amd64        ST2 Authentication
ii  st2common                            0.11.3-10                        amd64        ST2 Common
ii  st2debug                             0.11.3-10                        amd64        StackStorm Debug tool
ii  st2reactor                           0.11.3-10                        amd64        ST2 Reactor
vagrant@stabletest:~$ st2 --version
st2 ('0.11.3.10',)
```

**Comment by armab** [comment]
Confirming that `latest` is fixed https://github.com/StackStorm/st2/pull/1672
Thanks @manasdk!

**Comment by armab** [comment]
For `stable` after installing `hubot` pack, the rule `chatops.notify_hubot` is just not triggered (however it exist).

Also note `trigger.channel=test2` here: http://i.imgur.com/vS8jgIi.png
Have no idea why `test2` is there, but this is how it looks after fresh st2 stable install && hubot pack install.

-----

For `latest` it works as expected, `hubot` instead of `test2` and the rule is triggered.

**Comment by Kami** [comment]
@armab It's hard to say without seeing the logs - you should check (and gist) the rules engine log to see what is going on.

**Comment by armab** [comment]
Yeah, found it :rabbit: 

```
# do fresh install for stable

st2 rule list
No matching items found

st2ct reload --register-all
# suddenly, 1 rule found

# st2 rule list
+---------------------------+------+----------------------+------------------------------------------+
| ref                       | pack | name                 | description                              |
+---------------------------+------+----------------------+------------------------------------------+
| core.chatops.notify_hubot | core | chatops.notify_hubot | Notification rule to send messages to    |
|                           |      |                      | Hubot                                    |
+---------------------------+------+----------------------+------------------------------------------+
```

Here is that `notify_hubot` rule sitting in core: https://github.com/StackStorm/st2/blob/v0.11.2/contrib/core/rules/notify_hubot.yaml which produces dup errors in DB, when installing real `hubot` integration pack.

I'm pretty sure that tried `stable` before with `hubot` pack install and hadn't DB errors. Most probably can come from those [upstream pip version changes](https://github.com/StackStorm/st2/issues/1671#issuecomment-116909249).

---

Do the rest what you think is better here. Seems https://github.com/StackStorm/st2/blob/v0.11.2/contrib/core/rules/notify_hubot.yaml is obsolete.

**Comment by Kami** [comment]
@armab I assume you are talking about installing it using st2_deploy.

If so, not registering rules by default is a feature. Or at least it used to be. If we now only ship working hubot rule by default (we used to ship some other rules which we didn't want to register by default since they required modifications), then I do think we should also register rules (or at least just this rule) by default inside st2_deploy.

**Comment by manasdk** [comment]
@armab We will remove https://github.com/StackStorm/st2/blob/v0.11.3/contrib/core/rules/notify_hubot.yaml - that got in by mistake and release v0.11.4. 

To unblock locally you can drop that rule and retry.

**Comment by manasdk** [comment]
We have v0.11.4 with the duplicate rule removed. That is the new latest stable and issue should be fixed.

**Comment by manasdk** [comment]
Also, with the rule removed you will still need to make sure that the old DB is dropped to avoid having an old index on rule.name around which imposes a uniqueness constraint.

**Comment by armab** [comment]
So this should be fixed, thanks @manasdk.

Yeah, I don't have big problems here, since I figured out what's the reason and could remove that rule.

What I care about is chatops experience with `hubot` pack as it described in Ansible blog post and @jfryman's blog post, when people trying to play with ChatOps.
