### ISSUE TITLE
rule create without "enabled" returns 500

### ISSUE THREAD

**Issue by dzimine** [StackStorm/st2#1908]
If it's error, It must be client error, 400. 
Or may be a sane default == rule is enabled.

```
---
  name: sample.action-runners-rule
  pack: examples
  description: Sample rule that dogfoods st2.
  trigger: 
    type: sensu.event_handler
  criteria: 
    trigger.check.name: 
      pattern: "st2actionrunner_check"
      type: "equals"
    trigger.check.output: 
      pattern: "CheckProcs CRITICAL*"
      type: "matchregex"
  action: 
    ref: "core.local"
    parameters: 
      cmd: "echo \"{{trigger}}\" >> /tmp/sensu-sample.out"
```

```
2015-08-28 06:35:01,441 140344202642928 INFO log [-] 139e9d52-8936-4a53-9c60-1516156e6add -  POST /v1/rules with filters={} (remote_addr='127.0.0.1',method='POST',filters={},request_id='139e9d52-8936-4a53-9c60-1516156e6add',path='/v1/rules')
2015-08-28 06:35:01,442 140344202642928 AUDIT log [-] Token provided in headers
2015-08-28 06:35:01,443 140344202642928 AUDIT log [-] Token with id "55e00115e33b0719c9e2d08d" is validated.
2015-08-28 06:35:01,450 140344202642928 ERROR log [-] API call failed: 'RuleAPI' object has no attribute 'enabled'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 625, in __call__
    self.invoke_controller(controller, args, kwargs, state)
  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 531, in invoke_controller
    result = controller(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/st2common/models/api/base.py", line 176, in callfunction
    result = f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/rules.py", line 65, in post
    rule_db = RuleAPI.to_model(rule)
  File "/usr/lib/python2.7/dist-packages/st2common/models/api/rule.py", line 178, in to_model
    enabled = rule.enabled
AttributeError: 'RuleAPI' object has no attribute 'enabled' (_exception_data={},_exception_class='AttributeError',_exception_message="'RuleAPI' object has no attribute 'enabled'")
2015-08-28 06:35:01,470 140344202642928 ERROR log [-] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 625, in __call__
    self.invoke_controller(controller, args, kwargs, state)
  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 531, in invoke_controller
    result = controller(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/st2common/models/api/base.py", line 176, in callfunction
    result = f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/rules.py", line 65, in post
    rule_db = RuleAPI.to_model(rule)
  File "/usr/lib/python2.7/dist-packages/st2common/models/api/rule.py", line 178, in to_model
    enabled = rule.enabled
AttributeError: 'RuleAPI' object has no attribute 'enabled'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 625, in __call__
    self.invoke_controller(controller, args, kwargs, state)
  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 531, in invoke_controller
    result = controller(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/st2common/models/api/base.py", line 176, in callfunction
    result = f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/rules.py", line 65, in post
    rule_db = RuleAPI.to_model(rule)
  File "/usr/lib/python2.7/dist-packages/st2common/models/api/rule.py", line 178, in to_model
    enabled = rule.enabled
AttributeError: 'RuleAPI' object has no attribute 'enabled'
2015-08-28 06:35:01,471 140344202642928 INFO log [-] 139e9d52-8936-4a53-9c60-1516156e6add - POST /v1/rules result={
    "faultstring": "Internal Server Error"
} (result='{\n    "faultstring": "Internal Server Error"\n}',request_id='139e9d52-8936-4a53-9c60-1516156e6add',status_code='500 Internal Server Error',remote_addr='127.0.0.1',path='/v1/rules',method='POST')
```

**Comment by manasdk** [comment]
Fair enough should be a client error.

**Comment by Kami** [comment]
I thought this was fixed before, but it doesn't looks like it was fixed entirely.

Will push a fix.
