### ISSUE TITLE
Problems with mistral sync_db.py

### ISSUE THREAD

**Issue by johandahlberg** [StackStorm/st2#2062]
I realize that this might not be the correct place to report this, but I don't know what is so I though I'd report it here and then perhaps someone can point me to a better place.

We are using https://github.com/StackStorm/ansible-st2 to install StackStorm. This uses `/opt/openstack/mistral/tools/sync_db.py` to setup the database however in the current version (mistral 0.13) this is broken. It will give the following trace:

```
2015-10-08 14:22:29.091 18997 CRITICAL Mistral [-] OSError: [Errno 2] No such file or directory: '/opt/openstack/mistral/.venv/local/lib/python2.7/site-packages/mistral/../resources/actions'
2015-10-08 14:22:29.091 18997 TRACE Mistral Traceback (most recent call last):
2015-10-08 14:22:29.091 18997 TRACE Mistral   File "./tools/sync_db.py", line 44, in <module>
2015-10-08 14:22:29.091 18997 TRACE Mistral     main()
2015-10-08 14:22:29.091 18997 TRACE Mistral   File "./tools/sync_db.py", line 39, in main
2015-10-08 14:22:29.091 18997 TRACE Mistral     action_manager.sync_db()
2015-10-08 14:22:29.091 18997 TRACE Mistral   File "/opt/openstack/mistral/.venv/local/lib/python2.7/site-packages/mistral/services/action_manager.py", line 80, in sync_db
2015-10-08 14:22:29.091 18997 TRACE Mistral     register_standard_actions()
2015-10-08 14:22:29.091 18997 TRACE Mistral   File "/opt/openstack/mistral/.venv/local/lib/python2.7/site-packages/mistral/services/action_manager.py", line 41, in register_standard_actions
2015-10-08 14:22:29.091 18997 TRACE Mistral     action_paths = utils.get_file_list(ACTIONS_PATH)
2015-10-08 14:22:29.091 18997 TRACE Mistral   File "/opt/openstack/mistral/.venv/local/lib/python2.7/site-packages/mistral/utils/__init__.py", line 148, in get_file_list
2015-10-08 14:22:29.091 18997 TRACE Mistral     return [path.join(base_path, f) for f in os.listdir(base_path)
2015-10-08 14:22:29.091 18997 TRACE Mistral OSError: [Errno 2] No such file or directory: '/opt/openstack/mistral/.venv/local/lib/python2.7/site-packages/mistral/../resources/actions'
2015-10-08 14:22:29.091 18997 TRACE Mistral 
```

To me it appears that the culprit is the following snippet in `action_manager.py`:

```
ACTIONS_PATH = '../resources/actions'
_ACTION_CTX_PARAM = 'action_context'


# TODO(rakhmerov): It's confusing because we have std.xxx actions and actions
# TODO(rakhmerov): under '../resources/actions' that we also call standard.
def register_standard_actions():
    action_paths = utils.get_file_list(ACTIONS_PATH)

    for action_path in action_paths:
        action_definition = open(action_path).read()
        actions.update_actions(action_definition, scope='public')
```

It would be great if this could be resolved.

**Comment by armab** [comment]
@johandahlberg  We have [mistral](https://github.com/StackStorm/mistral) repo, but it's totally OK to place it here.

First run of `sync_db.py` https://github.com/StackStorm/ansible-st2/blob/master/roles/mistral/tasks/sync.yml#L2 during ansible provision always works for me (tried in Vagrant and AWS, Ubuntu 14 LTS).
[Same in CI](https://circleci.com/gh/StackStorm/ansible-st2/17): search for `mistral | Sync database`.

Can't reproduce it on clean machine with default settings, something custom/specific in your config maybe?

Running it manually second time I get errors about duplicated DB entries (worth handling/fixing I think): 
```py
# root@ip-172-30-0-206:/opt/openstack/mistral# /opt/openstack/mistral/.venv/bin/python ./tools/sync_db.py --config-file /etc/mistral/mistral.conf

2015-10-09 11:52:21.025 25278 CRITICAL Mistral [-] DBDuplicateEntryException: Duplicate entry for WorkflowDefinition: ['definitions_v2_name_project_id']
2015-10-09 11:52:21.025 25278 ERROR Mistral Traceback (most recent call last):
2015-10-09 11:52:21.025 25278 ERROR Mistral   File "./tools/sync_db.py", line 44, in <module>
2015-10-09 11:52:21.025 25278 ERROR Mistral     main()
2015-10-09 11:52:21.025 25278 ERROR Mistral   File "./tools/sync_db.py", line 40, in main
2015-10-09 11:52:21.025 25278 ERROR Mistral     workflows.sync_db()
2015-10-09 11:52:21.025 25278 ERROR Mistral   File "/opt/openstack/mistral/.venv/local/lib/python2.7/site-packages/mistral/services/workflows.py", line 32, in sync_db
2015-10-09 11:52:21.025 25278 ERROR Mistral     register_standard_workflows()
2015-10-09 11:52:21.025 25278 ERROR Mistral   File "/opt/openstack/mistral/.venv/local/lib/python2.7/site-packages/mistral/services/workflows.py", line 28, in register_standard_workflows
2015-10-09 11:52:21.025 25278 ERROR Mistral     create_workflows(workflow_definition, scope='public')
2015-10-09 11:52:21.025 25278 ERROR Mistral   File "/opt/openstack/mistral/.venv/local/lib/python2.7/site-packages/mistral/services/workflows.py", line 42, in create_workflows
2015-10-09 11:52:21.025 25278 ERROR Mistral     db_wfs.append(_create_workflow(wf_spec, definition, scope))
2015-10-09 11:52:21.025 25278 ERROR Mistral   File "/opt/openstack/mistral/.venv/local/lib/python2.7/site-packages/mistral/services/workflows.py", line 77, in _create_workflow
2015-10-09 11:52:21.025 25278 ERROR Mistral     _get_workflow_values(wf_spec, definition, scope)
2015-10-09 11:52:21.025 25278 ERROR Mistral   File "/opt/openstack/mistral/.venv/local/lib/python2.7/site-packages/mistral/db/v2/api.py", line 133, in create_workflow_definition
2015-10-09 11:52:21.025 25278 ERROR Mistral     return IMPL.create_workflow_definition(values)
2015-10-09 11:52:21.025 25278 ERROR Mistral   File "/opt/openstack/mistral/.venv/local/lib/python2.7/site-packages/mistral/db/sqlalchemy/base.py", line 91, in _within_session
2015-10-09 11:52:21.025 25278 ERROR Mistral     result = func(*args, **kw)
2015-10-09 11:52:21.025 25278 ERROR Mistral   File "/opt/openstack/mistral/.venv/local/lib/python2.7/site-packages/mistral/db/v2/sqlalchemy/api.py", line 295, in create_workflow_definition
2015-10-09 11:52:21.025 25278 ERROR Mistral     "Duplicate entry for WorkflowDefinition: %s" % e.columns
2015-10-09 11:52:21.025 25278 ERROR Mistral DBDuplicateEntryException: Duplicate entry for WorkflowDefinition: ['definitions_v2_name_project_id']
2015-10-09 11:52:21.025 25278 ERROR Mistral
```

@m4dcoder is Mistral rockstar, with his expertise for sure will suggest something.

**Comment by Kami** [comment]
@armab So did you guys figure it out? If so, what was the issue?

**Comment by armab** [comment]
Not really related to mistral codebase,
just variable collisions in `ansible-st2` repo, when wrong version of mistral was picked when using it with own custom roles.

![](http://i.imgur.com/ijmQLex.png)

Thanks @johandahlberg for report, I've changed it in https://github.com/StackStorm/ansible-st2/pull/30 to prevent this.

**Comment by armab** [comment]
Still errors about duplicated DB entries when running `sync_db.py` several times I think should be better handled.

**Comment by m4dcoder** [comment]
You guys are right. The sync DB script should be made idempotent. We'll fix it.

**Comment by armab** [comment]
@m4dcoder thanks!
I'm 100% sure it worked before with MySQL, appeared after moving to PostgreSQL as a backend.
