### ISSUE TITLE
Special characters in object keys

### ISSUE THREAD

**Issue by enykeev** [StackStorm/st2#2198]
Trying to run an action with `type:object` parameter with the key containing `.` like
```
{
  "a.b": "c"
}
```
returns 500 and creates a record in logs:
```
2015-11-11 23:55:43,183 ERROR [-] Unable to execute action. Unexpected error encountered.
Traceback (most recent call last):
  File "/mnt/st2/st2api/st2api/controllers/v1/actionexecutions.py", line 119, in _handle_schedule_execution
    return self._schedule_execution(liveaction=liveaction)
  File "/mnt/st2/st2api/st2api/controllers/v1/actionexecutions.py", line 149, in _schedule_execution
    _, actionexecutiondb = action_service.request(liveactiondb)
  File "/mnt/st2/st2common/st2common/services/action.py", line 98, in request
    liveaction = LiveAction.add_or_update(liveaction, publish=False)
  File "/mnt/st2/st2common/st2common/persistence/base.py", line 155, in add_or_update
    model_object = cls._get_impl().add_or_update(model_object)
  File "/mnt/st2/st2common/st2common/models/db/__init__.py", line 174, in add_or_update
    instance.save()
  File "/mnt/st2/virtualenv/local/lib/python2.7/site-packages/mongoengine/document.py", line 224, in save
    self.validate(clean=clean)
  File "/mnt/st2/virtualenv/local/lib/python2.7/site-packages/mongoengine/base/document.py", line 323, in validate
    raise ValidationError(message, errors=errors)
ValidationError: ValidationError (LiveActionDB:None) (Invalid dictionary key name - keys may not contain "." or "$" characters: ['parameters'])
2015-11-11 23:55:43,192 DEBUG [-] API call failed: None (exception_message='ValidationError (LiveActionDB:None) (Invalid dictionary key name - keys may not contain "." or "$" characters: [\'parameters\'])',exception_data={'comment': None, '_headers': None, 'conditional_response': False, 'detail': 'ValidationError (LiveActionDB:None) (Invalid dictionary key name - keys may not contain "." or "$" characters: [\'parameters\'])', '_app_iter': [''], '_status': '500 Internal Server Error', '_headerlist': [('Content-Type', 'text/html; charset=UTF-8'), ('Content-Length', '0')]},exception_class='HTTPInternalServerError')
2015-11-11 23:55:43,193 INFO [-] 2e24e698-6aa7-40d6-8122-b598b978bb44 - POST /v1/executions (remote_addr='172.168.60.1',method='POST',status_code='500 Internal Server Error',request_id='2e24e698-6aa7-40d6-8122-b598b978bb44',path='/v1/executions')
172.168.60.1 - - [11/Nov/2015 23:55:43] "POST /v1/executions HTTP/1.1" 500 646 0.021786
```

As much as I would like to just say "there's the list of characters you can't use in your object keys", we have a `core.remote` action which keys do indeed contain dots.

**Comment by manasdk** [comment]
I thought we escapes these keys before storing in DB. Will need to check.

**Comment by manasdk** [comment]
> As much as I would like to just say "there's the list of characters you can't use in your object keys", we have a core.remote action which keys do indeed contain dots.

```
$ st2 run core.remote -h

Action to execute arbitrary linux command remotely.

Required Parameters:
    cmd
        Arbitrary Linux command to be executed on the remote host(s).
        Type: string

    hosts
        A comma delimited string of a list of hosts where the remote command
        will be executed.
        Type: string

Optional Parameters:
    cwd
        Working directory where the script will be executed in
        Type: string
        Default: /tmp

    env
        Environment variables which will be available to the command(e.g.
        key1=val1,key2=val2)
        Type: object

    kwarg_op
        Operator to use in front of keyword args i.e. "--" or "-".
        Type: string
        Default: --

    password
        Password used to log in. If not provided, private key from the config
        file is used.
        Type: string

    port
        SSH port. Note: This parameter is used only in ParamikoSSHRunner.
        Type: integer
        Default: 22

    private_key
        Private key material to log in. Note: This needs to be actual private
        key data and NOT path.
        Type: string

    timeout
        Action timeout in seconds. Action will get killed if it doesn't finish
        in timeout seconds.
        Type: integer
        Default: 60

    username
        Username used to log-in. If not provided, default username from config
        is used.
        Type: string
```

Lets not support `.`
