### ISSUE TITLE
[ansible] using inventory-file (-) as alias parameter breaks parser 

### ISSUE THREAD

**Issue by vikrantpogula** [StackStorm/st2#2280]
Stack trace (/var/log/st2/st2api.log)

```
API call failed: bad character in group name u'inventory-file'#012Traceback (most recent call last):#012  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 631, in __call__#012    self.invoke_controller(controller, args, kwargs, state)#012  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 531, in invoke_controller#012    result = controller(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/st2common/models/api/base.py", line 230, in callfunction#012    result = f(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/aliasexecution.py", line 78, in post#012    param_stream=command)#012  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/aliasexecution.py", line 123, in _extract_parameters#012    return parser.get_extracted_param_value()#012  File "/usr/lib/python2.7/dist-packages/st2common/models/utils/action_alias_utils.py", line 80, in get_extracted_param_value#012    matched_stream = re.match(reg, self._param_stream, re.DOTALL)#012  File "/usr/lib/python2.7/re.py", line 137, in match#012    return _compile(pattern, flags).match(string)#012  File "/usr/lib/python2.7/re.py", line 244, in _compile#012    raise error, v # invalid expression#012error: bad character in group name u'inventory-file'
2015-12-10T01:03:34.362035+00:00 localhost st2api[4932]: ERROR 140361395123536 [-] Traceback (most recent call last):#012  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 631, in __call__#012    self.invoke_controller(controller, args, kwargs, state)#012  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 531, in invoke_controller#012    result = controller(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/st2common/models/api/base.py", line 230, in callfunction#012    result = f(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/aliasexecution.py", line 78, in post#012    param_stream=command)#012  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/aliasexecution.py", line 123, in _extract_parameters#012    return parser.get_extracted_param_value()#012  File "/usr/lib/python2.7/dist-packages/st2common/models/utils/action_alias_utils.py", line 80, in get_extracted_param_value#012    matched_stream = re.match(reg, self._param_stream, re.DOTALL)#012  File "/usr/lib/python2.7/re.py", line 137, in match#012    return _compile(pattern, flags).match(string)#012  File "/usr/lib/python2.7/re.py", line 244, in _compile#012    raise error, v # invalid expression#012error: bad character in group name u'inventory-file'#012Traceback (most recent call last):#012  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 631, in __call__#012    self.invoke_controller(controller, args, kwargs, state)#012  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 531, in invoke_controller#012    result = controller(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/st2common/models/api/base.py", line 230, in callfunction#012    result = f(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/aliasexecution.py", line 78, in post#012    param_stream=command)#012  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/aliasexecution.py", line 123, in _extract_parameters#012    return parser.get_extracted_param_value()#012
```

**Comment by Kami** [comment]
Thanks for the report.

This does indeed look like a st2 (st2api) issue. In any case, we will look into it ASAP :)

**Comment by Kami** [comment]
@emedvedev It looks like we don't escape the user input and `-` is considered as a special character.

I was thinking about this a while back when we were making ChatOps changes - I think it would be a good idea and a good default behavior to escape user supplied regex string by default. If not we should at least be very explicit about the escaping in the documentation (with examples) and also throw a more-friendly exception on this issue.

**Comment by emedvedev** [comment]
@Kami: It's not escaping, it's named grouping.

We use parameter-to-regex transformation, casting every parameter to a named group in the regex, and named groups in Python are restrictive, allowing [a-zA-z_] only.
```
>>> import re
>>> re.compile("(?P<a-a>)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 244, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character in group name 'aa-a'
```
It's sensible, although it's different now in Python 3.

Here's the deal: in our own spec we don't allow `-` in parameter names (if not this, `-` in parameters creates all sorts of mess in Python), but our Ansible pack doesn't follow it. It's really the pack that should be fixed, not the parser, and this issue has been raised before. Maybe the time has come? :stuck_out_tongue:

@vikrantpogula A couple days might be required before we solve this, and the fastest way for you to unblock will be digging into the Ansible pack and replacing `-` in parameters with underscores. I know this is not ideal, but it's the best we can do right now. :heart:

**Comment by emedvedev** [comment]
@vikrantpogula reinstall the Ansible pack, but specify the `ansible-underscores`branch instead of `master`. Then use underscores in your parameters. Should work. Let me know how it goes :)

**Comment by armab** [comment]
Resolved by @emedvedev  https://github.com/StackStorm/st2contrib/issues/340

Ansible now uses underscores only in action param names.
