### ISSUE TITLE
Sensor logging is screwed up on unhandled exceptions

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#2289]
I haven't played around much with sensors in v1.1.0, got around to it in v1.2.0, and here's what I get in the logs when some unhandled exception happens in the sensor:

```
2015-12-11T18:49:31.719378+00:00 st2 st2sensorcontainer: Traceback (most recent call last):
2015-12-11T18:49:31.719657+00:00 st2 st2sensorcontainer: File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
2015-12-11T18:49:31.719855+00:00 st2 st2sensorcontainer: msg = self.format(record)
2015-12-11T18:49:31.720036+00:00 st2 st2sensorcontainer: File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
2015-12-11T18:49:31.720249+00:00 st2 st2sensorcontainer: return fmt.format(record)
2015-12-11T18:49:31.720441+00:00 st2 st2sensorcontainer: File "/usr/lib/python2.7/site-packages/st2common/logging/formatters.py", line 180, in format
2015-12-11T18:49:31.720642+00:00 st2 st2sensorcontainer: msg = super(ConsoleLogFormatter, self).format(record)
2015-12-11T18:49:31.720828+00:00 st2 st2sensorcontainer: File "/usr/lib64/python2.7/logging/__init__.py", line 464, in format
2015-12-11T18:49:31.721011+00:00 st2 st2sensorcontainer: record.message = record.getMessage()
2015-12-11T18:49:31.721199+00:00 st2 st2sensorcontainer: File "/usr/lib64/python2.7/logging/__init__.py", line 328, in getMessage
2015-12-11T18:49:31.721478+00:00 st2 st2sensorcontainer: msg = msg % self.args
2015-12-11T18:49:31.721676+00:00 st2 st2sensorcontainer: ValueError: incomplete format
2015-12-11T18:49:31.721883+00:00 st2 st2sensorcontainer: Logged from file log.py, line 69
2015-12-11T18:49:31.722133+00:00 st2 st2sensorcontainer: Traceback (most recent call last):
2015-12-11T18:49:31.722370+00:00 st2 st2sensorcontainer: File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
2015-12-11T18:49:31.722568+00:00 st2 st2sensorcontainer: msg = self.format(record)
2015-12-11T18:49:31.722767+00:00 st2 st2sensorcontainer: File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
2015-12-11T18:49:31.722967+00:00 st2 st2sensorcontainer: return fmt.format(record)
2015-12-11T18:49:31.723171+00:00 st2 st2sensorcontainer: File "/usr/lib/python2.7/site-packages/st2common/logging/formatters.py", line 180, in format
2015-12-11T18:49:31.723339+00:00 st2 st2sensorcontainer: msg = super(ConsoleLogFormatter, self).format(record)
2015-12-11T18:49:31.723544+00:00 st2 st2sensorcontainer: File "/usr/lib64/python2.7/logging/__init__.py", line 464, in format
2015-12-11T18:49:31.723742+00:00 st2 st2sensorcontainer: record.message = record.getMessage()
2015-12-11T18:49:31.723914+00:00 st2 st2sensorcontainer: File "/usr/lib64/python2.7/logging/__init__.py", line 328, in getMessage
2015-12-11T18:49:31.724102+00:00 st2 st2sensorcontainer: msg = msg % self.args
2015-12-11T18:49:31.724283+00:00 st2 st2sensorcontainer: ValueError: incomplete format
2015-12-11T18:49:31.724461+00:00 st2 st2sensorcontainer: Logged from file log.py, line 69
```

That doesn't shed light on what exactly happened in the sensor script during its execution. I believe this is a bug, since it makes debugging your sensors almost impossible :(

**Comment by manasdk** [comment]
What could've sworn we fixed this stuff in the past!

Thanks for the report.

**Comment by emptywee** [comment]
Anytime. Let me know if you can repro it, or it is just my setup screwed that much :)

**Comment by jfryman** [comment]
@emptywee  is that the full error log? Usually there is some extra "context" around it that at least helps a bit. I'm having trouble seeing an error... other than we're not throwing a log properly.

**Comment by emptywee** [comment]
@jfryman It is the full log. Before that comes whatever my `self._logger.debug(...)` had to say and nothing after that, the script fails. If you can't reproduce it, I can create a simple sensor with some unhandled exception code inside and send it to you.

**Comment by jfryman** [comment]
Yeah, throw a sensor our way. Always helpful

**Comment by emptywee** [comment]
I noticed that it happens not on every exception, but this one is a good example:
```
import os
import datetime
import re
from inspect import getmembers
import pprint


from git.repo import Repo

from st2reactor.sensor.base import PollingSensor


class SimplePollingSensor(PollingSensor):
    def __init__(self, sensor_service, config=None, poll_interval=10):
        super(SimplePollingSensor, self).__init__(sensor_service=sensor_service,
                                              config=config,
                                              poll_interval=poll_interval)

        self._logger = self._sensor_service.get_logger(__name__)
        self._name = "SimpleSensor"

    def setup(self):
        git_opts = self._config

        pass

    def poll(self):
        self._logger.debug("Simple Polling Sensor Poll...")
        self._logger.debug("Unbelivable if you saw that in the logs %!", self._name)
        pass

    def cleanup(self):

        pass

    def add_trigger(self, trigger):
        pass

    def update_trigger(self, trigger):
        pass

    def remove_trigger(self, trigger):
        pass
```
Meta:
```
---
  class_name: "SimplePollingSensor"
  enabled: true
  entry_point: "sample_polling_sensor.py"
  description: "Simple polling sensor that emits triggers."
  poll_interval: 10
  trigger_types:
    -
      name: "polling_event"
      description: "An example trigger."
      payload_schema:
        type: "object"
        properties:
          executed_at:
            type: "string"
```

In my case I had a git monitoring sensor, and for some reason it blew up same stuff almost on any error I made, e.g. accessing not existing key in the dict, or when I reset my cloned repo to previous commits and sensor ran the pull() method, not sure what happened there exactly then, since I couldn't figure it out due to lack of info from the logs.

**Comment by emptywee** [comment]
I am relatively new to Python, so I still do many mistakes and meaningful logging would be highly appreciated.

**Comment by LindsayHill** [comment]
@emptywee any idea if this is still a problem with recent versions? I'm guessing there's been few changes in there since v1.2

**Comment by emptywee** [comment]
Yeah, need to verify. I can hardly remember what it is all about! :)

**Comment by LindsayHill** [comment]
I'm doing some archaeology here with old issues :)

If it is still a problem, we can pick it up. If it has been fixed somewhere along the line, we can close the issue. Just let us know

**Comment by LindsayHill** [comment]
Let's close this one for now, re-open later if needed.
