### ISSUE TITLE
st2-register-content CLI script should return 1 exit code on Error

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#2314]
`st2-register-content` CLI script should return 1 exit code if some of the components failed to load/register.

Example: 
```sh
# st2-register-content --register-all --config-dir /etc/st2

2015-12-19 18:20:57,006 INFO [-] Connecting to database "st2" @ "0.0.0.0:27017" as user "None".
2015-12-19 18:20:57,046 INFO [-] =========================================================
2015-12-19 18:20:57,046 INFO [-] ############## Registering sensors ######################
2015-12-19 18:20:57,046 INFO [-] =========================================================
2015-12-19 18:20:57,090 INFO [-] Registered 1 sensors.
2015-12-19 18:20:57,090 INFO [-] =========================================================
2015-12-19 18:20:57,090 INFO [-] ############## Registering actions ######################
2015-12-19 18:20:57,091 INFO [-] =========================================================
2015-12-19 18:20:57,871 INFO [-] Registered 40 actions.
2015-12-19 18:20:57,872 INFO [-] =========================================================
2015-12-19 18:20:57,872 INFO [-] ############## Registering rules ########################
2015-12-19 18:20:57,872 INFO [-] =========================================================
2015-12-19 18:20:57,878 INFO [-] Registered 0 rules.
2015-12-19 18:20:57,878 INFO [-] =========================================================
2015-12-19 18:20:57,879 INFO [-] ############## Registering aliases ######################
2015-12-19 18:20:57,879 INFO [-] =========================================================
2015-12-19 18:20:57,890 INFO [-] Registered 2 aliases.
2015-12-19 18:20:57,891 INFO [-] =========================================================
2015-12-19 18:20:57,891 INFO [-] ############## Registering policy types #################
2015-12-19 18:20:57,891 INFO [-] =========================================================
2015-12-19 18:20:57,891 WARNING [-] Failed to register policy types.
Traceback (most recent call last):
  File "/usr/share/python/st2common/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 174, in register_policies
    import st2actions
ImportError: No module named st2actions
2015-12-19 18:20:57,891 INFO [-] Registered 0 policy types.
2015-12-19 18:20:57,891 INFO [-] =========================================================
2015-12-19 18:20:57,891 INFO [-] ############## Registering policies #####################
2015-12-19 18:20:57,891 INFO [-] =========================================================
2015-12-19 18:20:57,892 INFO [-] Registered 0 policies.

# echo $?
0
```

**Comment by Kami** [comment]
That is a feature.

The idea is that you can also use this script to only register a single resource type (e.g. just rules in case only rules engine is running on that server - in that case st2actions would not be available.)

I believe there is also a comment about that in the code - if it's not we should definitely add it.

If you want to exit on failure for testing / development purposes, you can use ``--register-fail-on-failure`` flag which was added just recently (although, not 100% sure it would also fail if st2actions can't be imported).

**Comment by armab** [comment]
Awesome @Kami!
https://github.com/StackStorm/st2/pull/2291 exactly what I want (wow, just 4 days ago).

Will try it and let you know here.

**Comment by armab** [comment]
Sadly, `--register-fail-on-failure` didn't worked when module can't be imported: 

```
#st2-register-content --register-fail-on-failure --register-all --config-dir /etc/st2

2015-12-20 13:57:40,199 INFO [-] Connecting to database "st2" @ "0.0.0.0:27017" as user "None".
2015-12-20 13:57:40,231 INFO [-] =========================================================
2015-12-20 13:57:40,231 INFO [-] ############## Registering sensors ######################
2015-12-20 13:57:40,231 INFO [-] =========================================================
2015-12-20 13:57:40,262 INFO [-] Registered 1 sensors.
2015-12-20 13:57:40,262 INFO [-] =========================================================
2015-12-20 13:57:40,262 INFO [-] ############## Registering actions ######################
2015-12-20 13:57:40,262 INFO [-] =========================================================
2015-12-20 13:57:40,791 INFO [-] Registered 40 actions.
2015-12-20 13:57:40,791 INFO [-] =========================================================
2015-12-20 13:57:40,791 INFO [-] ############## Registering rules ########################
2015-12-20 13:57:40,791 INFO [-] =========================================================
2015-12-20 13:57:40,797 INFO [-] Registered 0 rules.
2015-12-20 13:57:40,797 INFO [-] =========================================================
2015-12-20 13:57:40,797 INFO [-] ############## Registering aliases ######################
2015-12-20 13:57:40,797 INFO [-] =========================================================
2015-12-20 13:57:40,805 INFO [-] Registered 2 aliases.
2015-12-20 13:57:40,805 INFO [-] =========================================================
2015-12-20 13:57:40,806 INFO [-] ############## Registering policy types #################
2015-12-20 13:57:40,806 INFO [-] =========================================================
2015-12-20 13:57:40,806 WARNING [-] Failed to register policy types.
Traceback (most recent call last):
  File "/usr/share/python/st2common/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 174, in register_policies
    import st2actions
ImportError: No module named st2actions
2015-12-20 13:57:40,807 INFO [-] Registered 0 policy types.
2015-12-20 13:57:40,808 INFO [-] =========================================================
2015-12-20 13:57:40,808 INFO [-] ############## Registering policies #####################
2015-12-20 13:57:40,808 INFO [-] =========================================================
2015-12-20 13:57:40,808 INFO [-] Registered 0 policies.

# echo $?
0
```

**Comment by Kami** [comment]
@armab Alright, I will look into making this change (also failing on any import) later today.

I will also think about it a bit more, might make sense to add another flag so the behavior doesn't change.

**Comment by armab** [comment]
Yeah, my understanding is that it should exit with error code if *any* type of error occured.
Looks like `--register-fail-on-failure` is perfect for that. There is no need of new flags, but you know better.

Also it's not a priority or blocker.
Just good thing to have, for better CI (to know if everything went OK, or it's errored somewhere).

**Comment by Kami** [comment]
Btw, this will become obsolete once https://github.com/StackStorm/st2/issues/2321 is implemented.
