### ISSUE TITLE
User-friendly YAML Validation

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#2320]
> Report from the #community

It's obvious that single-line Jinja variables like `{{ playbook }}` should be enclosed with `"{{ playbook }}"` or they treated as dict.
Ex:
```yaml
params:
    playbook: {{playbook}}
```

`st2` shows this error: 
```py
st2 run st2-chatops-aliases.deploy_and_run_task playbook=test-slack.yml 
..
id: 56787954089f67469a3d7627
action.ref: st2-chatops-aliases.deploy_and_run_task
status: failed
error: Failed to run task "run_task". Parameter rendering failed: Failed rendering value for action parameter "playbook" in task "run_task" (template string={{[playbook}}): unexpected '}', expected ']'
traceback: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/actionchainrunner.py", line 307, in run
    action_params=action_parameters, context_result=context_result)
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/actionchainrunner.py", line 504, in _get_next_action
    chain_context={'parent': parent_context})
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/actionchainrunner.py", line 486, in _resolve_params
    raise ParameterRenderingFailedException(msg)
ParameterRenderingFailedException: Failed rendering value for action parameter "playbook" in task "run_task" (template string={{[playbook}}): unexpected '}', expected ']'
```

Here is how Ansible handles it:
![stackstorm_ansible-st2_ 24_-_circleci_-_2015-12-22_04 07 23](https://cloud.githubusercontent.com/assets/1533818/11946322/0fcee356-a862-11e5-88aa-8f78ef61c9e9.png)
I was literally shocked and how many possible corner cases they handle, catching even upstream lib errors and how easy/useful were such error messages. Love to user is part of success :heart:

----

Just believe it's good example where to aim and what approach to follow someday with more user-readable errors, better overall error reporting (and less raw Python tracebacks). Honestly, not too much cases when full Python traceback in `st2` was useful for me personally (as user).

Leaving it here as example and food for thinking.

**Comment by Kami** [comment]
I do agree that we should always throw the most user friendly exception as possible.

As far as this specific case goes - is it possible to always throw an exception in such scenario? In some cases, a dictionary can be a valid value (when parameter type is `object`).

It seems like we would need to do another validation for all the parameters which are eventually render / can contain jinja expressions (e.g. throw if YAML dictionary notation is used for a parameter which type is not object).

**Comment by armab** [comment]
I stumbled into `distutils` doc https://docs.python.org/2/distutils/setupscript.html#debugging-the-setup-script which clarifies it right: 

> Sometimes things go wrong, and the setup script doesn’t do what the developer wants.
> 
> Distutils catches any exceptions when running the setup script, and print a simple error message before the script is terminated. The motivation for this behaviour is to not confuse administrators who don’t know much about Python and are trying to install a package. If they get a big long traceback from deep inside the guts of Distutils, they may think the package or the Python installation is broken because they don’t read all the way down to the bottom and see that it’s a permission problem.
>
>On the other hand, this doesn’t help the developer to find the cause of the failure. For this purpose, the DISTUTILS_DEBUG environment variable can be set to anything except an empty string, and distutils will now print detailed information about what it is doing, dump the full traceback when an exception occurs, and print the whole command line when an external program (like a C compiler) fails.

Which means: don't show full python traceback by default, - it will scary people (that's what happens in our case). Instead, use shorter message to describe the problem.
