### ISSUE TITLE
RulesEngine quit due to exception

### ISSUE THREAD

**Issue by alfasin** [StackStorm/st2#2398]
I suspect that there's a bug in eventlet that, once hit this edge-case, case the rule-engine to go down.

```
2015-11-14 09:59:01,864 140360772253008 ERROR log [-] (PID:12405) RulesEngine quit due to exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2reactor/cmd/rulesengine.py", line 46, in _run_worker
    return timer_thread.wait() and rules_engine_worker.wait()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenthread.py", line 175, in wait
    return self._exit_event.wait()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/event.py", line 121, in wait
    return hubs.get_hub().switch()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 346, in run
    self.wait(sleep_time)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/poll.py", line 85, in wait
    presult = self.do_poll(seconds)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/epolls.py", line 62, in do_poll
    return self.poll.poll(seconds)
  File "/usr/lib/python2.7/dist-packages/st2common/signal_handlers.py", line 44, in handle_sigusr1
    reopen_log_files(handlers=handlers)
  File "/usr/lib/python2.7/dist-packages/st2common/logging/misc.py", line 50, in reopen_log_files
    handler.release()
  File "/usr/lib/python2.7/logging/__init__.py", line 705, in release
    self.lock.release()
  File "/usr/lib/python2.7/threading.py", line 203, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
2015-11-14 09:59:01,920 140360772253008 INFO base [-] Scheduler has been shut down
```

Potentially related issue:
http://stackoverflow.com/questions/23116383/thread-condition-variables-un-acquired-lock

Behavioral issue:
Once an exception was raise, from line 63 in our case:
https://github.com/StackStorm/st2/blob/master/st2reactor/st2reactor/cmd/rulesengine.py#L63

The default behavior is to shutdown the rule-engine:
https://github.com/StackStorm/st2/blob/master/st2reactor/st2reactor/cmd/rulesengine.py#L66

I suggest to either use the fail-fast approach and turn-off *everything* (i.e. `st2ctl stop`), or just print error to log and continue.

The problem with the current approach is that st2 remains up and running, so it keep processing events (the sensor is up and running) but the trigger cannot be passed to the rule-engine since it's down, so the events are not being handled, only that now it fails silently, which makes it harder to detect and fix.

**Comment by Kami** [comment]
Thanks for the report.

It looks like the issue is related to combination of signals and eventlet. It looks like the service was sent SIGUSR1 at that time and asked to rotate the log files.

I will look into it, but I don't think it will be easy to reproduce it.

> I suggest to either use the fail-fast approach and turn-off everything (i.e. st2ctl stop), or just print error to log and continue.

> The problem with the current approach is that st2 remains up and running, so it keep processing events (the sensor is up and running) but the trigger cannot be passed to the rule-engine since it's down, so the events are not being handled, only that now it fails silently, which makes it harder to detect and fix.

I'm not sure I exactly understand this part. The way it's currently works it's by design - services act as independent part of the system.

If the rules engine is offline, messages will be queued and they will be processed again once rules engine is back online. Granted, there could be some catch up issues if rules engine is down for a very long period of time, but that's why monitoring is needed (on service availability and queue backlog sizes).

If you want the behavior mentioned above you could also achieve this via monitoring, but again, for cases like this I don't think this is really desired - it was a one time exception and service manager should pick the service being offline and started it again so the service should be back in a couple of seconds and start processing events / messages again.

**Comment by Kami** [comment]
As I have guessed, this turns out to be hard to reproduce. I tried a couple of different scenarios and can't reproduce it.

In any case, I believe the way it currently behaves is actually desired - we want the service to exit on fatal errors  / exceptions like that and that is exactly what happens right now. Ignoring this exception and trying to continue with work could potentially cause issues and result in a dead lock.

As mentioned above, users should have some kind of service manager in place and that service manager should restart the service if it exists.

Having said that, I will dig in some more. On thing which is possible that is happening is that `handler.acquire()` is not successful in acquiring a lock, but we try to release it at the end any way.

**Comment by alfasin** [comment]
@Kami thanks for taking the time to check it out!
Two feedbacks:
- I'm not sure what happened in our case (the logs offer limited amount of information), but we had two alerts that didn't get processed: from the logs we can see that triggers got created and I think that we can safely assume that they were entered to RabbitMQ only that after I restarted the rule-engine these messages were not picked up (maybe they TTL'ed ?).
- The idea of having a watchdog for each service is a great idea, and it would make sense to have it as part of Stackstorm.

**Comment by Kami** [comment]
You are welcome.

1. That's weird indeed. We only ACK the message once it has been processed so even if the process died half way through processing the message / rule, it should have been re-delivered and processed again when the rules engine comes back online. I will have a look and make sure that's indeed the case. As far as TTL goes - I would also investigate that (this would only apply if service is offline for a really long time though).

2. I personally think that's not responsibility of StackStorm. We should be good at executing rules, etc. but not at managing services. There are already many other battle tested service managers out there (supervisor, systemd, runit, etc.) who are much better at this then we will ever be since this is their main focus (well, except systemd, they try to be everything, maybe at some point they will just embedded StackStorm into it :P)
