### ISSUE TITLE
mistral tasks get stuck in RUNNING state when using both 'wait-before:' and 'with-items:'

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2#2536]
@m4dcoder asked me to raise this issue here.
On the latest `1.3.2.16` st2 with the latest code from mistral branch `1.3.2`, database stamp `010` I encountered the problem when my workflows, which have subflows (also mistral), which in their turn used `on-complete:` before the last action wouldn't finish and instead they would get stuck in the `RUNNING` state.

A typical workflow would be:

```

---
version: '2.0'
name: pack.wf
description: 'workflow'

workflows:
  main:
    type: direct
    input:
      - hostlist
    tasks:

... multiple other tasks skipped for length's sake ...

      show_diff:
        # [191, 512]
        workflow: diff_workflow
        input:
          before: <% $.info_before.get($.host).stdout %>
          after: <% $.info_after.get($.host).stdout %>
          hostname: <% $.host %>
        with-items: host in <% $.hosts_array %>
        concurrency: 1
        publish:
          hdiff: <% $.show_diff %>

        on-complete:
          - rm_temp_inv

      rm_temp_inv:
        # [73, 756]
        action: core.local
        input:
          cmd: "/usr/bin/rm -f <% $.inv_name %>"
          cwd: '<% $.inv_dir %>'

  diff_workflow:
    type: direct
    input:
      - before
      - after
      - hostname

    tasks:

      write_before:
        # [559, 504]
        action: core.local
        input:
          cmd: 'echo -e ''<% $.hostname %>\n<% $.before %>'' | sed -e ''s/\r//g'' > ~/tmp/<% $.hostname %>_before'

        on-success:
          - write_after
        on-error:
          - clean_up
      write_after:
        # [420, 580]
        action: core.local
        input:
          cmd: 'echo -e ''<% $.hostname %>\n<% $.after %>'' | sed -e ''s/\r//g'' > ~/tmp/<% $.hostname %>_after'

        on-success:
          - print_diff

        on-error:
          - clean_up
      print_diff:
        # [571, 683]
        action: core.local
        input:
          cmd: '/usr/bin/diff -W 130 -y -B --suppress-common-lines --text  ~/tmp/<% $.hostname %>_before ~/tmp/<% $.hostname %>_after; exit 0'
        publish:
          hdiff: <% $.print_diff.stdout %>

        on-error:
          - clean_up
        on-success:
          - clean_up

      # Clean up on the aisle 5
      clean_up:
        # [397, 759]
        action: core.local
        input:
          cmd: '/bin/rm -f ~/tmp/<% $.hostname %>_*; exit 0'

```

As far as I remember substitution of subflow with action didn't change things. But replacing `on-complete:` with `on-success:` definitely helped.

`mistral.log` would show something like that:

```
2016-02-26 14:38:15,685 64170256 INFO task [-] Fetch tasks.
2016-02-26 14:38:20,658 64170256 INFO execution [-] Fetch execution [id=d875c8b2-8f4d-4114-921d-6a2f0d68349a]
2016-02-26 14:38:20,680 64170256 INFO task [-] Fetch tasks.
2016-02-26 14:38:25,664 64170256 INFO execution [-] Fetch execution [id=d875c8b2-8f4d-4114-921d-6a2f0d68349a]
2016-02-26 14:38:25,689 64170256 INFO task [-] Fetch tasks.
2016-02-26 14:38:30,662 64170256 INFO execution [-] Fetch execution [id=d875c8b2-8f4d-4114-921d-6a2f0d68349a]
2016-02-26 14:38:30,690 64170256 INFO task [-] Fetch tasks.
2016-02-26 14:38:35,666 64170256 INFO execution [-] Fetch execution [id=d875c8b2-8f4d-4114-921d-6a2f0d68349a]
2016-02-26 14:38:35,700 64170256 INFO task [-] Fetch tasks.
2016-02-26 14:38:40,666 64170256 INFO execution [-] Fetch execution [id=d875c8b2-8f4d-4114-921d-6a2f0d68349a]
2016-02-26 14:38:40,692 64170256 INFO task [-] Fetch tasks.
2016-02-26 14:38:45,663 64170256 INFO execution [-] Fetch execution [id=d875c8b2-8f4d-4114-921d-6a2f0d68349a]
2016-02-26 14:38:45,684 64170256 INFO task [-] Fetch tasks.
2016-02-26 14:38:50,669 64170256 INFO execution [-] Fetch execution [id=d875c8b2-8f4d-4114-921d-6a2f0d68349a]
2016-02-26 14:38:50,702 64170256 INFO task [-] Fetch tasks.
2016-02-26 14:38:55,677 64170256 INFO execution [-] Fetch execution [id=d875c8b2-8f4d-4114-921d-6a2f0d68349a]
2016-02-26 14:38:55,706 64170256 INFO task [-] Fetch tasks.
2016-02-26 14:39:00,667 64170256 INFO execution [-] Fetch execution [id=d875c8b2-8f4d-4114-921d-6a2f0d68349a]
2016-02-26 14:39:00,692 64170256 INFO task [-] Fetch tasks.
2016-02-26 14:39:05,674 64170256 INFO execution [-] Fetch execution [id=d875c8b2-8f4d-4114-921d-6a2f0d68349a]
```

`mistral execution-get d875c8b2-8f4d-4114-921d-6a2f0d68349a` would show the execution in the `RUNNING` state.

Full mistral log is available upon request, but was also sent to support email along with full metas and workflows involved.

**Comment by emptywee** [comment]
Update: just got it stuck without `on-complete:` :-( No idea then what's causing it.

**Comment by emptywee** [comment]
Once I clicked "cancel" button on the stuck subflow, mistral.log showed the following:
```
2016-02-26 22:06:58,995 55396624 INFO execution [-] Update execution [id=0ac3cc59-6db3-4ae3-9ae7-f04402545065, execution=Execution [id='Unset', workflow_name='Unset', description='Unset', params='Unset', task_execution_id='Unset', state='PAUSED', state_info='Unset', input='Unset', output='Unset', created_at='Unset', updated_at='Unset']]
2016-02-26 22:06:59,025 64010512 INFO rpc [-] Received RPC request 'pause_workflow'[rpc_ctx=MistralContext {u'project_name': None, u'user_id': None, u'roles': [u''], u'auth_token': None, u'is_trust_scoped': False, u'service_catalog': None, u'project_id': None, u'user_name': None}, execution_id=0ac3cc59-6db3-4ae3-9ae7-f04402545065]
2016-02-26 22:06:59,045 64010512 ERROR dispatcher [-] Exception during message handling: Can't change workflow execution state from SUCCESS to PAUSED. [workflow=epsilon.patch.main, execution_id=0ac3cc59-6db3-4ae3-9ae7-f04402545065]
Traceback (most recent call last):
  File "/opt/openstack/mistral/.venv/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 143, in _dispatch_and_reply
    executor_callback))
  File "/opt/openstack/mistral/.venv/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 189, in _dispatch
    executor_callback)
  File "/opt/openstack/mistral/.venv/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 130, in _do_dispatch
    result = func(ctxt, **new_args)
  File "/opt/openstack/mistral/mistral/engine/rpc.py", line 160, in pause_workflow
    return self._engine.pause_workflow(execution_id)
  File "/opt/openstack/mistral/mistral/utils/__init__.py", line 112, in _logged
    return func(*args, **kw)
  File "/opt/openstack/mistral/mistral/engine/default_engine.py", line 283, in pause_workflow
    wf_handler.set_execution_state(wf_ex, states.PAUSED)
  File "/opt/openstack/mistral/mistral/engine/workflow_handler.py", line 106, in set_execution_state
    raise exc.WorkflowException(msg)
WorkflowException: Can't change workflow execution state from SUCCESS to PAUSED. [workflow=epsilon.patch.main, execution_id=0ac3cc59-6db3-4ae3-9ae7-f04402545065]
2016-02-26 22:06:59,048 64010512 ERROR common [-] Returning exception Can't change workflow execution state from SUCCESS to PAUSED. [workflow=epsilon.patch.main, execution_id=0ac3cc59-6db3-4ae3-9ae7-f04402545065] to caller
2016-02-26 22:06:59,048 64010512 ERROR common [-] ['Traceback (most recent call last):\n', '  File "/opt/openstack/mistral/.venv/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 143, in _dispatch_and_reply\n    executor_callback))\n', '  File "/opt/openstack/mistral/.venv/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 189, in _dispatch\n    executor_callback)\n', '  File "/opt/openstack/mistral/.venv/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 130, in _do_dispatch\n    result = func(ctxt, **new_args)\n', '  File "/opt/openstack/mistral/mistral/engine/rpc.py", line 160, in pause_workflow\n    return self._engine.pause_workflow(execution_id)\n', '  File "/opt/openstack/mistral/mistral/utils/__init__.py", line 112, in _logged\n    return func(*args, **kw)\n', '  File "/opt/openstack/mistral/mistral/engine/default_engine.py", line 283, in pause_workflow\n    wf_handler.set_execution_state(wf_ex, states.PAUSED)\n', '  File "/opt/openstack/mistral/mistral/engine/workflow_handler.py", line 106, in set_execution_state\n    raise exc.WorkflowException(msg)\n', "WorkflowException: Can't change workflow execution state from SUCCESS to PAUSED. [workflow=epsilon.patch.main, execution_id=0ac3cc59-6db3-4ae3-9ae7-f04402545065]\n"]
```

**Comment by emptywee** [comment]
And keeps fetching status for the main flow:

```
2016-02-26 22:07:48,466 55396624 INFO execution [-] Fetch execution [id=2c51cb3e-eda0-491d-8583-5a5f0d1b2dcb]
2016-02-26 22:07:48,495 55396624 INFO task [-] Fetch tasks.
2016-02-26 22:07:53,469 55396624 INFO execution [-] Fetch execution [id=2c51cb3e-eda0-491d-8583-5a5f0d1b2dcb]
2016-02-26 22:07:53,492 55396624 INFO task [-] Fetch tasks.
2016-02-26 22:07:58,467 55396624 INFO execution [-] Fetch execution [id=2c51cb3e-eda0-491d-8583-5a5f0d1b2dcb]
2016-02-26 22:07:58,490 55396624 INFO task [-] Fetch tasks.
2016-02-26 22:08:03,468 55396624 INFO execution [-] Fetch execution [id=2c51cb3e-eda0-491d-8583-5a5f0d1b2dcb]
2016-02-26 22:08:03,490 55396624 INFO task [-] Fetch tasks.
2016-02-26 22:08:08,467 55396624 INFO execution [-] Fetch execution [id=2c51cb3e-eda0-491d-8583-5a5f0d1b2dcb]
2016-02-26 22:08:08,487 55396624 INFO task [-] Fetch tasks.
```

```
$ mistral execution-get 2c51cb3e-eda0-491d-8583-5a5f0d1b2dcb
+-------------+--------------------------------------+
| Field       | Value                                |
+-------------+--------------------------------------+
| ID          | 2c51cb3e-eda0-491d-8583-5a5f0d1b2dcb |
| Workflow    | st2-epsibot.patch                    |
| Description |                                      |
| State       | RUNNING                              |
| State info  | None                                 |
| Created at  | 2016-02-26 21:24:41.500460           |
| Updated at  | 2016-02-26 21:25:18.540729           |
+-------------+--------------------------------------+
```

**Comment by emptywee** [comment]
Cancelling the main flow produces this:
```
2016-02-26 22:09:13,323 55396624 INFO execution [-] Update execution [id=2c51cb3e-eda0-491d-8583-5a5f0d1b2dcb, execution=Execution [id='Unset', workflow_name='Unset', description='Unset', params='Unset', task_execution_id='Unset', state='PAUSED', state_info='Unset', input='Unset', output='Unset', created_at='Unset', updated_at='Unset']]
2016-02-26 22:09:13,346 59509648 INFO rpc [-] Received RPC request 'pause_workflow'[rpc_ctx=MistralContext {u'project_name': None, u'user_id': None, u'roles': [u''], u'auth_token': None, u'is_trust_scoped': False, u'service_catalog': None, u'project_id': None, u'user_name': None}, execution_id=2c51cb3e-eda0-491d-8583-5a5f0d1b2dcb]
2016-02-26 22:09:13,359 59509648 INFO wf_trace [-] Execution of workflow 'st2-epsibot.patch' [RUNNING -> PAUSED] (execution_id=2c51cb3e-eda0-491d-8583-5a5f0d1b2dcb)
2016-02-26 22:09:13,477 55396624 INFO execution [-] Fetch execution [id=2c51cb3e-eda0-491d-8583-5a5f0d1b2dcb]
2016-02-26 22:09:13,518 55396624 INFO task [-] Fetch tasks.
```
And everything stops.

**Comment by m4dcoder** [comment]
@emptywee: please also run `mistral execution-list` to find the id for this specific top level workflow execution, then run `mistral task-list <execution-id>`, post the result here.  identify the task id for the show_diff task, run 'mistral action-execution-list <task-execution-id>` and post the result here.

**Comment by emptywee** [comment]
@m4dcoder 
Let's start over. I have it getting stuck every time I run it. Top-level workflow is `st2-epsibot.patch`. Then it runs `epsilon.patch.main` as a task named `patch_all`, which in its turn has subflow `epsilon.patch.diff_workflow` as a task named `show_diff`.

Currently it's stuck in RUNNING. st2 keeps fetching it from mistral. I will not cancel it or interfere in it unless you ask to.

Last `mistral.log` rows:
```
2016-02-26 23:59:02,757 64470384 INFO rpc [-] Received RPC request 'on_action_complete'[rpc_ctx=MistralContext {u'project_name': None, u'user_id': None, u'roles': [u''], u'auth_token': None, u'is_trust_scoped': False, u'service_catalog': None, u'project_id': None, u'user_name': None}, action_ex_id=6d689ac2-f55c-4d73-be8a-aa17f684d6b3, result=Result [data={u'succeeded': True, u'failed': False, u'return_code': 0, u'stderr': u'', u'stdout': u''}, error=None]]
2016-02-26 23:59:04,966 64470384 INFO wf_trace [-] Action execution 'st2.action' [RUNNING -> SUCCESS, result = {u'succeeded': True, u'failed': False, u'return_code': 0, u'stderr': u'', u'stdout': u''}]
2016-02-26 23:59:07,012 64470384 INFO wf_trace [-] Task execution 'rm_temp_inv' [RUNNING -> SUCCESS] (execution_id=f75b4217-0ead-421d-9ef4-0898ee21e5c2)
2016-02-26 23:59:15,512 64470384 INFO wf_trace [-] Execution of workflow 'epsilon.patch.main' [RUNNING -> SUCCESS] (execution_id=f75b4217-0ead-421d-9ef4-0898ee21e5c2)
2016-02-26 23:59:15,545 55396624 INFO execution [-] Fetch execution [id=55c002f5-b2b5-41cc-9c35-6d76d6be4f09]
2016-02-26 23:59:15,573 55396624 INFO task [-] Fetch tasks.
2016-02-26 23:59:18,642 55396624 INFO execution [-] Fetch execution [id=55c002f5-b2b5-41cc-9c35-6d76d6be4f09]
2016-02-26 23:59:18,670 55396624 INFO task [-] Fetch tasks.
2016-02-26 23:59:23,645 55396624 INFO execution [-] Fetch execution [id=55c002f5-b2b5-41cc-9c35-6d76d6be4f09]
```

`mistral task-list` has the following about it:
```
| bdb78423-b4a4-4bbd-bef6-efc773422b06 | patch_all                | st2-epsibot.patch                       | 55c002f5-b2b5-41cc-9c35-6d76d6be4f09 | RUNNING | None                         |
```

As far as I understand it only shows top-level workflows. Relevant entry from `mistral execution-list` is:
```
| 55c002f5-b2b5-41cc-9c35-6d76d6be4f09 | st2-epsibot.patch                       |                        | RUNNING | None                         | 2016-02-26 23:47:35.166438 | 2016-02-26 23:48:11.685328 |
```

`mistral task-list` for the execution that st2 keeps fetching data for:
```
$ mistral task-list 55c002f5-b2b5-41cc-9c35-6d76d6be4f09
+--------------------------------------+-------------------+-------------------+--------------------------------------+---------+------------+
| ID                                   | Name              | Workflow name     | Execution ID                         | State   | State info |
+--------------------------------------+-------------------+-------------------+--------------------------------------+---------+------------+
| bb0ffb33-3252-479c-8618-2fff41c03431 | get_group_members | st2-epsibot.patch | 55c002f5-b2b5-41cc-9c35-6d76d6be4f09 | SUCCESS | None       |
| a7bbc2e0-e6de-4ca9-9801-cb2e1240663e | publish_data      | st2-epsibot.patch | 55c002f5-b2b5-41cc-9c35-6d76d6be4f09 | SUCCESS | None       |
| 8a42c9ee-77ad-471e-8e3b-1788d9ba3b97 | access_granted    | st2-epsibot.patch | 55c002f5-b2b5-41cc-9c35-6d76d6be4f09 | SUCCESS | None       |
| 7194a92c-1192-4829-bd9e-14d5898c2dd8 | prep_hostlist     | st2-epsibot.patch | 55c002f5-b2b5-41cc-9c35-6d76d6be4f09 | SUCCESS | None       |
| bdb78423-b4a4-4bbd-bef6-efc773422b06 | patch_all         | st2-epsibot.patch | 55c002f5-b2b5-41cc-9c35-6d76d6be4f09 | RUNNING | None       |
+--------------------------------------+-------------------+-------------------+--------------------------------------+---------+------------+
```

Also I can run `mistral action-execution-list` for the `patch_all`:
```
$ mistral action-execution-list bdb78423-b4a4-4bbd-bef6-efc773422b06
+--------------------------------------+------------+-------------------+-----------+---------+------------+-------------+
| ID                                   | Name       | Workflow name     | Task name | State   | State info | Is accepted |
+--------------------------------------+------------+-------------------+-----------+---------+------------+-------------+
| 7827c42d-169e-453a-98cd-b7a8b32414cf | st2.action | st2-epsibot.patch | patch_all | RUNNING | None       | False       |
+--------------------------------------+------------+-------------------+-----------+---------+------------+-------------+
```

Not sure what else I can fetch from mistral. Please, let me know what command to run and I'll show the output.

Here's the gist for all meta and workflows defs: https://gist.github.com/emptywee/1b8a49139bb6f3acc516

Let me know what info I can provide more to help pin point the culprit for this problem. I think it's a very critical bug.

**Comment by emptywee** [comment]
Update. One more command relevant to the topic:
```
$ mistral action-execution-get 7827c42d-169e-453a-98cd-b7a8b32414cf
+---------------+--------------------------------------+
| Field         | Value                                |
+---------------+--------------------------------------+
| ID            | 7827c42d-169e-453a-98cd-b7a8b32414cf |
| Name          | st2.action                           |
| Workflow name | st2-epsibot.patch                    |
| Task name     | patch_all                            |
| State         | RUNNING                              |
| State info    | None                                 |
| Is accepted   | False                                |
+---------------+--------------------------------------+
```

**Comment by emptywee** [comment]
Funny thing, once I get rid of `with-items` from this part of the `epsilon.patch` workflow:
```
      wait_for_ssh:
        # [551, 303]
        action: e_int.wait_for_ssh
        #action: core.noop
        retry: 
          count: 2
          delay: 10
        wait-before: 90
        #with-items: ip in <% $.ip_addresses %>, host in <% $.patching_succeeded_hosts %>
        #with-items: ip in <% $.ip_addresses %>
        input:
          #hostname: '<% $.ip %>'
          hostname: '<% $.ip_addresses[0] %>'
          username: 'ansible'
          ssh_timeout: 10
          retries: 15
          retry_in: 10
          timeout: 300
```

it starts to finish with no problems.

**Comment by emptywee** [comment]
Noticed that going patching without reboot doesn't get the workflow stuck in RUNNING, so this is basically the only action that differs the way it goes with and without reboot. That's why I started to look into it and play with it (you can see it by commented out lines in it).

Thoughts?

**Comment by emptywee** [comment]
Okay, seems like I nailed it down to the following simple workflow:
```
---
version: '2.0'

e_playground.test3_test2:
  input:
    - items:
      - item1
      - item2
  tasks:
    task1:
      wait-before: 10
      with-items: item in <% $.items %>
      action: core.local
      input:
        cmd: 'echo <% $.item %>'
```

This workflow get stuck in the RUNNING state for me and never finishes. Once you remove `wait-before` or `with-items` - it starts to work with no issues. But the combo of the two - and you are screwed :)

mistral -  branch `1.3.2`
st2 - `1.3.2.16`

**Comment by m4dcoder** [comment]
@emptywee: awesome. thanks for narrowing this down for us.
