### ISSUE TITLE
Cron timer triggers not found this morning

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2#2715]
Issue from https://stackstorm-community.slack.com/archives/community/p1464270424007061

Looks like none of our cron rules ran last night. Found these in the st2rulesengine.log file

stackstorm blueprint node 1:
```
2016-05-26 02:15:00,010 140197381803856 ERROR worker [-] Failed to create trigger_instance {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7f823efd9dd0>, 'trigger': {'uid': u'trigger:core:5201a528-83a8-45a3-afed-1324d19d799c:184474b72fcfb6391b701239c1323bd2', 'parameters': {u'minute': 15, u'hour': 2}, 'description': None, 'ref_count': 1, 'name': u'5201a528-83a8-45a3-afed-1324d19d799c', 'type': u'core.st2.CronTimer', 'id': '57217437f469fc4355dd5e85', 'pack': u'core'}, 'payload': {'executed_at': '2016-05-26 07:15:00.004733+00:00', 'schedule': None}}.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/rules/worker.py", line 51, in process
    raise_on_no_trigger=True)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/utils.py", line 51, in create_trigger_instance
    raise StackStormDBObjectNotFoundError('Trigger not found for %s', trigger)
StackStormDBObjectNotFoundError: ('Trigger not found for %s', {'uid': u'trigger:core:5201a528-83a8-45a3-afed-1324d19d799c:184474b72fcfb6391b701239c1323bd2', 'parameters': {u'minute': 15, u'hour': 2}, 'description': None, 'ref_count': 1, 'name': u'5201a528-83a8-45a3-afed-1324d19d799c', 'type': u'core.st2.CronTimer', 'id': '57217437f469fc4355dd5e85', 'pack': u'core'})
--
2016-05-26 03:00:00,023 140197381803696 ERROR worker [-] Failed to create trigger_instance {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7f823ed2c0d0>, 'trigger': {'uid': u'trigger:core:65d02cf0-b01c-4e78-a904-daf1893f1e37:91302ea65fcee79862b663963e207d22', 'parameters': {u'hour': 3, u'minute': 0}, 'description': None, 'ref_count': 0, 'name': u'65d02cf0-b01c-4e78-a904-daf1893f1e37', 'type': u'core.st2.CronTimer', 'id': '572aaca559e5f159727c5134', 'pack': u'core'}, 'payload': {'executed_at': '2016-05-26 08:00:00.006160+00:00', 'schedule': None}}.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/rules/worker.py", line 51, in process
    raise_on_no_trigger=True)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/utils.py", line 51, in create_trigger_instance
    raise StackStormDBObjectNotFoundError('Trigger not found for %s', trigger)
StackStormDBObjectNotFoundError: ('Trigger not found for %s', {'uid': u'trigger:core:65d02cf0-b01c-4e78-a904-daf1893f1e37:91302ea65fcee79862b663963e207d22', 'parameters': {u'hour': 3, u'minute': 0}, 'description': None, 'ref_count': 0, 'name': u'65d02cf0-b01c-4e78-a904-daf1893f1e37', 'type': u'core.st2.CronTimer', 'id': '572aaca559e5f159727c5134', 'pack': u'core'})```
```

stackstorm blueprint node 2:
```
2016-05-26 03:00:00,018 140303599906160 ERROR worker [-] Failed to create trigger_instance {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7f9afa0a10d0>, 'trigger': {'uid': u'trigger:core:9d5eb720-e95e-475c-8a6d-c0bf0dc3bc82:e6d9bf27b0ede4bf3d03616c685a1e38', 'parameters': {u'day_of_week': u'0-4', u'minute': 0, u'hour': 3}, 'description': None, 'ref_count': 1, 'name': u'9d5eb720-e95e-475c-8a6d-c0bf0dc3bc82', 'type': u'core.st2.CronTimer', 'id': '573b7ee559e5f1422b7ba7ec', 'pack': u'core'}, 'payload': {'executed_at': '2016-05-26 08:00:00.004615+00:00', 'schedule': None}}.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/rules/worker.py", line 51, in process
    raise_on_no_trigger=True)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/utils.py", line 51, in create_trigger_instance
    raise StackStormDBObjectNotFoundError('Trigger not found for %s', trigger)
StackStormDBObjectNotFoundError: ('Trigger not found for %s', {'uid': u'trigger:core:9d5eb720-e95e-475c-8a6d-c0bf0dc3bc82:e6d9bf27b0ede4bf3d03616c685a1e38', 'parameters': {u'day_of_week': u'0-4', u'minute': 0, u'hour': 3}, 'description': None, 'ref_count': 1, 'name': u'9d5eb720-e95e-475c-8a6d-c0bf0dc3bc82', 'type': u'core.st2.CronTimer', 'id': '573b7ee559e5f1422b7ba7ec', 'pack': u'core'})
--
2016-05-26 06:30:00,017 140303599906160 ERROR worker [-] Failed to create trigger_instance {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7f9afa323c50>, 'trigger': {'uid': u'trigger:core:ffcf42ce-9514-484d-8193-9c60ddb661da:a0e7c2879668bb12ef7e519b29742d2f', 'parameters': {u'minute': 30, u'hour': 6}, 'description': None, 'ref_count': 1, 'name': u'ffcf42ce-9514-484d-8193-9c60ddb661da', 'type': u'core.st2.CronTimer', 'id': '57217437f469fc4355dd5e81', 'pack': u'core'}, 'payload': {'executed_at': '2016-05-26 11:30:00.010405+00:00', 'schedule': None}}.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/rules/worker.py", line 51, in process
    raise_on_no_trigger=True)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/utils.py", line 51, in create_trigger_instance
    raise StackStormDBObjectNotFoundError('Trigger not found for %s', trigger)
StackStormDBObjectNotFoundError: ('Trigger not found for %s', {'uid': u'trigger:core:ffcf42ce-9514-484d-8193-9c60ddb661da:a0e7c2879668bb12ef7e519b29742d2f', 'parameters': {u'minute': 30, u'hour': 6}, 'description': None, 'ref_count': 1, 'name': u'ffcf42ce-9514-484d-8193-9c60ddb661da', 'type': u'core.st2.CronTimer', 'id': '57217437f469fc4355dd5e81', 'pack': u'core'})
```

Trying to figure out ​why the cron triggers don't exist anymore.

Doesn't look like these types of triggers show up in `st2 trigger list` but I see the last five days (not today) in `st2 trigger-instance list --trigger=core.9d5eb720-e95e-475c-8a6d-c0bf0dc3bc82`

One exception: `core.65d02cf0-b01c-4e78-a904-daf1893f1e37` doesn't show up in the trigger-instance list (today or any previous days).

Looking directly in mongo, I find that the jobs are still in the 

```
stackstorm:SECONDARY> db.trigger_d_b.find({"name": "9d5eb720-e95e-475c-8a6d-c0bf0dc3bc82"})
{ "_id" : ObjectId("573b7ee559e5f1422b7ba7ec"), "uid" : "trigger:core:9d5eb720-e95e-475c-8a6d-c0bf0dc3bc82:e6d9bf27b0ede4bf3d03616c685a1e38", "name" : "9d5eb720-e95e-475c-8a6d-c0bf0dc3bc82", "pack" : "core", "type" : "core.st2.CronTimer", "parameters" : { "minute" : 0, "day_of_week" : "0-4", "hour" : 3 }, "ref_count" : 1 }

stackstorm:SECONDARY> db.trigger_d_b.find({"name":"65d02cf0-b01c-4e78-a904-daf1893f1e37"})
{ "_id" : ObjectId("572aaca559e5f159727c5134"), "uid" : "trigger:core:65d02cf0-b01c-4e78-a904-daf1893f1e37:91302ea65fcee79862b663963e207d22", "name" : "65d02cf0-b01c-4e78-a904-daf1893f1e37", "pack" : "core", "type" : "core.st2.CronTimer", "parameters" : { "minute" : 0, "hour" : 3 }, "ref_count" : 0 }
```

As a sanity check, I updated one of these rules to run at current time and watched it successfully complete. Interestingly, another rule that I hadn't touched and was scheduled for this afternoon should have just ran a few minutes ago as well but also failed with the same error.

```
2016-05-26 15:50:00,018 140632250726512 ERROR worker [-] Failed to create trigger_instance {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7fe77f498610>, 'trigger': {'uid': u'trigger:core:f618fa96-8838-4a8c-8664-e476fc653fe1:7ea45d3da0596aa5ba162d5f81049b44', 'parameters': {u'day_of_week': u'0-4', u'minute': 50, u'hour': 15}, 'description': None, 'ref_count': 2, 'name': u'f618fa96-8838-4a8c-8664-e476fc653fe1', 'type': u'core.st2.CronTimer', 'id': '57449a5859e5f17e2c71902c', 'pack': u'core'}, 'payload': {'executed_at': '2016-05-26 20:50:00.001940+00:00', 'schedule': None}}.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/rules/worker.py", line 51, in process
    raise_on_no_trigger=True)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/utils.py", line 51, in create_trigger_instance
    raise StackStormDBObjectNotFoundError('Trigger not found for %s', trigger)
StackStormDBObjectNotFoundError: ('Trigger not found for %s', {'uid': u'trigger:core:f618fa96-8838-4a8c-8664-e476fc653fe1:7ea45d3da0596aa5ba162d5f81049b44', 'parameters': {u'day_of_week': u'0-4', u'minute': 50, u'hour': 15}, 'description': None, 'ref_count': 2, 'name': u'f618fa96-8838-4a8c-8664-e476fc653fe1', 'type': u'core.st2.CronTimer', 'id': '57449a5859e5f17e2c71902c', 'pack': u'core'})
```

One thing that may be relevant is that one of our users has been having trouble with writing recursive workflows the last week or so (somehow it keeps getting re-enabled/re-deployed). As a result, I've had to restart st2ctl when actionrunners were pegging the CPU a few times. I'm not sure if there could have been a bad state or some persistence lost in the triggers after my restarts. (Specifically, I believe that I did a `st2ctl restart` on the two stackstorm nodes yesterday afternoon but did not run a `st2ctl reload --register-all`; I would assume that's not required to fix/remap cron trigger types to triggers etc, but this may be relevant since the updated rule fired correctly.

I'm tempted to blow away this cluster state and rebuild. I don't know what kinda funky state is going on right now.

I'm not sure where else to look to troubleshoot this but its super concerning for our use case. Help?

**Comment by Kami** [comment]
(We've already debugged this on Slack a bit and it seemed like a weird race during trigger creation).

Does this issue still exists or is it fine now? (When we checked the DB it looks like trigger was there and that's what made it looked like a race aka trigger didn't exist at some point back in time).

**Comment by codyaray** [comment]
It looks like my cron triggers are firing right now, but I've been traveling the last few days and might not have been as observant as normal.

**Comment by Kami** [comment]
Thanks for the clarification.

This could indeed indicate a race (trigger was first missing so it failed, but it was created later at some point so new cron timers are succeeding).

I will look into it some more when I get a chance.

**Comment by codyaray** [comment]
A fix for #2730 was pushed that should also fix this issue.

**Comment by Kami** [comment]
@codyaray Yeah, please let me know how it goes :)

**Comment by codyaray** [comment]
Woo, my rules ran again this morning. 

For the record (from the other issue), here's what I did yesterday:
> Just ran `db.trigger_d_b.remove()` on mongo master, `sudo st2ctl restart` on each node, and then ran `st2ctl reload --register-all`

**Comment by Kami** [comment]
Awesome, glad to hear that!

And yeah, I do believe that this workaround fixes this completely. The workaround is kinda hacky though, so in the near future we will also look into upgrading pymongo and mongoengine and hope that this bug is fixed in latest release.

**Comment by codyaray** [comment]
This happened again. :(

```
2016-06-22 06:30:00,018 140040664910416 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7f5dc1d67d10>, 'trigger': {'uid': u'trigger:core:f956f3de-e7f6-41b1-b32c-2fd38f8807c5:cf6f92443f5771e8b96e5f237a3d2817', 'parameters': {u'minute': 30, u'hour': 6, u'day_of_week': u'mon-fri'}, 'description': None, 'ref_count': 1, 'name': u'f956f3de-e7f6-41b1-b32c-2fd38f8807c5', 'type': u'core.st2.CronTimer', 'id': '57685af8f469fc5dc1a43776', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-22 11:30:00.006804+00:00', 'schedule': None}}
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/transport/consumers.py", line 76, in process
    response = self._handler.pre_ack_process(body)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/rules/worker.py", line 56, in pre_ack_process
    raise_on_no_trigger=True)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/utils.py", line 52, in create_trigger_instance
    raise StackStormDBObjectNotFoundError('Trigger not found for %s', trigger)
StackStormDBObjectNotFoundError: ('Trigger not found for %s', {'uid': u'trigger:core:f956f3de-e7f6-41b1-b32c-2fd38f8807c5:cf6f92443f5771e8b96e5f237a3d2817', 'parameters': {u'minute': 30, u'hour': 6, u'day_of_week': u'mon-fri'}, 'description': None, 'ref_count': 1, 'name': u'f956f3de-e7f6-41b1-b32c-2fd38f8807c5', 'type': u'core.st2.CronTimer', 'id': '57685af8f469fc5dc1a43776', 'pack': u'core'})
```

I'm currently running version 1.5dev-98.

**Comment by codyaray** [comment]
Actually, looks like this failed at a different spot this time.

```
2016-06-22 06:30:00,018 140040664910416 ERROR consumers [-] StagedQueueConsumer failed to process message:
```

instead of

```
2016-05-26 02:15:00,010 140197381803856 ERROR worker [-] Failed to create trigger_instance
```

Closing issue and creating new one.
