### ISSUE TITLE
st2stream traceback's with TokenExpiredError: Token has expired.

### ISSUE THREAD

**Issue by jjm** [StackStorm/st2#2751]
This morning one of our hubot's has been disconnected from StackStorm due to a traceback and associated restart of st2stream.

```python
2016-06-15 06:44:27,235 140676039022224 ERROR hooks [-] Token has expired.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/pecan/core.py", line 630, in __call__
    controller, args, kwargs = self.find_controller(state)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/pecan/core.py", line 786, in find_controller
    controller, args, kw = super(Pecan, self).find_controller(_state)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/pecan/core.py", line 516, in find_controller
    self.handle_hooks(self.determine_hooks(controller), 'before', state)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/pecan/core.py", line 793, in handle_hooks
    return super(Pecan, self).handle_hooks(hooks, *args, **kw)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/pecan/core.py", line 320, in handle_hooks
    result = getattr(hook, hook_type)(*args)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/hooks.py", line 115, in before
    user_db = self._validate_creds_and_get_user(request=state.request)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/hooks.py", line 203, in _validate_creds_and_get_user
    token_in_query_params=token_in_query_params)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/util/auth.py", line 65, in validate_token
    raise exceptions.TokenExpiredError('Token has expired.')
TokenExpiredError: Token has expired.
```

This seems to be the most common cause of hubot not sending relies to commands back to Slack.

**Comment by jjm** [comment]
About the same time hubot logged the following in it's log:

```
Wed Jun 15 2016 06:44:26 GMT+0100 (BST)] ERROR Stream error: Event { type: 'error' }
[Wed Jun 15 2016 06:44:27 GMT+0100 (BST)] ERROR Stream error: Event { type: 'error', status: 401 }
```

Ideally hubot should also reconnect (or exit and restart) when getting this error.

**Comment by jjm** [comment]
This happened again this morning with our other StackStorm installation.

**Comment by manasdk** [comment]
@jjm Enabled support for api key for hubot-stackstorm. This way you can use an API key instead of using username/password.

https://github.com/StackStorm/hubot-stackstorm/pull/115. Also, new package has been published to npm https://www.npmjs.com/package/hubot-stackstorm. 

st2chatops for v1.5 should have the new package but if you want it earlier you can run `npm update hubot-stackstorm` in `/opt/stackstorm/chatops`.

```
root@st2test:/opt/stackstorm/chatops# npm list | grep hubot-stackstorm
├─┬ hubot-stackstorm@0.4.2
root@st2test:/opt/stackstorm/chatops# npm update hubot-stackstorm
hubot-stackstorm@0.4.3 node_modules/hubot-stackstorm
└── rsvp@3.0.14
root@st2test:/opt/stackstorm/chatops# npm list | grep hubot-stackstorm
├─┬ hubot-stackstorm@0.4.3
```
