### ISSUE TITLE
Cron timers not found - StagedQueueConsumer failed to process message

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2#2765]
This looks similar to #2715 but could have a different cause.

```
2016-06-22 06:30:00,018 140040664910416 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7f5dc1d67d10>, 'trigger': {'uid': u'trigger:core:f956f3de-e7f6-41b1-b32c-2fd38f8807c5:cf6f92443f5771e8b96e5f237a3d2817', 'parameters': {u'minute': 30, u'hour': 6, u'day_of_week': u'mon-fri'}, 'description': None, 'ref_count': 1, 'name': u'f956f3de-e7f6-41b1-b32c-2fd38f8807c5', 'type': u'core.st2.CronTimer', 'id': '57685af8f469fc5dc1a43776', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-22 11:30:00.006804+00:00', 'schedule': None}}
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/transport/consumers.py", line 76, in process
    response = self._handler.pre_ack_process(body)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/rules/worker.py", line 56, in pre_ack_process
    raise_on_no_trigger=True)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/utils.py", line 52, in create_trigger_instance
    raise StackStormDBObjectNotFoundError('Trigger not found for %s', trigger)
StackStormDBObjectNotFoundError: ('Trigger not found for %s', {'uid': u'trigger:core:f956f3de-e7f6-41b1-b32c-2fd38f8807c5:cf6f92443f5771e8b96e5f237a3d2817', 'parameters': {u'minute': 30, u'hour': 6, u'day_of_week': u'mon-fri'}, 'description': None, 'ref_count': 1, 'name': u'f956f3de-e7f6-41b1-b32c-2fd38f8807c5', 'type': u'core.st2.CronTimer', 'id': '57685af8f469fc5dc1a43776', 'pack': u'core'})
```

It looks like this failed at a different spot this time than it did in #2715 .

```
2016-06-22 06:30:00,018 140040664910416 ERROR consumers [-] StagedQueueConsumer failed to process message:
```

instead of

```
2016-05-26 02:15:00,010 140197381803856 ERROR worker [-] Failed to create trigger_instance
```

I'm currently running an [HA setup](https://docs.stackstorm.com/latest/reference/ha.html) with version 1.5dev-98 on both nodes:

```
pstack3:~$ apt-cache policy st2 | grep Installed
  Installed: 1.5dev-98

pstack4:~$ apt-cache policy st2 | grep Installed
  Installed: 1.5dev-98
```

My controller node doesn't run any st2 workers:

```
pstackc1:~$ apt-cache policy st2 | grep Installed
  Installed: (none)
```

For what its worth, I haven't seen this (yet?) in my standalone dev instance which is running the same version of st2.

```
dstack1:~$ apt-cache policy st2 | grep Installed
  Installed: 1.5dev-98
```

We can confirm the dates these were updated for the fix from #2715.

```
pstack3:~$ grep "upgrade st2" /var/log/dpkg.log
2016-06-07 10:16:42 upgrade st2:amd64 1.4.0-6 1.5dev-92
2016-06-17 12:37:59 upgrade st2:amd64 1.5dev-92 1.5dev-98

pstack4:~$ grep "upgrade st2" /var/log/dpkg.log
2016-06-07 10:18:56 upgrade st2:amd64 1.4.0-6 1.5dev-92
2016-06-17 12:38:24 upgrade st2:amd64 1.5dev-92 1.5dev-98

dstack1:~$ grep "upgrade st2" /var/log/dpkg.log
2016-06-07 14:46:24 upgrade st2:amd64 1.4.0-8 1.5dev-92
2016-06-13 10:50:35 upgrade st2:amd64 1.5dev-92 1.5dev-94
2016-06-14 10:01:55 upgrade st2:amd64 1.5dev-94 1.5dev-98
```

Added to this, I [manually removed](https://github.com/StackStorm/st2/issues/2715#issuecomment-224901871) all the triggers from mongo and re-synced on June 8th.
> Just ran `db.trigger_d_b.remove()` on mongo master, `sudo st2ctl restart` on each node, and then ran `st2ctl reload --register-all`

The timer is configured to only run on pstack3 in our prod st2 cluster.

```
pstack3:~$ cat /etc/st2/st2.conf | tail -3
[timer]
local_timezone = America/Chicago
enable = True

pstack4:~$ cat /etc/st2/st2.conf | tail -3
[timer]
local_timezone = America/Chicago
enable = False
```

Interestingly, though, I just found that I see the above **error in both pstack3 and pstack4 even though the timer is disabled on pstack4** (`StagedQueueConsumer failed...`).

First, let's confirm that timer was enabled/disabled as configured:

```
pstack3:~$ grep -A 1 "RulesEngine started" /plogs/st2/st2rulesengine.log | tail -8
2016-06-08 12:09:10,857 139742839966928 INFO rulesengine [-] (PID=14492) RulesEngine started.
2016-06-08 12:09:10,888 139742839966928 INFO rulesengine [-] Timer is enabled.
--
2016-06-17 12:39:18,421 140338173979856 INFO rulesengine [-] (PID=22571) RulesEngine started.
2016-06-17 12:39:18,445 140338173979856 INFO rulesengine [-] Timer is enabled.
--
2016-06-21 08:35:52,985 140040761011408 INFO rulesengine [-] (PID=14829) RulesEngine started.
2016-06-21 08:35:53,008 140040761011408 INFO rulesengine [-] Timer is enabled.
```

```
pstack4:~$ grep -A 1 "RulesEngine started" /plogs/st2/st2rulesengine.log | tail -8
2016-06-08 12:12:18,300 140230543654096 INFO rulesengine [-] (PID=5826) RulesEngine started.
2016-06-08 12:12:18,301 140230543654096 INFO rulesengine [-] Timer is disabled.
--
2016-06-17 12:39:42,553 139752184933584 INFO rulesengine [-] (PID=525) RulesEngine started.
2016-06-17 12:39:42,554 139752184933584 INFO rulesengine [-] Timer is disabled.
--
2016-06-21 08:35:47,334 139798719732944 INFO rulesengine [-] (PID=31479) RulesEngine started.
2016-06-21 08:35:47,335 139798719732944 INFO rulesengine [-] Timer is disabled.
```

Now let's look at some errors.

The most recent "Failed to create trigger_instance" error (original from #2715) occurred on 2016-06-08. We haven't seen this since we updated, but we also didn't see it between 06-08 (when we reset the triggers in mongodb) and the upgrade on 06-17. First, note that the old issues also appear on both nodes with and without the timer enabled.

```
pstack3:~$ grep "Failed to create trigger_instance" /plogs/st2/st2rulesengine.log  | grep "^2016-06-" | tail -1
2016-06-08 03:00:00,016 139845580057648 ERROR worker [-] Failed to create trigger_instance {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7f30561dc350>, 'trigger': {'uid': u'trigger:core:65d02cf0-b01c-4e78-a904-daf1893f1e37:91302ea65fcee79862b663963e207d22', 'parameters': {u'hour': 3, u'minute': 0}, 'description': None, 'ref_count': 0, 'name': u'65d02cf0-b01c-4e78-a904-daf1893f1e37', 'type': u'core.st2.CronTimer', 'id': '572aaca559e5f159727c5134', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-08 08:00:00.009770+00:00', 'schedule': None}}.

pstack4:~$ grep "Failed to create trigger_instance" /plogs/st2/st2rulesengine.log  | grep "^2016-06-" | tail -1
2016-06-08 12:09:10,872 140006417108176 ERROR worker [-] Failed to create trigger_instance {'trace_context': None, 'trigger': 'core.st2.sensor.process_spawn', 'payload': {'timestamp': 1465405750, 'cmd': u'/opt/stackstorm/virtualenvs/trading/bin/python /opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py --pack=trading --file-path=/opt/stackstorm/packs/trading/sensors/hours.py --class-name=MarketHoursSensor --trigger-type-refs=trading.market.open,trading.market.close --parent-args=["--config-file", "/etc/st2/st2.conf"]', 'pid': 14766, 'id': u'MarketHoursSensor'}}.
```

For this issue, we were seeing failures to create trigger_instances for both CronTimer and sensor.process_spawn. (We had 13 CronTimer failures on June 8th and 1 sensor.process_spawn on pstack4 and 7 CronTimer failures on pstack3)

But it looks like **we started seeing "StagedQueueConsumer failed to process message" issues immediately after the upgrade on June 17th**. Also, you can see below that these new errors appear on the node with and without timer enabled.

```
pstack3:~$ grep "StagedQueueConsumer failed to process message" /plogs/st2/st2rulesengine.log
2016-06-17 13:30:00,029 140338077878864 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7fa301131f10>, 'trigger': {'uid': u'trigger:core:9c00c30d-7422-457b-9042-f181e0566103:db2bf78158a18a6ea544effecf45c8e7', 'parameters': {u'minute': 30, u'hour': 13}, 'description': None, 'ref_count': 1, 'name': u'9c00c30d-7422-457b-9042-f181e0566103', 'type': u'core.st2.CronTimer', 'id': '5758522759e5f13ee808f2dc', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-17 18:30:00.002170+00:00', 'schedule': None}}
2016-06-17 21:15:00,021 140338077878864 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7fa30121f2d0>, 'trigger': {'uid': u'trigger:core:2b9cf27e-d2a3-452f-b293-78c6e01700fa:5f56ffb96ed14a08d578383f8a365587', 'parameters': {u'minute': 15, u'hour': 21}, 'description': None, 'ref_count': 1, 'name': u'2b9cf27e-d2a3-452f-b293-78c6e01700fa', 'type': u'core.st2.CronTimer', 'id': '5758522859e5f13ee808f2de', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-18 02:15:00.005433+00:00', 'schedule': None}}
2016-06-18 06:30:00,014 140338077878864 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7fa301186650>, 'trigger': {'uid': u'trigger:core:aab6e071-a464-4288-b962-30ec37d83cf2:a0e7c2879668bb12ef7e519b29742d2f', 'parameters': {u'minute': 30, u'hour': 6}, 'description': None, 'ref_count': 1, 'name': u'aab6e071-a464-4288-b962-30ec37d83cf2', 'type': u'core.st2.CronTimer', 'id': '5758522859e5f13ee808f2e0', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-18 11:30:00.005416+00:00', 'schedule': None}}
2016-06-18 13:30:00,012 140338077878864 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7fa300e35810>, 'trigger': {'uid': u'trigger:core:9c00c30d-7422-457b-9042-f181e0566103:db2bf78158a18a6ea544effecf45c8e7', 'parameters': {u'minute': 30, u'hour': 13}, 'description': None, 'ref_count': 1, 'name': u'9c00c30d-7422-457b-9042-f181e0566103', 'type': u'core.st2.CronTimer', 'id': '5758522759e5f13ee808f2dc', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-18 18:30:00.003753+00:00', 'schedule': None}}
2016-06-19 02:15:00,015 140338077878864 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7fa30106e5d0>, 'trigger': {'uid': u'trigger:core:d4dc7bfd-c7b6-4c8f-8d39-bf0db9387378:184474b72fcfb6391b701239c1323bd2', 'parameters': {u'minute': 15, u'hour': 2}, 'description': None, 'ref_count': 1, 'name': u'd4dc7bfd-c7b6-4c8f-8d39-bf0db9387378', 'type': u'core.st2.CronTimer', 'id': '5758522859e5f13ee808f2ec', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-19 07:15:00.005560+00:00', 'schedule': None}}
2016-06-19 13:30:00,010 140338077878864 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7fa300e90950>, 'trigger': {'uid': u'trigger:core:9c00c30d-7422-457b-9042-f181e0566103:db2bf78158a18a6ea544effecf45c8e7', 'parameters': {u'minute': 30, u'hour': 13}, 'description': None, 'ref_count': 1, 'name': u'9c00c30d-7422-457b-9042-f181e0566103', 'type': u'core.st2.CronTimer', 'id': '5758522759e5f13ee808f2dc', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-19 18:30:00.002391+00:00', 'schedule': None}}
2016-06-20 02:15:00,011 140338077878864 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7fa300e90950>, 'trigger': {'uid': u'trigger:core:d4dc7bfd-c7b6-4c8f-8d39-bf0db9387378:184474b72fcfb6391b701239c1323bd2', 'parameters': {u'minute': 15, u'hour': 2}, 'description': None, 'ref_count': 1, 'name': u'd4dc7bfd-c7b6-4c8f-8d39-bf0db9387378', 'type': u'core.st2.CronTimer', 'id': '5758522859e5f13ee808f2ec', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-20 07:15:00.002450+00:00', 'schedule': None}}
2016-06-20 06:30:00,014 140338077878864 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7fa300fc6b90>, 'trigger': {'uid': u'trigger:core:aab6e071-a464-4288-b962-30ec37d83cf2:a0e7c2879668bb12ef7e519b29742d2f', 'parameters': {u'minute': 30, u'hour': 6}, 'description': None, 'ref_count': 1, 'name': u'aab6e071-a464-4288-b962-30ec37d83cf2', 'type': u'core.st2.CronTimer', 'id': '5758522859e5f13ee808f2e0', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-20 11:30:00.004565+00:00', 'schedule': None}}
2016-06-20 13:30:00,021 140338077878864 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7fa300f96b90>, 'trigger': {'uid': u'trigger:core:9c00c30d-7422-457b-9042-f181e0566103:db2bf78158a18a6ea544effecf45c8e7', 'parameters': {u'minute': 30, u'hour': 13}, 'description': None, 'ref_count': 1, 'name': u'9c00c30d-7422-457b-9042-f181e0566103', 'type': u'core.st2.CronTimer', 'id': '5758522759e5f13ee808f2dc', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-20 18:30:00.005895+00:00', 'schedule': None}}
2016-06-21 21:15:00,021 140040664910416 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7f5dc1d349d0>, 'trigger': {'uid': u'trigger:core:28fbb9e7-2207-4d6f-b114-ed7f75270a88:025fd26f9f12c07d9f0f5f5aed35150a', 'parameters': {u'minute': u'15', u'hour': u'21'}, 'description': None, 'ref_count': 1, 'name': u'28fbb9e7-2207-4d6f-b114-ed7f75270a88', 'type': u'core.st2.CronTimer', 'id': '57685af7f469fc5dc1a43774', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-22 02:15:00.002165+00:00', 'schedule': None}}
2016-06-22 06:30:00,018 140040664910416 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7f5dc1d67d10>, 'trigger': {'uid': u'trigger:core:f956f3de-e7f6-41b1-b32c-2fd38f8807c5:cf6f92443f5771e8b96e5f237a3d2817', 'parameters': {u'minute': 30, u'hour': 6, u'day_of_week': u'mon-fri'}, 'description': None, 'ref_count': 1, 'name': u'f956f3de-e7f6-41b1-b32c-2fd38f8807c5', 'type': u'core.st2.CronTimer', 'id': '57685af8f469fc5dc1a43776', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-22 11:30:00.006804+00:00', 'schedule': None}}

pstack4:~$ grep "StagedQueueConsumer failed to process message" /plogs/st2/st2rulesengine.log | head -1
2016-06-17 13:48:00,028 139752088832432 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7f1a916b4dd0>, 'trigger': {'uid': u'trigger:core:dfb6ebf1-7b99-411a-a379-52935b9b9709:00a0cd535d41e10305568f7cc98abeef', 'parameters': {u'minute': 48, u'hour': 13, u'day_of_week': 4}, 'description': None, 'ref_count': 1, 'name': u'dfb6ebf1-7b99-411a-a379-52935b9b9709', 'type': u'core.st2.CronTimer', 'id': '5758522859e5f13ee808f2e4', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-17 18:48:00.019587+00:00', 'schedule': None}}

pstack4:~$ grep "StagedQueueConsumer failed to process message" /plogs/st2/st2rulesengine.log | tail -1
2016-06-22 03:00:00,021 139798623631792 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7f2566ec8590>, 'trigger': {'uid': u'trigger:core:c64a9845-e548-400e-b88d-1c9a350ee273:e6d9bf27b0ede4bf3d03616c685a1e38', 'parameters': {u'day_of_week': u'0-4', u'minute': 0, u'hour': 3}, 'description': None, 'ref_count': 1, 'name': u'c64a9845-e548-400e-b88d-1c9a350ee273', 'type': u'core.st2.CronTimer', 'id': '57685796f469fc3bc217ea3d', 'pack': u'core'}, 'payload': {'executed_at': '2016-06-22 08:00:00.011584+00:00', 'schedule': None}}
```

So that's all the context that I can think of to share without digging more directly into mongo. Let me know if any other data would be helpful and I'm happy to provide. :)

**Comment by codyaray** [comment]
For the record (from the other issue), here's what I did just now to hopefully clear things up:
> Just ran db.trigger_d_b.remove() on mongo master, sudo st2ctl restart on each node, and then ran st2ctl reload --register-all

Got an error on reload: `A simple trigger should have been created when registering triggertype. Cannot create trigger`. Had to manually re-add some other stuff:

```
st2 trigger delete check_mk.event_handler
st2 trigger create triggers/event_handler.yaml
```

Then the reload worked as expected.

Here's hoping it works *fingers crossed*

**Comment by codyaray** [comment]
This happened again this morning.

![](https://s32.postimg.org/hu7ipm4w5/Screen_Shot_2016_06_27_at_12_51_05_PM.png)

**Comment by Kami** [comment]
@codyaray Thanks for the great and extensive (bug) report.

As mentioned the other day, it might take a while till we go to it so please hold tight.

I will also make sure one of our next tasks also is mongoengine and pymongone upgrade, this should hopefully resolve some of those not found looked related issues.

**Comment by codyaray** [comment]
Bad news guys. This just hit our second StackStorm cluster as well. All 200+ scheduled jobs silently failed to run. Also running 1.5dev-98. This cluster has been through fewer unstable upgrades and hadn't seen this issue at all until last night. The only thing that changed was I switched the mongodb connection string and was testing mongodb failover with ya'll yesterday. There definitely seem to be a bug here. This kind of bug is a show-stopper for us. :'(

EDIT: reviewing old logs, this had happened in this cluster a few times previously as well. I just didn't notice it apparently.

**Comment by codyaray** [comment]
We've had one rule hit this issue since the patch. Not sure if this should still be expected or not.

```
2016-07-09 14:37:07,019 139767544646384 ERROR consumers [-] StagedQueueConsumer failed to process message: {'trace_context': <st2common.models.api.trace.TraceContext object at 0x7f1e2aa4e410>, 'trigger': {'uid': u'trigger:core:551eb127-1ea5-41d3-819b-31622d43a733:425f230deef6d69b5555fc811ae3be29', 'parameters': {u'minute': u'*', u'hour': u'*', u'day': u'*'}, 'description': None, 'ref_count': 1, 'name': u'551eb127-1ea5-41d3-819b-31622d43a733', 'type': u'core.st2.CronTimer', 'id': '5776af1170608e5712db92e7', 'pack': u'core'}, 'payload': {'executed_at': '2016-07-09 19:37:00.001592+00:00', 'schedule': None}}
```

**Comment by Kami** [comment]
This shouldn't happen anymore unless there is something else going on. The object contains the id and uid so it should be looked up by it.

**Comment by Kami** [comment]
@codyaray How is this thing looking? Can this issue be closed now?

**Comment by codyaray** [comment]
I think we can close it.  I haven't ran into a case where *all* my jobs
have failed since then (*knock on wood*) but I have seen this message at
least once more. I'll let you know if it comes back up. Thanks!

**Comment by Kami** [comment]
Great to hear that and thanks again for reporting and following up on this :)

I also hope we can get rid of the nasty mongoengine caching related work-around I added a while back in v1.6 where we use newer version of mongoengine.
