### ISSUE TITLE
Broker connection error should be ERROR not WARNING

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2#2776]
These broker connection errors should probably be logged at ERROR level rather than WARNING level currently.

![Uploading Screen Shot 2016-06-23 at 12.36.16 PM 1.png…](https://s32.postimg.org/wzggpn6ph/Screen_Shot_2016_06_23_at_12_36_16_PM_1.png)

Not high priority.

**Comment by longfei-zhang** [comment]
I met this issue recently:
```
2018-05-26 06:05:15,245 WARNING [-] Broker connection error, trying again in 32.0 seconds: timeout('timed out',).
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/kombu/utils/functional.py", line 333, in retry_over_time
    return fun(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/kombu/connection.py", line 261, in connect
    return self.connection
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/amqp/connection.py", line 282, in connect
    self.transport.connect()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/amqp/transport.py", line 109, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/amqp/transport.py", line 150, in _connect
    self.sock.connect(sa)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/eventlet/greenio/base.py", line 252, in connect
    timeout_exc=socket.timeout("timed out"))
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/eventlet/greenio/base.py", line 203, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 162, in trampoline
    return hub.switch()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
timeout: timed out
```
here are the error msg in MQ side:
```
2018-05-26 12:06:27.721 [info] <0.5532.2> accepting AMQP connection <0.5532.2> (10.233.64.234:52784 -> 10.233.64.163:5672)
2018-05-26 12:06:27.722 [warning] <0.5532.2> closing AMQP connection <0.5532.2> (10.233.64.234:52784 -> 10.233.64.163:5672):
{handshake_timeout,handshake}
```

**Comment by winem** [comment]
Still the case for st2 v3.5.0
