### ISSUE TITLE
Concurrency lock is stuck and I am unable to remove it.

### ISSUE THREAD

**Issue by JohnWelborn** [StackStorm/st2#2843]
I created a concurrency.attr policy that cancels the workflow if more than one request is made for the same server. Even though nothing is running, it is still killing executions with the same workflow and attr. I have not found a way to clear it from this state.

Also, the default zookeeper does not work with nodes that have spaces in the name.

This situation may have started when a workflow became stuck running in st2 after it failed in mistral.

cat policy_workflow_uber_status.yaml

```
name: workflow_uber_status.concurrency
description: Limits the workflow to only run one request per machine.
enabled: true
resource_ref: ec.workflow_uber_status
policy_type: action.concurrency.attr
parameters:
    action: cancel
    threshold: 1
    attributes:
        - server
```

"st2 execution list|grep run" is empty

I've tried deleting the zookeeper lock node but it just comes back and the workflow is still canceled:
zookeepercli -servers localhost -c delete '/tooz/locks/{"action": "ec.workflow_uber_status", "attributes": ["server"], "policy_type": "action.concurrency.attr"}'

I've tried deleting /var/lib/zookeeper/version-2/ and restarting zookeeper and st2.

/var/log/st2/st2notifier.log

```
2016-08-01 19:22:10,170 140655748461904 DEBUG notifier [-] Processing liveaction 579fa162f2bcb53fe9ccaa0e (live_action_db={'status': u'canceled', 'start_timestamp': '2016-0
8-01 19:22:10.014420+00:00', 'parameters': {u'status': u'maintenance_cold', u'quiet': True, u'server': u'cache1.bnj'}, 'runner_info': {}, 'callback': {}, 'notify': None, 'r
esult': {}, 'context': {u'trace_context': {u'id_': u'579f8dd0f2bcb521d9dbb64a'}, u're-run': {u'ref': u'579f9eb2f2bcb53fe9ccaa0d'}, u'user': u'jwelborn'}, 'action': u'ec.wor
kflow_uber_status', 'id': '579fa162f2bcb53fe9ccaa0e', 'end_timestamp': None})
2016-08-01 19:22:10,192 140655748461904 DEBUG notifier [-] Applying 1 post_run policies
2016-08-01 19:22:10,194 140655748461904 DEBUG notifier [-] Applying post_run policy "ec.workflow_uber_status.concurrency" (action.concurrency.attr) for liveaction 579fa162f
2bcb53fe9ccaa0e
2016-08-01 19:22:10,194 140655748461904 DEBUG concurrency_by_attr [-] ConcurrencyByAttributeApplicator is attempting to acquire lock "{"action": "ec.workflow_uber_status", 
"attributes": ["server"], "policy_type": "action.concurrency.attr"}".
2016-08-01 19:22:10,197 140655753943792 DEBUG connection [-] Sending request(xid=82): Exists(path=u'/tooz/locks/{"action": "ec.workflow_uber_status", "attributes": ["server
"], "policy_type": "action.concurrency.attr"}', watcher=None)
2016-08-01 19:22:10,199 140655753943792 DEBUG connection [-] Received response(xid=82): ZnodeStat(czxid=1958, mzxid=1958, ctime=1470075435216, mtime=1470075435216, version=
0, cversion=21, aversion=0, ephemeralOwner=0, dataLength=0, numChildren=1, pzxid=2015)
2016-08-01 19:22:10,200 140655753943792 DEBUG connection [-] Sending request(xid=83): Create(path=u'/tooz/locks/{"action": "ec.workflow_uber_status", "attributes": ["server
"], "policy_type": "action.concurrency.attr"}/f96bf4d5f90c4c6baa6afb73ae31b4c2__lock__', data='[REDACTED_HOST]_16173', acl=[ACL(perms=31, acl_list=['ALL'], id=Id(scheme='worl
d', id='anyone'))], flags=3)
2016-08-01 19:22:10,202 140655753943792 DEBUG connection [-] Received response(xid=83): u'/tooz/locks/{"action": "ec.workflow_uber_status", "attributes": ["server"], "polic
y_type": "action.concurrency.attr"}/f96bf4d5f90c4c6baa6afb73ae31b4c2__lock__0000000011'
2016-08-01 19:22:10,203 140655753943792 DEBUG connection [-] Sending request(xid=84): GetChildren(path=u'/tooz/locks/{"action": "ec.workflow_uber_status", "attributes": ["s
erver"], "policy_type": "action.concurrency.attr"}', watcher=None)
2016-08-01 19:22:10,204 140655753943792 DEBUG connection [-] Received response(xid=84): [u'd725f01e35584007b6a73918ae26a293__lock__0000000010', u'f96bf4d5f90c4c6baa6afb73ae
31b4c2__lock__0000000011']
2016-08-01 19:22:10,204 140655753943792 DEBUG connection [-] Sending request(xid=85): Exists(path=u'/tooz/locks/{"action": "ec.workflow_uber_status", "attributes": ["server
"], "policy_type": "action.concurrency.attr"}/d725f01e35584007b6a73918ae26a293__lock__0000000010', watcher=<bound method Lock._watch_predecessor of <kazoo.recipe.lock.Lock 
object at 0x7fecf7f01550>>)
2016-08-01 19:22:10,205 140655753943792 DEBUG connection [-] Received response(xid=85): ZnodeStat(czxid=2015, mzxid=2015, ctime=1470079330138, mtime=1470079330138, version=
0, cversion=0, aversion=0, ephemeralOwner=96342862191394825, dataLength=19, numChildren=0, pzxid=2015)
2016-08-01 19:22:10,206 140655753943792 DEBUG connection [-] Sending request(xid=86): GetChildren(path=u'/tooz/locks/{"action": "ec.workflow_uber_status", "attributes": ["s
erver"], "policy_type": "action.concurrency.attr"}', watcher=None)
2016-08-01 19:22:10,207 140655753943792 DEBUG connection [-] Received response(xid=86): [u'd725f01e35584007b6a73918ae26a293__lock__0000000010', u'f96bf4d5f90c4c6baa6afb73ae
31b4c2__lock__0000000011']
2016-08-01 19:22:10,208 140655753943792 DEBUG connection [-] Sending request(xid=87): Delete(path=u'/tooz/locks/{"action": "ec.workflow_uber_status", "attributes": ["server
"], "policy_type": "action.concurrency.attr"}/f96bf4d5f90c4c6baa6afb73ae31b4c2__lock__0000000011', version=-1)
2016-08-01 19:22:10,210 140655753943792 DEBUG connection [-] Received response(xid=87): True
2016-08-01 19:22:10,210 140655748461904 ERROR notifier [-] An exception occurred while applying policy "ec.workflow_uber_status.concurrency".
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/notifier/notifier.py", line 254, in _apply_post_run_policies
    liveaction = driver.apply_after(liveaction)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/policies/concurrency_by_attr.py", line 136, in apply_after
    with self.coordinator.get_lock(lock_uid):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/locking.py", line 35, in __enter__
    self.acquire()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/drivers/zookeeper.py", line 56, in acquire
    return _lock()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/drivers/zookeeper.py", line 49, in _lock
    timeout=0):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kazoo/recipe/lock.py", line 170, in acquire
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kazoo/recipe/lock.py", line 160, in acquire
    blocking=blocking, timeout=timeout)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kazoo/retry.py", line 123, in __call__
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kazoo/recipe/lock.py", line 240, in _inner_acquire
    "%s seconds" % (self.path, timeout))
LockTimeout: Failed to acquire lock on /tooz/locks/{"action": "ec.workflow_uber_status", "attributes": ["server"], "policy_type": "action.concurrency.attr"} after 0 seconds
2016-08-01 19:22:10,229 140655748461904 DEBUG notifier [-] POSTing st2.generic.actiontrigger for 579fa162f2bcb53fe9ccaa0e. Payload - {'status': u'canceled', 'start_timestamp': '2016-08-01 19:22:10.014420+00:00', 'result': {}, 'parameters': {u'status': u'maintenance_cold', u'quiet': True, u'server': u'cache1.bnj'}, 'action_ref': u'ec.workflow_uber_status', 'runner_ref': u'mistral-v2', 'execution_id': '579fa162f2bcb53fe9ccaa0f', 'action_name': u'ec.workflow_uber_status'}. TraceContext - {id_: 579f8dd0f2bcb521d9dbb64a, trace_tag: execution-579f8dd0f2bcb521d9dbb648}
2016-08-01 19:22:10,229 140655748461904 DEBUG reactor [-] Dispatching trigger (trigger=core.st2.generic.actiontrigger,payload={'trace_context': <st2common.models.api.trace.TraceContext object at 0x7fecf7ee5350>, 'trigger': 'core.st2.generic.actiontrigger', 'payload': {'status': u'canceled', 'start_timestamp': '2016-08-01 19:22:10.014420+00:00', 'result': {}, 'parameters': {u'status': u'maintenance_cold', u'quiet': True, u'server': u'cache1.bnj'}, 'action_ref': u'ec.workflow_uber_status', 'runner_ref': u'mistral-v2', 'execution_id': '579fa162f2bcb53fe9ccaa0f', 'action_name': u'ec.workflow_uber_status'}})
2016-08-01 19:22:10,230 140655748461904 DEBUG channel [-] using channel_id: 1
2016-08-01 19:22:10,231 140655753943792 DEBUG connection [-] Received EVENT: Watch(type=2, state=3, path=u'/tooz/locks/{"action": "ec.workflow_uber_status", "attributes": ["server"], "policy_type": "action.concurrency.attr"}/d725f01e35584007b6a73918ae26a293__lock__0000000010')
```

/var/log/st2/st2actionrunner.16116.audit.log

```
{"asctime": "2016-08-01 19:22:10,129", "thread": 140401311456144, "levelname": "INFO", "module": "client", "message":          "Zookeeper connection established, state: CONNECTED"}
{"asctime": "2016-08-01 19:22:10,133", "thread": 140401311456144, "levelname": "DEBUG", "module": "connection", "message":     "Sending request(xid=1): Exists(path=u'/tooz', watcher=None)"}
{"asctime": "2016-08-01 19:22:10,134", "thread": 140401311456144, "levelname": "DEBUG", "module": "connection", "message":     "Received response(xid=1): ZnodeStat(czxid=2, mzxid=2, ctime=1469815437041, mtime=1469815437041, version=0, cversion=1, aversion=0, ephemeralOwner=0, dataLength=0,         numChildren=1, pzxid=3)"}
{"asctime": "2016-08-01 19:22:10,135", "thread": 140401325317488, "levelname": "DEBUG", "module": "concurrency_by_attr",       "message": "ConcurrencyByAttributeApplicator is attempting to acquire lock \"{\"action\": \"ec.workflow_uber_status\", \"attributes\": [\"server\"], \"policy_type\":       \"action.concurrency.attr\"}\"."}
{"asctime": "2016-08-01 19:22:10,136", "thread": 140401311456144, "levelname": "DEBUG", "module": "connection", "message":     "Sending request(xid=2): Exists(path=u'/tooz/locks/{\"action\": \"ec.workflow_uber_status\", \"attributes\": [\"server\"], \"policy_type\": \"action.concurrency.attr\"}',  watcher=None)"}
{"asctime": "2016-08-01 19:22:10,137", "thread": 140401311456144, "levelname": "DEBUG", "module": "connection", "message":     "Received response(xid=2): ZnodeStat(czxid=1958, mzxid=1958, ctime=1470075435216, mtime=1470075435216, version=0, cversion=20, aversion=0, ephemeralOwner=0, dataLength=0,  numChildren=0, pzxid=2009)"}
{"asctime": "2016-08-01 19:22:10,138", "thread": 140401311456144, "levelname": "DEBUG", "module": "connection", "message":     "Sending request(xid=3): Create(path=u'/tooz/locks/{\"action\": \"ec.workflow_uber_status\", \"attributes\": [\"server\"], \"policy_type\": \"action.concurrency.attr\"}/   d725f01e35584007b6a73918ae26a293__lock__', data='[HOSTNAME_REDACT]_16116', acl=[ACL(perms=31, acl_list=['ALL'], id=Id(scheme='world', id='anyone'))], flags=3)"}
{"asctime": "2016-08-01 19:22:10,140", "thread": 140401311456144, "levelname": "DEBUG", "module": "connection", "message":     "Received response(xid=3): u'/tooz/locks/{\"action\": \"ec.workflow_uber_status\", \"attributes\": [\"server\"], \"policy_type\": \"action.concurrency.attr\"}/             d725f01e35584007b6a73918ae26a293__lock__0000000010'"}
{"asctime": "2016-08-01 19:22:10,141", "thread": 140401311456144, "levelname": "DEBUG", "module": "connection", "message":     "Sending request(xid=4): GetChildren(path=u'/tooz/locks/{\"action\": \"ec.workflow_uber_status\", \"attributes\": [\"server\"], \"policy_type\": \"action.concurrency.      attr\"}', watcher=None)"}
{"asctime": "2016-08-01 19:22:10,142", "thread": 140401311456144, "levelname": "DEBUG", "module": "connection", "message":     "Received response(xid=4): [u'd725f01e35584007b6a73918ae26a293__lock__0000000010']"}
{"asctime": "2016-08-01 19:22:10,145", "thread": 140401325317488, "levelname": "DEBUG", "module": "concurrency_by_attr",       "message": "There are 1 instances of ec.workflow_uber_status in scheduled or running status. Threshold of ec.workflow_uber_status.concurrency is reached. Action execution  will be canceled."}
{"asctime": "2016-08-01 19:22:10,147", "thread": 140401325317488, "levelname": "DEBUG", "module": "action_db", "message":      "Updating ActionExection: \"579fa162f2bcb53fe9ccaa0e\" with status=\"canceled\""}
{"asctime": "2016-08-01 19:22:10,159", "thread": 140401325317488, "levelname": "DEBUG", "module": "channel", "message": "using channel_id: 1"}
{"asctime": "2016-08-01 19:22:10,160", "thread": 140401325317488, "levelname": "DEBUG", "module": "channel", "message":        "Channel open"}
{"asctime": "2016-08-01 19:22:10,163", "thread": 140401325317488, "levelname": "DEBUG", "module": "channel", "message":        "Closed channel #1"}
{"asctime": "2016-08-01 19:22:10,169", "thread": 140401325317488, "levelname": "DEBUG", "module": "action_db", "message":      "Updated status for LiveAction object."}
{"asctime": "2016-08-01 19:22:10,193", "thread": 140401325317488, "levelname": "DEBUG", "module": "channel", "message": "using channel_id: 1"}
{"asctime": "2016-08-01 19:22:10,195", "thread": 140401325317488, "levelname": "DEBUG", "module": "channel", "message":        "Channel open"}
{"asctime": "2016-08-01 19:22:10,198", "thread": 140401325317488, "levelname": "DEBUG", "module": "channel", "message":        "Closed channel #1"}
{"asctime": "2016-08-01 19:22:10,199", "thread": 140401325317488, "levelname": "AUDIT", "module": "action", "message": "The    status of action execution is changed from requested to canceled. <LiveAction.id=579fa162f2bcb53fe9ccaa0e, ActionExecution.id=579fa162f2bcb53fe9ccaa0f>"}
{"asctime": "2016-08-01 19:22:10,222", "thread": 140401325317488, "levelname": "INFO", "module": "action", "message": "The     status of action execution is changed from requested to canceled. <LiveAction.id=579fa162f2bcb53fe9ccaa0e, ActionExecution.id=579fa162f2bcb53fe9ccaa0f>"}
```

/var/log/st2/st2actionrunner.16116.log

```
2016-08-01 19:22:10,129 140401311456144 INFO client [-] Zookeeper connection established, state: CONNECTED
2016-08-01 19:22:10,133 140401311456144 DEBUG connection [-] Sending request(xid=1): Exists(path=u'/tooz', watcher=None)
2016-08-01 19:22:10,134 140401311456144 DEBUG connection [-] Received response(xid=1): ZnodeStat(czxid=2, mzxid=2,                   ctime=1469815437041, mtime=1469815437041, version=0, cversion=1, aversion=0, ephemeralOwner=0, dataLength=0, numChildren=1, pzxid=3)
2016-08-01 19:22:10,135 140401325317488 DEBUG concurrency_by_attr [-] ConcurrencyByAttributeApplicator is attempting to acquire lock "{"action": "ec.workflow_uber_status", "attributes": ["server"], "policy_type": "action.concurrency.attr"}".
2016-08-01 19:22:10,136 140401311456144 DEBUG connection [-] Sending request(xid=2): Exists(path=u'/tooz/locks/{"action": "ec.       workflow_uber_status", "attributes": ["server"], "policy_type": "action.concurrency.attr"}', watcher=None)
2016-08-01 19:22:10,137 140401311456144 DEBUG connection [-] Received response(xid=2): ZnodeStat(czxid=1958, mzxid=1958,             ctime=1470075435216, mtime=1470075435216, version=0, cversion=20, aversion=0, ephemeralOwner=0, dataLength=0, numChildren=0, pzxid=2009)
2016-08-01 19:22:10,138 140401311456144 DEBUG connection [-] Sending request(xid=3): Create(path=u'/tooz/locks/{"action": "ec.       workflow_uber_status", "attributes": ["server"], "policy_type": "action.concurrency.attr"}/d725f01e35584007b6a73918ae26a293__lock__', data='[HOSTNAME_REDACT]_16116',           acl=[ACL(perms=31, acl_list=['ALL'], id=Id(scheme='world', id='anyone'))], flags=3)
2016-08-01 19:22:10,140 140401311456144 DEBUG connection [-] Received response(xid=3): u'/tooz/locks/{"action": "ec.                 workflow_uber_status", "attributes": ["server"], "policy_type": "action.concurrency.attr"}/d725f01e35584007b6a73918ae26a293__lock__0000000010'
2016-08-01 19:22:10,141 140401311456144 DEBUG connection [-] Sending request(xid=4): GetChildren(path=u'/tooz/locks/{"action": "ec.  workflow_uber_status", "attributes": ["server"], "policy_type": "action.concurrency.attr"}', watcher=None)
2016-08-01 19:22:10,142 140401311456144 DEBUG connection [-] Received response(xid=4):                                               [u'd725f01e35584007b6a73918ae26a293__lock__0000000010']
2016-08-01 19:22:10,145 140401325317488 DEBUG concurrency_by_attr [-] There are 1 instances of ec.workflow_uber_status in scheduled  or running status. Threshold of ec.workflow_uber_status.concurrency is reached. Action execution will be canceled.
2016-08-01 19:22:10,147 140401325317488 DEBUG action_db [-] Updating ActionExection: "579fa162f2bcb53fe9ccaa0e" with                 status="canceled" (liveaction_db={'status': u'requested', 'start_timestamp': '2016-08-01 19:22:10.014420+00:00', 'parameters': {u'status': u'maintenance_cold', u'quiet':   True, u'server': u'cache1.bnj'}, 'runner_info': {}, 'callback': {}, 'notify': None, 'result': {}, 'context': {u'trace_context': {u'id_': u'579f8dd0f2bcb521d9dbb64a'}, u're-run': {u'ref': u'579f9eb2f2bcb53fe9ccaa0d'}, u'user': u'jwelborn'}, 'action': u'ec.workflow_uber_status', 'id': '579fa162f2bcb53fe9ccaa0e', 'end_timestamp': None})
2016-08-01 19:22:10,159 140401325317488 DEBUG channel [-] using channel_id: 1
2016-08-01 19:22:10,160 140401325317488 DEBUG channel [-] Channel open
2016-08-01 19:22:10,163 140401325317488 DEBUG channel [-] Closed channel #1
```

**Comment by LindsayHill** [comment]
Lots of code has changed in the last couple of years - I don't think it's worth going down the rabbit hole of trying to reproduce this, when we're not seeing any other similar recent reports. Can re-open if needed.
