### ISSUE TITLE
Error while building docker image

### ISSUE THREAD

**Issue by anpodila** [StackStorm/st2#2845]
Hi,

I am trying to build docker image using the command:
`st2 run docker.build_image dockerfile_path=/home/stanley`

Getting below error where are same Dockerfile is working if I try from docker build command. Anyone has tried this?  Can you help me in resolving?

``` py
.......
id: 57a0979e44ec770f95b82449
status: failed
parameters:
  dockerfile_path: /home/stanley
result:
  exit_code: 1
  result: null
  stderr: "Error: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 179, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 116, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/docker/actions/build_image.py", line 14, in run
    return self.wrapper.build(path=dockerfile_path, tag=tag)
  File "/opt/stackstorm/packs/docker/actions/lib/docker_wrapper.py", line 57, in build
    raise e
requests.packages.urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
"
  stdout: "Building docker container. Path = /home/stanley, Tag = None
```

**Comment by anpodila** [comment]
Hi Team,

Did you get any clue regarding this error. Still I am seeing the same error when I try to build image using st2 run docker.build_image.

**Comment by LindsayHill** [comment]
What does your Docker pack configuration look like? (`/opt/stackstorm/configs/docker.yaml`)
