### ISSUE TITLE
`|` operator in regex criteria for a rule doesn't work correctly.

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#2863]
Sample rule:

```
---
name: "log_failed_actions"
pack: "sentinel"
description: "Sends a failed StackStorm action to Sentinel (via logfile -> logstash)"
enabled: true
trigger:
  type: "core.st2.generic.actiontrigger"
criteria:
  trigger.action_name:
    type: "startswith"
    pattern: "core."
  trigger.status:
    type: "regex"
    pattern: "(failed|timeout)"
action:
  ref: "core.local_sudo"
  parameters:
    cmd: "echo '{{trigger.start_timestamp}} ERROR {{trigger.action_name}} {{trigger.status}} with error: {% trigger.result.stderr if trigger.status == 'failed' else trigger.result.error %}' >> /plogs/st2/sentinel.log"
```

No unit test available in https://github.com/StackStorm/st2/blob/master/st2common/tests/unit/test_operators.py

Reported by: @codyaray

**Comment by codyaray** [comment]
I take it back. This works:

```
---
name: "log_failed_actions"
pack: "sentinel"
description: "Sends a failed StackStorm action to Sentinel (via logfile -> logstash)"
enabled: true
trigger:
  type: "core.st2.generic.actiontrigger"
criteria:
  trigger.action_name:
    type: "startswith"
    pattern: "core."
  trigger.status:
    type: "regex"
    pattern: "(failed|timeout)"
action:
  ref: "core.local_sudo"
  parameters:
    cmd: "echo '{{trigger.start_timestamp}} ERROR {{trigger.action_name}} failed with error: {{trigger.result.stderr}}' >> /plogs/st2/sentinel.log"
```

Something else in the first one is preventing it from triggering. Seems like the only thing different is the `cmd`. Gonna keep digging.

**Comment by codyaray** [comment]
Okay, this is a `TemplateSyntaxError: Encountered unknown tag 'trigger'.`

I feel shame. I changed the trigger.status and the parameters at the same time.

```
2016-08-11 15:50:43,491 140034436430256 ERROR enforcer [-] Failed kicking off execution for rule RuleDB(action=ActionExecutionSpecDB@140034434814480(ref="core.local_sudo", parameters="{u'cmd': u"echo '{{trigger.start_timestamp}} ERROR {{trigger.action_name}} {{trigger.status}} with error: {% trigger.result.stderr if trigger.status == 'failed' else trigger.result.error %}' >> /plogs/st2/sentinel.log"}"), criteria={u'trigger.action_name': {u'pattern': u'core.', u'type': u'startswith'}, u'trigger.status': {u'pattern': u'(failed|timeout)', u'type': u'regex'}}, description="Sends a failed StackStorm action to Sentinel (via logfile -> logstash)", enabled=True, id=57acc68970608e18d66c09f5, name="log_failed_actions", pack="sentinel", ref="sentinel.log_failed_actions", tags=[], trigger="core.st2.generic.actiontrigger", type=RuleTypeSpecDB@140034434814096(ref="standard", parameters="{}"), uid="rule:sentinel:log_failed_actions").
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/rules/enforcer.py", line 74, in enforce
    execution_db = self._do_enforce()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/rules/enforcer.py", line 98, in _do_enforce
    params = self.get_resolved_parameters()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/rules/enforcer.py", line 62, in get_resolved_parameters
    return self.data_transformer(self.rule.action.parameters)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/rules/datatransform.py", line 32, in __call__
    return jinja_utils.render_values(mapping=mapping, context=context)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/util/jinja.py", line 193, in render_values
    raise e
TemplateSyntaxError: Encountered unknown tag 'trigger'. (_rule_db={'description': u'Sends a failed StackStorm action to Sentinel (via logfile -> logstash)', 'tags': [], 'ref': u'sentinel.log_failed_actions', 'enabled': True, 'name': u'log_failed_actions', 'trigger': u'core.st2.generic.actiontrigger', 'criteria': {u'trigger.action_name': {u'pattern': u'core.', u'type': u'startswith'}, u'trigger.status': {u'pattern': u'(failed|timeout)', u'type': u'regex'}}, 'action': 'ActionExecutionSpecDB@140034434814480(ref="core.local_sudo", parameters="{u\'cmd\': u"echo \'{{trigger.start_timestamp}} ERROR {{trigger.action_name}} {{trigger.status}} with error: {% trigger.result.stderr if trigger.status == \'failed\' else trigger.result.error %}\' >> /plogs/st2/sentinel.log"}")', 'pack': u'sentinel', 'type': 'RuleTypeSpecDB@140034434814096(ref="standard", parameters="{}")', 'id': '57acc68970608e18d66c09f5', 'uid': u'rule:sentinel:log_failed_actions'},_trigger_instance_db={'status': 'processing', 'occurrence_time': '2016-08-11 20:50:43.447097+00:00', 'trigger': u'core.st2.generic.actiontrigger', 'id': '57ace52370608e4ffd1b4e1a', 'payload': {'status': u'failed', 'start_timestamp': '2016-08-11 20:50:43.187671+00:00', 'parameters': {u'cmd': u'wtf'}, 'runner_ref': u'local-shell-cmd', 'action_name': u'core.local', 'result': {'failed': True, 'stderr': 'bash: wtf: command not found', 'return_code': 127, 'succeeded': False, 'stdout': ''}, 'action_ref': u'core.local', 'execution_id': '57ace52370608e5084ae401d'}})
2016-08-11 15:50:43,496 140034436430256 AUDIT enforcer [-] Rule enforcement failed. Execution of Action core.local_sudo failed. TriggerInstance: TriggerInstanceDB(id=57ace52370608e4ffd1b4e1a, occurrence_time="2016-08-11 20:50:43.447097+00:00", payload={'status': u'failed', 'start_timestamp': '2016-08-11 20:50:43.187671+00:00', 'parameters': {u'cmd': u'wtf'}, 'runner_ref': u'local-shell-cmd', 'action_name': u'core.local', 'result': {'succeeded': False, 'failed': True, 'return_code': 127, 'stderr': 'bash: wtf: command not found', 'stdout': ''}, 'action_ref': u'core.local', 'execution_id': '57ace52370608e5084ae401d'}, status="processing", trigger="core.st2.generic.actiontrigger") and Rule: RuleDB(action=ActionExecutionSpecDB@140034434814480(ref="core.local_sudo", parameters="{u'cmd': u"echo '{{trigger.start_timestamp}} ERROR {{trigger.action_name}} {{trigger.status}} with error: {% trigger.result.stderr if trigger.status == 'failed' else trigger.result.error %}' >> /plogs/st2/sentinel.log"}"), criteria={u'trigger.action_name': {u'pattern': u'core.', u'type': u'startswith'}, u'trigger.status': {u'pattern': u'(failed|timeout)', u'type': u'regex'}}, description="Sends a failed StackStorm action to Sentinel (via logfile -> logstash)", enabled=True, id=57acc68970608e18d66c09f5, name="log_failed_actions", pack="sentinel", ref="sentinel.log_failed_actions", tags=[], trigger="core.st2.generic.actiontrigger", type=RuleTypeSpecDB@140034434814096(ref="standard", parameters="{}"), uid="rule:sentinel:log_failed_actions") (rule_db={'description': u'Sends a failed StackStorm action to Sentinel (via logfile -> logstash)', 'tags': [], 'ref': u'sentinel.log_failed_actions', 'enabled': True, 'name': u'log_failed_actions', 'trigger': u'core.st2.generic.actiontrigger', 'criteria': {u'trigger.action_name': {u'pattern': u'core.', u'type': u'startswith'}, u'trigger.status': {u'pattern': u'(failed|timeout)', u'type': u'regex'}}, 'action': 'ActionExecutionSpecDB@140034434814480(ref="core.local_sudo", parameters="{u\'cmd\': u"echo \'{{trigger.start_timestamp}} ERROR {{trigger.action_name}} {{trigger.status}} with error: {% trigger.result.stderr if trigger.status == \'failed\' else trigger.result.error %}\' >> /plogs/st2/sentinel.log"}")', 'pack': u'sentinel', 'type': 'RuleTypeSpecDB@140034434814096(ref="standard", parameters="{}")', 'id': '57acc68970608e18d66c09f5', 'uid': u'rule:sentinel:log_failed_actions'},trigger_instance_db={'status': 'processing', 'occurrence_time': '2016-08-11 20:50:43.447097+00:00', 'trigger': u'core.st2.generic.actiontrigger', 'id': '57ace52370608e4ffd1b4e1a', 'payload': {'status': u'failed', 'start_timestamp': '2016-08-11 20:50:43.187671+00:00', 'parameters': {u'cmd': u'wtf'}, 'runner_ref': u'local-shell-cmd', 'action_name': u'core.local', 'result': {'failed': True, 'stderr': 'bash: wtf: command not found', 'return_code': 127, 'succeeded': False, 'stdout': ''}, 'action_ref': u'core.local', 'execution_id': '57ace52370608e5084ae401d'}})
```

**Comment by codyaray** [comment]
I have brought shame to my family. All I was missing was a `print`.

```
---
name: "log_failed_actions"
pack: "sentinel"
description: "Sends a failed StackStorm action to Sentinel (via logfile -> logstash)"
enabled: true
trigger:
  type: "core.st2.generic.actiontrigger"
criteria:
  trigger.action_name:
    type: "startswith"
    pattern: "core."
  trigger.status:
    type: "regex"
    pattern: "(failed|timeout)"
action:
  ref: "core.local_sudo"
  parameters:
    cmd: "echo '{{trigger.start_timestamp}} ERROR {{trigger.action_name}} {{trigger.status}} with error: {% print trigger.result.stderr if trigger.status == 'failed' else trigger.result.error %}' >> /plogs/st2/sentinel.log"
```

I'll go ahead, close this and cry.
