### ISSUE TITLE
Disabling the result section of an alias still calls chatops.post_result which fails

### ISSUE THREAD

**Issue by JohnWelborn** [StackStorm/st2#2873]
#cat alias_ping.yaml
```
name: "ping"
action_ref: "ec.host_pingable"
description: "Check if machine is pingable"
formats:
  - "ping {{server}}"
ack:
  enabled: false
result:
  enabled: false
```

```
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 179, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 116, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/chatops/actions/format_execution_result.py", line 42, in run
    raise Exception("Output of this template is disabled.")
Exception: Output of this template is disabled.
```

These expected failures make it difficult to monitor for other actual problems that cause failures.

Thanks

**Comment by Kami** [comment]
Thanks for the report.

This does indeed sound like a bug which we should fix.

/cc @lakshmi-kannan @emedvedev

**Comment by Kami** [comment]
Now that I think about it some more - we don't really have many options on the action level.

One option would be to utilize new ability of Python runner actions to return status flag and in this case instead of throwing we would log that output of this template is disabled and we would return something like `True, 'Output of this template is disabled`.

What do others think? /cc @lakshmi-kannan @emedvedev

**Comment by emedvedev** [comment]
Ideally, if the result output is disabled, then post_result shouldn't be called at all, so a clean solution to this problem wouldn't be on the action level. Status flag is fine, and if you submit a PR we can (and should) merge it, since it's better than what we have now, but then instead of "Disabling the result section of an alias still calls chatops.post_result which fails" we'll have "Disabling the result section of an alias still calls chatops.post_result," which is still a legit issue. :)

**Comment by Kami** [comment]
I agree, the problem with action not being called is that, afaik, is not achievable right now without the following:

1) One off change in the rules engine
2) Support for more flexible rule criteria - we would need to make alias some how available in the rule criteria context. I didn't really think much about it so don't even know if that's (easily) possible right now.

**Comment by emedvedev** [comment]
It's not possible without significant changes, that's mainly why we implemented it like that in the first place. I'm fine with the intermediate fix, just calling out that this is still somewhat of an issue that would be good to fix at some point.
