### ISSUE TITLE
st2rulesengine error: "skipped: maximum number of running instances reached"

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2#2893]
**version:** 1.5.1-1
**package:** ubuntu
**hardware:** 2 VMs with 8 CPUs, 8 GB ram each

My st2rulesengine timed jobs are all being `skipped: maximum number of running instances reach`.

I'm concerned that all of these "running" jobs are preventing all my cron jobs, implemented as pairs of st2.CronTimer rule and action, from kicking off over-night / in the morning. I want to get the DB into a state where this isn't a concern.

We have a bunch of actions which show that they're in the running state even though they're not actually running anymore. These actions are simple actionchain workflows which call core.remote actions. These are bad/leftover jobs which ran on Aug 26th and Aug 29th. Around that time, logstash on the box began taking up the whole CPU and causing StackStorm to queue their jobs for a time. We did a reboot to add memory across all hosts, which might have "orphaned" these scheduled jobs. I've confirmed on the remote host that these actions aren't running there anymore, so it seems like bad state in MongoDB. How do I clean up these "running" jobs so StackStorm starts working again?

It was suggested in #community to try canceling these actions, but the cancel call just hangs. When I control-C it, here's the stack trace that shows where its hung:

```
$ st2 execution cancel 57c483e53aa3793357009a68
^CTraceback (most recent call last):
  File "/usr/bin/st2", line 11, in <module>
    sys.exit(main())
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/shell.py", line 635, in main
    return Shell().run(argv)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/shell.py", line 374, in run
    args.func(args)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 44, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/action.py", line 1061, in run_and_print
    response = self.run(args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/action.py", line 1057, in run
    return self.manager.delete_by_id(args.id)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/models/core.py", line 37, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/models/core.py", line 303, in delete_by_id
    response = self.client.delete(url, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 33, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 51, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 106, in delete
    response = requests.delete(self.root + url, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/requests/api.py", line 149, in delete
    return request('delete', url, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 385, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
```

I've tried canceling several different actions and they all exhibit this hung behavior. It appears that the cancel commands are hanging waiting on a response from st2api. Here's the logs from the time I called `cancel` to the time that the command hung:

```
2016-09-08 16:24:20,722 139959830646288 INFO hooks [-] 7492c5c9-5b41-4656-b3b7-298ae60776b7 -  DELETE /v1/executions/57c483e43aa3793357009a5e with filters={} (remote_addr='127.0.0.1',method='DELETE',filters={},request_id='7492c5c9-5b41-4656-b3b7-298ae60776b7',path='/v1/executions/57c483e43aa3793357009a5e')
2016-09-08 16:24:20,723 139959830646288 AUDIT auth [-] Token provided in headers
​
==> /plogs/st2/st2api.audit.log <==
{"version": "1.1", "level": 6, "timestamp": 1473369860, "_python": {"process": 13319, "module": "auth", "funcName": "validate_token", "processName": "MainProcess", "lineno": 54, "filename": "auth.py"}, "host": "pvlchi6dstack1", "full_message": "Token provided in headers", "short_message": "Token provided in headers"}
​
==> /plogs/st2/st2api.log <==
2016-09-08 16:24:20,725 139959830646288 AUDIT auth [-] Token with id "57d1d69870608e344f9534f7" is validated.
​
==> /plogs/st2/st2api.audit.log <==
{"version": "1.1", "level": 6, "timestamp": 1473369860, "_python": {"process": 13319, "module": "auth", "funcName": "validate_token", "processName": "MainProcess", "lineno": 67, "filename": "auth.py"}, "host": "pvlchi6dstack1", "full_message": "Token with id \"57d1d69870608e344f9534f7\" is validated.", "short_message": "Token with id \"57d1d69870608e344f9534f7\" is validated."}
​
==> /plogs/st2/st2api.log <==
2016-09-08 16:24:20,745 139959830646288 INFO resource [-] GET /v1/executions/57c483e43aa3793357009a5e with id=57c483e43aa3793357009a5e
```

If I try to cancel a job that I previously control-C'd during cancel (when it was hung), I see this:
```
$ st2 execution cancel 57c483e33aa3793357009a5b
Action cannot be canceled. State = canceling.
```
but I still see it as `running` in `st2 execution list --status running`.

Querying MongoDB action_execution_d_b directly, I can see that I have 370ish jobs that are showing in running state. Looking through the list of actions, I can see that they're all short-lived. I've spot checked the remote hosts and haven't found any actions actually running.

Calling `st2 execution list --status canceling` shows nothing, even though attempting to cancel again shows "Action cannot be canceled. State = canceling."

The UI filtered by status:abandoned shows abandoned tasks up to the day that a lot (but not all) of these "running" jobs started (August 26th or 29th). Clicking a specific action within the actionchain shows that the actionchain workflow is abandoned, but the inner action is showing as scheduled. 

The UI filtered by status:running shows workflows that are "running" state but tasks that are "scheduled" state.

Its disturbing that the CLI hangs when canceling. The st2api logs look like GET /v1/executions/<id> endpoint doesn't return (or at least logging stops after this call is made-even if it finishes correctly). 

I went ahead and purged my executions so that I only have 196k executions in mongo now (deleted all before 2016-08-01), down from 321k. In comparison, my other cluster has 1.1 million. But I still have 376 executions in a "running" state.

 ```
db.action_execution_d_b.find({status:"running"}, {"action.name":1}).count()
376
```

When running the cancel operation, the API process and MongoDB process aren't using much CPU. 

<img width="592" alt="screen shot 2016-09-09 at 2 51 45 pm" src="https://cloud.githubusercontent.com/assets/44062/18400778/fc7b1d1a-769c-11e6-9278-7a20b008b738.png">

MongoStat also looks like MongoDB isn't doing much.

<img width="1196" alt="screen shot 2016-09-09 at 2 55 05 pm" src="https://cloud.githubusercontent.com/assets/44062/18400897/72de41c6-769d-11e6-955d-49b810c03896.png">

Can i just update all of those "status":"running" in MongoDB to something not-running? Will that fix apscheduler?

**Comment by codyaray** [comment]
Just ran this to update them all directly in mongodb. Let's hope it works.
(Tried on Friday but forgot "multi: true")

```
stackstorm-dev:PRIMARY> db.action_execution_d_b.update({"status":"running"}, {$set: {"status":"canceled"}}, {multi:true})
stackstorm-dev:PRIMARY> db.action_execution_d_b.find({"status":"running"}).count()
0
```

**Comment by Kami** [comment]
Thanks for the report.

It looks like there is a weird edge case with cancel - cancel should definitely work in this scenario. Just to confirm, you tried to cancel the parent action (workflow) or the child actions (actions inside the workflow)?

**Comment by Kami** [comment]
I wasn't able to reproduce the canceling issue.

I did the following.

1. Ran action chain workflow which ran an action with long sleep
2. Kill -9 actionrunner process
3. Checked execution status (it was running)
4. Did execution cancel - execution correctly went to `canceling`
5. Restarted action runner. After it came back online, it correctly marked action as `canceled`

So from here it seems like it works as designed, so you must be hitting a different issue or similar.

As far as the hanging goes - is it possible that execution produces a lot of data (big result) which causes client GET to hang?

**Comment by Kami** [comment]
Actually, I checked another thing - hanging seems to be related to a different API request. `st2 execution cancel` only results in HTTP DELETE request, no GET and in the log you pasted I only see GET.

So it's possible that yeah, some other HTTP request caused API to hang (like retrieving a lot of executions from the DB).

**Comment by Kami** [comment]
So right now there isn't much on our side we can do - things appear to be working as designed.

Having said that, I would recommend you to upgrade to at least v1.6.0 (or even better, v2.0.0). This way you can utilize this "Update action runner to use two internal green thread pools - one for regular (non-workflow) and one for workflow actions. Both pool sizes are user-configurable. This should help increase the throughput of a single action runner when the system is not over-utilized. It can also help prevent deadlocks which may occur when using delay policies with action-chain workflows. (improvement)" - https://github.com/StackStorm/st2/blob/master/CHANGELOG.rst#160---august-8-2016.

**Comment by codyaray** [comment]
I tried restarting st2api (well, did a full st2ctl restart). Trying to cancel an execution was hanging even after that. 

I've been trying to cancel parent workflows.

The action_executions_d_b never appeared to be updated with status:canceled until I manually updated mongodb directly.

I'm still waiting to see if my timed rules actually trigger. I saw the same error message after updating mongo, realized I might need to restart things if apscheduler caches in-memory, then apparently filled my disk with spewing logstash logs, had to restart rabbit, the whole shebang. So now I'm waiting again. :)

**Comment by Kami** [comment]
Since there is no DELETE request in the API log it could also mean nginx is stuck and needs to be restarted.

As far as this weird DB behavior you are observing - you are running a replica set? I wonder if it's some edge case with consistency in multi-node set up. In any case, another reason to upgrade to latest version of StackStorm and Mongo DB 3.2 with WireTiger which allows you to better tweak consistency requirements.

And yeah, filled up disk could definitely cause all kinds of similar issues to this one :)

**Comment by codyaray** [comment]
They triggered! This is the first time StackStorm jobs have run since the 7th. Glad to be back in business. :)

**Comment by codyaray** [comment]
I don't know the root cause or why cancel got stuck, but I know a really easy workaround if I ever see this again. So that's good.

**Comment by Kami** [comment]
Great to hear that.

When you have time I would still recommend the upgrades mentioned above :)

**Comment by codyaray** [comment]
A little more data. I realized that we also had a ton (3000+) jobs in a "scheduled" state so I also manually updated MongoDB to show them as cancelled. In the interim another job which started last night was still running when I restarted the cluster and got stuck in a "running" state. I tried to cancel it manually in the UI which moved move_glacier_indexes task to "requested" but didn't seem to affect "optimize_indices" or  but saw this instead:

![screen shot 2016-09-13 at 2 44 45 pm](https://cloud.githubusercontent.com/assets/44062/18488858/dbd7c3ca-79c0-11e6-89a0-e95be077853d.png)

Note the last line. Even though the API is returning "running" to the `execution list` command, when I tried to cancel "optimize_indices" it says that the action is in state "timeout".

```
$ st2 execution cancel 57d7619770608e34f7469d60
Action cannot be canceled. State = timeout.
```

**Comment by codyaray** [comment]
Should we be checking `live_action_d_b` or `action_execution_d_b` for status here? Want to monitor whether we have too many jobs in "running" or "scheduled" states. We also need to know so we can document it as part of #289. (I think my existing suggestion of `action_execution_d_b` might be wrong.)

**Comment by Kami** [comment]
I believe you or someone else reported the same issue in past, but I never managed to replicate it. That time my guess was some weird MongoDB consistency or replication issue because I can't reproduce it on a single node setup.

Ideally you should monitor both - live actions and executions. Can you please gist both - liveaction and actionexecution object for this execution in question. There might be an edge case where one is updated but the other is not or similar...

**Comment by codyaray** [comment]
Is this what you're looking for?

Below are equivalent objects in live_action_d_b and action_execution_d_b. I matched them up on trace_id. I found a unique trace_id so that I knew I had the correct live_action and action_execution.
```
db.action_execution_d_b.aggregate([{$group: { _id: "$context.trace_context.id_", count: {$sum: 1} }}, {$match:{count:1}}, {$limit: 1}])
{
              "result" : [
                     {
                            "_id" : "5808af6870608e369f538a5a",
                            "count" : 1
                     }
              ],
              "ok" : 1
}
```

Here's the action_execution:
```
db.action_execution_d_b.find({"context.trace_context.id_":"5808af6870608e369f538a5a"}).pretty()
{
       	"_id" : ObjectId("5808af6870608e369f538a5f"),
       	"action" : {
       		"name" : "lock_someprocess_start_workhost",
       		"parameters" : {

       		},
       		"tags" : [ ],
       		"description" : "",
       		"enabled" : true,
       		"entry_point" : "lock-workflows/lock_someprocess_start_workhost.yaml",
       		"notify" : {

       		},
       		"uid" : "action:cron:lock_someprocess_start_workhost",
       		"pack" : "cron",
       		"ref" : "cron.lock_someprocess_start_workhost",
       		"id" : "578e165370608e2d20d86605",
       		"runner_type" : "action-chain"
       	},
       	"children" : [
       		"5808af6870608e3656b54447",
       		"5808af6a70608e3656b5444c",
       		"5808af6e70608e3656b54452"
       	],
       	"context" : {
       		"trigger_instance" : {
       			"id" : "5808af6870608e369f538a59",
       			"name" : null
       		},
       		"trace_context" : {
       			"id_" : "5808af6870608e369f538a5a",
       			"trace_tag" : "st2.CronTimer-b2fe1cad-d46d-4b67-8bdf-567690645648"
       		},
       		"rule" : {
       			"id" : "578e166370608e2d20d8670a",
       			"name" : "someprocess_start_workhost"
       		},
       		"user" : "stackstormservice"
       	},
       	"end_timestamp" : NumberLong("1476964210425129"),
       	"liveaction" : {
       		"action" : "cron.lock_someprocess_start_workhost",
       		"callback" : {

       		},
       		"runner_info" : {
       			"hostname" : "st2host",
       			"pid" : 13910
       		},
       		"id" : "5808af6870608e369f538a5d",
       		"parameters" : {

       		}
       	},
       	"log" : [
       		{
       			"status" : "requested",
       			"timestamp" : ISODate("2016-10-20T11:50:00.122Z")
       		},
       		{
       			"status" : "scheduled",
       			"timestamp" : ISODate("2016-10-20T11:50:00.210Z")
       		},
       		{
       			"status" : "running",
       			"timestamp" : ISODate("2016-10-20T11:50:00.364Z")
       		},
       		{
       			"status" : "succeeded",
       			"timestamp" : ISODate("2016-10-20T11:50:10.451Z")
       		}
       	],
       	"parameters" : {

       	},
       	"result" : {
       		"tasks" : [
       			{
       				"name" : "acquire_zookeeper_lease",
       				"workflow" : null,
       				"created_at" : "2016-10-20T11:50:00.476308+00:00",
       				"updated_at" : "2016-10-20T11:50:02.600633+00:00",
       				"state" : "succeeded",
       				"result" : {
       					"stdout" : "",
       					"result" : null,
       					"stderr" : "",
       					"exit_code" : 0
       				},
       				"id" : "acquire_zookeeper_lease",
       				"execution_id" : "5808af6870608e3656b54447"
       			},
       			{
       				"name" : "is_running",
       				"workflow" : null,
       				"created_at" : "2016-10-20T11:50:02.607192+00:00",
       				"updated_at" : "2016-10-20T11:50:06.231603+00:00",
       				"state" : "failed",
       				"result" : {
       					"workhost" : {
       						"failed" : true,
       						"stderr" : "",
       						"return_code" : 1,
       						"succeeded" : false,
       						"stdout" : ""
       					}
       				},
       				"id" : "is_running",
       				"execution_id" : "5808af6a70608e3656b5444c"
       			},
       			{
       				"name" : "execute_action",
       				"workflow" : null,
       				"created_at" : "2016-10-20T11:50:06.243417+00:00",
       				"updated_at" : "2016-10-20T11:50:10.409932+00:00",
       				"state" : "succeeded",
       				"result" : {
       					"workhost" : {
       						"failed" : false,
       						"stderr" : "",
       						"return_code" : 0,
       						"succeeded" : true,
       						"stdout" : ""
       					}
       				},
       				"id" : "execute_action",
       				"execution_id" : "5808af6e70608e3656b54452"
       			}
       		]
       	},
       	"rule" : {
       		"description" : "",
       		"tags" : [ ],
       		"type" : {
       			"ref" : "standard",
       			"parameters" : {

       			}
       		},
       		"enabled" : true,
       		"name" : "someprocess_start_workhost",
       		"trigger" : {
       			"ref" : "core.b2fe1cad-d46d-4b67-8bdf-567690645648",
       			"type" : "core.st2.CronTimer",
       			"parameters" : {
       				"minute" : "50",
       				"hour" : "6",
       				"day_of_week" : "mon-fri",
       				"day" : "*"
       			}
       		},
       		"criteria" : {

       		},
       		"action" : {
       			"ref" : "cron.lock_someprocess_start_workhost",
       			"parameters" : {

       			}
       		},
       		"pack" : "cron",
       		"ref" : "cron.someprocess_start_workhost",
       		"id" : "578e166370608e2d20d8670a",
       		"uid" : "rule:cron:someprocess_start_workhost"
       	},
       	"runner" : {
       		"runner_module" : "st2actions.runners.actionchainrunner",
       		"uid" : "runner_type:action-chain",
       		"description" : "A runner for launching linear action chains.",
       		"enabled" : true,
       		"runner_parameters" : {
       			"skip_notify" : {
       				"default" : [ ],
       				"type" : "array",
       				"description" : "List of tasks to skip notifications for."
       			},
       			"display_published" : {
       				"default" : false,
       				"type" : "boolean",
       				"description" : "Intermediate published variables will be stored and displayed."
       			}
       		},
       		"id" : "57488f0370608e603c7b9e6a",
       		"name" : "action-chain"
       	},
       	"start_timestamp" : NumberLong("1476964200080771"),
       	"status" : "succeeded",
       	"trigger" : {
       		"uid" : "trigger:core:b2fe1cad-d46d-4b67-8bdf-567690645648:8a13e36853e939e8387e62a3c5f80671",
       		"parameters" : {
       			"minute" : "50",
       			"hour" : "6",
       			"day_of_week" : "mon-fri",
       			"day" : "*"
       		},
       		"name" : "b2fe1cad-d46d-4b67-8bdf-567690645648",
       		"type" : "core.st2.CronTimer",
       		"id" : "578e166370608e2d20d86709",
       		"pack" : "core"
       	},
       	"trigger_instance" : {
       		"status" : "processing",
       		"occurrence_time" : "2016-10-20T11:50:00.007000Z",
       		"trigger" : "core.b2fe1cad-d46d-4b67-8bdf-567690645648",
       		"id" : "5808af6870608e369f538a59",
       		"payload" : {
       			"executed_at" : "2016-10-20 11:50:00.004240+00:00",
       			"schedule" : null
       		}
       	},
       	"trigger_type" : {
       		"description" : "Triggers whenever current time matches the specified time constaints like a UNIX cron scheduler.",
       		"tags" : [ ],
       		"parameters_schema" : {
       			"additionalProperties" : false,
       			"type" : "object",
       			"properties" : {
       				"week" : {
       					"minimum" : 1,
       					"anyOf" : [
       						{
       							"type" : "string"
       						},
       						{
       							"type" : "integer"
       						}
       					],
       					"maximum" : 53
       				},
       				"hour" : {
       					"minimum" : 0,
       					"anyOf" : [
       						{
       							"type" : "string"
       						},
       						{
       							"type" : "integer"
       						}
       					],
       					"maximum" : 23
       				},
       				"day_of_week" : {
       					"minimum" : 0,
       					"anyOf" : [
       						{
       							"type" : "string"
       						},
       						{
       							"type" : "integer"
       						}
       					],
       					"maximum" : 6
       				},
       				"month" : {
       					"minimum" : 1,
       					"anyOf" : [
       						{
       							"type" : "string"
       						},
       						{
       							"type" : "integer"
       						}
       					],
       					"maximum" : 12
       				},
       				"second" : {
       					"minimum" : 0,
       					"anyOf" : [
       						{
       							"type" : "string"
       						},
       						{
       							"type" : "integer"
       						}
       					],
       					"maximum" : 59
       				},
       				"year" : {
       					"anyOf" : [
       						{
       							"type" : "string"
       						},
       						{
       							"type" : "integer"
       						}
       					]
       				},
       				"timezone" : {
       					"type" : "string"
       				},
       				"day" : {
       					"minimum" : 1,
       					"anyOf" : [
       						{
       							"type" : "string"
       						},
       						{
       							"type" : "integer"
       						}
       					],
       					"maximum" : 31
       				},
       				"minute" : {
       					"minimum" : 0,
       					"anyOf" : [
       						{
       							"type" : "string"
       						},
       						{
       							"type" : "integer"
       						}
       					],
       					"maximum" : 59
       				}
       			}
       		},
       		"name" : "st2.CronTimer",
       		"payload_schema" : {
       			"type" : "object",
       			"properties" : {
       				"executed_at" : {
       					"default" : "2014-07-30 05:04:24.578325",
       					"type" : "string",
       					"format" : "date-time"
       				},
       				"schedule" : {
       					"default" : {
       						"units" : "seconds",
       						"delta" : 30
       					},
       					"type" : "object"
       				}
       			}
       		},
       		"uid" : "trigger_type:core:st2.CronTimer",
       		"id" : "57488efa70608e5e7f22f865",
       		"pack" : "core"
       	}
}
```

And the corresponding live action:
```
db.live_action_d_b.find({"context.trace_context.id_":"5808af6870608e369f538a5a"}).pretty()
{
              "_id" : ObjectId("5808af6870608e369f538a5d"),
              "action" : "cron.lock_someprocess_start_workhost",
              "callback" : {

              },
              "context" : {
                     "trigger_instance" : {
                            "id" : "5808af6870608e369f538a59",
                            "name" : null
                     },
                     "trace_context" : {
                            "id_" : "5808af6870608e369f538a5a",
                            "trace_tag" : "st2.CronTimer-b2fe1cad-d46d-4b67-8bdf-567690645648"
                     },
                     "rule" : {
                            "id" : "578e166370608e2d20d8670a",
                            "name" : "someprocess_start_workhost"
                     },
                     "user" : "stackstormservice"
              },
              "end_timestamp" : NumberLong("1476964210425129"),
              "parameters" : {

              },
              "result" : {
                     "tasks" : [
                            {
                                   "name" : "acquire_zookeeper_lease",
                                   "workflow" : null,
                                   "created_at" : "2016-10-20T11:50:00.476308+00:00",
                                   "updated_at" : "2016-10-20T11:50:02.600633+00:00",
                                   "state" : "succeeded",
                                   "result" : {
                                          "stdout" : "",
                                          "result" : null,
                                          "stderr" : "",
                                          "exit_code" : 0
                                   },
                                   "id" : "acquire_zookeeper_lease",
                                   "execution_id" : "5808af6870608e3656b54447"
                            },
                            {
                                   "name" : "is_running",
                                   "workflow" : null,
                                   "created_at" : "2016-10-20T11:50:02.607192+00:00",
                                   "updated_at" : "2016-10-20T11:50:06.231603+00:00",
                                   "state" : "failed",
                                   "result" : {
                                          "workhost" : {
                                                 "failed" : true,
                                                 "stderr" : "",
                                                 "return_code" : 1,
                                                 "succeeded" : false,
                                                 "stdout" : ""
                                          }
                                   },
                                   "id" : "is_running",
                                   "execution_id" : "5808af6a70608e3656b5444c"
                            },
                            {
                                   "name" : "execute_action",
                                   "workflow" : null,
                                   "created_at" : "2016-10-20T11:50:06.243417+00:00",
                                   "updated_at" : "2016-10-20T11:50:10.409932+00:00",
                                   "state" : "succeeded",
                                   "result" : {
                                          "workhost" : {
                                                 "failed" : false,
                                                 "stderr" : "",
                                                 "return_code" : 0,
                                                 "succeeded" : true,
                                                 "stdout" : ""
                                          }
                                   },
                                   "id" : "execute_action",
                                   "execution_id" : "5808af6e70608e3656b54452"
                            }
                     ]
              },
              "runner_info" : {
                     "hostname" : "st2host",
                     "pid" : 13910
              },
              "start_timestamp" : NumberLong("1476964200080771"),
              "status" : "succeeded"
}
```

**Comment by Kami** [comment]
I assume that's for other action and not the one which is causing issues, right?

This looks OK to me since status is the same on both cases.

**Comment by codyaray** [comment]
Duh. Let me get a better example. In the meantime, should these be the same?

```
stackstorm:PRIMARY> db.action_execution_d_b.count()
328886
stackstorm:PRIMARY> db.live_action_d_b.count()
432186
```

We have enabled the garbage collector. I didn't see a separate config for live_actions in the docs.
```
[garbagecollector]
logging = /etc/st2/logging.garbagecollector.conf
action_executions_ttl = 15
trigger_instances_ttl = 15
```
