### ISSUE TITLE
execution canceled by policy does not set end_timestamp which causes notifier failure

### ISSUE THREAD

**Issue by JohnWelborn** [StackStorm/st2#2923]
When a policy cancels a request due to concurrency, it leaves end_timestamp set to None which the notifier expects to be a date.

```
2016-09-23 17:44:56,767 140603018531216 ERROR notifier [-] An exception occurred while applying policy "REDACT.concurrency".
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/notifier/notifier.py", line 254, in _apply_post_run_policies
    liveaction_db = driver.apply_after(liveaction_db)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/policies/concurrency_by_attr.py", line 136, in apply_after
    with self.coordinator.get_lock(lock_uid):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/locking.py", line 35, in __enter__
    self.acquire()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/drivers/zookeeper.py", line 56, in acquire
    return _lock()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/drivers/zookeeper.py", line 49, in _lock
    timeout=0):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kazoo/recipe/lock.py", line 170, in acquire
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kazoo/recipe/lock.py", line 160, in acquire
    blocking=blocking, timeout=timeout)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kazoo/retry.py", line 123, in __call__
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kazoo/recipe/lock.py", line 240, in _inner_acquire
    "%s seconds" % (self.path, timeout))

LockTimeout: Failed to acquire lock on /tooz/locks/{"action": "REDACT", "attributes": ["server"], "policy_type": "action.concurrency.attr"} after 0 seconds
2016-09-23 17:44:56,773 140603018531216 ERROR consumers [-] QueueConsumer failed to process message: LiveActionDB(action="REDACT", action_is_workflow=True, callback={}, context={REDACT}, REDACT, end_timestamp=None, REDACT, result={}, runner_info={}, start_timestamp="2016-09-23 17:44:56.672719+00:00", status="canceled")
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/transport/consumers.py", line 71, in _process_message
    self._handler.process(body)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/notifier/notifier.py", line 96, in process
    self._post_notify_triggers(liveaction=liveaction, execution=execution)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/notifier/notifier.py", line 118, in _post_notify_triggers
    default_message_suffix='completed.')
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/notifier/notifier.py", line 170, in _post_notify_subsection_triggers
    payload['end_timestamp'] = isotime.format(liveaction.end_timestamp)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/util/isotime.py", line 49, in format
    ost = dt.strftime('%z')
AttributeError: 'NoneType' object has no attribute 'strftime'
```

As a quick and dirty workaround I've replaced
`payload['end_timestamp'] = isotime.format(liveaction.end_timestamp)`
with 

```
if liveaction.end_timestamp:                                       
    payload['end_timestamp'] = isotime.format(liveaction.end_timestamp)
else:                                                              
    payload['end_timestamp'] = isotime.format(liveaction.start_timestamp)
```

in
/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/notifier/notifier.py

**Comment by andrew-regan** [comment]
@Mierdin trying to figure out if this may be impacting my Mistral workflow. I have a mistral workflow that runs 2 actions the first has succeeded and the 2nd has been canceled due to a policy. The workflow is stuck in a running state.

```
root@f4faa449b7ab mistral]# st2 execution get 58286da1527ddd0aa0eb670c
id: 58286da1527ddd0aa0eb670c
action.ref: vsphere.enable_discovery_protocol_for_all_vspheres
parameters: None
status: running (728s elapsed)
start_timestamp: 2016-11-13T13:41:53.389285Z
end_timestamp: None
+--------------------------+------------------------+----------------------------+-------------------------------------+-------------------------------+
| id                       | status                 | task                       | action                              | start_timestamp               |
+--------------------------+------------------------+----------------------------+-------------------------------------+-------------------------------+
| 58286da2527ddd0a31509346 | succeeded (1s elapsed) | get_auto_discovery_configs | vsphere.get_vsphere_auto_discovery_ | Sun, 13 Nov 2016 13:41:54 UTC |
|                          |                        |                            | configurations                      |                               |
| 58286da4527ddd0a31509348 | canceled               | enable_auto_discovery      | vsphere.enable_discovery_protocol   | Sun, 13 Nov 2016 13:41:56 UTC |
+--------------------------+------------------------+----------------------------+-------------------------------------+-------------------------------+
```
