### ISSUE TITLE
Workflow core.remote_sudo - parse nested output to publish variable

### ISSUE THREAD

**Issue by beasurajitroy** [StackStorm/st2#2937]
---
    chain:
        -
            name: "c1"
            ref: "core.local_sudo"
            parameters:
                cmd: "cat /root/.ssh/{{cloud}}"
            publish:
                key: "{{c1.stdout}}"
            on-success: "c2"
            on-failure: "c4"
        -
            name: "c2"
            ref: "core.remote_sudo"
            parameters:
                cmd: "ps -eo pcpu,pid,user,args --no-headers| sort -t. -nk1,2 -k4,4 -r |head -n 3| awk '{print $19}'|xargs| sed -e 's/ /,/g'"
                hosts: "{{hostname}}"
                username: "root"
                private_key: "{{key}}"
            on-success: "c3"
            on-failure: "c4"
        -
            name: "c3"
            ref: "core.sendmail"
            parameters:
                body: "{{c2.result.stdout}}"
                from: "xxxxx"
                to: "xxxxxx"
                content-type: "text/plain"
                subject: "st2 found high cpu on {{cloud}} hostname {{hostname}} sensu alert:{{alert}}"
        -
            name: "c4"
            ref: "core.sendmail"
            parameters:
                body: "St2 not able to find top cpu offenders, please login and check"
                from: "xxxxxx"
                to: "xxxxx"
                content-type: "text/plain"
                subject: "st2 found high cpu on {{cloud}} hostname {{hostname}} sensu alert:{{alert}}"
    default: "c1"

Above chain I want to traverse to the output of c2

Its failing

st2 execution get 57f436d7197664f59f3decc7
id: 57f436d7197664f59f3decc7
action.ref: default.action-cpu-compute-prod
parameters:
  alert: 'CheckCPU TOTAL WARNING: total=85.75 user=42.16 nice=0.0 system=1.2 idle=14.25 iowait=0.02 irq=0.0 softirq=0.24 steal=0.0 guest=42.14
    '
  cloud: xxxx
  hostname: xxxxxxx
status: failed
error: Failed to run task "c3". Parameter rendering failed: Failed rendering value for action parameter "body" in task "c3" (template string={{c2.result.stdout}}): 'dict object' has no attribute 'result'
traceback: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/actionchainrunner.py", line 317, in run
    action_params=action_parameters, context_result=context_result)
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/actionchainrunner.py", line 516, in _get_next_action
    chain_context={'parent': parent_context})
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/actionchainrunner.py", line 498, in _resolve_params
    raise ParameterRenderingFailedException(msg)
ParameterRenderingFailedException: Failed rendering value for action parameter "body" in task "c3" (template string={{c2.result.stdout}}): 'dict object' has no attribute 'result'
start_timestamp: 2016-10-04T23:10:15.677040Z
end_timestamp: 2016-10-04T23:10:20.335157Z
+--------------------------+-----------+------+------------------+-------------------------------+
| id                       | status    | task | action           | start_timestamp               |
+--------------------------+-----------+------+------------------+-------------------------------+
| 57f436d8197664f598e8a250 | succeeded | c1   | core.local_sudo  | Tue, 04 Oct 2016 23:10:16 UTC |
| 57f436d9197664f598e8a252 | succeeded | c2   | core.remote_sudo | Tue, 04 Oct 2016 23:10:17 UTC |
+--------------------------+-----------+------+------------------+-------------------------------+

st2 execution get 57f436d9197664f598e8a252
id: 57f436d9197664f598e8a252
status: succeeded
parameters:
  cmd: ps -eo pcpu,pid,user,args --no-headers| sort -t. -nk1,2 -k4,4 -r |head -n 3| awk '{print $19}'|xargs| sed -e 's/ /,/g'
  hosts: dal-appblx075-08.prod.walmart.com
  private_key: '********'
  username: root
result:
  xxxhostxxxx:
    failed: false
    return_code: 0
    stderr: ''
    stdout: 0b408cc9-943d-466f-9d60-c323f08c4476,170ed9c5-387f-4903-9622-81b6803741c6,21f69687-c430-40d5-b2c2-6600a9a2d99e
    succeeded: true

All I want is to get the stdout of c2 which is a core.remote_sudo action

**Comment by beasurajitroy** [comment]
I got a workaround {{c2[hostname].stdout}}
Please close the bug.
