### ISSUE TITLE
Validation error when providing key-value parameters from Slack

### ISSUE THREAD

**Issue by roberterdin** [StackStorm/st2#2943]
When providing a numerical key-value parameters, e.g. `diskspace some-host /var timeout=300`, this results in a validation error. 

From st2api.log
```
ERROR aliasexecution [-] Unable to execute action. Parameter validation failed.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/aliasexecution.py", line 163, in _schedule_execution
    _, action_execution_db = action_service.request(liveaction)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/services/action.py", line 148, in request
    liveaction, execution = create_request(liveaction)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/services/action.py", line 79, in create_request
    allow_default_none=True)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/schema/__init__.py", line 293, in validate
    jsonschema.validate(instance=instance, schema=schema, cls=cls, *args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/jsonschema/validators.py", line 478, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/jsonschema/validators.py", line 123, in validate
    raise error
ValidationError: u'300' is not of type u'integer'

Failed validating u'type' in schema['properties'][u'timeout']:
    {u'default': 1500,
     u'description': u'Time to wait for the action to finish',
     u'type': u'integer'}

On instance[u'timeout']:
    u'300'
```

This is the according action alias:
```
---
name: "remote_diskspace"
description: "Run diskspace analysis on a remote server"
runner_type: local-shell-cmd
entry_point: ""
enabled: true
parameters:
  sudo:
    description: "Run command with sudo"
    type: boolean
    immutable: true
    default: true
  cmd:
    description: "Command to run"
    type: string
    immutable: true
    default: "export ANSIBLE_STDOUT_CALLBACK='json' && /opt/stackstorm/virtualenvs/ansible/bin/ansible-playbook -i /opt/ansible-action/cmdb_connect/dynamic_inventory.sh /opt/ansible-action/playbooks/diskspace.yaml --extra-vars='{\"hosts\":\"{{hosts|replace('http://','')}}\", \"folder\":\"{{folder|replace('\\\\','/')}}\"}'"
  hosts:
    description: "Ansible hosts"
    type: string
    required: true
  folder:
    description: "Folder to analyze"
    type: string
    required: true
  timeout:
    description: "Time to wait for the action to finish"
    default: 1500
```

ST2 version: st2 2.0.1

**Comment by lakshmi-kannan** [comment]
@roberterdin It appears like in the alias you aren't setting the `type` for `timeout`. 

Now:

```
  timeout:
    description: "Time to wait for the action to finish"
    default: 1500
```

Suggested change:

```
  timeout:
    description: "Time to wait for the action to finish"
    default: 1500

**Comment by roberterdin** [comment]
Thanks for your quick response!
Unfortunately that leads to:
```
Traceback (most recent call last):
  File "/usr/bin/st2-register-content", line 22, in <module>
    sys.exit(content_loader.main(sys.argv[1:]))
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 354, in main
    register_content()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 313, in register_content
    register_actions()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 195, in register_actions
    raise e
st2common.exceptions.action.InvalidActionParameterException: The attribute "type" for the runner parameter "timeout" in action "unic_chatops.remote_diskspace" cannot be overridden.
```

**Comment by emedvedev** [comment]
@roberterdin Hiya! Please try `type: integer` (not `number`) in `timeout` (see https://github.com/StackStorm/st2/blob/ed6fdb4043647b766551c25f365782a58abce019/contrib/packs/actions/load.yaml).

`cast_params()` just can't infer the correct type for `timeout`, since it's inherited, not specified in the action. `integer` is its actual type, so you shouldn't get the "overridden" error (see https://github.com/StackStorm/st2/blob/ed6fdb4043647b766551c25f365782a58abce019/st2common/st2common/util/schema/__init__.py#L315).

**Comment by emedvedev** [comment]
`type: integer` should unblock you, but if want to take a stab at fixing the bug, it's right here: https://github.com/StackStorm/st2/blob/ed6fdb4043647b766551c25f365782a58abce019/st2common/st2common/models/utils/action_param_utils.py#L96-L99

You get `timeout` from `runner_parameters_schema`, and it contains `type: integer`. Then it gets overwritten with the contents of `timeout` from `action_parameters_schema` (and that one doesn't contain `type` in your case). Should be merged instead of calling `.update()`.

**Comment by roberterdin** [comment]
@emedvedev I can confirm that `type: "integer"` resolves the issue. I'll leave the issue open for now, maybe I find the time to look into it.
