### ISSUE TITLE
Include rule name in St2Timer logs

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2#2961]
Right now we have to work backwards from the times to identify a particular rule. This is non-trivial with a lot of cron rules in StackStorm.

Here's a couple example logs from our dev instance:

```
2016-10-18 00:31:00,001 140302986729904 WARNING base [-] Execution of job "St2Timer._emit_trigger_instance (trigger: cron[day='*', day_of_week='*', hour='*', minute='31'], next run at: 2016-10-18 00:31:00 CDT)" skipped: maximum number of running instances reached (1)
```

```
2016-10-18 01:18:40,620 140302986731344 WARNING base [-] Run time of job "St2Timer._emit_trigger_instance (trigger: cron[day='*', day_of_week='*', hour='22', minute='5'], next run at: 2016-10-18 22:05:00 CDT)" was missed by 2 days, 3:13:40.620955
```

It would also be great if these were logged as ERRORs instead of WARNINGs.

**Comment by Kami** [comment]
Thanks for opening this issue.

I do think including the rule name would make debugging things. To see how easy it is to make the actual change, we will need to check the code (is the rule name / ref already available in this particular context or not, if it's fully decoupled it might be hard).

**Comment by lakshmi-kannan** [comment]
https://github.com/StackStorm/st2/issues/2935 is also related. Maybe if I expose the rule name with st2 timers list, it can help with debugging.

**Comment by lakshmi-kannan** [comment]
I checked the code and it looks like rule ref is not part of the model.
```
{ "_id" : ObjectId("5806ca63d9d7ed4e9a5efadd"), "uid" : "trigger:core:352b9b3d-3b32-4f88-8f62-d7a1ea1c10c8:9284f9e5bfbb479342f5ff56e36b917d", "name" : "352b9b3d-3b32-4f88-8f62-d7a1ea1c10c8", "pack" : "core", "type" : "core.st2.IntervalTimer", "parameters" : { "unit" : "seconds", "delta" : 5 }, "ref_count" : 1 }
```
I am going to focus on st2 timer list first and then make this change to include rule in the model. I do think it's a good idea to include the rule.ref in the data model for webhooks and timers.

**Comment by codyaray** [comment]
Any update on this? Running into a case where I have multiple jobs triggered at the same time so its not clear which one of them failed. My scripts can only say "these jobs all run at this time", not definitely say which job failed.

```
2017-02-10 11:40:00,005 140341109311920 WARNING base [-] Execution of job "St2Timer._emit_trigger_instance (trigger: cron[day='*', day_of_week='mon-fri', hour='6-18', minute='*/10'], next run at: 2017-02-10 11:40:00 CST)" skipped: maximum number of running instances reach
```

So that tells me its one of, say, 10 different jobs which run every 10 minutes throughout the day.

**Comment by Kami** [comment]
Sorry for the delay - we are quite busy with v2.2.0 release and other things atm so we haven't had the time to look into this yet.

**Comment by codyaray** [comment]
For what its worth, it seems to be configurable from apscheduler POV.

Examples from an [SO question](http://stackoverflow.com/questions/30235604/next-run-time-missed-by-some-seconds-in-job-scheduling-in-apscheuler)
```
2015-05-14_00:00:02.76629 WARNING: Run time of job "Daily VPN Connexion__1 (trigger: cron[day='*', hour='0', minute='0', second='0'], next run at: 2015-05-14 00:00:00)" was missed by 0:00:02.493426
2015-05-14_00:00:02.79309 WARNING: Run time of job "Daily Report VPN Connection ALIGRO__1 (trigger: cron[day='*', hour='0', minute='0', second='0'], next run at: 2015-05-14 00:00:00)" was missed by 0:00:02.777450
```

So I take it this won't make it into v2.2.0? :)

**Comment by Kami** [comment]
@codyaray If you feel adventurous you can also take a stab :)

And sadly no, because we are just in the process of testing v2.2.0 and fixing any issues that may came up (unless you manage to open a PR today which implements it with the tests and everything else included :)).

**Comment by codyaray** [comment]
Fair enough. I don't think I'm going to do this, test it, and get it in 2.2.0 either.

Generally rule and action names would be super helpful throughout the logs. I'm looking at an error in our monitoring dashboard (which ingests StackStorm logs) and we have to backtrack from the action command to the action to figure out what to change.

```
Failed executing command "export ST2_ACTION_PACK_NAME=cron ST2_ACTION_EXECUTION_ID=58a693bf92cc9b2132aefa34 ST2_ACTION_AUTH_TOKEN=******** ST2_ACTION_API_URL=http://127.0.0.1:9101/v1 && cd /tmp && sudo -u myuser bash -c 'export SHELL=/bin/bash HOME=/opt/home/myuser USER=myuser && cd /plogs/events; for d in `find -mindepth 1 -type d`; do if [ ! -e $d.tar.gz -a ! -e $d.tar.bz2 ]; then tar cf - $d | pbzip2 -p16 > $d.tar.bz2 && rm -r $d && unlink /plogs/events/myuser.current ; fi ;done'" on host "myhost" Traceback (most recent call last): File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/ssh/parallel_ssh.py", line 260, in _run_command (stdout, stderr, exit_code) = client.run(cmd, timeout=timeout) File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/ssh/paramiko_ssh.py", line 399, in run stderr=stderr) SSHCommandTimeoutError: Command didn't finish in 300 seconds
```

What we need to know here is the action name and that it timed out. These errors go to a T1 Support team who freaks out when they see big stack traces like this when a simple "Failed executing command <action_name>: SSHCommandTimeoutError: Command didn't finish in 300 seconds" would do just as well and tell them the appropriate action to take. And probably save a few heartbeats.

I know its more complex than this, but just sharing thoughts like a good little user.

Good luck on the release!

**Comment by winem** [comment]
Just verified with st2 v3.5.0 that this is still up-to-date and the rule / action name is not part of the log output. 

Example:
```
2021-09-10 20:42:29,538 139995445124080 INFO base [-] Running job "St2Timer._emit_trigger_instance (trigger: interval[0:01:00], next run at: 2021-09-10 20:43:29 UTC)" (scheduled at 2021-09-10 20:42:29.530680+00:00)
2021-09-10 20:42:29,542 139995445124080 INFO base [-] Job "St2Timer._emit_trigger_instance (trigger: interval[0:01:00], next run at: 2021-09-10 20:43:29 UTC)" executed successfully
```
