### ISSUE TITLE
Actions run in duplicate with corresponding concurrency.attr policy

### ISSUE THREAD

**Issue by tim-ireland** [StackStorm/st2#3150]
I have a st2 build consisting of the release branch v2.1.1 with the following PR cherry-picked: https://github.com/StackStorm/st2/pull/3125.  I suspect it will happen on master as well, which I will confirm next.

Attached is a test pack that illustrates the issue.  It consists of a single action which logs 2 random integers with a 5 second pause in between.

```
class TestDuplicateAction(Action):
    def run(self, uuid):
        self.logger.info('Run TestDuplicateAction for uuid %s rand [%s]',
                         uuid, random.randint(1, 5000))
        time.sleep(5)
        self.logger.info('End TestDuplicateAction uuid %s rand [%s]',
                         uuid, random.randint(1, 5000))
```

In addition, this action has a concurrency policy which limits the threshold per attribute to 1

```
  name: test_concurrency_attr_policy.concurrency
  description: Limits the concurrent executions for the action.
  enabled: true
  resource_ref: test_pack.test_action
  policy_type: action.concurrency.attr
  parameters:
    threshold: 1
    attributes:
      - uuid
```

With this pack loaded, I manually execute the action.  There is nothing else going on on this system.

```
[root@878a3c883d6f test_pack]# st2 run test_pack.test_action uuid=foo
...
id: 586dcaa73bd69311c001a75f
status: succeeded
parameters:
  uuid: foo
result:
  exit_code: 0
  result: null
  stderr: 'st2.actions.python.TestDuplicateAction: INFO     Run TestDuplicateAction for uuid foo rand [886]

    st2.actions.python.TestDuplicateAction: INFO     End TestDuplicateAction uuid foo rand [2674]

    '
  stdout: ''
```

And see the following in the action log.  Note the logs at timestamps 2017-01-05 04:25:17,660 and 2017-01-05 04:25:17,662.  There are 2 liveactions reported as being completed under the same id (586dcaa73bd69311c001a75e) but the logs for those actions contain different random numbers!  Also, note the traceback at 2017-01-05 04:25:17,672 which indicates that the first of the 2 actions already removed the liveaction_db.id and the second failed to.

```
2017-01-05 04:25:11,798 68301680 AUDIT action [-] The status of action execution is changed from requested to scheduled. <LiveAction.id=586dcaa73bd69311c001a75e, ActionExecution.id=586dcaa73bd69311c001a75f> (liveaction_db={'status': 'scheduled', 'runner_info': {}, 'parameters': {u'uuid': u'foo'}, 'action_is_workflow': False, 'start_timestamp': '2017-01-05 04:25:11.718321+00:00', 'callback': {}, 'notify': None, 'result': {}, 'context': {u'user': u'plexxi'}, 'action': u'test_pack.test_action', 'id': '586dcaa73bd69311c001a75e', 'end_timestamp': None},action_execution_db={'status': u'scheduled', 'start_timestamp': '2017-01-05 04:25:11.718321+00:00', 'web_url': u'https://878a3c883d6f/#/history/586dcaa73bd69311c001a75f/general', 'log': [{u'status': u'requested', u'timestamp': datetime.datetime(2017, 1, 5, 4, 25, 11, 727000, tzinfo=<bson.tz_util.FixedOffset object at 0x452a050>)}, {u'status': u'scheduled', u'timestamp': datetime.datetime(2017, 1, 5, 4, 25, 11, 790000, tzinfo=<bson.tz_util.FixedOffset object at 0x452a050>)}], 'parameters': {u'uuid': u'foo'}, 'trigger_type': {}, 'runner': {u'runner_module': u'python_runner', u'uid': u'runner_type:python-script', u'description': u'A runner for launching python actions.', u'enabled': True, u'runner_parameters': {u'env': {u'type': u'object', u'description': u'Environment variables which will be available to the script.'}, u'timeout': {u'default': 600, u'type': u'integer', u'description': u"Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}}, u'id': u'586dc05d3bd69312e426e89f', u'name': u'python-script'}, 'rule': {}, 'children': [], 'trigger_instance': {}, 'trigger': {}, 'parent': None, 'result': {}, 'context': {u'user': u'plexxi'}, 'action': {u'description': u'demonstrate duplicate action issue', u'parameters': {u'uuid': {u'required': True, u'type': u'string', u'description': u'UUID to enforce concurrency.attr policy'}}, u'tags': [], u'enabled': True, u'name': u'test_action', u'entry_point': u'test_action.py', u'notify': {}, u'uid': u'action:test_pack:test_action', u'pack': u'test_pack', u'ref': u'test_pack.test_action', u'id': u'586dc05f3bd69312e426e8e1', u'runner_type': u'python-script'}, 'liveaction': {u'runner_info': {}, u'parameters': {u'uuid': u'foo'}, u'action_is_workflow': False, u'callback': {}, u'action': u'test_pack.test_action', u'id': u'586dcaa73bd69311c001a75e'}, 'id': '586dcaa73bd69311c001a75f', 'end_timestamp': None})
2017-01-05 04:25:11,807 68301680 INFO action [-] The status of action execution is changed from requested to scheduled. <LiveAction.id=586dcaa73bd69311c001a75e, ActionExecution.id=586dcaa73bd69311c001a75f>
2017-01-05 04:25:11,857 71148080 AUDIT worker [-] Launching action execution. (liveaction_db={'status': 'running', 'runner_info': {'hostname': '878a3c883d6f', 'pid': 4585}, 'parameters': {u'uuid': u'foo'}, 'action_is_workflow': False, 'start_timestamp': '2017-01-05 04:25:11.718321+00:00', 'callback': {}, 'notify': None, 'result': {}, 'context': {u'user': u'plexxi'}, 'action': u'test_pack.test_action', 'id': '586dcaa73bd69311c001a75e', 'end_timestamp': None},action_execution_db={'status': u'running', 'start_timestamp': '2017-01-05 04:25:11.718321+00:00', 'web_url': u'https://878a3c883d6f/#/history/586dcaa73bd69311c001a75f/general', 'log': [{u'status': u'requested', u'timestamp': datetime.datetime(2017, 1, 5, 4, 25, 11, 727000, tzinfo=<bson.tz_util.FixedOffset object at 0x452ae50>)}, {u'status': u'scheduled', u'timestamp': datetime.datetime(2017, 1, 5, 4, 25, 11, 790000, tzinfo=<bson.tz_util.FixedOffset object at 0x452ae50>)}, {u'status': u'running', u'timestamp': datetime.datetime(2017, 1, 5, 4, 25, 11, 844000, tzinfo=<bson.tz_util.FixedOffset object at 0x452ae50>)}], 'parameters': {u'uuid': u'foo'}, 'trigger_type': {}, 'runner': {u'runner_module': u'python_runner', u'uid': u'runner_type:python-script', u'description': u'A runner for launching python actions.', u'enabled': True, u'runner_parameters': {u'env': {u'type': u'object', u'description': u'Environment variables which will be available to the script.'}, u'timeout': {u'default': 600, u'type': u'integer', u'description': u"Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}}, u'id': u'586dc05d3bd69312e426e89f', u'name': u'python-script'}, 'rule': {}, 'children': [], 'trigger_instance': {}, 'trigger': {}, 'parent': None, 'result': {}, 'context': {u'user': u'plexxi'}, 'action': {u'description': u'demonstrate duplicate action issue', u'parameters': {u'uuid': {u'required': True, u'type': u'string', u'description': u'UUID to enforce concurrency.attr policy'}}, u'tags': [], u'enabled': True, u'name': u'test_action', u'entry_point': u'test_action.py', u'notify': {}, u'uid': u'action:test_pack:test_action', u'pack': u'test_pack', u'ref': u'test_pack.test_action', u'id': u'586dc05f3bd69312e426e8e1', u'runner_type': u'python-script'}, 'liveaction': {u'runner_info': {u'hostname': u'878a3c883d6f', u'pid': 4585}, u'parameters': {u'uuid': u'foo'}, u'action_is_workflow': False, u'callback': {}, u'action': u'test_pack.test_action', u'id': u'586dcaa73bd69311c001a75e'}, 'id': '586dcaa73bd69311c001a75f', 'end_timestamp': None})
2017-01-05 04:25:11,866 71149840 AUDIT worker [-] Launching action execution. (liveaction_db={'status': 'running', 'runner_info': {'hostname': '878a3c883d6f', 'pid': 4585}, 'parameters': {u'uuid': u'foo'}, 'action_is_workflow': False, 'start_timestamp': '2017-01-05 04:25:11.718321+00:00', 'callback': {}, 'notify': None, 'result': {}, 'context': {u'user': u'plexxi'}, 'action': u'test_pack.test_action', 'id': '586dcaa73bd69311c001a75e', 'end_timestamp': None},action_execution_db={'status': u'running', 'start_timestamp': '2017-01-05 04:25:11.718321+00:00', 'web_url': u'https://878a3c883d6f/#/history/586dcaa73bd69311c001a75f/general', 'log': [{u'status': u'requested', u'timestamp': datetime.datetime(2017, 1, 5, 4, 25, 11, 727000, tzinfo=<bson.tz_util.FixedOffset object at 0x452a290>)}, {u'status': u'scheduled', u'timestamp': datetime.datetime(2017, 1, 5, 4, 25, 11, 790000, tzinfo=<bson.tz_util.FixedOffset object at 0x452a290>)}, {u'status': u'running', u'timestamp': datetime.datetime(2017, 1, 5, 4, 25, 11, 844000, tzinfo=<bson.tz_util.FixedOffset object at 0x452a290>)}], 'parameters': {u'uuid': u'foo'}, 'trigger_type': {}, 'runner': {u'runner_module': u'python_runner', u'uid': u'runner_type:python-script', u'description': u'A runner for launching python actions.', u'enabled': True, u'runner_parameters': {u'env': {u'type': u'object', u'description': u'Environment variables which will be available to the script.'}, u'timeout': {u'default': 600, u'type': u'integer', u'description': u"Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}}, u'id': u'586dc05d3bd69312e426e89f', u'name': u'python-script'}, 'rule': {}, 'children': [], 'trigger_instance': {}, 'trigger': {}, 'parent': None, 'result': {}, 'context': {u'user': u'plexxi'}, 'action': {u'description': u'demonstrate duplicate action issue', u'parameters': {u'uuid': {u'required': True, u'type': u'string', u'description': u'UUID to enforce concurrency.attr policy'}}, u'tags': [], u'enabled': True, u'name': u'test_action', u'entry_point': u'test_action.py', u'notify': {}, u'uid': u'action:test_pack:test_action', u'pack': u'test_pack', u'ref': u'test_pack.test_action', u'id': u'586dc05f3bd69312e426e8e1', u'runner_type': u'python-script'}, 'liveaction': {u'runner_info': {u'hostname': u'878a3c883d6f', u'pid': 4585}, u'parameters': {u'uuid': u'foo'}, u'action_is_workflow': False, u'callback': {}, u'action': u'test_pack.test_action', u'id': u'586dcaa73bd69311c001a75e'}, 'id': '586dcaa73bd69311c001a75f', 'end_timestamp': None})
2017-01-05 04:25:11,872 71148080 INFO worker [-] Dispatched {~}action_execution: 586dcaa73bd69311c001a75f / {~}live_action: 586dcaa73bd69311c001a75e with "running" status.
2017-01-05 04:25:11,881 71149840 INFO worker [-] Dispatched {~}action_execution: 586dcaa73bd69311c001a75f / {~}live_action: 586dcaa73bd69311c001a75e with "running" status.
2017-01-05 04:25:11,888 71148080 INFO base [-] Dispatching Action to a runner (liveaction_db={'status': 'running', 'runner_info': {'hostname': '878a3c883d6f', 'pid': 4585}, 'parameters': {u'uuid': u'foo'}, 'action_is_workflow': False, 'start_timestamp': '2017-01-05 04:25:11.718321+00:00', 'callback': {}, 'notify': None, 'result': {}, 'context': {u'user': u'plexxi'}, 'action': u'test_pack.test_action', 'id': '586dcaa73bd69311c001a75e', 'end_timestamp': None},runnertype_db={'runner_module': u'python_runner', 'uid': u'runner_type:python-script', 'name': u'python-script', 'enabled': True, 'query_module': None, 'runner_parameters': {u'env': {u'type': u'object', u'description': u'Environment variables which will be available to the script.'}, u'timeout': {u'default': 600, u'type': u'integer', u'description': u"Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}}, 'id': '586dc05d3bd69312e426e89f', 'description': u'A runner for launching python actions.'})
2017-01-05 04:25:11,890 71149840 INFO base [-] Dispatching Action to a runner (liveaction_db={'status': 'running', 'runner_info': {'hostname': '878a3c883d6f', 'pid': 4585}, 'parameters': {u'uuid': u'foo'}, 'action_is_workflow': False, 'start_timestamp': '2017-01-05 04:25:11.718321+00:00', 'callback': {}, 'notify': None, 'result': {}, 'context': {u'user': u'plexxi'}, 'action': u'test_pack.test_action', 'id': '586dcaa73bd69311c001a75e', 'end_timestamp': None},runnertype_db={'runner_module': u'python_runner', 'uid': u'runner_type:python-script', 'name': u'python-script', 'enabled': True, 'query_module': None, 'runner_parameters': {u'env': {u'type': u'object', u'description': u'Environment variables which will be available to the script.'}, u'timeout': {u'default': 600, u'type': u'integer', u'description': u"Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}}, 'id': '586dc05d3bd69312e426e89f', 'description': u'A runner for launching python actions.'})
2017-01-05 04:25:11,895 71148080 INFO loader [-] Reusing runner module "/opt/stackstorm/runners/python_runner/python_runner.py" from cache.
2017-01-05 04:25:11,901 71149840 INFO loader [-] Reusing runner module "/opt/stackstorm/runners/python_runner/python_runner.py" from cache.
2017-01-05 04:25:11,917 71148080 AUDIT access [-] Access granted to "plexxi" with the token set to expire at "2017-01-06T04:25:11.915797Z". (username=u'plexxi',token_expiration='2017-01-06T04:25:11.915797Z')
2017-01-05 04:25:11,923 71149840 AUDIT access [-] Access granted to "plexxi" with the token set to expire at "2017-01-06T04:25:11.916565Z". (username=u'plexxi',token_expiration='2017-01-06T04:25:11.916565Z')
2017-01-05 04:25:17,660 71148080 AUDIT base [-] Liveaction completed (liveaction_db={'status': 'succeeded', 'runner_info': {u'hostname': u'878a3c883d6f', u'pid': 4585}, 'parameters': {u'uuid': u'foo'}, 'action_is_workflow': False, 'start_timestamp': '2017-01-05 04:25:11.718321+00:00', 'callback': {}, 'notify': None, 'result': {'stdout': '', 'exit_code': 0, 'stderr': 'st2.actions.python.TestDuplicateAction: INFO     Run TestDuplicateAction for uuid foo rand [593]\nst2.actions.python.TestDuplicateAction: INFO     End TestDuplicateAction uuid foo rand [4911]\n', 'result': None}, 'context': {u'user': u'plexxi'}, 'action': u'test_pack.test_action', 'id': '586dcaa73bd69311c001a75e', 'end_timestamp': '2017-01-05 04:25:17.620757+00:00'})
2017-01-05 04:25:17,662 71149840 AUDIT base [-] Liveaction completed (liveaction_db={'status': 'succeeded', 'runner_info': {u'hostname': u'878a3c883d6f', u'pid': 4585}, 'parameters': {u'uuid': u'foo'}, 'action_is_workflow': False, 'start_timestamp': '2017-01-05 04:25:11.718321+00:00', 'callback': {}, 'notify': None, 'result': {'stdout': '', 'exit_code': 0, 'stderr': 'st2.actions.python.TestDuplicateAction: INFO     Run TestDuplicateAction for uuid foo rand [886]\nst2.actions.python.TestDuplicateAction: INFO     End TestDuplicateAction uuid foo rand [2674]\n', 'result': None}, 'context': {u'user': u'plexxi'}, 'action': u'test_pack.test_action', 'id': '586dcaa73bd69311c001a75e', 'end_timestamp': '2017-01-05 04:25:17.619681+00:00'})
2017-01-05 04:25:17,672 71149840 ERROR consumers [-] ActionsQueueConsumer failed to process message: LiveActionDB(action="test_pack.test_action", action_is_workflow=False, callback={}, context={u'user': u'plexxi'}, end_timestamp=None, id=586dcaa73bd69311c001a75e, notify=None, parameters={u'uuid': u'foo'}, result={}, runner_info={}, start_timestamp="2017-01-05 04:25:11.718321+00:00", status="scheduled")
Traceback (most recent call last):
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/st2common/transport/consumers.py", line 71, in _process_message
    self._handler.process(body)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/st2actions/worker.py", line 95, in process
    if liveaction.status == action_constants.LIVEACTION_STATUS_SCHEDULED
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/st2actions/worker.py", line 148, in _run_action
    self._running_liveactions.remove(liveaction_db.id)
KeyError: ObjectId('586dcaa73bd69311c001a75e')
```

The execution only shows the one action (the second one to complete - according to the logs):

```
[root@878a3c883d6f test_pack]# st2 execution get 586dcaa73bd69311c001a75f
id: 586dcaa73bd69311c001a75f
status: succeeded (6s elapsed)
parameters:
  uuid: foo
result:
  exit_code: 0
  result: null
  stderr: 'st2.actions.python.TestDuplicateAction: INFO     Run TestDuplicateAction for uuid foo rand [886]

    st2.actions.python.TestDuplicateAction: INFO     End TestDuplicateAction uuid foo rand [2674]

    '
  stdout: ''
```

Now, to prove that this is related to the policy, I deleted the policy:

```
[root@878a3c883d6f test_pack]# st2 policy delete test_pack.test_concurrency_attr_policy.concurrency
Resource with id "test_pack.test_concurrency_attr_policy.concurrency" has been successfully deleted.
```

And re-ran the action.  This time, no duplicates and no Traceback.

```
2017-01-05 14:44:35,399 70401072 AUDIT action [-] The status of action execution is changed from requested to scheduled. <LiveAction.id=586e5bd33bd69311c001a761, ActionExecution.id=586e5bd33bd69311c001a762> (liveaction_db={'status': 'scheduled', 'runner_info': {}, 'parameters': {u'uuid': u'foo'}, 'action_is_workflow': False, 'start_timestamp': '2017-01-05 14:44:35.328414+00:00', 'callback': {}, 'notify': None, 'result': {}, 'context': {u'user': u'plexxi'}, 'action': u'test_pack.test_action', 'id': '586e5bd33bd69311c001a761', 'end_timestamp': None},action_execution_db={'status': u'scheduled', 'start_timestamp': '2017-01-05 14:44:35.328414+00:00', 'web_url': u'https://878a3c883d6f/#/history/586e5bd33bd69311c001a762/general', 'log': [{u'status': u'requested', u'timestamp': datetime.datetime(2017, 1, 5, 14, 44, 35, 335000, tzinfo=<bson.tz_util.FixedOffset object at 0x43d52d0>)}, {u'status': u'scheduled', u'timestamp': datetime.datetime(2017, 1, 5, 14, 44, 35, 391000, tzinfo=<bson.tz_util.FixedOffset object at 0x43d52d0>)}], 'parameters': {u'uuid': u'foo'}, 'trigger_type': {}, 'runner': {u'runner_module': u'python_runner', u'uid': u'runner_type:python-script', u'description': u'A runner for launching python actions.', u'enabled': True, u'runner_parameters': {u'env': {u'type': u'object', u'description': u'Environment variables which will be available to the script.'}, u'timeout': {u'default': 600, u'type': u'integer', u'description': u"Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}}, u'id': u'586dc05d3bd69312e426e89f', u'name': u'python-script'}, 'rule': {}, 'children': [], 'trigger_instance': {}, 'trigger': {}, 'parent': None, 'result': {}, 'context': {u'user': u'plexxi'}, 'action': {u'description': u'demonstrate duplicate action issue', u'parameters': {u'uuid': {u'required': True, u'type': u'string', u'description': u'UUID to enforce concurrency.attr policy'}}, u'tags': [], u'enabled': True, u'name': u'test_action', u'entry_point': u'test_action.py', u'notify': {}, u'uid': u'action:test_pack:test_action', u'pack': u'test_pack', u'ref': u'test_pack.test_action', u'id': u'586dc05f3bd69312e426e8e1', u'runner_type': u'python-script'}, 'liveaction': {u'runner_info': {}, u'parameters': {u'uuid': u'foo'}, u'action_is_workflow': False, u'callback': {}, u'action': u'test_pack.test_action', u'id': u'586e5bd33bd69311c001a761'}, 'id': '586e5bd33bd69311c001a762', 'end_timestamp': None})
2017-01-05 14:44:35,409 70401072 INFO action [-] The status of action execution is changed from requested to scheduled. <LiveAction.id=586e5bd33bd69311c001a761, ActionExecution.id=586e5bd33bd69311c001a762>
2017-01-05 14:44:35,438 70401072 AUDIT worker [-] Launching action execution. (liveaction_db={'status': 'running', 'runner_info': {'hostname': '878a3c883d6f', 'pid': 4585}, 'parameters': {u'uuid': u'foo'}, 'action_is_workflow': False, 'start_timestamp': '2017-01-05 14:44:35.328414+00:00', 'callback': {}, 'notify': None, 'result': {}, 'context': {u'user': u'plexxi'}, 'action': u'test_pack.test_action', 'id': '586e5bd33bd69311c001a761', 'end_timestamp': None},action_execution_db={'status': u'running', 'start_timestamp': '2017-01-05 14:44:35.328414+00:00', 'web_url': u'https://878a3c883d6f/#/history/586e5bd33bd69311c001a762/general', 'log': [{u'status': u'requested', u'timestamp': datetime.datetime(2017, 1, 5, 14, 44, 35, 335000, tzinfo=<bson.tz_util.FixedOffset object at 0x452a310>)}, {u'status': u'scheduled', u'timestamp': datetime.datetime(2017, 1, 5, 14, 44, 35, 391000, tzinfo=<bson.tz_util.FixedOffset object at 0x452a310>)}, {u'status': u'running', u'timestamp': datetime.datetime(2017, 1, 5, 14, 44, 35, 430000, tzinfo=<bson.tz_util.FixedOffset object at 0x452a310>)}], 'parameters': {u'uuid': u'foo'}, 'trigger_type': {}, 'runner': {u'runner_module': u'python_runner', u'uid': u'runner_type:python-script', u'description': u'A runner for launching python actions.', u'enabled': True, u'runner_parameters': {u'env': {u'type': u'object', u'description': u'Environment variables which will be available to the script.'}, u'timeout': {u'default': 600, u'type': u'integer', u'description': u"Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}}, u'id': u'586dc05d3bd69312e426e89f', u'name': u'python-script'}, 'rule': {}, 'children': [], 'trigger_instance': {}, 'trigger': {}, 'parent': None, 'result': {}, 'context': {u'user': u'plexxi'}, 'action': {u'description': u'demonstrate duplicate action issue', u'parameters': {u'uuid': {u'required': True, u'type': u'string', u'description': u'UUID to enforce concurrency.attr policy'}}, u'tags': [], u'enabled': True, u'name': u'test_action', u'entry_point': u'test_action.py', u'notify': {}, u'uid': u'action:test_pack:test_action', u'pack': u'test_pack', u'ref': u'test_pack.test_action', u'id': u'586dc05f3bd69312e426e8e1', u'runner_type': u'python-script'}, 'liveaction': {u'runner_info': {u'hostname': u'878a3c883d6f', u'pid': 4585}, u'parameters': {u'uuid': u'foo'}, u'action_is_workflow': False, u'callback': {}, u'action': u'test_pack.test_action', u'id': u'586e5bd33bd69311c001a761'}, 'id': '586e5bd33bd69311c001a762', 'end_timestamp': None})
2017-01-05 14:44:35,448 70401072 INFO worker [-] Dispatched {~}action_execution: 586e5bd33bd69311c001a762 / {~}live_action: 586e5bd33bd69311c001a761 with "running" status.
2017-01-05 14:44:35,453 70401072 INFO base [-] Dispatching Action to a runner (liveaction_db={'status': 'running', 'runner_info': {'hostname': '878a3c883d6f', 'pid': 4585}, 'parameters': {u'uuid': u'foo'}, 'action_is_workflow': False, 'start_timestamp': '2017-01-05 14:44:35.328414+00:00', 'callback': {}, 'notify': None, 'result': {}, 'context': {u'user': u'plexxi'}, 'action': u'test_pack.test_action', 'id': '586e5bd33bd69311c001a761', 'end_timestamp': None},runnertype_db={'runner_module': u'python_runner', 'uid': u'runner_type:python-script', 'name': u'python-script', 'enabled': True, 'query_module': None, 'runner_parameters': {u'env': {u'type': u'object', u'description': u'Environment variables which will be available to the script.'}, u'timeout': {u'default': 600, u'type': u'integer', u'description': u"Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."}}, 'id': '586dc05d3bd69312e426e89f', 'description': u'A runner for launching python actions.'})
2017-01-05 14:44:35,459 70401072 INFO loader [-] Reusing runner module "/opt/stackstorm/runners/python_runner/python_runner.py" from cache.
2017-01-05 14:44:35,469 70401072 AUDIT access [-] Access granted to "plexxi" with the token set to expire at "2017-01-06T14:44:35.467964Z". (username=u'plexxi',token_expiration='2017-01-06T14:44:35.467964Z')
2017-01-05 14:44:41,199 70401072 AUDIT base [-] Liveaction completed (liveaction_db={'status': 'succeeded', 'runner_info': {u'hostname': u'878a3c883d6f', u'pid': 4585}, 'parameters': {u'uuid': u'foo'}, 'action_is_workflow': False, 'start_timestamp': '2017-01-05 14:44:35.328414+00:00', 'callback': {}, 'notify': None, 'result': {'stdout': '', 'exit_code': 0, 'stderr': 'st2.actions.python.TestDuplicateAction: INFO     Run TestDuplicateAction for uuid foo rand [4593]\nst2.actions.python.TestDuplicateAction: INFO     End TestDuplicateAction uuid foo rand [4414]\n', 'result': None}, 'context': {u'user': u'plexxi'}, 'action': u'test_pack.test_action', 'id': '586e5bd33bd69311c001a761', 'end_timestamp': '2017-01-05 14:44:41.169034+00:00'})
```

Test Pack:

[test_pack.zip](https://github.com/StackStorm/st2/files/687524/test_pack.zip)

**Comment by andrew-regan** [comment]
@m4dcoder

**Comment by tim-ireland** [comment]
I reproduced this issue using the current st2 master branch as well.

**Comment by tim-ireland** [comment]
I should also note that I tested this on release branch v2.1.1 directly and did not see the issue.

**Comment by Kami** [comment]
Thanks for the detailed report - we will have a look.

/cc @m4dcoder

**Comment by m4dcoder** [comment]
Fix at https://github.com/StackStorm/st2/pull/3151, please cherry pick the patch and let us know if this fixes the problem.

**Comment by tim-ireland** [comment]
@m4dcoder Confirmed fix, thanks for the quick turn around!
