### ISSUE TITLE
Update all the CLI scripts and tools to try to use st2.conf from the default production path by default

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#3203]
We should update all the command-line scripts and tools to try and use and load config from default production location (`/etc/st2/st2.conf`) by default on invocation.

Right now this doesn't happen so user needs to manually pass ``--config-file /etc/st2/st2.conf`` flag to each of those tools and scripts.

This should save everyone some typing and also improve the user experience - currently in some scenarios if ``--config-file`` argument is not provided logging is not set up which causes confusion.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1493236758167201

**Comment by nmaludy** [comment]
@Kami this would have saved me, see https://github.com/StackStorm/st2docs/pull/636

Without `--config /etc/st2/st2.conf` i got the following error with `st2-purge-executions`:

```
[root@johnst2 st2]# /opt/stackstorm/st2/bin/st2-purge-executions --timestamp="2017-10-19T16:31:00.000000Z" --purge-incomplete
2017-10-19 13:25:42,148 INFO [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "None".
Traceback (most recent call last):
  File "/opt/stackstorm/st2/bin/st2-purge-executions", line 22, in <module>
    sys.exit(main())
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/cmd/purge_executions.py", line 67, in main
    common_setup(config=config, setup_db=True, register_mq_exchanges=False)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/script_setup.py", line 92, in setup
    db_setup()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/database_setup.py", line 43, in db_setup
    ssl_match_hostname=cfg.CONF.database.ssl_match_hostname)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/persistence/db_init.py", line 65, in db_setup_with_retry
    ssl_match_hostname=ssl_match_hostname)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/__init__.py", line 94, in db_setup
    db_ensure_indexes()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/__init__.py", line 129, in db_ensure_indexes
    raise e
pymongo.errors.OperationFailure: not authorized on st2 to execute command { createIndexes: "user_d_b", indexes: [ { unique: true, background: false, sparse: false, key: { name: 1 }, name: "name_1" } ], writeConcern: {} }
```

This is not very intuitive as to what's going wrong. Took me a minute to figure it out.

**Comment by Kami** [comment]
@nmaludy I agree - we should make this change as soon as possible :)
