### ISSUE TITLE
Chatops '!pack get' fails under EL6

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#3222]
> Original story and possible "root" solutions are described in https://github.com/StackStorm/st2-packages/issues/363

As it was before with outdated `EL6` `git` version, there is another issue where `!pack get ` ChatOps command fails:

![](https://i.imgur.com/gqMyqRW.png)

### Reproduce

```sh
$ st2 run packs.install packs=aws

$ st2 run packs.get pack=aws
.
id: 58a4717de138231b0a0e38a4
status: failed
parameters: 
  pack: bitcoin
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/get_installed.py", line 71, in run
    '--left-right', '--count', 'HEAD...origin/master'
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/cmd.py", line 423, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/cmd.py", line 868, in _call_process
    return self.execute(call, **_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/cmd.py", line 686, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
  cmdline: git rev-list --left-right --count HEAD...origin/master
  stderr: 'usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=nr
    --max-age=epoch
    --min-age=epoch
    --sparse
    --no-merges
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=nr | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all'
"
  stdout: ''
```

**Comment by armab** [comment]
Closed in https://github.com/StackStorm/st2/pull/4984 as EL6 is not supported anymore.
