### ISSUE TITLE
StackStorm-Exchange hosted packs using BaseActionAliasTestCase fail with an exception

### ISSUE THREAD

**Issue by jjm** [StackStorm/st2#3250]
When running alias tests for a pack on StackStorm Exchange they fail with the following error:

```
======================================================================
ERROR: test_geoip (test_action_aliases.GeoIP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/st2/st2tests/st2tests/action_aliases.py", line 44, in setUp
    self.action_alias_db = self._get_action_alias_db_by_name(name=self.action_alias_name)
  File "/tmp/st2/st2tests/st2tests/action_aliases.py", line 108, in _get_action_alias_db_by_name
    action_alias=alias_path)
  File "/tmp/st2/st2common/st2common/bootstrap/aliasesregistrar.py", line 118, in _get_action_alias_db
    (pack, pack_field))
Exception: Model is in pack "stackstorm-networking_utils" but field "pack" is different: networking_utils
```

I've encountered this on a PR StackStorm-Exchange/stackstorm-networking_utils#1.

**Comment by Kami** [comment]
Thanks again for reporting this.

As commented on the other issue, I found the root cause and I will work on a fix on Monday :)
