### ISSUE TITLE
st2-purge-executions script not working

### ISSUE THREAD

**Issue by efenian** [StackStorm/st2#3297]
$ st2 --version
st2 2.2.0

$ mongo -version
MongoDB shell version: 3.2.12

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

$ /opt/stackstorm/st2/bin/st2-purge-executions --timestamp="2017-03-20T00:00:00.000000Z"
2017-03-22 02:42:46,594 INFO [-] Connecting to database "st2" @ "0.0.0.0:27017" as user "None".
Traceback (most recent call last):
  File "/opt/stackstorm/st2/bin/st2-purge-executions", line 22, in <module>
    sys.exit(main())
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/cmd/purge_executions.py", line 67, in main
    common_setup(config=config, setup_db=True, register_mq_exchanges=False)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/script_setup.py", line 86, in setup
    db_setup()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/database_setup.py", line 43, in db_setup
    ssl_match_hostname=cfg.CONF.database.ssl_match_hostname)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/persistence/db_init.py", line 65, in db_setup_with_retry
    ssl_match_hostname=ssl_match_hostname)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/models/db/__init__.py", line 94, in db_setup
    db_ensure_indexes()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/models/db/__init__.py", line 131, in db_ensure_indexes
    raise e
pymongo.errors.OperationFailure: not authorized on st2 to execute command { createIndexes: "user_d_b", indexes: [ { unique: true, background: false, sparse: false, key: { name: 1 }, name: "name_1" } ] }

**Comment by LindsayHill** [comment]
The problem is that since v2.2 we set a random password for MongoDB & PostgreSQL. Previously MongoDB had no authentication.

These values are stored in `/etc/st2/st2.conf`. By default, `st2-purge-executions` does *not* read this file, but you can pass it in as an option. This is a known problem, and we'd like to address it in v2.2.2. See https://github.com/StackStorm/st2/issues/3203

The short-term workaround for you is to pass in the `--config-file` option, e.g.:
```
vagrant@st2trusty:/opt/stackstorm/st2/bin$ /opt/stackstorm/st2/bin/st2-purge-executions --timestamp="2017-03-20T00:00:00.000000Z" --config-file=/etc/st2/st2.conf
2017-03-22 03:19:28,412 INFO [-] Connecting to database "st2" @ "0.0.0.0:27017" as user "stackstorm".
2017-03-22 03:19:28,566 INFO [-] Purging executions older than timestamp: 2017-03-20T00:00:00.000000Z
2017-03-22 03:19:28,599 INFO [-] Deleted 32 action execution objects
2017-03-22 03:19:28,609 INFO [-] Deleted 32 liveaction objects
2017-03-22 03:19:28,614 INFO [-] All execution models older than timestamp 2017-03-20 00:00:00+00:00 were deleted.
vagrant@st2trusty:/opt/stackstorm/st2/bin$
```
