### ISSUE TITLE
'make requirements' fails for versions < 2.0.

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2#3301]
Running `make requirements` fails for ST2 versions < 2.0.

I am trying to make an update to some older st2docs branches, e.g. https://github.com/StackStorm/st2docs/pull/427. This works for v2.0, v2.1, v2.2. It fails for v1.2, v1.4, v1.5, v1.6.

With no changes to the Makefile, installing st2docs requirements or st2 requirements will fail with this:
```
Installing requirements.txt...
Exception:
Traceback (most recent call last):
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/setuptools/dist.py", line 386, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 862, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2568, in requires
    dm = self._dep_map
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2815, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2824, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2806, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1468, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/home/vagrant/st2docs_gtm/virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1577, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/home/vagrant/st2docs_gtm/virtualenv/lib/python2.7/site-packages/six-1.10.0.dist-info/METADATA'
```

If I modify the st2docs/Makefile to install pip >=8.1.2, < 8.2 like this, it passes that step:
```
--- a/Makefile
+++ b/Makefile
@@ -87,7 +87,8 @@ requirements: virtualenv
        @echo

        # Make sure we use latest version of pip
-       $(VIRTUALENV_DIR)/bin/pip install --upgrade "pip<8.0.0"
+       #$(VIRTUALENV_DIR)/bin/pip install --upgrade "pip<8.0.0"
+       $(VIRTUALENV_DIR)/bin/pip install --upgrade "pip>=8.1.2,<8.2"

        # Install requirements
        #
```
It then fails when running `cd st2; make requirements` with a similar error. Again, when changing st2/Makefile to use a newer version of pip, it passes.

It then fails at this point:
```
# Generate all requirements to support current CI pipeline.
virtualenv/bin/python scripts/fixate-requirements.py --skip=virtualenv -s st2*/in-requirements.txt -f fixed-requirements.txt -o requirements.txt
Traceback (most recent call last):
  File "scripts/fixate-requirements.py", line 174, in <module>
    skip=skip)
  File "scripts/fixate-requirements.py", line 117, in write_requirements
    requirements = merge_source_requirements(sources)
  File "scripts/fixate-requirements.py", line 96, in merge_source_requirements
    if req.req.project_name in projects:
AttributeError: 'Requirement' object has no attribute 'project_name'
make: *** [requirements] Error 1
```

Looks like I'll also need to back port https://github.com/StackStorm/st2/pull/2854 into some older branches to get it to build. 

Am I on the right track with that? Or is there some easier way of dealing with this problem?

**Comment by lakshmi-kannan** [comment]
I'd actively remove documentation for those versions because we only support current stable and previous version for the product itself.

**Comment by LindsayHill** [comment]
Have found some nasty hacks to get old docs building. Will keep those workarounds in the st2docs tree, not try to port them into here
