### ISSUE TITLE
st2 pack show in master is broken

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#3377]
```
(virtualenv)vagrant@st2dev /m/s/s/st2 ❯❯❯ st2 pack show core                                                                     master ✭ ◼
ERROR: Expecting value: line 1 column 1 (char 0)
```

with --debug

```
(virtualenv)vagrant@st2dev /m/s/s/st2 ❯❯❯ st2 --debug pack show core                                                           ⏎ master ✭ ◼
# -------- begin 139705409745296 request ----------
curl -X POST -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.13.0' -H  'content-type: application/json' -H  'Content-Length: 16' --data-binary '{"pack": "core"}' http://127.0.0.1:9101/v1/packs/index/search
# -------- begin 139705409745296 response ----------

# -------- end 139705409745296 response ------------

ERROR: Expecting value: line 1 column 1 (char 0)
CLI settings:
----------------
Config file path: /home/vagrant/.st2/config
Client settings:
----------------
ST2_BASE_URL: http://127.0.0.1
ST2_AUTH_URL: http://127.0.0.1:9100
ST2_API_URL: http://127.0.0.1:9101/v1
ST2_AUTH_TOKEN: None

Proxy settings:
---------------
HTTP_PROXY:
HTTPS_PROXY:

Traceback (most recent call last):
  File "/mnt/src/storm/st2/st2client/st2client/shell.py", line 289, in run
    args.func(args)
  File "/mnt/src/storm/st2/st2client/st2client/commands/pack.py", line 85, in run_and_print
    raise OperationFailureException(message)
OperationFailureException: Expecting value: line 1 column 1 (char 0)
(virtualenv)vagrant@st2dev /m/s/s/st2 ❯❯❯
```

**Comment by Mierdin** [comment]
Seems like this is because `core` isn't in the index (naturally, it's installed with stackstorm) and this functionality works by searching the index only. Wondering if right approach is to maintain a list of preinstalled packs in the API controller and if requests come in for one of them, don't look at the index, rather pull metadata from filesystem. Thoughts?

**Comment by bigmstone** [comment]
@Mierdin I believe the bug is the traceback/unfriendly error handing and not the need to add pre-installed packs to the index (which I'm -1 on, if that's what we're thinking).

**Comment by Mierdin** [comment]
The error message on the client was obfuscated when that OperationFailureException - when you raise the original exception, this is what you get:

```
Traceback (most recent call last):
  File "/home/vagrant/st2/st2client/st2client/shell.py", line 298, in run
    args.func(args)
  File "/home/vagrant/st2/st2client/st2client/commands/pack.py", line 75, in run_and_print
    instance = self.run(args, **kwargs)
  File "/home/vagrant/st2/st2client/st2client/commands/resource.py", line 44, in decorate
    return func(*args, **kwargs)
  File "/home/vagrant/st2/st2client/st2client/commands/pack.py", line 174, in run
    return self.manager.search(args, **kwargs)
  File "/home/vagrant/st2/st2client/st2client/models/core.py", line 39, in decorate
    return func(*args, **kwargs)
  File "/home/vagrant/st2/st2client/st2client/models/core.py", line 427, in search
    data = response.json()
  File "/home/vagrant/st2/virtualenv/local/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/vagrant/st2/virtualenv/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/home/vagrant/st2/virtualenv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/vagrant/st2/virtualenv/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I changed the API to return an empty list instead of `None` and that seems to work. (See https://github.com/StackStorm/st2/pull/3458/commits/37b63900750967968617ef727a28f45ebe6d5a55)
