### ISSUE TITLE
Bug in book keeping running actions in action runner

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2#3448]
```2017-06-02 20:09:03,958 139793049977232 INFO consumers [-] Shutting down ActionExecutionDispatcher...
2017-06-02 20:09:04,050 139793049977232 INFO executions [-] Marked execution 5931bfdb55fc8c07d2bcfbf7 as abandoned.
2017-06-02 20:09:04,051 139793049977232 INFO utils [-] Invoking post run for action execution 5931bfdb55fc8c07d2bcfbf6.
2017-06-02 20:09:04,064 139793049977232 INFO utils [-] Action execution 5931bfdb55fc8c07d2bcfbf6 runs local of runner type local-shell-cmd.
2017-06-02 20:09:04,073 139793049977232 INFO loader [-] Reusing runner module "/opt/stackstorm/runners/local_runner/local_runner.py" from cache.
2017-06-02 20:09:04,175 139792930625808 AUDIT base [-] Liveaction completed (liveaction_db={'status': 'failed', 'runner_info': {u'hostname': u'st2test', u'pid': 6839}, 'parameters': {u'cmd': u'sleep 180; echo covfefe', u'timeout': 300}, 'action_is_workflow': False, 'start_timestamp': '2017-06-02 19:43:23.795896+00:00', 'callback': {}, 'notify': None, 'result': {'succeeded': False, 'failed': True, 'return_code': -15, 'stderr': '', 'stdout': ''}, 'context': {u'user': u'st2admin'}, 'action': u'core.local', 'id': '5931bfdb55fc8c07d2bcfbf6', 'end_timestamp': '2017-06-02 20:09:04.010835+00:00'})
2017-06-02 20:09:04,204 139792930625808 ERROR consumers [-] ActionsQueueConsumer failed to process message: LiveActionDB(action="core.local", action_is_workflow=False, callback={}, context={u'user': u'st2admin'}, end_timestamp=None, id=5931bfdb55fc8c07d2bcfbf6, notify=None, parameters={u'cmd': u'sleep 180; echo covfefe', u'timeout': 300}, result={}, runner_info={}, start_timestamp="2017-06-02 19:43:23.795896+00:00", status="scheduled")
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/transport/consumers.py", line 71, in _process_message
    self._handler.process(body)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/worker.py", line 95, in process
    if liveaction.status == action_constants.LIVEACTION_STATUS_SCHEDULED
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/worker.py", line 148, in _run_action
    self._running_liveactions.remove(liveaction_db.id)
KeyError: ObjectId('5931bfdb55fc8c07d2bcfbf6')```

**Comment by m4dcoder** [comment]
@lakshmi-kannan Ok I figured out why. So basically, the action is still running, and it's in the _running_liveactions set. But on shutdown, the running action gets remove at https://github.com/StackStorm/st2/blob/ed6fdb4043647b766551c25f365782a58abce019/st2actions/st2actions/worker.py#L102. After the action is abandoned, the _run_action that originally runs the action tries to remove it from the set https://github.com/StackStorm/st2/blob/ed6fdb4043647b766551c25f365782a58abce019/st2actions/st2actions/worker.py#L148.

**Comment by m4dcoder** [comment]
https://github.com/StackStorm/st2/pull/3451
