### ISSUE TITLE
st2 action-alias delete <pack.alias> broken with v2.3

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2#3502]
`st2 action-alias delete <pack.alias>`is broken with 2.3. Worked in 2.2.1, breaks in 2.3.0. 

NB: Doesn't matter if you try it with an alias reference or ID - it returns the same error:

```sh
vagrant@bwcvagrant:~$ st2 action-alias delete packs.pack_show
ERROR: More than one actionalias named "packs.pack_show" are found.
```

This is *not* a duplicate pack name. This has been verified with looking into MongoDB. Similar result seen when deleting by ID. Again, there are no duplicate IDs in Mongo.

Drilling into the API calls with `st2 --debug`, it looks like the problem is with the first call made. When you run `st2 --debug action-alias delete packs.pack_get`, the first request/response looks like this:

```
# -------- begin 140061842088656 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.11.1' -H  'X-Auth-Token: 34560751f75a4911b724d3f73ffe1842' 'http://127.0.0.1:9101/v1/actionalias/?name=packs.pack_get'
# -------- begin 140061842088656 response ----------
[]
# -------- end 140061842088656 response ------------
```

After that, it calls `curl -X GET http://127.0.0.1:9101/v1/actionalias/packs.pack_get` to get the JSON object for the alias. It extracts the ID, and then does `curl -X DELETE  http://127.0.0.1:9101/v1/actionalias/594b21aadeb4c2316ea5250f` That all works OK.

But with 2.3.0, the first call instead returns all configured aliases:

```
vagrant@bwcvagrant:~$ st2 --debug action-alias delete packs.pack_get
2017-06-21 00:15:16,611  DEBUG - Using cached token from file "/home/vagrant/.st2/token-st2admin"
# -------- begin 140231044360784 request ----------
curl -X GET -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.14.2' -H  'X-Auth-Token: aa19627fcf9d4ed8842715f502b51870' 'http://127.0.0.1:9101/v1/actionalias/?name=packs.pack_get'
# -------- begin 140231044360784 response ----------
[
    {
        "description": "Find the interface/Port-Channel/Tunnel where the MAC address shows up in a VCS fabric",
        "extra": {},
        "ack": {},
        "enabled": true,
        "name": "find_mac",
        "result": {},
        "formats": [
            "find MAC {{macs}} on {{host}}"
        ],
        "action_ref": "network_essentials.find_mac",
        "pack": "network_essentials",
        "ref": "network_essentials.find_mac",
        "id": "5887be73bb0f1859c8af10dd",
        "uid": "action:network_essentials:find_mac"
    },
<snip - output showed all the configured aliases on this system>
    }
]
# -------- end 140231044360784 response ------------

ERROR: More than one actionalias named "packs.pack_get" are found.

CLI settings:
----------------
Config file path: /home/vagrant/.st2/config
Client settings:
----------------
ST2_BASE_URL: http://127.0.0.1
ST2_AUTH_URL: http://127.0.0.1:9100
ST2_API_URL: http://127.0.0.1:9101/v1
ST2_AUTH_TOKEN: aa19627fcf9d4ed8842715f502b51870

Proxy settings:
---------------
HTTP_PROXY:
HTTPS_PROXY:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/shell.py", line 298, in run
    args.func(args)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 542, in run_and_print
    self.run(args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 44, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 535, in run
    instance = self.get_resource(resource_id, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 149, in get_resource
    instance = self.get_resource_by_name_or_id(name_or_id=name_or_id, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 191, in get_resource_by_name_or_id
    instance = self.get_resource_by_name(name=name_or_id, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/commands/resource.py", line 187, in get_resource_by_name
    instance = self.manager.get_by_name(name, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/models/core.py", line 39, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/models/core.py", line 287, in get_by_name
    (self.resource.__name__.lower(), name))
Exception: More than one actionalias named "packs.pack_get" are found.
```

It is possible to manually delete the alias by making a direct API call, e.g.:

`curl -X DELETE http://127.0.0.1:9101/v1/actionalias/5887bd71bb0f1834bc628d9a`

Expected behavior: `st2 action-alias delete <alias>` deletes the alias like I tell it to, and doesn't get uppity

**Comment by LindsayHill** [comment]
Fixed in https://github.com/StackStorm/st2/pull/3503, will be published with 2.3.1
