### ISSUE TITLE
Incorrect casing for log level config causes errors

### ISSUE THREAD

**Issue by mickmcgrath13** [StackStorm/st2#3513]
Support any case?

Example (EL6),
in `/etc/st2/logging.actionrunner.conf`
if you have
```
[logger_root]
level=debug
```
instead of 
```
[logger_root]
level=DEBUG
```

..this happens
```
$ sudo /opt/stackstorm/st2/bin/python /opt/stackstorm/st2/bin/st2actionrunner --config-file /etc/st2/st2.conf
2017-06-23 11:26:37,074 DEBUG [-] Using config files: /etc/st2/st2.conf
2017-06-23 11:26:37,075 DEBUG [-] Using logging config: /etc/st2/logging.actionrunner.conf
ERROR: Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/log.py", line 186, in setup
    disable_existing_loggers=disable_existing_loggers)
  File "/usr/share/python/st2python/lib/python2.7/logging/config.py", line 85, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/share/python/st2python/lib/python2.7/logging/config.py", line 166, in _install_handlers
    h.setLevel(logging._levelNames[level])
KeyError: 'debug'
2017-06-23 11:26:37,077 ERROR [-] (PID=1189) Worker quit due to exception.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/cmd/actionrunner.py", line 81, in main
    _setup()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/cmd/actionrunner.py", line 36, in _setup
    register_signal_handlers=True)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/service_setup.py", line 92, in setup
    excludes=cfg.CONF.log.excludes)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/log.py", line 196, in setup
    raise Exception(six.text_type(exc))
Exception: 'debug'
```

**Comment by Kami** [comment]
That's by design and now much we can do since it's native Python functionality.

Well, we could do some hacking around and process the logging config and manually load it but this seems unnecessary to me.

Perhaps best way to do that would just be to document that log levels need to be uppercase?

**Comment by Kami** [comment]
That's about as much as we can do - https://github.com/StackStorm/st2docs/pull/536.

I looked if we could perhaps throw a more user-friendly exception in our code, but sadly that's not easily possible. Loggign module from Python stdlib logs exception to stderr instead of throwing it which means re-throwing more friendly exception would require a lot of hacky code to determine what exception was printed to stderr (we would need to intercept and inspect stderr which is error prone, hacky and not worth it in this case).
