### ISSUE TITLE
st2 pack install fails unless git repo has .git suffix (SSH)

### ISSUE THREAD

**Issue by carbineneutral** [StackStorm/st2#3534]
Our private git repository has an SSH URL that does not end in ".git"

When we attempt to install a pack it fails because the git command appends a ".git" to the URL, which is not valid for our repo.

If we artificially create a new repo with ".git" in it's URL, it works as expected.

If we manually execute the git command from the cmdline excerpt (below), but remove the ".git" suffix, the clone works as expected.

st2 2.3.0
Linux st2-local 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Trace included (with obfuscations).

```
ubuntu@st2-local:~$ st2 pack install ssh://<user@host>/AutomationStackStorm

        [       failed       ] download pack

id: 595525a6a5fb1d0755645a1e
action.ref: packs.install
parameters:
  packs:
  - ssh://<user@host>/AutomationStackStorm
status: failed
error: Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 75, in run
    verifyssl=verifyssl, ref=pack_version)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 102, in _clone_repo
    repo = Repo.clone_from(repo_url, temp_dir)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/repo/base.py", line 942, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/repo/base.py", line 897, in _clone
    finalize_process(proc, stderr=stderr)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/util.py", line 341, in finalize_process
    proc.wait(**kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/git/cmd.py", line 292, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v ssh://<user@host>/AutomationStackStorm.git /root/<hash>
  stderr: 'Cloning into '/root/<hash>'...

Your Git command did not succeed.
Details:
        TF401019: The Git repository with name or identifier AutomationStackStorm.git does not exist or you do not have permissions for the operation you are attempting.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
'

traceback: None
failed_on: download pack
start_timestamp: 2017-06-29T16:07:02.112809Z
end_timestamp: 2017-06-29T16:07:08.565932Z
+--------------------------+---------------------+---------------+----------------+-----------------+
| id                       | status              | task          | action         | start_timestamp |
+--------------------------+---------------------+---------------+----------------+-----------------+
| 595525a6a5fb1d0559d30ab4 | failed (6s elapsed) | download pack | packs.download | Thu, 29 Jun     |
|                          |                     |               |                | 2017 16:07:02   |
|                          |                     |               |                | UTC             |
+--------------------------+---------------------+---------------+----------------+-----------------+
```

**Comment by armab** [comment]
From the log, it looks like `.git` append `ssh://<user@host>/AutomationStackStorm` -> `ssh://<user@host>/AutomationStackStorm.git` is taking place which results in a wrong repo.

Mind to provide a Pull Request with a fix?

1 line to change here: 
https://github.com/StackStorm/st2/blob/b3f9b547072ed0ef747a3824b147670e720cf1b3/contrib/packs/actions/pack_mgmt/download.py#L296

**Comment by carbineneutral** [comment]
Thanks for the prompt response.

Yes, that fixes my immediate problem, but a full solution is more complex than a single line change as that would result in a regression for users currently using the de facto suffix functionality.

If the intention was to add ".git" for github repos, then the following might work.
```
           if len(repo_url.split('/')) == 2 and 'git@' not in repo_url:
                url = 'https://github.com/{}'.format(repo_url)
                if not url.endswith('.git'):
                    url = '{}.git'.format(url)
            else:
                url = repo_url
            return url
```

I do not know enough about the requirements to make that call, however.

**Comment by armab** [comment]
:+1:

But GitHub is not a problem, because all of the following works:
```
git clone git@github.com:StackStorm/st2.git
git clone git@github.com:StackStorm/st2
git clone https://github.com/StackStorm/st2.git
git clone https://github.com/StackStorm/st2
```

So either 1 line change removing the `.git` or something similar might be good enough to start with and continue discussion in a PR. Also other team members are there to help & think about the corner cases and request changes if needed :wink:

**Comment by Kami** [comment]
Thanks for reporting this and yeah, agree with @armab.

Feel free to open a PR and we will work from there (we already have some tests for URI handling and it looks like we need more :)).
