### ISSUE TITLE
Support for alternative queues?

### ISSUE THREAD

**Issue by johnarnold** [StackStorm/st2#3601]
Hi,

Since you're using kombu for communication with the queue, would it be possible to use other kombu-supported queues, other than RabbitMQ?

E.g. we use Redis with kombu for our celery service.  Could we use Redis for stackstorm, too?  Any special features that require RabbitMQ?

Redis is available as a SaaS on our cloud, so I'd like to take advantage of that if possible.

Thanks,
John

**Comment by johnarnold** [comment]
Also would be happy to use Azure Service Bus :)  Although not supported in kombu, it seems possible to make a virtual broker over it.

**Comment by LindsayHill** [comment]
I can't find a link to it now, but I recall from previous discussions with the team that the opinion was: "There's a fair chance it would work, but no-one's tested it, so can't say for sure."

Haven't heard of anyone planning on testing it, but you're welcome to try

**Comment by johnarnold** [comment]
@LindsayHill 

I set up a dev instance for testing.  So far, I found that:

- If you specify the database number in the URL, it blows up (not a showstopper, use default db 0)
- multiple processes still blow up trying to create the exchange...

```
2017-08-01 01:35:39,460 140109504094608 ERROR st2notifier [-] (PID=11807) Results tracker quit due to exception.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/st2notifier.py", line 56, in main
    _setup()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/st2notifier.py", line 27, in _setup
    register_signal_handlers=True)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 117, in setup
    register_exchanges_with_retry()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/transport/bootstrap_utils.py", line 83, in register_exchanges_with_retry
    return retrying_obj.call(register_exchanges)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 205, in call
    if not self.should_reject(attempt):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 189, in should_reject
    reject |= self._retry_on_exception(attempt.value[1])
TypeError: unsupported operand type(s) for |=: 'bool' and 'error'

```

**Comment by johnarnold** [comment]
For historical reference, this error occurs when using a database number in the messaging url:
```
2017-08-01 01:03:33,829 140313745072848 ERROR connection_retry_wrapper [-] Connections to rabbitmq cannot be re-established: sequence item 0: expected string, list found
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/transport/connection_retry_wrapper.py", line 115, in run
    channel = connection.channel()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kombu/connection.py", line 255, in channel
    chan = self.transport.create_channel(self.connection)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kombu/connection.py", line 756, in connection
    self._connection = self._establish_connection()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kombu/connection.py", line 711, in _establish_connection
    conn = self.transport.establish_connection()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 106, in establish_connection
    'host': conninfo.host,
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kombu/connection.py", line 779, in host
    return ':'.join([self.hostname, str(self.port)])
TypeError: sequence item 0: expected string, list found
```
