### ISSUE TITLE
st2api keeps restarting

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#3615]
Our `st2api` service keeps restarting with the following error in the logs:

```
2017-07-26 13:49:19,037 INFO [-] (PID=22624) ST2 API is serving on http://0.0.0.0:9101.
2017-07-26 13:49:19,038 INFO [-] Creating st2api: StackStorm v2.3.1 as OpenAPI app.
2017-07-26 13:49:20,749 INFO [-] Connected to amqp://guest:**@127.0.0.1:5672//
2017-07-26 13:49:20,782 WARNING [-] Coordination backend is not configured. Code paths which use coordination service will use best effort approach and race conditions are possible.
2017-07-26 13:49:20,783 ERROR [-] (PID=22624) ST2 API quit due to exception.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/cmd/api.py", line 74, in main
    return _run_server()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/cmd/api.py", line 63, in _run_server
    wsgi.server(sock, app.setup_app(), custom_pool=worker_pool, log=LOG, log_output=False)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/app.py", line 66, in setup_app
    router.add_spec(spec, transforms=transforms)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/router.py", line 185, in add_spec
    __import__(module_name)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/keyvalue.py", line 306, in <module>
    key_value_pair_controller = KeyValuePairController()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/keyvalue.py", line 62, in __init__
    self._coordinator = coordination.get_coordinator()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/services/coordination.py", line 177, in get_coordinator
    COORDINATOR = coordinator_setup()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/services/coordination.py", line 159, in coordinator_setup
    coordinator = NoOpDriver(member_id)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/services/coordination.py", line 59, in __init__
    super(NoOpDriver, self).__init__(member_id)
TypeError: __init__() takes exactly 4 arguments (2 given)
2017-07-26 13:49:20,790 INFO [-] Started timer core.2d24c68d-61d9-42f9-9536-98bf0fddf42d with parameters {u'unit': u'seconds', u'delta': 5}
```

This was installed with one-liner install.

Running version 2.3.1

**Comment by Kami** [comment]
It looks like you are running latest version of `tooz` which changes driver class signature.

This could happen if you manually upgraded tooz or if installer script used `requirements.txt` from master (which it shouldn't have unless you are using an old deprecated installer script).

**Comment by Kami** [comment]
^Having said that - can you please clarify how you have upgraded / installed StackStorm? Did you upgrade tooz or any other dependency? Did you previously install v2.4 dev or similar?

The tooz change was made in st2/master (v2.4dev) and it should in no way affect v2.3.1. v2.3.1 packages were built much earlier then that change has been made and all the dependency are vendored and packaged with StackStorm release package so I can't think of a way that change could leak into an existing release.

**Comment by nmaludy** [comment]
This is another developers instance. Let me browser through command history to see if they ran a pip upgrade. I'll also check the version of tooz installed.

**Comment by nmaludy** [comment]
@Kami looks like the developer ran a pip upgrade while they had the st2 virtualenv activated. Of course they "did nothing"... closing this. Thanks for the help!

**Comment by Kami** [comment]
@nmaludy no problem :)

If you want to use latest version of `tooz` and you don't mind running dev version you can use v2.4 dev :)
