### ISSUE TITLE
weird, it succeeded after 4 retries for "pack install"

### ISSUE THREAD

**Issue by leoxhj** [StackStorm/st2#3623]
Dear support,

During package deployment to our production, we encountered very strange behavior, we run exactly same command "st2 pack install git@git.dev.xyz.com:st2/poseidon.git=dev" 4 times, it only succeeded the 4th time.

1st time, pack install says all succeeded, but apparently directory "poseidon" has not been created.
2nd time, same as 1st time
3rd time, pack install failed at 4 step when registering pack since the directory was not created.
4th time, pack install succeeded and the directory "poseidon" finally have been created.

please assist, maybe pack install need another more step to verify if the directory has been really created or not.

above scenario is not always the case, sometimes it maybe succeeded 1 times, maybe 2 times...

Detail command output as shown below

---------output--------------

```sh
[powerop@VMS52784 packs]$ st2 pack install git@git.dev.xyz.com:st2/poseidon.git=dev

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[ succeeded ] install pack dependencies
	[ succeeded ] register pack

+-------------+-------------------------------------------------------+
| Property    | Value                                                 |
+-------------+-------------------------------------------------------+
| name        | poseidon                                              |
| description | A pack containing all actions, workflows, rules, etc. |
| version     | 0.1.0                                                 |
| author      | hj_xu                                                 |
+-------------+-------------------------------------------------------+
[powerop@VMS52784 packs]$ ll
total 36
drwxrwxr-x  6 root st2packs 4096 Jul 28 11:05 ars
drwxrwxr-x  5 root st2packs 4096 Jul 14 15:51 chatops
drwxrwxr-x  5 root st2packs 4096 Jul 28 10:22 cms
drwxrwxr-x  5 root st2packs 4096 Jul 14 15:51 core
drwxrwxr-x  5 root st2packs 4096 Jul 14 15:51 default
drwxrwxr-x  5 root st2packs 4096 Jul 28 10:25 jump
drwxrwxr-x 10 root st2packs 4096 Jul 28 10:59 liberty
drwxrwxr-x  4 root st2packs 4096 Jul 14 15:51 linux
drwxrwxr-x  5 root st2packs 4096 Jul 14 15:51 packs
[powerop@VMS52784 packs]$ st2 pack install git@git.dev.sh.xyz.com:st2/poseidon.git=dev

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[ succeeded ] install pack dependencies
	[ succeeded ] register pack

+-------------+-------------------------------------------------------+
| Property    | Value                                                 |
+-------------+-------------------------------------------------------+
| name        | poseidon                                              |
| description | A pack containing all actions, workflows, rules, etc. |
| version     | 0.1.0                                                 |
| author      | hj_xu                                                 |
+-------------+-------------------------------------------------------+
[powerop@VMS52784 packs]$ ll
total 36
drwxrwxr-x  6 root st2packs 4096 Jul 28 11:05 ars
drwxrwxr-x  5 root st2packs 4096 Jul 14 15:51 chatops
drwxrwxr-x  5 root st2packs 4096 Jul 28 10:22 cms
drwxrwxr-x  5 root st2packs 4096 Jul 14 15:51 core
drwxrwxr-x  5 root st2packs 4096 Jul 14 15:51 default
drwxrwxr-x  5 root st2packs 4096 Jul 28 10:25 jump
drwxrwxr-x 10 root st2packs 4096 Jul 28 10:59 liberty
drwxrwxr-x  4 root st2packs 4096 Jul 14 15:51 linux
drwxrwxr-x  5 root st2packs 4096 Jul 14 15:51 packs
[powerop@VMS52784 packs]$ st2 pack install git@git.dev.sh.xyz.com:st2/poseidon.git=dev

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[ succeeded ] install pack dependencies
	[  failed   ] register pack

id: 597aab2225f69632fcc24d49
action.ref: packs.install
parameters: 
  packs:
  - git@git.dev.sh.ctripcorp.com:st2/poseidon.git=dev
status: failed
error: st2.actions.python.St2RegisterAction: DEBUG    Calling client method "register" with kwargs "{'types': [u'all'], 'packs': [u'poseidon']}"
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py", line 81, in run
    format_func=format_result)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py", line 149, in _run_client_method
    result = method(**method_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 39, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 443, in register
    self.handle_error(response)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 165, in handle_error
    response.raise_for_status()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request
MESSAGE: Pack "poseidon" not found on disk: Directory "/opt/stackstorm/packs/poseidon" doesn't exist for url: http://127.0.0.1:9101/v1/packs/register

traceback: None
failed_on: register pack
start_timestamp: 2017-07-28T03:10:26.778984Z
end_timestamp: 2017-07-28T03:10:55.840301Z
+--------------------------+-------------------------+---------------------------+-------------------------+-------------------------------+
| id                       | status                  | task                      | action                  | start_timestamp               |
+--------------------------+-------------------------+---------------------------+-------------------------+-------------------------------+
| 597aab236742b95a89fd2fa6 | succeeded (2s elapsed)  | download pack             | packs.download          | Fri, 28 Jul 2017 03:10:27 UTC |
| 597aab266742b95a89fd2fa8 | succeeded (1s elapsed)  | make a prerun             | packs.virtualenv_prerun | Fri, 28 Jul 2017 03:10:30 UTC |
| 597aab286742b95a89fd2faa | succeeded (21s elapsed) | install pack dependencies | packs.setup_virtualenv  | Fri, 28 Jul 2017 03:10:32 UTC |
| 597aab3d6742b95a89fd2fac | failed (2s elapsed)     | register pack             | packs.load              | Fri, 28 Jul 2017 03:10:53 UTC |
+--------------------------+-------------------------+---------------------------+-------------------------+-------------------------------+
[powerop@VMS52784 packs]$ st2 pack install git@git.dev.sh.xyz.com:st2/poseidon.git=dev

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[ succeeded ] install pack dependencies
	[ succeeded ] register pack

+-------------+-------------------------------------------------------+
| Property    | Value                                                 |
+-------------+-------------------------------------------------------+
| name        | poseidon                                              |
| description | A pack containing all actions, workflows, rules, etc. |
| version     | 0.1.0                                                 |
| author      | hj_xu                                                 |
+-------------+-------------------------------------------------------+
[powerop@VMS52784 packs]$ ll
total 40
drwxrwxr-x  6 root st2packs 4096 Jul 28 11:05 ars
drwxrwxr-x  5 root st2packs 4096 Jul 14 15:51 chatops
drwxrwxr-x  5 root st2packs 4096 Jul 28 10:22 cms
drwxrwxr-x  5 root st2packs 4096 Jul 14 15:51 core
drwxrwxr-x  5 root st2packs 4096 Jul 14 15:51 default
drwxrwxr-x  5 root st2packs 4096 Jul 28 10:25 jump
drwxrwxr-x 10 root st2packs 4096 Jul 28 10:59 liberty
drwxrwxr-x  4 root st2packs 4096 Jul 14 15:51 linux
drwxrwxr-x  5 root st2packs 4096 Jul 14 15:51 packs
drwxrwxr-x  6 root st2packs 4096 Jul 28 11:11 poseidon
```

**Comment by LindsayHill** [comment]
That seems...strange. Do you see similar behavior with other packs, or just this one?

Do you see anything interesting in st2api.log around this time?

**Comment by leoxhj** [comment]
I noticed this probably due to application HA issue. we have 3 st2 application servers. and If I run pack install one of of them, and sometimes, seems the pack files will be downloaded to other node in the cluster. that can explain why it failed at the 4th step. not confirmed, but I guess to.

we still don't quite understand how to build the st2 application HA according the official doc,  the database like mongod HA seems pretty much easier.

**Comment by armab** [comment]
@leoxhj Of course, HA is absolutely special story.

Did you configure shared NFS for `/opt/stackstorm/packs` on all st2 servers as suggested in HA doc?
https://docs.stackstorm.com/reference/ha.html#read-write-nfs-mounts

**Comment by LindsayHill** [comment]
Closing this in favour of #3191
