### ISSUE TITLE
Mistral workflow end-up with failed after one day.

### ISSUE THREAD

**Issue by leoxhj** [StackStorm/st2#3666]
Dear support,

We have wrote our mistral workflow, there's a few long running tasks defined timeout: 86400 (one day), and this morning when one of such task continues, the whole workflow ended-up. we have built our own front-end webui, and all api calls use st2-api-key instead of token and according to st2api.log, seems http header has X-Auth-Token, detail log please shown as follows: 

```
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 1665
Content-Type: application/json
Host: 127.0.0.1:9101
St2-Context: {"parent": {"user": "st2admin", "execution_id": "598abac56742b955ccc30760"}, "mistral": {"action_execution_id": "eb94187d-ab61-44e5-88bb-9950fa80c44c", "task_id": "cbfba0d1-ca9b-44a6-8084-d411a07a5a2f", "workflow_name": "liberty.pool-decommission.main", "workflow_execution_id": "8868bdb2-582e-45db-b2d8-5b8ca8ad4880", "task_tags": null, "task_name": "t_poseidon_group_disable", "callback_url": "/v2/action_executions/eb94187d-ab61-44e5-88bb-9950fa80c44c"}}
User-Agent: python-requests/2.17.3
X-Auth-Token: f31926403b464b928a003f69db756496
X-Request-Id: 42263536-4f94-4fa0-97a3-78689bc0b88a

{"action": "poseidon.group_disable", "callback": {"url": "http://0.0.0.0:8989/v2/action_executions/eb94187d-ab61-44e5-88bb-9950fa80c44c", "source": "mistral_v2"}, "notify": {}, "parameters": {"group_info": [], "pool_info": [{"specialSegment": null, "extendAttributes": [], "appType": "Application", "memberType": "SERVER", "entityStatus": "NORMAL", "tools": false, "supporter": "jiawenwang\u738b\u5609\u6587,hwyuan\u8881\u6000\u65fa", "joinMonitoring": true, "cpuAllocationRatio": "1.5", "IDC": null, "version": "1", "joinTars": false, "joinPci": false, "supportTeam": "\u4e0a\u6d77-OPS-APP", "performanceLevel": "50", "description": "\u3010\u5468\u8fb9\u6e38\u3011\u8fd0\u8425\u6570\u636e\u7ec4\u6570\u636e\u5206\u6790\u6240\u7528\u7684Pool(\u7533\u8bf7\u4eba:sfyu)", "importance": "\u4e8c\u7ea7\uff08\u4e2d\uff09", "canRelease": true, "assetDept": null, "specialComponentDescribe": "", "internetAccessible": false, "opsSupportTeam": "APP", "poolType": "\u96c6\u7fa4", "managementDepartment": "OPS", "createTime": "2016-11-17 17:33:26", "specialComponentSupport": false, "osFamily": "linux", "belongToBi": true, "name": "shx.da.bi", "selfSupport": true, "onLB": true, "appEnv": "linux_common", "joinSalt": true, "joinRelease": false, "serviceCode": "OPS-APP-\u5468\u8fb9\u6e38(\u81ea\u7ef4\u62a4)", "poolId": "5500", "organization": {"status": "\u6b63\u5e38", "code": "TOUR", "description": null, "sbu": "\u5ea6\u5047", "organizationId": "51", "cost_center": "\u5ea6\u5047", "cp4code": "", "englishName": "Package", "domainNameKeywords": "package,visa,outie,mice,ctr,vdp", "createTime": null, "name": "\u5ea6\u5047"}}], "execution_id": "598abac56742b955ccc30760"}}
2017-08-11 09:58:27,753 66309808 INFO logging [-] 66831e2c-2e51-48e0-82d1-5b468f02a7b6 - 201 2331 146.054ms (content_length=2331,request_id='66831e2c-2e51-48e0-82d1-5b468f02a7b6',runtime=146.054,remote_addr='127.0.0.1',status=201,method='POST',path='/v1/executions')
2017-08-11 09:58:27,754 63400048 DEBUG router [-] Match path: /v1/actionexecutions
2017-08-11 09:58:27,755 63400048 DEBUG router [-] Parsed endpoint: {'x-parameters': [{'in': 'context', 'x-as': 'requester_user', 'name': 'user', 'description': 'User performing the operation.'}], 'responses': {'default': {'description': 'Unexpected error', 'schema': {'$ref': '#/definitions/Error'}}, '200': {'schema': {'$ref': '#/definitions/Execution'}, 'examples': {'application/json': {'action': {'type': 'object'}, 'trigger': {'type': 'object'}}}, 'description': 'Execution being created'}}, 'parameters': [{'in': 'body', 'description': 'Execution request', 'name': 'liveaction_api', 'schema': {'$ref': '#/definitions/ExecutionRequest'}}, {'in': 'query', 'type': 'boolean', 'description': 'Show secrets in plain text', 'name': 'show_secrets'}, {'in': 'header', 'type': 'string', 'x-as': 'context_string', 'name': 'st2-context', 'description': 'Additional execution context'}], 'x-log-result': False, 'description': 'Create a new execution.\n', 'operationId': 'st2api.controllers.v1.actionexecutions:action_executions_controller.post'}
2017-08-11 09:58:27,755 63400048 DEBUG router [-] Parsed path_vars: {}
2017-08-11 09:58:27,757 63400048 AUDIT auth [-] Token with id "598abac61b1c605e44f26846" has expired.
2017-08-11 09:58:27,758 63400048 ERROR router [-] Token has expired.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/router.py", line 259, in __call__
    auth_resp = auth_func(token)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/auth.py", line 53, in validate_token
    raise exceptions.TokenExpiredError('Token has expired.')
TokenExpiredError: Token has expired.
2017-08-11 09:58:27,759 63400048 DEBUG error_handling [-] API call failed: Unauthorized - Token has expired. (exception_message='Unauthorized - Token has expired.',exception_data={'comment': 'Unauthorized - Token has expired.', '_headers': None, 'conditional_response': False, 'detail': 'Unauthorized - Token has expired.', '_app_iter': [''], '_status': '401 Unauthorized', '_headerlist': [('Content-Type', 'text/html; charset=UTF-8'), ('Content-Length', '0')]},exception_class='HTTPUnauthorized')
2017-08-11 09:58:27,759 63400048 DEBUG error_handling [-] Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/middleware/error_handling.py", line 46, in __call__
    return self.app(environ, start_response)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/router.py", line 445, in as_wsgi
    resp = self(req)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/router.py", line 277, in __call__
    return abort_unauthorized(str(e))
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/router.py", line 56, in abort_unauthorized
    raise exc.HTTPUnauthorized('Unauthorized - %s' % msg if msg else 'Unauthorized')
HTTPUnauthorized: Unauthorized - Token has expired.
 ```

**Comment by m4dcoder** [comment]
When st2 invokes a Mistral workflow, a one time token is generated for Mistral to use.  This token allows Mistral to communicate back with st2.  The st2-api-key doesn't get passed to Mistral.  If you anticipate workflow to run longer than a day, then you'll need to change the TTL setting for st2 tokens.
