### ISSUE TITLE
Broken API endpoint "/api/v1/packs/index/health"

### ISSUE THREAD

**Issue by humblearner** [StackStorm/st2#3672]
st2 2.3.2

```
$ curl -X GET -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.14.2' -H  'X-Auth-Token: <token>' 'http://127.0.0.1:9101/v1/packs/index/health'
{
    "faultstring": "Internal Server Error"
}
```
st2api.log

```
2017-08-14 21:20:38,584 140453678780080 INFO logging [-] 3223f7fe-a627-43dc-bb5f-70b61e660bfc - GET /v1/packs/index/health with query={} (remote_addr='127.0.0.1',method='GET',request_id='3223f7fe-a627-43dc-bb5f-70b61e660bfc',query={},path='/v1/packs/index/health')
2017-08-14 21:20:38,587 140453678780080 AUDIT auth [-] Token with id "5992135fde59a41f7127fb87" is validated.
2017-08-14 21:20:38,591 140453678780080 ERROR router [-] Failed to load controller for operation "st2api.controllers.v1.packs:packs_controller.index.get": PacksIndexController instance has no attribute 'get'
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/router.py", line 419, in __call__
    func = op_resolver(endpoint['operationId'])
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/router.py", line 48, in op_resolver
    return functools.reduce(getattr, func_name.split('.'), module)
AttributeError: PacksIndexController instance has no attribute 'get'
2017-08-14 21:20:38,591 140453678780080 ERROR error_handling [-] API call failed: PacksIndexController instance has no attribute 'get'
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/middleware/error_handling.py", line 46, in __call__
    return self.app(environ, start_response)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/router.py", line 472, in as_wsgi
    resp = self(req)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/router.py", line 423, in __call__
    raise e
AttributeError: PacksIndexController instance has no attribute 'get' (_exception_data={},_exception_class='AttributeError',_exception_message="PacksIndexController instance has no attribute 'get'")
2017-08-14 21:20:38,592 140453678780080 INFO logging [-] 3223f7fe-a627-43dc-bb5f-70b61e660bfc - 500 46 8.661ms (content_length=46,request_id='3223f7fe-a627-43dc-bb5f-70b61e660bfc',runtime=8.661,remote_addr='127.0.0.1',status=500,method='GET',path='/v1/packs/index/health')
```

**Comment by enykeev** [comment]
Fixed in https://github.com/StackStorm/st2/pull/3671
