### ISSUE TITLE
getting internal server error 500 after executing workflow when is used openstack pack or mistral runner

### ISSUE THREAD

**Issue by QualoZe0t** [StackStorm/st2#3695]
can you please help us or analyse what could be the RC why we are getting always 500 as separate openstack commands are able to connect to openstack + execute particular action

workflow:

ubuntu@ansible-node:/opt/stackstorm/packs/mmuransky/actions/workflows$ cat wf-ref.yaml 

```
---
version: '2.0'

mmuransky.wf-ref:
    description: OpenStack communication test 
    type: direct
   
    input:
      - vm_name
      - image_ref
      - flavor_ref
 
    output:
      vm_id: <% $.vm_id %>

    tasks:
      create_vm:
        action: openstack.server.create server_name=<% $.vm_name %> image=<% $.image_ref %> flavor=<% $.flavor_ref %> nic='net-id=abe198df-fb28-42b5-8e86-a6b11f6312e8'
        publish:
          vm_id: <% task(create_vm).result.id %>
        on-success:
          - wait_for_instance

      wait_for_instance:
          action: openstack.server.show id=<% $.vm_id %> status='ACTIVE'
          retry:
            delay: 5
            count: 15
```

ubuntu@ansible-node:/opt/stackstorm/packs/mmuransky/actions/workflows$ 

metadata
-----------
ubuntu@ansible-node:/opt/stackstorm/packs/mmuransky/actions$ cat wf-ref.yaml 

```
---
description: Test Workflow (OpenStack communication nr2)
enabled: true
runner_type: mistral-v2
entry_point: workflows/wf-ref.yaml
name: wf-ref
pack: mmuransky
parameters:
  vm_name:    
    required: true    
    type: string  
  image_ref:    
    required: true    
    type: string  
  flavor_ref:    
    required: true    
    type: string
ubuntu@ansible-node:/opt/stackstorm/packs/mmuransky/actions$ 
```

output from execution
ubuntu@ansible-node:/opt/stackstorm/packs/mmuransky/actions$ st2 execution get --detail 599c3cd37d0507671e9eb585

```
+-----------------+--------------------------------------------------------------+
| Property        | Value                                                        |
+-----------------+--------------------------------------------------------------+
| id              | 599c3cd37d0507671e9eb585                                     |
| action.ref      | mmuransky.wf-ref                                             |
| context.user    | stanley                                                      |
| parameters      | {                                                            |
|                 |     "vm_name": "test2_vm",                                   |
|                 |     "flavor_ref": "m1.small",                                |
|                 |     "image_ref": "ubuntu-14.04.5"                            |
|                 | }                                                            |
| status          | failed (0s elapsed)                                          |
| start_timestamp | Tue, 22 Aug 2017 14:16:51 UTC                                |
| end_timestamp   | Tue, 22 Aug 2017 14:16:51 UTC                                |
| result          | {                                                            |
|                 |     "traceback": "  File                                     |
|                 | "/opt/stackstorm/st2/local/lib/python2.7/site-               |
|                 | packages/st2actions/container/base.py", line 102, in _do_run |
|                 |     (status, result, context) = runner.run(action_params)    |
|                 |   File "/opt/stackstorm/st2/local/lib/python2.7/site-        |
|                 | packages/retrying.py", line 49, in wrapped_f                 |
|                 |     return Retrying(*dargs, **dkw).call(f, *args, **kw)      |
|                 |   File "/opt/stackstorm/st2/local/lib/python2.7/site-        |
|                 | packages/retrying.py", line 206, in call                     |
|                 |     return attempt.get(self._wrap_exception)                 |
|                 |   File "/opt/stackstorm/st2/local/lib/python2.7/site-        |
|                 | packages/retrying.py", line 247, in get                      |
|                 |     six.reraise(self.value[0], self.value[1], self.value[2]) |
|                 |   File "/opt/stackstorm/st2/local/lib/python2.7/site-        |
|                 | packages/retrying.py", line 200, in call                     |
|                 |     attempt = Attempt(fn(*args, **kwargs), attempt_number,   |
|                 | False)                                                       |
|                 |   File "/opt/stackstorm/runners/mistral_v2/mistral_v2.py",   |
|                 | line 233, in run                                             |
|                 |     result = self.start(action_parameters=action_parameters) |
|                 |   File "/opt/stackstorm/runners/mistral_v2/mistral_v2.py",   |
|                 | line 272, in start                                           |
|                 |     self._save_workflow(action_ref, def_yaml_xformed)        |
|                 |   File "/opt/stackstorm/runners/mistral_v2/mistral_v2.py",   |
|                 | line 125, in _save_workflow                                  |
|                 |     wf = self._client.workflows.create(def_yaml)[0]          |
|                 |   File "/opt/stackstorm/st2/local/lib/python2.7/site-        |
|                 | packages/mistralclient/api/v2/workflows.py", line 46, in     |
|                 | create                                                       |
|                 |     self._raise_api_exception(resp)                          |
|                 |   File "/opt/stackstorm/st2/local/lib/python2.7/site-        |
|                 | packages/mistralclient/api/base.py", line 143, in            |
|                 | _raise_api_exception                                         |
|                 |     error_message=error_data)                                |
|                 | ",                                                           |
|                 |     "error": "<html>                                         |
|                 |   <head>                                                     |
|                 |     <title>Internal Server Error</title>                     |
|                 |   </head>                                                    |
|                 |   <body>                                                     |
|                 |     <h1><p>Internal Server Error</p></h1>                    |
|                 |                                                              |
|                 |   </body>                                                    |
|                 | </html>                                                      |
|                 | "                                                            |
|                 | }                                                            |
| liveaction      | {                                                            |
|                 |     "runner_info": {                                         |
|                 |         "hostname": "ansible-node",                          |
|                 |         "pid": 26155                                         |
|                 |     },                                                       |
|                 |     "parameters": {                                          |
|                 |         "vm_name": "test2_vm",                               |
|                 |         "flavor_ref": "m1.small",                            |
|                 |         "image_ref": "ubuntu-14.04.5"                        |
|                 |     },                                                       |
|                 |     "action_is_workflow": true,                              |
|                 |     "callback": {},                                          |
|                 |     "action": "mmuransky.wf-ref",                            |
|                 |     "id": "599c3cd37d0507671e9eb584"                         |
|                 | }                                                            |
+-----------------+--------------------------------------------------------------+
ubuntu@ansible-node:/opt/stackstorm/packs/mmuransky/actions$ 
```

mistral-server.log

```
--------------------
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server [-] Exception during message handling: InvalidActionException: Failed to find action [action_name=create.yaml]
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 157, in _process_incoming
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 213, in dispatch
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 183, in _do_dispatch
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/engine_server.py", line 130, in start_action
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server     **params
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/action_queue.py", line 70, in decorate
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server     res = func(*args, **kw)
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/default_engine.py", line 55, in start_action
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server     action = action_handler.build_action_by_name(action_name)
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/action_handler.py", line 93, in build_action_by_name
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server     action_def = actions.resolve_action_definition(action_name)
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/actions.py", line 530, in resolve_action_definition
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server     "Failed to find action [action_name=%s]" % action_spec_name
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server InvalidActionException: Failed to find action [action_name=create.yaml]
2017-08-22 07:18:06.980 18778 ERROR oslo_messaging.rpc.server 
2017-08-22 13:03:43.555 26277 WARNING oslo_db.sqlalchemy.engines [-] URL postgresql://mistral:***@localhost/mistral does not contain a '+drivername' portion, and will make use of a default driver.  A full dbname+drivername:// protocol is recommended.
2017-08-22 13:03:43.782 26277 INFO oslo_messaging.server [-] blocking executor handles only one message at once. threading or eventlet executor is recommended.
(END)
```

**Comment by nmaludy** [comment]
I was able to get this working by modifying the `openstack.server.create` action metadata file.

I had to add in the line `pack: openstack` and the reload the action.

Is the `pack: openstack` line necessary? Or is something broken with auto ref creation when the action has a `.` in the name?

**Comment by QualoZe0t** [comment]
i have did same test as you did but still getting 500. 
1. edited openstack  
---
description: null
enabled: true
entry_point: src/wrapper.py
name: server.create
pack: openstack
parameters:
    availability_zone:
        description: Select an availability zone for the server
        type: string

2. reload changes 
 sudo st2ctl reload --register-all

3. execute: 
sudo st2 run mmuransky.wf-ref vm_name='test2_vm' image_ref='ubuntu-14.04.5' flavor_ref='m1.small'

output from the task:
.
id: 599c41807d0507671e9eb58e
action.ref: mmuransky.wf-ref
parameters: 
  flavor_ref: m1.small
  image_ref: ubuntu-14.04.5
  vm_name: test2_vm
status: failed
error: <html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>

traceback:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/container/base.py", line 102, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/stackstorm/runners/mistral_v2/mistral_v2.py", line 233, in run
    result = self.start(action_parameters=action_parameters)
  File "/opt/stackstorm/runners/mistral_v2/mistral_v2.py", line 272, in start
    self._save_workflow(action_ref, def_yaml_xformed)
  File "/opt/stackstorm/runners/mistral_v2/mistral_v2.py", line 125, in _save_workflow
    wf = self._client.workflows.create(def_yaml)[0]
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/mistralclient/api/v2/workflows.py", line 46, in create
    self._raise_api_exception(resp)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/mistralclient/api/base.py", line 143, in _raise_api_exception
    error_message=error_data)

start_timestamp: 2017-08-22T14:36:48.235794Z
end_timestamp: 2017-08-22T14:36:48.845907Z
result: See error and traceback.

**Comment by MonolithProjects** [comment]
@nmaludy I can confirm that your solution works (QualoZe0t accidently added the `pack: openstack` to different file.

**Comment by MonolithProjects** [comment]
Guys, the line `action: openstack.server.show id=<% $.vm_id %> status='ACTIVE'` caused the error. There is no `status` parameter in `server.show` action.

**Comment by QualoZe0t** [comment]
Please close the issue
