### ISSUE TITLE
St2 pack install fails if new required config is added to schema

### ISSUE THREAD

**Issue by dfezzie** [StackStorm/st2#3793]
If a pack is already installed in the system, and a new required configuration variable is added to `config.schema.yaml` the install will fail with

```
error: st2.actions.python.St2RegisterAction: DEBUG    Calling client method "register" with kwargs "{'types': [u'all'], 'packs': [u'ipa']}"
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py", line 81, in run
    format_func=format_result)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py", line 149, in _run_client_method
    result = method(**method_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 39, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 480, in register
    self.handle_error(response)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 165, in handle_error
    response.raise_for_status()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error
MESSAGE: Internal Server Error for url: http://127.0.0.1:9101/v1/packs/register
```
Trying to re-register the pack will validate that the new required configuration is the issue
```
2017-10-18 15:02:29,478 WARNING [-] Failed to register configs: Failed to register config "/opt/stackstorm/configs/ipa.yaml" for pack "ipa": Failed validating attribute "bucket_name" in config for pack "ipa" (/opt/stackstorm/configs/ipa.yaml): u'bucket_name' is a required property
```

You can run `st2 pack config <packname>` to fix the issue, but I imagine this is not the intended behavior.

**Comment by Kami** [comment]
Thanks for reporting this.

It's probably related to trying to register config for that pack and that fails because now the config doesn't pass schema validation anymore.

So this is actually the correct and expected behavior -  one thing we should do though is throw a more user-friendly error message.

We could perhaps also consider disabling config registration on pack install - register all the resources except the config to avoid such scenarios.

What do others think?

**Comment by armab** [comment]
I think the current behavior is where we headed for a long time: by default register all content belonging to pack on pack install.

If user updated the pack config schema with the required property, - he should update config as well by adding that required setting.

I agree that only issue in this report is error message which is not user-friendly.

**Comment by LindsayHill** [comment]
I've been wondering about the 'right' behavior here too.  At a minimum, a more user-friendly error would be helpful.

I don't think that disabling config registration on pack install is the right approach. Would cause issues for people who have distributed then pack configs via config mgmt, then installed packs. 

I guess for people that have updated the pack schema themselves, then they should know this change is required. I think it catches out people who are installing a pack maintained by someone else, because it adds a new config requirement. This is actually a more general problem we have related to breaking changes in packs, and how we communicate that to users.

So maybe the first step is just to improve the error message, then work out the broader problem of communicating breaking pack changes.

**Comment by johanek** [comment]
I've been caught by this twice now while developing packs. A more informative error message would be most helpful 😄

**Comment by piyush4669** [comment]
I am still facing this or a similar issue while installing packs.

COMMAND : st2 pack install email 

ERROR: 

```
For the "email" pack, the following content will be registered:

rules     |  1
sensors   |  2
triggers  |  0
actions   |  1
aliases   |  0

Installation may take a while for packs with many items.

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[ succeeded ] install pack dependencies
	[  failed   ] register pack

id: 5e5caf337f704d0822fbb49f
action.ref: packs.install
parameters:
  packs:
  - email
  python3: false
status: failed
result_task: register pack
result:
  exit_code: 1
  result: None
  stderr: "st2.actions.python.St2RegisterAction: DEBUG    Calling client method "register" with kwargs "{'types': [u'all'], 'packs': [u'email']}"
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 333, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 192, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py", line 80, in run
    format_func=format_result)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py", line 148, in _run_client_method
    result = method(**method_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 41, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 548, in register
    response = self.client.post(url, payload, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 32, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 50, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 60, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 95, in post
    response = requests.post(self.root + url, json.dumps(data), **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='myhost.examples.com', port=443): Max retries exceeded with url: /api/v1/packs/register (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd8b138b2d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
"
  stdout: ''
error: st2.actions.python.St2RegisterAction: DEBUG    Calling client method "register" with kwargs "{'types': [u'all'], 'packs': [u'email']}"
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 333, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 192, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py", line 80, in run
    format_func=format_result)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/register.py", line 148, in _run_client_method
    result = method(**method_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 41, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 548, in register
    response = self.client.post(url, payload, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 32, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 50, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 60, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/utils/httpclient.py", line 95, in post
    response = requests.post(self.root + url, json.dumps(data), **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='myhost.examples.com', port=443): Max retries exceeded with url: /api/v1/packs/register (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd8b138b2d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

traceback: None
failed_on: register pack
start_timestamp: Mon, 02 Mar 2020 07:01:07 UTC
end_timestamp: Mon, 02 Mar 2020 07:01:26 UTC
+--------------------------+------------------------+----------------------+----------------------+------------------+
| id                       | status                 | task                 | action               | start_timestamp  |
+--------------------------+------------------------+----------------------+----------------------+------------------+
| 5e5caf347f704d0441348b51 | succeeded (7s elapsed) | download pack        | packs.download       | Mon, 02 Mar 2020 |
|                          |                        |                      |                      | 07:01:08 UTC     |
| 5e5caf3c7f704d0441348b53 | succeeded (0s elapsed) | make a prerun        | packs.virtualenv_pre | Mon, 02 Mar 2020 |
|                          |                        |                      | run                  | 07:01:16 UTC     |
| 5e5caf3d7f704d0441348b55 | succeeded (7s elapsed) | install pack         | packs.setup_virtuale | Mon, 02 Mar 2020 |
|                          |                        | dependencies         | nv                   | 07:01:17 UTC     |
| 5e5caf447f704d0441348b57 | failed (2s elapsed)    | register pack        | packs.load           | Mon, 02 Mar 2020 |
|                          |                        |                      |                      | 07:01:24 UTC     |
+--------------------------+------------------------+----------------------+----------------------+------------------+
```

**Comment by armab** [comment]
@piyush4669 Your issue is different to reported.
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='myhost.examples.com', port=443): Max retries exceeded with url: /api/v1/packs/register (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd8b138b2d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```
With `Name or service not known` for `myhost.examples.com` it's probably a DNS issue. Is that host resolvable/accessible at all?
