### ISSUE TITLE
Jinja is not rendered in action default values prior to schema checking

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#3820]
# Problem

When trying to call an action with Jinja for its default value an error is raised complaining about a type mismatch.

## Action metadata

```yaml
---
description: Run a local linux command
enabled: true
runner_type: mistral-v2
entry_point: workflows/mistral-basic.yaml
name: mistral-basic
pack: examples
parameters:
  cmd:
    required: true
    type: string
  timeout:
    type: integer
    default: 60
  kv_test:
    type: integer
    default: "{{ st2kv.system.nick_test | int }}"
```

## Error - CLI

``` shell
[root@stackstorm st2]# st2 key set nick_test 123
+------------------+-----------+
| Property         | Value     |
+------------------+-----------+
| name             | nick_test |
| value            | 123       |
| expire_timestamp |           |
+------------------+-----------+

[root@stackstorm st2]# st2 run examples.mistral-basic cmd="ls"
ERROR: 400 Client Error: Bad Request
MESSAGE: '{{ st2kv.system.nick_test | int }}' is not of type 'integer' for url: http://127.0.0.1:9101/v1/executions
```

## Error - Logs

``` shell
2017-10-30 16:03:59,072 107609136 ERROR actionexecutions [-] Unable to execute action. Parameter validation failed.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/actionexecutions.py", line 128, in _handle_schedule_execution
    pack=action_db.pack)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/actionexecutions.py", line 177, in _schedule_execution
    liveaction_db, actionexecution_db = action_service.create_request(liveaction_db)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/services/action.py", line 87, in create_request
    allow_default_none=True)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/schema/__init__.py", line 293, in validate
    jsonschema.validate(instance=instance, schema=schema, cls=cls, *args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
ValidationError: u'{{ st2kv.system.nick_test | int }}' is not of type u'integer'

Failed validating u'type' in schema['properties'][u'kv_test']:
    {u'default': u'{{ st2kv.system.nick_test | int }}',
     u'type': u'integer'}

On instance[u'kv_test']:
    u'{{ st2kv.system.nick_test | int }}'
2017-10-30 16:03:59,072 107609136 ERROR router [-] Failed to call controller function "post" for operation "st2api.controllers.v1.actionexecutions:action_executions_controller.post": '{{ st2kv.system.nick_test | int }}' is not of type 'integer'
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/router.py", line 434, in __call__
    resp = func(**kw)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/actionexecutions.py", line 575, in post
    show_secrets=show_secrets)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/actionexecutions.py", line 134, in _handle_schedule_execution
    abort(http_client.BAD_REQUEST, re.sub("u'([^']*)'", r"'\1'", e.message))
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/router.py", line 53, in abort
    raise exc.status_map[status_code](message)
HTTPBadRequest: '{{ st2kv.system.nick_test | int }}' is not of type 'integer'
2017-10-30 16:03:59,073 107609136 INFO logging [-] 2c636a0c-d2ff-4405-9632-8268bd09d76b - 400 86 19.061ms (content_length=86,request_id='2c636a0c-d2ff-4405-9632-8268bd09d76b',runtime=19.061,remote_addr='127.0.0.1',status=400,method='POST',path='/v1/executions')
```

**Comment by humblearner** [comment]
@nmaludy: The problem doesn't seem to be jinja filters. It is the quotes around the integer. The default value for type integer should be a number instead of string. Example:

```bash
vagrant@u16:/opt/stackstorm/packs/examples/actions$ st2  run examples.mistral-basic cmd="ls"
ERROR: 400 Client Error: Bad Request
MESSAGE: '2020' is not of type 'integer' for url: http://127.0.0.1:9101/v1/executions
```
Action
```yaml
---
description: Run a local linux command
enabled: true
runner_type: mistral-v2
entry_point: workflows/mistral-basic.yaml
name: mistral-basic
pack: examples
parameters:
  cmd:
    required: true
    type: string
  timeout:
    type: integer
    default: 60
  kv_test:
    type: integer
    default: "2020" 
vagrant@u16:/opt/stackstorm/packs/examples/actions$
```

**Comment by nmaludy** [comment]
@humblearner The example i gave was simplified to demonstrate the problem.

This also breaks when doing something like:

### Objects

``` YAML
---
description: Run a local linux command
enabled: true
runner_type: mistral-v2
entry_point: workflows/mistral-basic.yaml
name: mistral-basic
pack: examples
parameters:
  cmd:
    required: true
    type: string
  timeout:
    type: integer
    default: 60
  kv_test:
    type: object
    default: "{{ st2kv.system.nick_test | from_json_string }}"
```

``` shell
st2 key set nick_test '{"test_key": "test_value}'
```

### Arrays

``` YAML
---
description: Run a local linux command
enabled: true
runner_type: mistral-v2
entry_point: workflows/mistral-basic.yaml
name: mistral-basic
pack: examples
parameters:
  cmd:
    required: true
    type: string
  timeout:
    type: integer
    default: 60
  kv_test:
    type: array
    default: "{{ st2kv.system.nick_test | from_json_string }}"
```

``` shell
st2 key set nick_test '["a", "b", "c"]'
```

**Comment by Mierdin** [comment]
This is happening because the ActionExecutions API controller [is calling out to param_utils.render_live_params](https://github.com/StackStorm/st2/blob/ac6c00a129e1dc29f8a84a4fab33b94ff3382cd5/st2api/st2api/controllers/v1/actionexecutions.py#L183) which only renders "live" params (meaning params being explicitly passed in, which doesn't include default values. So, [when the controller requests an execution](https://github.com/StackStorm/st2/blob/ac6c00a129e1dc29f8a84a4fab33b94ff3382cd5/st2api/st2api/controllers/v1/actionexecutions.py#L199), the schema is checked, and this value is still an unrendered template, which is of course a string. So with this behavior, the value you're intending to get better also be a string

I'm looking at alternatives now, but figured I'd update the discussion with a root cause. I also see the reference to https://github.com/StackStorm/st2/issues/3828 but as @kami suggests, that's a much bigger change, so I'm looking to see if there's a less dangerous, temporary solution to this problem.
