### ISSUE TITLE
Support unicode in resource refs

### ISSUE THREAD

**Issue by Mierdin** [StackStorm/st2#3874]
Unicode characters break bootstrap code:

```
2017-11-22 00:56:10,611 WARNING [-] Failed to register actions: Failed to register action "/opt/stackstorm/packs/testpack/actions/pythontest.meta.yaml" from pack "testpack": 'ascii' codec can't encode character u'\u2021' in position 10: ordinal not in range(128)
Traceback (most recent call last):
  File "./st2common/bin/st2-register-content", line 22, in <module>
    sys.exit(content_loader.main(sys.argv[1:]))
  File "/home/vagrant/st2/st2common/st2common/content/bootstrap.py", line 388, in main
    register_content()
  File "/home/vagrant/st2/st2common/st2common/content/bootstrap.py", line 338, in register_content
    register_actions()
  File "/home/vagrant/st2/st2common/st2common/content/bootstrap.py", line 219, in register_actions
    raise e
ValueError: Failed to register action "/opt/stackstorm/packs/testpack/actions/pythontest.meta.yaml" from pack "testpack": 'ascii' codec can't encode character u'\u2021' in position 10: ordinal not in range(128)
```

Should make sure this works for all resources, actions, rules, etc.

**Comment by Mierdin** [comment]
@bigmstone suggested that the exception was being obfuscated so I went down the rabbit hole and this was the most detail I could get:

```
Traceback (most recent call last):
  File "./st2common/bin/st2-register-content", line 22, in <module>
    sys.exit(content_loader.main(sys.argv[1:]))
  File "/home/vagrant/st2/st2common/st2common/content/bootstrap.py", line 388, in main
    register_content()
  File "/home/vagrant/st2/st2common/st2common/content/bootstrap.py", line 338, in register_content
    register_actions()
  File "/home/vagrant/st2/st2common/st2common/content/bootstrap.py", line 213, in register_actions
    fail_on_failure=fail_on_failure)
  File "/home/vagrant/st2/st2common/st2common/bootstrap/actionsregistrar.py", line 209, in register_actions
    result = registrar.register_from_packs(base_dirs=packs_base_paths)
  File "/home/vagrant/st2/st2common/st2common/bootstrap/actionsregistrar.py", line 65, in register_from_packs
    count = self._register_actions_from_pack(pack=pack, actions=actions)
  File "/home/vagrant/st2/st2common/st2common/bootstrap/actionsregistrar.py", line 180, in _register_actions_from_pack
    self._register_action(pack, action)
  File "/home/vagrant/st2/st2common/st2common/bootstrap/actionsregistrar.py", line 155, in _register_action
    action_ref = ResourceReference.to_string_reference(pack=pack, name=str(content['name']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2021' in position 10: ordinal not in range(128)
```

For some reason I am not able to figure out what in `ResourceReference.to_string_reference` is raising the exception. It seems to return just fine - but obviously it's part of the above stack trace so something else is afoot. Going to work on other things for now - thought this might save someone some time.

**Comment by cognifloyd** [comment]
At a glance, I'd say `str(content['name'])` is the culprit, not `to_string_reference`. If `content['name']` has unicode in it, and you try to cast it as a byte string (ie using `str()` is often an issue when dealing with unicode), it will try to convert it using ascii, but unicode != ascii. So, you'd need to either use a helper function that specifies the encoding (something like [to_bytes here](https://github.com/ansible/ansible/blob/fc5d71de0d/lib/ansible/module_utils/_text.py#L52-L166)) or, if `content['name']` will always be a unicode string, you could do `content['name'].encode('utf-8')`. In my code base, I searched for `str(` and replaced almost every occurance with a helper function that makes sure things are unicode or bytes, depending on where I am in the [unicode sandwhich](https://nedbatchelder.com/text/unipain/unipain.html#35).

I really like ansible's `to_bytes` (to a native python2 `str` which is `bytes` in 3), `to_text` (to python2's `unicode` which is 3's native `str`), and `to_native` (`bytes` in 2, `unicode` in 3) functions and use them quite a bit. [That file](https://github.com/ansible/ansible/blob/fc5d71de0d/lib/ansible/module_utils/_text.py) is BSD licensed, so there shouldn't be an issue in including it in ST2. It would probably fit nicely with the python3 work that's going on in addition to handling unicode more uniformly.
