### ISSUE TITLE
St2 Mistral unicode Error

### ISSUE THREAD

**Issue by walterVeiga** [StackStorm/st2#3958]
Hello, 
I'm not being able to use unicode in the stackstorm workflow.
(e.g. from workflow test="<% $.testing %>" my workflow doesn't work if testing is equal "não".)

The following errors are shown in the mistral log (mistral-server.log).
Any prevision about when stackstorm will support unicode ? Thanks.

2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server [req-68e0a0c1-2f6f-4d27-8a68-d5a5b993fc3a - - - - -] Exception during message handling: UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-6: ordinal not in range(128)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 157, in _process_incoming
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 213, in dispatch
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 183, in _do_dispatch
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/engine_server.py", line 154, in on_action_complete
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     return self.engine.on_action_complete(action_ex_id, result, wf_action)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/db/utils.py", line 75, in decorate
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     return _with_auth_context(auth_ctx, func, *args, **kw)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/tenacity/__init__.py", line 173, in wrapped_f
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     return self.call(f, *args, **kw)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/tenacity/__init__.py", line 244, in call
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     start_time=start_time)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/tenacity/__init__.py", line 205, in iter
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     return fut.result()
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/concurrent/futures/_base.py", line 422, in result
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     return self.__get_result()
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/tenacity/__init__.py", line 247, in call
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     result = fn(*args, **kwargs)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/db/utils.py", line 48, in _with_auth_context
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     return func(*args, **kw)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/action_queue.py", line 92, in decorate
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     res = func(*args, **kw)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py", line 157, in wrapper
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     result = f(*args, **kwargs)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/default_engine.py", line 119, in on_action_complete
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     action_handler.on_action_complete(action_ex, result)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py", line 157, in wrapper
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     result = f(*args, **kwargs)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/action_handler.py", line 54, in on_action_complete
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     task_handler.schedule_on_action_complete(action_ex)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/task_handler.py", line 437, in schedule_on_action_complete
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     _on_action_complete(action_ex)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py", line 157, in wrapper
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     result = f(*args, **kwargs)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/task_handler.py", line 110, in _on_action_complete
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     task.on_action_complete(action_ex)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py", line 157, in wrapper
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     result = f(*args, **kwargs)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/tasks.py", line 306, in on_action_complete
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     self.complete(state, state_info)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py", line 157, in wrapper
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     result = f(*args, **kwargs)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/tasks.py", line 200, in complete
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     dispatcher.dispatch_workflow_commands(self.wf_ex, cmds)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py", line 157, in wrapper
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     result = f(*args, **kwargs)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/dispatcher.py", line 94, in dispatch_workflow_commands
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     task_handler.run_task(cmd)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py", line 157, in wrapper
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     result = f(*args, **kwargs)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/task_handler.py", line 63, in run_task
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     task.run()
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py", line 157, in wrapper
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     result = f(*args, **kwargs)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/tasks.py", line 315, in run
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     self._run_new()
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py", line 157, in wrapper
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     result = f(*args, **kwargs)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/tasks.py", line 341, in _run_new
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     self._schedule_actions()
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/tasks.py", line 399, in _schedule_actions
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     input_dict = self._get_action_input()
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/osprofiler/profiler.py", line 157, in wrapper
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     result = f(*args, **kwargs)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/tasks.py", line 428, in _get_action_input
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     input_dict = self._evaluate_expression(self.task_spec.get_input(), ctx)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/engine/tasks.py", line 452, in _evaluate_expression
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     ctx_view
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/expressions/__init__.py", line 100, in evaluate_recursively
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     data[key] = _evaluate_item(data[key], context)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/expressions/__init__.py", line 89, in _evaluate_item
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     return evaluate_recursively(item, context)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/expressions/__init__.py", line 100, in evaluate_recursively
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     data[key] = _evaluate_item(data[key], context)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/expressions/__init__.py", line 79, in _evaluate_item
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     return evaluate(item, context)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/expressions/__init__.py", line 71, in evaluate
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     return evaluator.evaluate(expression, context)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server   File "/opt/stackstorm/mistral/lib/python2.7/site-packages/mistral/expressions/yaql_expression.py", line 104, in evaluate
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server     result = result.replace(expr, str(evaluated))
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-6: ordinal not in range(128)
2018-01-23 14:15:57.554 12160 ERROR oslo_messaging.rpc.server

**Comment by wyjuly** [comment]
I saw the same error before and made below change. Now it works.

vi /opt/stackstorm/mistral/lib/python2.7/site-packages/sitecustomize.py

```
# encoding=utf8
import sys
reload(sys)
sys.setdefaultencoding('utf8')
```

**Comment by lemeur** [comment]
@wyjuly,
I have the same issue, I tried to add the sitecustomize.py file as described, but it is never used.
How do you make sure it is loaded by mistral ?
Basically it is never compiled into a byte-code ".pyc" file.

**Comment by LindsayHill** [comment]
Did you restart the Mistral services?

**Comment by lemeur** [comment]
Yes, I even rebooted the OS.
# ls -al /opt/stackstorm/mistral/lib/python2.7/site-packages/sitecustomize.py*
-rw-r--r-- 1 root root 70 Jun  2 18:07 /opt/stackstorm/mistral/lib/python2.7/site-packages/sitecustomize.py

# cat /opt/stackstorm/mistral/lib/python2.7/site-packages/sitecustomize.py
# encoding=utf8
import sys
reload(sys)
sys.setdefaultencoding('utf8')
