### ISSUE TITLE
`st2 key get` for non-existent key has excessive ERROR logs

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2#3961]
If I query for a non-existent key in the datastore, `st2api.log` logs are unnecessarily verbose.

e.g. if I run `st2 key get foobar` (where that key does not exist), the user experience is OK:

```shell
ubuntu@st2vagrant:~$ st2 key get foobar
Key Value Pair "foobar" is not found.

ubuntu@st2vagrant:~$
```

But I see this in `/var/log/st2/st2api.log`:

```shell
2018-01-24 03:26:05,200 140238317697936 ERROR router [-] Failed to call controller function "get_one" for operation "st2api.controllers.v1.keyvalue:key_value_pair_controller.get_one": KeyValuePair with name: foobar and scope: st2kv.system not found in db.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/router.py", line 450, in __call__
    resp = func(**kw)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/controllers/v1/keyvalue.py", line 102, in get_one
    from_model_kwargs=from_model_kwargs
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/controllers/resource.py", line 318, in _get_one_by_scope_and_name
    raise StackStormDBObjectNotFoundError(msg)
StackStormDBObjectNotFoundError: KeyValuePair with name: foobar and scope: st2kv.system not found in db.
2018-01-24 03:26:05,203 140238317697936 INFO logging [-] b858d708-9712-4eb0-a4d8-0d9524856dd6 - 404 96 12.065ms (content_length=96,request_id='b858d708-9712-4eb0-a4d8-0d9524856dd6',runtime=12.065,remote_addr='127.0.0.1',status=404,method='GET',path='/v1/keys/foobar')
```

This seems rather excessive. Perhaps just a WARN log?

**Comment by LindsayHill** [comment]
It's still relevant - we still produce excessively noisy logs

**Comment by winem** [comment]
This is no longer an issue with st2 3.5.0

Now the logs look like this: 
```
2021-09-11 20:27:12,473 139653755012368 INFO logging [-] 48668613-71d1-46cd-a95b-8c393351f477 - GET /v1/keys/foobar with query={'decrypt': ['false'], 'scope': ['system']} (method='GET',path='/v1/keys/foobar',remote_addr='127.0.0.1',query={'decrypt': ['false'], 'scope': ['system']},request_id='48668613-71d1-46cd-a95b-8c393351f477')
2021-09-11 20:27:12,480 139653755012368 WARNING router [-] Failed to call controller function "get_one" for operation "st2api.controllers.v1.keyvalue:key_value_pair_controller.get_one": The key "foobar" does not exist in the StackStorm datastore.
2021-09-11 20:27:12,481 139653755012368 INFO logging [-] 48668613-71d1-46cd-a95b-8c393351f477 - 404 80 7.628ms (method='GET',path='/v1/keys/foobar',remote_addr='127.0.0.1',status=404,runtime=7.628,content_length=80,request_id='48668613-71d1-46cd-a95b-8c393351f477')
```

So the stacktrace is gone and the remaining log lines should be ok. I'll close this issue.
