### ISSUE TITLE
Tests of stackstorm-openstack failed.

### ISSUE THREAD

**Issue by apolloliu** [StackStorm/st2#3965]
https://circleci.com/gh/StackStorm-Exchange/stackstorm-openstack/58?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link#

Should oslo_config be added into the requirement of st2common?

**Comment by LindsayHill** [comment]
oslo.config is already in ST2 requirements. It looks like something else was broken upstream when that test ran:
```text
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 324, in read
    flush_decoder = True
  File "/opt/circleci/python/2.7.11/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ubuntu/stackstorm-openstack/virtualenv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 250, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
ProtocolError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
```

Re-running the tests and things look OK
