### ISSUE TITLE
st2api have no module __version__

### ISSUE THREAD

**Issue by apolloliu** [StackStorm/st2#3978]
```
root@ubuntu:/opt/stack/github/st2/st2api# pip install -e .
Obtaining file:///opt/stack/github/st2/st2api
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/stack/github/st2/st2api/setup.py", line 23, in <module>
        from st2api import __version__
    ImportError: cannot import name __version__
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /opt/stack/github/st2/st2api/
```
So propose #3979 to fix it.

**Comment by apolloliu** [comment]
No big deal.
