### ISSUE TITLE
Better logging around DB Successful and Unsuccessful Connections

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2#3990]
When ST2 processes start they make a connection to MongoDB.

We log that this connection is being attempted https://github.com/StackStorm/st2/blob/master/st2common/st2common/models/db/__init__.py#L104

This looks like this in the logs:
```
2018-02-06 16:37:02,232 140623438244432 INFO __init__ [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "None".
```

But we do *not* log if this connection was successful, nor do we properly log connection errors. This can be confusing for users that are debugging startup issues. For example, if RabbitMQ is not running, this is what is seen in the st2api logs:

```
2018-02-06 17:34:32,905 140082567223888 INFO __init__ [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "None".
2018-02-06 17:34:33,129 140082567223888 ERROR connection_retry_wrapper [-] Connection or channel error identified: [Errno 111] ECONNREFUSED.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/transport/connection_retry_wrapper.py", line 115, in run
    channel = connection.channel()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kombu/connection.py", line 266, in channel
    chan = self.transport.create_channel(self.connection)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/amqp/connection.py", line 282, in connect
    self.transport.connect()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/amqp/transport.py", line 109, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/amqp/transport.py", line 150, in _connect
    self.sock.connect(sa)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 256, in connect
    socket_checkerr(fd)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 46, in socket_checkerr
    raise socket.error(err, errno.errorcode[err])
error: [Errno 111] ECONNREFUSED
```

From a casual glance, an admin can see the connection to `:27017` (implying Mongo), followed by `ECONNREFUSED`. It takes an eagle eye to realize that the second error is coming from AMQP-related code, so we need to check RabbitMQ.

It would be helpful if our logs looked more like this

```
2018-02-06 17:34:32,905 140082567223888 INFO __init__ [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "None".
2018-02-06 17:34:32,905 140082567223888 INFO __init__ [-] Successfully connected to database "st2" @ "127.0.0.1:27017" as user "None".
```

Related: If there are connection failures - e.g. MongoDB not running - then this is all we see in the st2api.log:
```
2018-02-06 17:53:06,135 140026482362960 INFO __init__ [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "None".
2018-02-06 17:53:36,603 140026482362960 INFO __init__ [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "None".
2018-02-06 17:54:07,039 140026482362960 INFO __init__ [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "None".
2018-02-06 17:54:37,536 140026482362960 INFO __init__ [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "None".
```

Some of the other logs have better error messages - e.g. st2notifier has this:

```
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/models/db/__init__.py", line 153, in db_ensure_indexes
    model_class.ensure_indexes()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/mongoengine/document.py", line 808, in ensure_indexes
    collection = cls._get_collection()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/mongoengine/document.py", line 206, in _get_collection
    cls.ensure_indexes()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/mongoengine/document.py", line 836, in ensure_indexes
    collection.create_index(fields, background=background, **opts)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/pymongo/collection.py", line 1571, in create_index
    self.__create_index(keys, kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/pymongo/collection.py", line 1459, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 868, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] ECONNREFUSED
```

But st2api.log doesn't, and it would be much more useful if we had an ERROR message for each of the processes when they are unable to connect to MongoDB.

(There is a separate issue here around better logging of RabbitMQ errors - I'll open a separate issue for that)

**Comment by armab** [comment]
@LindsayHill @blag @Kami Can be closed now via https://github.com/StackStorm/st2/pull/4141 and https://github.com/StackStorm/st2/pull/4167?

**Comment by blag** [comment]
Yep, this is fixed. The credit belongs to @Kami.
