### ISSUE TITLE
Special characters in passwords break st2auth config

### ISSUE THREAD

**Issue by kugelman** [StackStorm/st2#4029]
I'm using the open source ldap auth backend from github, and setting a complex bind_pw parameter (passed through backend_kwargs under the [auth] header in st2.conf) causes NoSuchOptError. In my case, bind_pw contained the sequence "$aop!"

```
Mar 07 13:45:23 ubuntu1604 systemd[1]: Started StackStorm service st2auth.
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]: [2018-03-07 13:45:23 +0000] [27946] [INFO] Starting gunicorn 19.7.1
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]: [2018-03-07 13:45:23 +0000] [27946] [INFO] Listening at: http://127.0.0.1:9100 (27946)
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]: [2018-03-07 13:45:23 +0000] [27946] [INFO] Using worker: eventlet
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]: [2018-03-07 13:45:23 +0000] [27954] [INFO] Booting worker with pid: 27954
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]: [2018-03-07 13:45:23 +0000] [27954] [ERROR] Exception in worker process
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]: Traceback (most recent call last):
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     worker.init_process()
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/geventlet
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     super(EventletWorker, self).init_process()
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/base.py",
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     self.load_wsgi()
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/workers/base.py",
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     self.wsgi = self.app.wsgi()
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/app/base.py", lin
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     self.callable = self.load()
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", 
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     return self.load_wsgiapp()
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", 
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     return util.import_app(self.app_uri)
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/gunicorn/util.py", line 35
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     __import__(module)
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2auth/wsgi.py", line 25,
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     application = app.setup_app(config)
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2auth/app.py", line 53, 
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     config_args=config.get('config_args', None))
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     config.parse_args(config_args)
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2auth/config.py", line 2
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     cfg.CONF(args=args, version=VERSION_STRING)
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     else sys.argv[1:])
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     return self._parse_config_files()
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     self._validate_cli_options(namespace)
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     value = self._substitute(value, group=group, namespace=namespace)
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     self.StrSubWrapper(self, group=group, namespace=namespace))
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/usr/lib/python2.7/string.py", line 207, in safe_substitute
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     return self.pattern.sub(convert, self.template)
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/usr/lib/python2.7/string.py", line 198, in convert
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     return '%s' % (mapping[named],)
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     value = self.conf._get(key, namespace=self.namespace)
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     value = self._do_get(name, group, namespace)
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     info = self._get_opt_info(name, group)
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]:     raise NoSuchOptError(opt_name, group)
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]: NoSuchOptError: no such option: aop
Mar 07 13:45:23 ubuntu1604 gunicorn[27946]: [2018-03-07 13:45:23 +0000] [27954] [INFO] Worker exiting (pid: 27954)
Mar 07 13:45:24 ubuntu1604 gunicorn[27946]: [2018-03-07 13:45:24 +0000] [27946] [INFO] Shutting down: Master
Mar 07 13:45:24 ubuntu1604 gunicorn[27946]: [2018-03-07 13:45:24 +0000] [27946] [INFO] Reason: Worker failed to boot.
Mar 07 13:45:24 ubuntu1604 systemd[1]: st2auth.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Mar 07 13:45:24 ubuntu1604 systemd[1]: st2auth.service: Unit entered failed state.
Mar 07 13:45:24 ubuntu1604 systemd[1]: st2auth.service: Failed with result 'exit-code'.
```

**Comment by nmaludy** [comment]
StackStorm uses the Oslo config library. In this library they allow variable substitution by referencing variables with a $, example `$myoption`.

According to the Oslo config documentation you can escape $ with a double $$. It even had an example that references LDAP passwords.

https://docs.openstack.org/oslo.config/latest/configuration/format.html#substitution

**Comment by bigmstone** [comment]
@nmaludy good find. @kugelman can you confirm this resolves your issue?

**Comment by kugelman** [comment]
Ahhh, that works. Thanks @nmaludy !
