### ISSUE TITLE
st2kv inside the rules criteria is not working

### ISSUE THREAD

**Issue by arulvelu21** [StackStorm/st2#4043]
Hi ,

I am trying to retreive  datastore value inside the criteria of the rules as like below. 

Yaml:

name: ticket-to-stackstorm-rule
pack: avmarmusecase
enabled: true
trigger:
  type: "default.workflowinitiate"
criteria:
  trigger.category:
    pattern: "{{st2kv.system.db}}"
    type: "equals"
  trigger.item:
    pattern: "Policy_Update"
    type: "equals"

Error Log:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/rules/filter.py", line 118, in _check_criterion
    criteria_context=payload_lookup.context
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/rules/filter.py", line 189, in _render_criteria_pattern
    context=criteria_context
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/util/templating.py", line 86, in render_template_with_system_context
    rendered = render_template(value=value, context=context)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/util/templating.py", line 53, in render_template
    rendered = template.render(context)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/jinja/filters/complex_type.py", line 24, in to_complex
    result = json.dumps(value)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")

Please help on this issue.

Thanks
Arul

**Comment by Kami** [comment]
This might be related to change in #3273 and #3018 since it looks like it fails on `to_complex` filter rendering.

@bigmstone any ideas?

**Comment by bigmstone** [comment]
Hmm. Would like to know the value of `{{st2kv.system.db}}`, will need to look a bit more into how a scenario like this would be handled in the code.

This exception block is clearly not robust enough: https://github.com/StackStorm/st2/blob/master/st2reactor/st2reactor/rules/filter.py#L187

And the error message here is abysmal. When I get a few cycles I'll look into it. If someone else can get to it before me, go for it.

**Comment by arulvelu21** [comment]
@armab  @bigmstone  Hi, To add the point to error log message.

**ERROR filter [-] Failed to render pattern value "{{st2kv.system.db}}" for key "trigger.category"** 

{{st2kv.system.db}} is a string with value  as "DATABASE" which is stored in st2kv.system.db.

**Comment by dsabsay** [comment]
For whatever it's worth, I get a similar error in v2.8.1:

```
+---------------------+--------------------------------------------------------------+
| Property            | Value                                                        |
+---------------------+--------------------------------------------------------------+
| id                  | 5ddc5b1c51ca270037b21af9                                     |
| rule.ref            | tutorial.iss_over_new_country                                |
| trigger_instance_id | 5ddc5b1c51ca270037b21af7                                     |
| execution_id        |                                                              |
| failure_reason      | Failed to match rule "tutorial.iss_over_new_country" against |
|                     | trigger instance "5ddc5b1c51ca270037b21af7": Failed to       |
|                     | render pattern value "{{                                     |
|                     | st2kv.system.tutorial_iss_nearest_country }}" for key        |
|                     | "trigger.country_code":                                      |
|                     | <st2common.services.keyvalues.KeyValueLookup object at       |
|                     | 0x7fbc68f65cd0> is not JSON serializable                     |
| enforced_at         | 2019-11-25T22:52:12.148191Z                                  |
+---------------------+--------------------------------------------------------------+
```

The rule looks like this:
```
---
name: iss_over_new_country
description: Rule that fires when the ISS passes over a country border.
enabled: true
trigger:
  type: tutorial.iss_location
criteria:
  trigger.country_code:
    type: nequals
    pattern: "{{ st2kv.system.tutorial_iss_nearest_country }}"
action:
  ref: tutorial.hello_world
  parameters:
    name: "{{ trigger.nearest_country }}"
```
