### ISSUE TITLE
render_live_params failed when run send email action from workflow

### ISSUE THREAD

**Issue by longfei-zhang** [StackStorm/st2#4084]
I have installed email pack and direct run email.send_email action works fine.
I try to run this action in a mistral workflow but failed.

here are my metadata:

**mistral-check-disk-send-mail.yaml  under /opt/stackstorm/packs/email/actions**
---
description: Run disk_usage_root.sh script and output the result then send email.
enabled: true
runner_type: mistral-v2
entry_point: workflows/mistral-check-disk-send-mail.yaml
name: mistral-check-disk-send-mail
pack: email
parameters:
  account:
    type: string
    default: stackstorm
  email_from:
    type: string
    default: test@abc.cn
  email_to:
    required: true
    type: string
  subject:
    required: true
    type: string
  message:
    required: true
    type: string

and here are the definition
**mistral-check-disk-send-mail.yaml under  /opt/stackstorm/packs/email/actions/workflows**
version: '2.0'
email.mistral-check-disk-send-mail:
    description: Run disk_usage_root.sh script and output the result then send email.
    type: direct
    input:
        - account
        - email_from
        - email_to
        - subject
        - message
    output:
        stdout: <% $.stdout %>
    tasks:
        task1:
            action: email.send_email account=<% $.account %> email_from=<% $.email_from %> email_to=<% $.email_to%> message=<% $.message %> subject=<% $.subject %>

**and here are the run cmd**
st2 run email.mistral-check-disk-send-mail  email_to="longfei.zhang@easystack.cn" subject="test workflow" message="test"

**I can see the error in console output:**
  reason: Internal Server Error
  status: 500
  url: http://st2api:9101/v1/actionexecutions

**and also some error log in the st2api**
2018-04-17 18:45:35,009 INFO [-] a0aad215-7b2e-4911-bc4a-599c270fc579 - POST /v1/actionexecutions with query={} (remote_addr='10.233.68.225',method='POST',request_id='a0aad215-7b2e-4911-bc4a-599c270fc579',query={},path='/v1/actionexecutions')
2018-04-17 18:45:35,012 AUDIT [-] Token with id "5ad5d04dabcf04000106c0ca" is validated.
2018-04-17 18:45:35,074 ERROR [-] Unable to execute action. Unexpected error encountered.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/actionexecutions.py", line 129, in _handle_schedule_execution
    pack=action_db.pack)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/actionexecutions.py", line 184, in _schedule_execution
    liveaction_db.context)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/param.py", line 289, in render_live_params
    live_params = _cast_params_from(params, context, [action_parameters, runner_parameters])
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/param.py", line 231, in _cast_params_from
    result[name] = _cast(context[name], param_schema)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/param.py", line 74, in _cast
    return cast(v)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/casts.py", line 38, in _cast_object
    return ast.literal_eval(x)
  File "/usr/lib64/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib64/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    longfei.zhang@easystack.cn
                                                 ^
SyntaxError: invalid syntax
2018-04-17 18:45:35,075 ERROR [-] Failed to call controller function "post" for operation "st2api.controllers.v1.actionexecutions:action_executions_controller.post": invalid syntax (<unknown>, line 1)
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/router.py", line 450, in __call__
    resp = func(**kw)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/actionexecutions.py", line 583, in post
    show_secrets=show_secrets)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/actionexecutions.py", line 142, in _handle_schedule_execution
    abort(http_client.INTERNAL_SERVER_ERROR, str(e))
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/router.py", line 53, in abort
    raise exc.status_map[status_code](message)
HTTPInternalServerError: invalid syntax (<unknown>, line 1)
2018-04-17 18:45:35,075 ERROR [-] API call failed: invalid syntax (<unknown>, line 1)
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/middleware/error_handling.py", line 46, in __call__
    return self.app(environ, start_response)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/middleware/streaming.py", line 47, in __call__
    return self.app(environ, start_response)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/router.py", line 499, in as_wsgi
    resp = self(req)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/router.py", line 454, in __call__
    raise e
HTTPInternalServerError: invalid syntax (<unknown>, line 1) (_exception_data={'comment': 'invalid syntax (<unknown>, line 1)', '_headers': None, 'conditional_response': False, 'detail': 'invalid syntax (<unknown>, line 1)', '_app_iter': [''], '_status': '500 Internal Server Error', '_headerlist': [('Content-Type', 'text/html; charset=UTF-8'), ('Content-Length', '0')]},_exception_class='HTTPInternalServerError',_exception_message='invalid syntax (<unknown>, line 1)')

**I can reproduce this issue and my current st2 version is st2 2.6.0**

**Comment by longfei-zhang** [comment]
longfei.zhang@easystack.cn
                           ^
SyntaxError: invalid syntax

**Comment by longfei-zhang** [comment]
the ^ is under @ character

**Comment by nmaludy** [comment]
The `email.send_email` action takes a parameter `email_to` of type `array`: https://github.com/StackStorm-Exchange/stackstorm-email/blob/master/actions/send_email.yaml#L12-L15

You are passing in a string.

Your task definition should be something like:

```
task1:
  action: email.send_email
  input:
    account: <% $.account %>
    email_from: <% $.email_from %>
    email_to:
      - <% $.email_to%>
    message: <% $.message %>
    subject: <% $.subject %>
```

I agree the error message could be better here. Maybe something like `Error, unable to convert input 'abc@gmail.com' to type 'array'` would be better

**Comment by longfei-zhang** [comment]
Changed parameter 'email_to' to type array solved my issue.
Thanks @nmaludy

**Comment by longfei-zhang** [comment]
Can I closed this issue?
