### ISSUE TITLE
python3 error with a non-python3 pack

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/st2#4090]
client and server are running on the same machine.

Error message:
```
$ st2 pack install https://github.com/cognifloyd/stackstorm-ansible=directives-and-json-command
ERROR: 400 Client Error: Bad Request
MESSAGE: Additional properties are not allowed ('python3' was unexpected) for url: http://127.0.0.1:9101/v1/packs/install
```

client version
```
$ st2 --version
st2 2.7.0, on Python 2.7
```

server version
```
$ yum info st2
Loaded plugins: fastestmirror, langpacks
Determining fastest mirrors
 * base: mirror.atlantic.net
 * epel: mirror.oss.ou.edu
 * extras: centos.mirror.lstn.net
 * nux-dextop: mirror.li.nux.ro
 * updates: mirror.teklinks.com
StackStorm_stable                                                                                                                                                           92/92
Installed Packages
Name        : st2
Arch        : x86_64
Version     : 2.7.0
Release     : 4
Size        : 125 M
Repo        : installed
From repo   : StackStorm_stable
Summary     : StackStorm all components bundle
URL         : https://github.com/StackStorm/st2
License     : Apache
Description :   Package is full standalone stackstorm installation including
            :   all components
```

problematic command with --debug
```
$ st2 --debug pack install https://github.com/cognifloyd/stackstorm-ansible\=directives-and-json-command
2018-04-18 15:03:24,607  DEBUG - Using cached token from file "/home/jacob/.st2/token-jacob"
# -------- begin 29629136 request ----------
curl -X POST -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.14.2' -H  'content-type: application/json' -H  'X-Auth-Token: c678eec7f32f4b70b725f4cb6db6d8ae' -H  'Content-Length: 88' --data-binary '{"pack": "https://github.com/cognifloyd/stackstorm-ansible=directives-and-json-command"}' http://127.0.0.1:9101/v1/packs/index/search
# -------- begin 29629136 response ----------
[]
# -------- end 29629136 response ------------

# -------- begin 29629136 request ----------
curl -X POST -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.14.2' -H  'content-type: application/json' -H  'X-Auth-Token: c678eec7f32f4b70b725f4cb6db6d8ae' -H  'Content-Length: 125' --data-binary '{"force": false, "python3": false, "packs": ["https://github.com/cognifloyd/stackstorm-ansible=directives-and-json-command"]}' http://127.0.0.1:9101/v1/packs/install
# -------- begin 29629136 response ----------
{
    "faultstring": "Additional properties are not allowed ('python3' was unexpected)"
}
# -------- end 29629136 response ------------

ERROR: 400 Client Error: Bad Request
MESSAGE: Additional properties are not allowed ('python3' was unexpected) for url: http://127.0.0.1:9101/v1/packs/install

CLI settings:
----------------
Config file path: /home/jacob/.st2/config
Client settings:
----------------
ST2_BASE_URL: http://127.0.0.1
ST2_AUTH_URL: http://127.0.0.1:9100
ST2_API_URL: http://127.0.0.1:9101/v1
ST2_STREAM_URL: http://127.0.0.1:9102/v1
ST2_AUTH_TOKEN: <token>

Proxy settings:
---------------
HTTP_PROXY: 
HTTPS_PROXY: 

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/shell.py", line 343, in run
    func(args)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/commands/resource.py", line 47, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/commands/pack.py", line 248, in run_and_print
    instance = super(PackInstallCommand, self).run_and_print(args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/commands/resource.py", line 47, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/commands/pack.py", line 107, in run_and_print
    instance = self.run(args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/commands/pack.py", line 195, in run
    return self.manager.install(args.packs, force=args.force, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 40, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 488, in install
    self.handle_error(response)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 166, in handle_error
    response.raise_for_status()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 400 Client Error: Bad Request
MESSAGE: Additional properties are not allowed ('python3' was unexpected) for url: http://127.0.0.1:9101/v1/packs/install
```

extract of st2api.log
```
2018-04-18 15:03:25,077 104103760 ERROR actionexecutions [-] Unable to execute action. Parameter validation failed.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/actionexecutions.py", line 127, in _handle_schedule_execution
    pack=action_db.pack)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/actionexecutions.py", line 200, in _schedule_execution
    liveaction_db, actionexecution_db = action_service.create_request(liveaction_db)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/services/action.py", line 89, in create_request
    allow_default_none=True)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/schema/__init__.py", line 294, in validate
    jsonschema.validate(instance=instance, schema=schema, cls=cls, *args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
ValidationError: Additional properties are not allowed ('python3' was unexpected)

Failed validating 'additionalProperties' in schema:
    {'additionalProperties': False,
     'description': u'Installs or upgrades a pack into local content repository, either by git URL or a short name matching an index entry. Will download pack, load the actions, sensors and rules from the pack. Note that install requires reboot of some st2 services.',
     'properties': {u'display_published': {u'default': True,
                                           u'description': u'Intermediate published variables will be stored and displayed.',
                                           u'type': u'boolean'},
                    u'env': {u'description': u'Optional environment variables.',
                             u'required': False,
                             u'type': [u'object', 'null']},
                    u'force': {u'default': False,
                               u'description': u'Set to True to force install the pack and skip StackStorm version compatibility check and also delete and ignore lock file if one exists.',
                               u'required': False,
                               u'type': u'boolean'},
                    u'packs': {u'description': u'Name of the pack in Exchange or a git repo URL.',
                               u'items': {u'type': u'string'},
                               u'required': True,
                               u'type': u'array'},
                    u'register': {u'default': u'all',
                                  u'description': u'Possible options are all, sensors, actions, rules, aliases, runners, triggers, rule_types, policiy_types, policies, configs.',
                                  u'type': u'string'},
                    u'skip_notify': {u'default': [],
                                     u'description': u'List of tasks to skip notifications for.',
                                     u'type': u'array'}},
     'title': u'install',
     'type': 'object'}

On instance:
    {u'display_published': True,
     u'force': False,
     'packs': [u'https://github.com/cognifloyd/stackstorm-ansible=directives-and-json-command'],
     'python3': False,
     u'register': u'all',
     u'skip_notify': []}
2018-04-18 15:03:25,079 104103760 ERROR router [-] Failed to call controller function "post" for operation "st2api.controllers.v1.packs:packs_controller.install.post": Additional properties are not allowed ('python3' was unexpected)
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/router.py", line 470, in __call__
    resp = func(**kw)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/packs.py", line 115, in post
    requester_user=requester_user)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/v1/actionexecutions.py", line 133, in _handle_schedule_execution
    abort(http_client.BAD_REQUEST, re.sub("u'([^']*)'", r"'\1'", e.message))
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/router.py", line 55, in abort
    raise exc.status_map[status_code](message)
HTTPBadRequest: Additional properties are not allowed ('python3' was unexpected)
2018-04-18 15:03:25,081 104103760 INFO logging [-] e29126da-dde2-45b9-8bbd-f7f54ef7cf6f - 400 89 72.231ms (content_length=89,request_id='e29126da-dde2-45b9-8bbd-f7f54ef7cf6f',runtime=72.231,remote_addr='127.0.0.1',status=400,method='POST',path='/v1/packs/install')
```

**Comment by LindsayHill** [comment]
For reference for others, running `sudo st2ctl reload --register-all` may be required. I had to do that for some one of my upgraded systems.

**Comment by devfaz** [comment]
getting the same err. 

`2018-12-07 07:40:11,631 139831636704624 ERROR actionexecutions [-] Unable to execute action. Parameter validation failed.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/controllers/v1/actionexecutions.py", line 135, in _handle_schedule_execution
    action_db=action_db)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/controllers/v1/actionexecutions.py", line 207, in _schedule_execution
    runnertype_db=runnertype_db)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/services/action.py", line 104, in create_request
    allow_default_none=True)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/util/schema/__init__.py", line 305, in validate
    jsonschema.validate(instance=instance, schema=schema, cls=cls, *args, **kwargs)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
ValidationError: Additional properties are not allowed (u'python3' was unexpected)

Failed validating 'additionalProperties' in schema:
    {'additionalProperties': False,
     'description': u'Installs or upgrades a pack into local content repository, either by git URL or a short name matching an index entry. Will download pack, load the actions, sensors and rules from the pack. Note that install requires reboot of some st2 services.',
     'properties': {u'display_published': {u'default': True,
                                           u'description': u'Intermediate published variables will be stored and displayed.',
                                           u'type': u'boolean'},
                    u'env': {u'description': u'Optional environment variables.',
                             u'required': False,
                             u'type': [u'object', 'null']},
                    u'force': {u'default': False,
                               u'description': u'Set to True to force install the pack and skip StackStorm version compatibility check and also delete and ignore lock file if one exists.',
                               u'required': False,
                               u'type': u'boolean'},
                    u'packs': {u'description': u'Name of the pack in Exchange or a git repo URL.',
                               u'items': {u'type': u'string'},
                               u'required': True,
                               u'type': u'array'},
                    u'register': {u'default': u'all',
                                  u'description': u'Possible options are all, sensors, actions, rules, aliases, runners, triggers, rule_types, policiy_types, policies, configs.',
                                  u'type': u'string'},
                    u'skip_notify': {u'default': [],
                                     u'description': u'List of tasks to skip notifications for.',
                                     u'type': u'array'}},
     'title': u'install',
     'type': 'object'}

On instance:
    {u'display_published': True,
     u'force': False,
     u'packs': [u'https://github.com/StackStorm-Exchange/stackstorm-st2.git'],
     u'python3': False,
     u'register': u'all',
     u'skip_notify': []}
2018-12-07 07:40:11,634 139831636704624 ERROR router [-] Failed to call controller function "post" for operation "st2api.controllers.v1.packs:packs_controller.install.post": Additional properties are not allowed ('python3' was unexpected)
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/router.py", line 516, in __call__
    resp = func(**kw)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/controllers/v1/packs.py", line 115, in post
    requester_user=requester_user)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2api/controllers/v1/actionexecutions.py", line 141, in _handle_schedule_execution
    abort(http_client.BAD_REQUEST, re.sub("u'([^']*)'", r"'\1'", e.message))
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/router.py", line 80, in abort
    raise exc.status_map[status_code](message)
HTTPBadRequest: Additional properties are not allowed ('python3' was unexpected)
2018-12-07 07:40:11,635 139831636704624 INFO logging [-] 29c85fa7-06d1-4133-830d-a452bc15c23d - 400 89 27.971ms (content_length=89,request_id='29c85fa7-06d1-4133-830d-a452bc15c23d',runtime=27.971,remote_addr='127.0.0.1',status=400,method='POST',path='/v1/packs/install')


st2 --version
st2 2.9.1, on Python 2.7.6
`

maybe it is related to enabling parameter validation by default (as mentioned in changelog) ?

**Comment by devfaz** [comment]
@armab maybe you can remove the "invalid" tag?

**Comment by devfaz** [comment]
Ok, found a solution and hopefully it helps someone else:

I'm using st2-docker and it looks like upgrading didnt update the /opt/stackstorm/packs/... directory which is located on a persistent volume. I just removed the volume and docker-compose created a new one with up-to-date (default) packs.

Now Im able to install further packs.
