### ISSUE TITLE
AWS Pack install failing in st2 2.7.1

### ISSUE THREAD

**Issue by harishgopalan** [StackStorm/st2#4097]
Team,

I'm not able to install any pack in st2 2.7.1

```
id: 5ae874f91dcea036e8b3fee5
action.ref: packs.install
parameters:
  packs:
  - file:////home/example/aws
  python3: false
status: failed
result_task: download pack
result:
  error: 'Failed running task "download pack".. Update failed (Unknown modifier: $pushAll)'
  traceback: "Traceback (most recent call last):
  File "/opt/stackstorm/runners/action_chain_runner/action_chain_runner/action_chain_runner.py", line 516, in _run_chain
    liveaction = self._run_action(liveaction)
  File "/opt/stackstorm/runners/action_chain_runner/action_chain_runner/action_chain_runner.py", line 734, in _run_action
    raise e
OperationError: Update failed (Unknown modifier: $pushAll)
"
error: Failed running task "download pack".. Update failed (Unknown modifier: $pushAll)
traceback: Traceback (most recent call last):
  File "/opt/stackstorm/runners/action_chain_runner/action_chain_runner/action_chain_runner.py", line 516, in _run_chain
    liveaction = self._run_action(liveaction)
  File "/opt/stackstorm/runners/action_chain_runner/action_chain_runner/action_chain_runner.py", line 734, in _run_action
    raise e
OperationError: Update failed (Unknown modifier: $pushAll)

failed_on: download pack
start_timestamp: Tue, 01 May 2018 07:08:57 PDT
end_timestamp: Tue, 01 May 2018 07:08:58 PDT
+--------------------------+-----------+---------------+----------------+------------------------------+
| id                       | status    | task          | action         | start_timestamp              |
+--------------------------+-----------+---------------+----------------+------------------------------+
| 5ae874fa1dcea0376989786f | requested | download pack | packs.download | Tue, 01 May 2018 07:08:58    |
|                          |           |               |                | PDT                          |
+--------------------------+-----------+---------------+----------------+------------------------------+
```
Could this be a bug ? I'm able to execute any other adhoc actions though.

Regards
Harish

**Comment by LindsayHill** [comment]
How are you installing that pack? It looks like you are not using the normal commands `st2 pack install aws`, but something else?

Are you doing it by running something like `git clone https://github.com/StackStorm-Exchange/stackstorm-aws /home/example/aws` first?

It looks like your problem is that you are running something like `st2 pack install file:////home/example/aws`

That is one `/` too many. The command should be `st2 pack install file:///home/example/aws`

**Comment by LindsayHill** [comment]
Also, **PLEASE** use Github markdown formatting when pasting large blobs of code, logs or command output. It's much easier to read.

**Comment by harishgopalan** [comment]
Hi Lindsay, 

I figured out the issue, i had a higher version of mongodb 3.6.4 causing this issue, i downgraded it to 3.4.14 and it works

Regards
Harish

**Comment by LindsayHill** [comment]
Thanks for the update. 

Not surprising, since I don’t think we’ve done any testing with Mongo 3.6.
