### ISSUE TITLE
The secret value in email config file seems not work

### ISSUE THREAD

**Issue by longfei-zhang** [StackStorm/st2#4121]
I use the following cmd to set a key in the datastore.
`$ st2 key set -e smtp_account.me.password "I'm Encrypted"`

and here are my email pack config /opt/stackstorm/configs/email.yaml

```
---
smtp_accounts:
  - name: name
    password: "{{ st2kv.system.smtp_account.me.password }}"
```

then run the email action but failed
```
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 278, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 171, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/email/actions/send_email.py", line 49, in run
    s.login(account_data['username'], account_data['password'])
  File "/usr/lib64/python2.7/smtplib.py", line 621, in login
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (460, 'ERR.LOGIN.PASSERR')
```

I added some log to see the password value in File "/opt/stackstorm/packs/email/actions/send_email.py", line 49.
It seems that we get
{{ st2kv.system.smtp_account.me.password }} as the password.

do i missed something?
FYI
If I run the send email action and put the {{ st2kv.system.smtp_account.me.password }} as the message
I can see the message's value is correct.

**Comment by LindsayHill** [comment]
From Slack - probably related to https://github.com/StackStorm/st2/blob/master/st2common/st2common/util/config_loader.py#L102-L138

> ...conditional for nested objects, but not nested lists
