### ISSUE TITLE
Password Decryption is not working in sensor

### ISSUE THREAD

**Issue by guptasakshi01** [StackStorm/st2#4150]
##### ISSUE TYPE
 - Other

##### STACKSTORM VERSION
2.7.2

##### OS 
Ubuntu

##### SUMMARY
I am using datastore to store the password of exchange in encrypted form instead of using config file.
But While decrypting password in sensor using following:-

`password = client.keys.get_by_name(name="password", decrypt=True).value`

I am getting following error:-
```
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 332, in _get_sensor_instance
    sensor_instance = sensor_class(**sensor_class_kwargs)
  File "/opt/stackstorm/packs/hivecenter_msexchange/sensors/monitor_mailbox.py", line 40, in __init__
    password = client.keys.get_by_name(name="password", decrypt=True).value
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 40, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 292, in get_by_name
    instances = self.query(name=name, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 40, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 279, in query
    instances, _ = self._query_details(**kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 272, in _query_details
    self.handle_error(response)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 166, in handle_error
    response.raise_for_status()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden
MESSAGE: Decrypt option requires administrator access for url: http://127.0.0.1:9101/v1/keys/?decrypt=True&name=password
```
##### EXPECTED RESULTS
Expecting decrypted password to be return back

Please help on this issue

**Comment by LindsayHill** [comment]
Are you using RBAC?

**Comment by LindsayHill** [comment]
Also, is your sensor code published anywhere?

**Comment by guptasakshi01** [comment]
Please find the link below for sensor code

https://github.com/guptasakshi01/St2/blob/master/monitor_mailbox.py

**Comment by LindsayHill** [comment]
I think you should be using this method to get that value: https://docs.stackstorm.com/sensors.html#get-value-name-local-true-decrypt-false

**Comment by guptasakshi01** [comment]
2018-05-29 02:00:52,497 ERROR [-] Exception retrieving value from datastore (name=msexchange.MonitorMailbox:password): 403 Client Error: Forbidden
MESSAGE: Decrypt option requires administrator access for url: http://127.0.0.1:9101/v1/keys/msexchange.MonitorMailbox:password?scope=system&decrypt=true
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/services/datastore.py", line 125, in get_value
    kvp = client.keys.get_by_id(id=name, params=params)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 40, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 204, in get_by_id
    self.handle_error(response)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2client/models/core.py", line 166, in handle_error
    response.raise_for_status()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden
**MESSAGE: Decrypt option requires administrator access for url: http://127.0.0.1:9101/v1/keys/msexchange.MonitorMailbox:password?scope=system&decrypt=true
2018-05-29 02:00:52,500 ERROR [-] Failed to instantiate "MonitorMailbox" sensor class**

**Comment by Kami** [comment]
Sensors use special `sensors_container` user when talking to the API and decrypting values and as such, if you want to be able to decrypt values inside sensors, `sensors_container` user needs administrator access / role (you grant it in the same way you grant RBAC roles to other users).

In that sense, sensors are different from actions, because actions which are executed via API use the user which triggered the execution via the API.

**Comment by guptasakshi01** [comment]
@Kami  Can you please tell where to find special sensor_container user ??

**Comment by Kami** [comment]
It's a system user created inside StackStorm code (there are a couple of other system users like `stanley` to which we automatically grant administrator role on installation since it's needed for other purposes). 

And you grant administrator privileges (role) to it in the same way you grant it to any other StackStorm user - https://docs.stackstorm.com/rbac.html#defining-user-role-assignments

**Comment by guptasakshi01** [comment]
@Kami  I am using st2admin to execute sensor,And st2admin has administrator privileges.
But still getting same error.

**Comment by Kami** [comment]
@guptasakshi01 Again, all the sensors use StackStorm (not system) user named `sensors_container` when talking to the API so that user needs admin permissions (and that user is not related to `st2admin`).

**Comment by guptasakshi01** [comment]
@LindsayHill  It worked via both ways Assigning Admin to sensor service and Disabling RBAC.
