### ISSUE TITLE
Multi-Entrypoint Workflow issue after 2.7.2 upgrade

### ISSUE THREAD

**Issue by tjsampson** [StackStorm/st2#4176]
##### SUMMARY

BUG: After upgrading from 2.6.0 to 2.7.2 we are now having issues with multi-entrypoint workflows. 

`st2 action execute ems.deploy_artifacts customers=ems environment=prod `

Also note, we currently have this same pack installed on an instance with 2.6.0 running, and there aren't any issues. We didn't notice this until the 2.7.2 upgrade.

##### ISSUE TYPE
Pick one below and delete the rest:
 - Bug Report

##### STACKSTORM VERSION
Paste the output of `st2 --version`: st2 2.7.2, on Python 2.7

##### OS / ENVIRONMENT / INSTALL METHOD
OS: Ubuntu:16.04
Install: curl -sSL https://stackstorm.com/packages/install.sh | bash -s -- --user=st2admin --password=somethingsupersecret

##### STEPS TO REPRODUCE
Upgrade from 2.6.0 to 2.7.2 and try and execute a workflow that has multiple entry points.

Action Definition: 
```yaml
---
name: deploy_artifacts
pack: ems
entry_point: workflows/deploy_artifacts.yml
runner_type: "mistral-v2"
description: Deploy, Notify, and Promote
enabled: true
parameters:
  skip_notify:
    default:
      - "deployment_plan"
      - "dryrun_deploy_summary"
      - "download_artifacts"
      - "deploy_customer"
      - "deploy_summary"
      - "promote_artifacts"
      - "deploy"
      
  customers:
    type: string
    description: comma separated list of customers you want to deploy too, if not specified, it will deploy to all customers in the env
    required: false
    default: ''

  snapshot:
    type: string
    description: snapshot that you want to deploy, this takes precedence over packages and will then ignore packages
    required: false
    default: ''

  artifacts:
    type: string
    description: comma separated list of artifacts you want to deploy, if not specified, it will deploy all artifacts configured for customers in env
    required: false
    default: ''

  environment:
    type: string
    description: the environment you want to deploy packages to
    required: true

  ignore_deployed:
    type: boolean
    description: set to true if you want to force a deploy regardless of what version(s) the customer already has deployed (defaults to false)
    required: false
    default: false

  dryrun:
    type: boolean
    description: set to true if you want to see what would be deployed
    required: false
    default: false

  machine:
    type: string
    description: set to limit the machines you want to deploy to
    required: false
    default: ''

  source_machine:
    type: string
    description: the machine you want to use as the source for deploying artifacts
    required: false
    default: ''

  workflow:
    default: ems.deploy_artifacts.main
    immutable: true
    type: string

```

Multiple Entrypoint Workflow Definition: main and deploy_customer
```yaml
version: '2.0'
name: 'ems.deploy_artifacts'
description: Deploy Artifacts Workflow.
workflows:
  main:
    type: direct
    input: 
      - customers
      - snapshot
      - artifacts
      - environment
      - ignore_deployed
      - dryrun
      - machine
      - source_machine

    output:
      result:
        successful_artifacts: <% $.successful_artifacts %>
        failed_deploys_exist: <% $.failed_deploys_exist %>
        failed_tests_exist: <% $.failed_tests_exist %>
        dryrun: <% $.dryrun %>
        something_deployed: <% $.something_deployed %>

    tasks:
      
      deployment_plan:
        action: ems.deployment_plan  
        input:
          customers: <% $.customers %>
          snapshot: <% $.snapshot %>
          artifacts: <% $.artifacts %>
          source_machine: <% $.source_machine %>
          environment: <% $.environment %>
          ignore_deployed: <% $.ignore_deployed %>
        publish:
          something_deployed: ''
          successful_artifacts: ''
          failed_deploys_exist: ''
          failed_tests_exist: ''
          deployment_plan: <% task(deployment_plan).result.result %>
        on-success:
          - download_artifacts: <% not $.dryrun %>
          - dryrun_deploy_summary: <% $.dryrun and task(deployment_plan).result.result.deployments %>
      
      dryrun_deploy_summary:
        action: ems.deploy_summary
        input:
          environment: <% $.environment %>
          deployments: <% $.deployment_plan.deployments %>
          dryrun: <% $.dryrun %>
        publish:
          something_deployed: <% task(dryrun_deploy_summary).result.result.something_deployed %> 

      download_artifacts:
        with-items: download in <% $.deployment_plan.downloads %>
        concurrency: 3
        action: ems.download_artifacts
        input:
          artifacts: <% $.download.artifacts %>
          machine: <% $.download.machine %>
        on-success:
          - deploy_customer
      
      deploy_customer:
        join: all
        workflow: deploy_customer
        input:
          deployment_plan: <% $.deployment_plan %>
          environment: <% $.environment %>
          machine: <% $.machine %>
        publish:
          deploy_results: <% task(deploy_customer).result.deploy_results %>
        on-success:
          - deploy_summary

      deploy_summary:
        join: all
        action: ems.deploy_summary
        input:
          environment: <% $.environment %>
          deployments: <% $.deploy_results %>
          dryrun: <% $.dryrun %>
        publish:
          successful_artifacts: <% task(deploy_summary).result.result.successful_artifacts %>
          failed_deploys_exist: <% task(deploy_summary).result.result.failed_deploys_exist %>
          failed_tests_exist: <% task(deploy_summary).result.result.failed_tests_exist %>
          something_deployed: <% task(deploy_summary).result.result.something_deployed %> 
        on-success:
          - promote_artifacts: <% task(deploy_summary).result.result.successful_artifacts and $.environment = 'int' %>

      promote_artifacts:
        action: ems.promote_artifacts
        input:
          artifacts: <% $.successful_artifacts %>
          environment: int
  
  deploy_customer:
    type: direct
    input: 
      - deployment_plan
      - environment
      - machine

    output:
      deploy_results: <% $.deploy_results %>

    tasks:
      deploy:
        with-items: deployment in <% $.deployment_plan.deployments %>
        concurrency: 3
        action: ems.deploy_customer
        input:
          customer: <% $.deployment.customer %>
          artifacts: <% $.deployment.artifacts %>
          environment: <% $.environment %>
          machine: <% $.machine %>
        publish:
          deploy_results: <% task(deploy).result.result %>
```

##### EXPECTED RESULTS
For the workflow to successfully complete

##### ACTUAL RESULTS
```yaml
id: 5b200d39e3bdea08d7967ac4
action.ref: ems.deploy_artifacts
parameters:
  customers: ems
  environment: prod
status: failed (0s elapsed)
start_timestamp: Tue, 12 Jun 2018 18:13:13 UTC
end_timestamp: Tue, 12 Jun 2018 18:13:13 UTC
result:
  extra:
    state: ERROR
    state_info: "Failed to run task [error=Invalid input [name=st2.action, class=st2mistral.actions.stackstorm.St2Action, missing=['action_context']], wf=ems.deploy_artifacts.main, task=deployment_plan]:
Traceback (most recent call last):
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/task_handler.py", line 63, in run_task
    task.run()
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/osprofiler/profiler.py", line 158, in wrapper
    result = f(*args, **kwargs)
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/tasks.py", line 374, in run
    self._run_new()
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/osprofiler/profiler.py", line 158, in wrapper
    result = f(*args, **kwargs)
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/tasks.py", line 403, in _run_new
    self._schedule_actions()
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/tasks.py", line 475, in _schedule_actions
    action.validate_input(input_dict)
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/actions.py", line 322, in validate_input
    self.action_def.action_class
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/utils.py", line 66, in validate_input
    raise exc.InputException(msg % tuple(msg_props))
InputException: Invalid input [name=st2.action, class=st2mistral.actions.stackstorm.St2Action, missing=['action_context']]
"
  result: "Failed to run task [error=Invalid input [name=st2.action, class=st2mistral.actions.stackstorm.St2Action, missing=['action_context']], wf=ems.deploy_artifacts.main, task=deployment_plan]:
Traceback (most recent call last):
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/task_handler.py", line 63, in run_task
    task.run()
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/osprofiler/profiler.py", line 158, in wrapper
    result = f(*args, **kwargs)
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/tasks.py", line 374, in run
    self._run_new()
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/osprofiler/profiler.py", line 158, in wrapper
    result = f(*args, **kwargs)
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/tasks.py", line 403, in _run_new
    self._schedule_actions()
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/tasks.py", line 475, in _schedule_actions
    action.validate_input(input_dict)
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/actions.py", line 322, in validate_input
    self.action_def.action_class
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/utils.py", line 66, in validate_input
    raise exc.InputException(msg % tuple(msg_props))
InputException: Invalid input [name=st2.action, class=st2mistral.actions.stackstorm.St2Action, missing=['action_context']]
"
  tasks:
  - created_at: '2018-06-12 18:13:13'
    id: dcf54c94-493f-4f74-a250-3ed90b83b733
    input: null
    name: deployment_plan
    published: {}
    result: []
    state: ERROR
    state_info: "Failed to run task [error=Invalid input [name=st2.action, class=st2mistral.actions.stackstorm.St2Action, missing=['action_context']], wf=ems.deploy_artifacts.main, task=deployment_plan]:
Traceback (most recent call last):
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/task_handler.py", line 63, in run_task
    task.run()
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/osprofiler/profiler.py", line 158, in wrapper
    result = f(*args, **kwargs)
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/tasks.py", line 374, in run
    self._run_new()
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/osprofiler/profiler.py", line 158, in wrapper
    result = f(*args, **kwargs)
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/tasks.py", line 403, in _run_new
    self._schedule_actions()
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/tasks.py", line 475, in _schedule_actions
    action.validate_input(input_dict)
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/actions.py", line 322, in validate_input
    self.action_def.action_class
  File "/opt/stackstorm/mistral/local/lib/python2.7/site-packages/mistral/engine/utils.py", line 66, in validate_input
    raise exc.InputException(msg % tuple(msg_props))
InputException: Invalid input [name=st2.action, class=st2mistral.actions.stackstorm.St2Action, missing=['action_context']]
"
    updated_at: '2018-06-12 18:13:13'
    workflow_execution_id: 26b306d3-5f79-4355-bf46-1df60e154fc8
    workflow_name: ems.deploy_artifacts.main

```

**Comment by nmaludy** [comment]
Are there any errors in `/var/log/mistral/mistral-server.log`?

**Comment by LindsayHill** [comment]
Might also need to check that all the upgrade steps were done. Specifically step 3 here https://docs.stackstorm.com/install/upgrades.html#general-upgrade-procedure

**Comment by tjsampson** [comment]
@LindsayHill Thank you for the upgrade link. I re-provisioned the box with 2.6.0 and then went through the upgrade process you sent, and everything is working as expected. Thanks again!

**Comment by LindsayHill** [comment]
Cool, good to hear - thanks for letting us know
