### ISSUE TITLE
Orchestra - Expose task data on failure

### ISSUE THREAD

**Issue by kingsleyadam** [StackStorm/st2#4319]
##### SUMMARY

When a task fails in an orchestra workflow I don't have a way of exposing that task stderr value to the parent workflow task. Along with stderr, any other variable could be useful including stdout. Or any variable assigned in context.

Because of this I can't immediately see the stderr output by looking at the workflow task. Instead I first need to get the id of the task that failed, and then look at the details of that task to see the error.

Idealy we can set this in the `notify_on_error` section of the configuration.

When querying the workflow task the result is:

```yaml
result:
  errors: []
  output: null
```

When quering the task that failed inside the workflow the result is:

```yaml
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py", line 320, in <module>
    obj.run()
  File "/opt/stackstorm/runners/python_runner/python_runner/python_action_wrapper.py", line 179, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/glint_operations/actions/scripts/branch/branch_realm_destruct_security_groups.py", line 20, in run
    SecurityGroup(aws_profile, region=aws_region, group_name=group.get(u'GroupName')).delete_group()
  File "/opt/stackstorm/virtualenvs/glint_operations/lib/python2.7/site-packages/operations_python_package/aws_ec2_security_groups.py", line 144, in delete_group
    self.group.delete(GroupName=self.group.group_name)
  File "/opt/stackstorm/virtualenvs/glint_operations/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/opt/stackstorm/virtualenvs/glint_operations/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/opt/stackstorm/virtualenvs/glint_operations/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/stackstorm/virtualenvs/glint_operations/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (DependencyViolation) when calling the DeleteSecurityGroup operation: resource sg-097d20681a52d7b71 has a dependent object
"
  stdout: '2018-08-28 05:56:25,624 - lib.actions - INFO - deleting security groups
    2018-08-28 05:56:26,572 - operations_python_package.aws_ec2_security_groups - INFO - INBOUND rule removed for security group sg-09de6f18a318da0a3
    '
```

I'd like it if the task's information can be shown in the workflow task.

##### ISSUE TYPE
 - Feature Idea

##### STACKSTORM VERSION

`st2 2.8.1, on Python 2.7.12`

##### OS / ENVIRONMENT / INSTALL METHOD

One line install running on Ubuntu 16.04

##### STEPS TO REPRODUCE

```yaml
version: 1.0

description: A workflow description.

input:
  - realm
  - aws_profile
  - aws_region

tasks:
  task1:
    action: example_action.branch_realm_destruct_security_groups
    input:
      realm: <% ctx(realm) %>
      aws_profile: <% ctx(aws_profile) %>
      aws_region: <% ctx(aws_region) %>
    next:
      - when: <% failed() %>
        publish:
          - stderr: <% result().stderr %>
          - stdout: <% result().stdout %>
        do: notify_on_error
  notify_on_error:
    action: core.echo message=<% ctx(stderr) %>
    next:
    - do: fail

output:
  - realm: <% ctx(realm) %>
  - message: "realm <% ctx(realm) %> destroyed"
```

##### EXPECTED RESULTS

I would expect that at least the stderr information would be exposed in the workflow action.

##### ACTUAL RESULTS

No error information gets shown in the workflow action.

**Comment by nmaludy** [comment]
I can confirm this.

It looks like `st2 execution get xxx` on a orquesta workflow does NOT query information for the children, even when specifying `--detail`.

**Comment by m4dcoder** [comment]
Let me review the code first. I think we should/can expose the task error in the workflow errors list.

**Comment by m4dcoder** [comment]
Addressed at https://github.com/StackStorm/st2/pull/4340
