### ISSUE TITLE
Can't run redex it raise exception

### ISSUE THREAD

**Issue by AbdulAli** [StackStorm/st2#4422]
##### SUMMARY

I have built redex project on my machine but when I try to run a default transformation OSError: [Errno 2] No such file or directory ERROR occurs.

My command is simple: 
./redex ../../APKs/multitouch.apk -o ../../APKs/out.apk 

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
Traceback (most recent call last):
  File "/tmp/redex.nJ4Laf/redex.py", line 833, in <module>
    run_redex(args)
  File "/tmp/redex.nJ4Laf/redex.py", line 817, in run_redex
    finalize_redex(state)
  File "/tmp/redex.nJ4Laf/redex.py", line 758, in finalize_redex
    state.args.keyalias, state.args.keypass, state.args.ignore_zipalign, state.args.page_align_libs)
  File "/tmp/redex.nJ4Laf/redex.py", line 326, in create_output_apk
    zipalign(unaligned_apk_path, output_apk_path, ignore_zipalign, page_align)
  File "/tmp/redex.nJ4Laf/redex.py", line 276, in zipalign
    subprocess.check_call(zipalign + args)
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

##### OS / ENVIRONMENT / INSTALL METHOD
O/S = Ubuntu 18.04
G++ = 7.3.0

##### STEPS TO REPRODUCE

```yaml

```

**Comment by LindsayHill** [comment]
This Github repository is for StackStorm. I think you have logged this issue in the wrong place
