### ISSUE TITLE
st2ctl reload --register-all fails when pack name has spaces

### ISSUE THREAD

**Issue by sahilsk** [StackStorm/st2#4558]
##### SUMMARY

`st2ctl reload --register-all` is throwing schema validator error when pack name contains spaces in spite of having `ref` property in the pack.yaml file.

##### ISSUE TYPE

 - Bug Report

##### STACKSTORM VERSION
Paste the output of `st2 --version`:

```
st2 2.9.1, on Python 2.7.6
```

##### OS / ENVIRONMENT / INSTALL METHOD
- docker: st2-docker project

##### STEPS TO REPRODUCE

Pack code: https://docs.stackstorm.com/reference/packs.html#creating-your-first-pack

- Create a pack.yaml file with  `ref` and `name` property. 
- Add spaces in `name` property
- install pack: `st2 pack install file:///$PWD`    :  Succeed 
- Manual installation:  copy entire content of pack into:  /opt/stackstorm/packs/<mypack> 

Try to register config: 
- `st2ctl reload --register-all` 
-  schema validation failed error should show up in the console.

```yaml
---
ref: nexus3
name: Sontatype nexus3
description: Sontatype nexus3 stackstorm pack
keywords:
    - example
    - test
version: 0.1.0
python_versions:
  - "2"
  - "3"
author: Sonu K. Meena
email: sonu.meena@example.com
```

##### EXPECTED RESULTS
- It should register pack without any schema issue

##### ACTUAL RESULTS

```
  utils.DeprecatedIn23,
2019-02-20 08:22:54,066 INFO [-] Connecting to database "st2" @ "mongo:27017" as user "None".
2019-02-20 08:22:54,073 INFO [-] Successfully connected to database "st2" @ "mongo:27017" as user "None".
2019-02-20 08:22:54,444 INFO [-] =========================================================
2019-02-20 08:22:54,444 INFO [-] ############## Registering triggers #####################
2019-02-20 08:22:54,444 INFO [-] =========================================================
2019-02-20 08:22:54,470 WARNING [-] Failed to register sensors: Failed to register pack "Sontatype Nexus3": Pack ref / name can only contain valid word characters (a-z, 0-9 and _), dashes are not allowed.

'Sontatype Nexus3' does not match '^[a-z0-9_]+$'

Failed validating 'pattern' in schema['properties']['ref']:
    {'default': None,
     'description': 'Reference for the pack, used as an internal id.',
     'pattern': '^[a-z0-9_]+$',
     'type': ['string', 'null']}

On instance['ref']:
    'Sontatype Nexus3'
Traceback (most recent call last):
  File "/usr/bin/st2-register-content", line 22, in <module>
    sys.exit(content_loader.main(sys.argv[1:]))
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 389, in main
    register_content()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 336, in register_content
    register_triggers()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 146, in register_triggers
    raise e
ValueError: Failed to register pack "Sontatype Nexus3": Pack ref / name can only contain valid word characters (a-z, 0-9 and _), dashes are not allowed.

'Sontatype Nexus3' does not match '^[a-z0-9_]+$'

Failed validating 'pattern' in schema['properties']['ref']:
    {'default': None,
     'description': 'Reference for the pack, used as an internal id.',
     'pattern': '^[a-z0-9_]+$',
     'type': ['string', 'null']}

On instance['ref']:
    'Sontatype Nexus3'
##### st2 components status #####
st2actionrunner PID: 111
```

**Comment by LindsayHill** [comment]
> * install pack: `st2 pack install file:///$PWD`    :  Succeed

So it succeeded when you ran `st2 pack install`, but failed when you tried to manually register it?

What does your sensor yaml contain?

**Comment by LindsayHill** [comment]
There are tests related to packs with a space in the 'name:` field - see https://github.com/StackStorm/st2/blob/master/st2tests/st2tests/fixtures/packs/dummy_pack_16/pack.yaml

But I wonder if this is somehow connected to https://github.com/StackStorm/st2/issues/3682

It may be that this becomes an issue when you have sensors

**Comment by sahilsk** [comment]
@LindsayHill 
Correct:  `st2 pack install` works but manual registration fails even without sensors

```
root@72b8ebf04e73:/nexus3# rm -rf sensors
root@72b8ebf04e73:/nexus3# rm -rf /opt/stackstorm/packs/nexus3/*
root@72b8ebf04e73:/nexus3# cp -rf ./* /opt/stackstorm/packs/nexus3/
root@72b8ebf04e73:/nexus3# tree -L 2 /opt/stackstorm/packs/nexus3/
/opt/stackstorm/packs/nexus3/
├── actions
│   ├── create_repositories.yaml
│   ├── create_scripts.yaml
│   ├── delete_repositories.yaml
│   ├── delete_scripts.yaml
│   ├── get_repositories.yaml
│   ├── get_scripts.yaml
│   ├── lib
│   ├── list_repositories.yaml
│   ├── list_scripts.yaml
│   ├── run.py
│   └── run_scripts.yaml
├── aliases
├── config.schema.yaml
├── icon.png
├── nexus3.yaml.example
├── pack.yaml
├── policies
│   └── retry_core_http_on_timeout.yaml
├── README.md
├── README-test.md
├── requirements.txt
└── rules


2019-02-20 14:36:57,355 WARNING [-] Failed to register sensors: Failed to register pack "Sontatype Nexus3": Pack ref / name can only contain valid word characters (a-z, 0-9 and _), dashes are not allowed.

'Sontatype Nexus3' does not match '^[a-z0-9_]+$'

Failed validating 'pattern' in schema['properties']['ref']:
    {'default': None,
     'description': 'Reference for the pack, used as an internal id.',
     'pattern': '^[a-z0-9_]+$',
     'type': ['string', 'null']}

On instance['ref']:
    'Sontatype Nexus3'
Traceback (most recent call last):
  File "/usr/bin/st2-register-content", line 22, in <module>
    sys.exit(content_loader.main(sys.argv[1:]))
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 389, in main
    register_content()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 336, in register_content
    register_triggers()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/content/bootstrap.py", line 146, in register_triggers
    raise e
ValueError: Failed to register pack "Sontatype Nexus3": Pack ref / name can only contain valid word characters (a-z, 0-9 and _), dashes are not allowed.

'Sontatype Nexus3' does not match '^[a-z0-9_]+$'

Failed validating 'pattern' in schema['properties']['ref']:
    {'default': None,
     'description': 'Reference for the pack, used as an internal id.',
     'pattern': '^[a-z0-9_]+$',
     'type': ['string', 'null']}

On instance['ref']:
    'Sontatype Nexus3'
```

I'm following the official pack guide:

https://docs.stackstorm.com/reference/packs.html#creating-your-first-pack

Sensor:

```
---
class_name: "HelloSensor"
entry_point: "sensor1.py"
description: "Test sensor that emits triggers."
trigger_types:
  -
    name: "event1"
    description: "An example trigger."
    payload_schema:
      type: "object"
```

**Comment by LindsayHill** [comment]
> manual registration **fails even without sensors**

It's _possible_ that what's happened here is that you still have some reference to the sensor in the DB. Just deleting the content from disk doesn't delete it from DB.

**Comment by LindsayHill** [comment]
Just running some tests on my system:

```shell
vagrant@stackstorm:~$ st2 --version
st2 2.10.1, on Python 2.7.12
vagrant@stackstorm:~$
```

Start with a very simple pack containing no actions or sensors:

```shell
vagrant@stackstorm:~$ cd mypack/
vagrant@stackstorm:~/mypack$ ll
total 16
drwxrwxr-x 3 vagrant vagrant 4096 Feb 20 14:48 ./
drwxr-xr-x 8 vagrant vagrant 4096 Feb 20 14:48 ../
drwxrwxr-x 8 vagrant vagrant 4096 Feb 20 14:48 .git/
-rwxrwxr-x 1 vagrant vagrant  123 Feb 20 14:48 pack.yaml*
vagrant@stackstorm:~/mypack$ cat pack.yaml
---
ref: mypack
name: My Pack
description: My Test Pack
version: 1.0.0
author: StackStorm, Inc.
email: info@stackstorm.com
vagrant@stackstorm:~/mypack$
```

Installing the pack works fine:

```shell
vagrant@stackstorm:~$ st2 pack install file:///home/vagrant/mypack

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[ succeeded ] install pack dependencies
	[ succeeded ] register pack

+-------------+------------------+
| Property    | Value            |
+-------------+------------------+
| name        | My Pack          |
| description | My Test Pack     |
| version     | 1.0.0            |
| author      | StackStorm, Inc. |
+-------------+------------------+
vagrant@stackstorm:~$
```

At this point it is registered, but we will re-register everything to see if we can trigger any errors:

```
vagrant@stackstorm:~$ sudo st2ctl reload --register-all
Registering content...[flags = --config-file /etc/st2/st2.conf --register-all]
2019-02-20 14:50:01,751 INFO [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "stackstorm".
2019-02-20 14:50:01,791 INFO [-] Successfully connected to database "st2" @ "127.0.0.1:27017" as user "stackstorm".
2019-02-20 14:50:02,364 INFO [-] =========================================================
2019-02-20 14:50:02,366 INFO [-] ############## Registering triggers #####################
2019-02-20 14:50:02,367 INFO [-] =========================================================
2019-02-20 14:50:02,602 INFO [-] Registered 0 triggers.
2019-02-20 14:50:02,605 INFO [-] =========================================================
2019-02-20 14:50:02,606 INFO [-] ############## Registering sensors ######################
2019-02-20 14:50:02,607 INFO [-] =========================================================
2019-02-20 14:50:02,651 INFO [-] Registered 1 sensors.
2019-02-20 14:50:02,657 INFO [-] =========================================================
2019-02-20 14:50:02,660 INFO [-] ############## Registering runners ######################
2019-02-20 14:50:02,664 INFO [-] =========================================================
2019-02-20 14:50:04,686 INFO [-] Registered 18 runners.
2019-02-20 14:50:04,686 INFO [-] =========================================================
2019-02-20 14:50:04,686 INFO [-] ############## Registering actions ######################
2019-02-20 14:50:04,686 INFO [-] =========================================================
2019-02-20 14:50:08,612 INFO [-] Registered 76 actions.
2019-02-20 14:50:08,612 INFO [-] =========================================================
2019-02-20 14:50:08,613 INFO [-] ############## Registering rules ########################
2019-02-20 14:50:08,613 INFO [-] =========================================================
2019-02-20 14:50:08,705 INFO [-] Registered 1 rules.
2019-02-20 14:50:08,705 INFO [-] =========================================================
2019-02-20 14:50:08,705 INFO [-] ############## Registering aliases ######################
2019-02-20 14:50:08,705 INFO [-] =========================================================
2019-02-20 14:50:08,928 INFO [-] Registered 11 aliases.
2019-02-20 14:50:08,928 INFO [-] =========================================================
2019-02-20 14:50:08,929 INFO [-] ############## Registering policy types #################
2019-02-20 14:50:08,930 INFO [-] =========================================================
2019-02-20 14:50:08,961 INFO [-] Registered 3 policy types.
2019-02-20 14:50:08,962 INFO [-] =========================================================
2019-02-20 14:50:08,963 INFO [-] ############## Registering policies #####################
2019-02-20 14:50:08,963 INFO [-] =========================================================
2019-02-20 14:50:08,965 INFO [-] Registered 0 policies.
2019-02-20 14:50:08,966 INFO [-] =========================================================
2019-02-20 14:50:08,967 INFO [-] ############## Registering configs ######################
2019-02-20 14:50:08,968 INFO [-] =========================================================
2019-02-20 14:50:08,973 INFO [-] Registered 0 configs.
##### st2 components status #####
st2actionrunner PID: 1014
st2actionrunner PID: 1070
st2actionrunner PID: 1103
st2actionrunner PID: 1106
st2actionrunner PID: 1114
st2actionrunner PID: 1117
st2actionrunner PID: 1129
st2actionrunner PID: 1133
st2actionrunner PID: 1143
st2actionrunner PID: 1146
st2api PID: 796
st2api PID: 2150
st2stream PID: 799
st2stream PID: 2149
st2auth PID: 790
st2auth PID: 2172
st2garbagecollector PID: 805
st2notifier PID: 813
st2resultstracker PID: 811
st2rulesengine PID: 814
st2sensorcontainer PID: 818
st2chatops is not running.
st2timersengine PID: 823
st2workflowengine PID: 792
st2scheduler PID: 800
mistral-server PID: 1063
mistral.api PID: 1021
mistral.api PID: 2124
mistral.api PID: 2133
vagrant@stackstorm:~$
```

So far so good. I'll do some more tests with adding actions & sensors to this pack.

**Comment by sahilsk** [comment]
@LindsayHill 
> Out of interest, why were you doing `st2 pack install`, then doing manual copy & registration?

`st2 pack install` is a current workaround for me to register all **.yaml files. I do copy to update all my *.py files as they don't require any `reload`.

Since manual registration doesn't work for me, every time i need to update any yaml file, i had to do everything from scratch 

- remove pack: `st2 pack remove nexus3`
- install again : `st2 pack install nexus3`




> It's _possible_ that what's happened here is that you still have some reference to the sensor in the DB. Just deleting the content from disk doesn't delete it from DB.

Not sure. Probably not. otherwise  `st2 pack list` and `st2 sensor list` should pick something.

**Comment by sahilsk** [comment]
@LindsayHill 
please pull this repo and try to register it:

https://github.com/sahilsk/stackstorm-nexus3

**Comment by LindsayHill** [comment]
Thanks for that repo. I just installed it, and then also did a reload, and everything works as expected:

```shell
vagrant@stackstorm:~$ st2 pack install https://github.com/sahilsk/stackstorm-nexus3

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[ succeeded ] install pack dependencies
	[ succeeded ] register pack

+-------------+----------------------------------+
| Property    | Value                            |
+-------------+----------------------------------+
| name        | Sontatype nexus3                 |
| description | Sontatype nexus3 stackstorm pack |
| version     | 0.1.0                            |
| author      | Sonu K. Meena                    |
+-------------+----------------------------------+
vagrant@stackstorm:~$ sudo st2ctl reload --register-all
Registering content...[flags = --config-file /etc/st2/st2.conf --register-all]
2019-02-20 15:02:55,039 INFO [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "stackstorm".
2019-02-20 15:02:55,081 INFO [-] Successfully connected to database "st2" @ "127.0.0.1:27017" as user "stackstorm".
2019-02-20 15:02:55,715 INFO [-] =========================================================
2019-02-20 15:02:55,716 INFO [-] ############## Registering triggers #####################
2019-02-20 15:02:55,716 INFO [-] =========================================================
2019-02-20 15:02:56,024 INFO [-] Registered 0 triggers.
2019-02-20 15:02:56,025 INFO [-] =========================================================
2019-02-20 15:02:56,025 INFO [-] ############## Registering sensors ######################
2019-02-20 15:02:56,026 INFO [-] =========================================================
2019-02-20 15:02:56,064 INFO [-] Registered 1 sensors.
2019-02-20 15:02:56,064 INFO [-] =========================================================
2019-02-20 15:02:56,065 INFO [-] ############## Registering runners ######################
2019-02-20 15:02:56,065 INFO [-] =========================================================
2019-02-20 15:02:57,951 INFO [-] Registered 18 runners.
2019-02-20 15:02:57,952 INFO [-] =========================================================
2019-02-20 15:02:57,952 INFO [-] ############## Registering actions ######################
2019-02-20 15:02:57,952 INFO [-] =========================================================
2019-02-20 15:03:00,997 INFO [-] Registered 85 actions.
2019-02-20 15:03:00,998 INFO [-] =========================================================
2019-02-20 15:03:00,999 INFO [-] ############## Registering rules ########################
2019-02-20 15:03:01,002 INFO [-] =========================================================
2019-02-20 15:03:01,047 INFO [-] Registered 1 rules.
2019-02-20 15:03:01,048 INFO [-] =========================================================
2019-02-20 15:03:01,048 INFO [-] ############## Registering aliases ######################
2019-02-20 15:03:01,048 INFO [-] =========================================================
2019-02-20 15:03:01,297 INFO [-] Registered 11 aliases.
2019-02-20 15:03:01,298 INFO [-] =========================================================
2019-02-20 15:03:01,299 INFO [-] ############## Registering policy types #################
2019-02-20 15:03:01,299 INFO [-] =========================================================
2019-02-20 15:03:01,348 INFO [-] Registered 3 policy types.
2019-02-20 15:03:01,349 INFO [-] =========================================================
2019-02-20 15:03:01,349 INFO [-] ############## Registering policies #####################
2019-02-20 15:03:01,350 INFO [-] =========================================================
2019-02-20 15:03:01,378 INFO [-] Registered 1 policies.
2019-02-20 15:03:01,380 INFO [-] =========================================================
2019-02-20 15:03:01,381 INFO [-] ############## Registering configs ######################
2019-02-20 15:03:01,382 INFO [-] =========================================================
2019-02-20 15:03:01,383 INFO [-] Registered 0 configs.
##### st2 components status #####
st2actionrunner PID: 1014
st2actionrunner PID: 1070
st2actionrunner PID: 1103
st2actionrunner PID: 1106
st2actionrunner PID: 1114
st2actionrunner PID: 1117
st2actionrunner PID: 1129
st2actionrunner PID: 1133
st2actionrunner PID: 1143
st2actionrunner PID: 1146
st2api PID: 796
st2api PID: 2150
st2stream PID: 799
st2stream PID: 2149
st2auth PID: 790
st2auth PID: 2172
st2garbagecollector PID: 805
st2notifier PID: 813
st2resultstracker PID: 811
st2rulesengine PID: 814
st2sensorcontainer PID: 818
st2chatops is not running.
st2timersengine PID: 823
st2workflowengine PID: 792
st2scheduler PID: 800
mistral-server PID: 1063
mistral.api PID: 1021
mistral.api PID: 2124
mistral.api PID: 2133
vagrant@stackstorm:~$
```

My current suspicion is that you have something else somewhere under `/opt/stackstorm/packs` that is causing problems at registration time, since it tries to register everything it finds.

**Comment by LindsayHill** [comment]
When you do `st2 pack install`, it only registers that pack-specific content. When you do `st2ctl reload`, it tries to register everything. Might be some other content you have there that is breaking things. Unfortunately the registration script is not telling us exactly which file it is that causes problems.

But here's something interesting: In that repo you provided, you have this: `name: Sontatype nexus3`

**But**: look at the error message you were getting earlier: `'Sontatype Nexus3' does not match '^[a-z0-9_]+$'`

Note the upper-case "Nexus3". 

So now I'm pretty sure that you've got something leftover or incorrectly copied under `/opt/stackstorm/packs` (or any other path you have configured under system_packs_base_path).

You could try something like `grep -r Nexus3 /opt/stackstorm/packs` to track it down

**Comment by sahilsk** [comment]
@LindsayHill  nice catch.  Something fishy was going on. I didn't find anything buggy inside `packs` directory. 
I re-created stackstorm container from `st2-docker`  with all volumes pruned. This time everything is working smoothly.

During development of this pack, I did change pack name multiple times.  This could have left some dangling sensors inside.

Anyways, thanks for the help @LindsayHill 

btw, in future you can leverage this stackstorm pack scaffolding project : [generator-st2pack](https://www.npmjs.com/package/generator-st2pack) (alpha) to create pack instantly.

**Comment by LindsayHill** [comment]
Odd, must have been something hanging around. Good to know it's working now. 

There's also this for pack scaffolding - https://github.com/EncoreTechnologies/cookiecutter-stackstorm
