### ISSUE TITLE
st2 pods stuck in loop

### ISSUE THREAD

**Issue by nagrigore** [StackStorm/st2#4606]
I'm deploying a stackstorm/stackstorm-ha cluster with helm and since yesterday some of the pods seem to be stuck in a loop.
"Deployment does not have minimum availability". This was previously working without any issues.

We don't have much info on the logs:

 Logs: st2actionrunner
2019-03-21 08:40:38,795 DEBUG [-] Using Python: 2.7.12 (/opt/stackstorm/st2/bin/python)
2019-03-21 08:40:38,796 DEBUG [-] Using config files: /etc/st2/st2.conf,/etc/st2/st2.docker.conf,/etc/st2/st2.user.conf
2019-03-21 08:40:38,796 DEBUG [-] Using logging config: /etc/st2/logging.actionrunner.conf
2019-03-21 08:40:38,802 INFO [-] Connecting to database "st2" @ "aspiring-ferret-mongodb-ha:27017" as user "None".
2019-03-21 08:40:38,830 INFO [-] Successfully connected to database "st2" @ "aspiring-ferret-mongodb-ha:27017" as user "None".
2019-03-21 08:40:39,972 ERROR [-] (PID=1) Worker quit due to exception.
Traceback (most recent call last):
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/actionrunner.py", line 80, in main
_setup()
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/actionrunner.py", line 41, in _setup
register_signal_handlers=True, service_registry=True, capabilities=capabilities)
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 187, in setup
start_heart=True)
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 224, in register_service_in_service_registry
coordinator.create_group(group_id).get()
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/coordination.py", line 476, in create_group
raise tooz.NotImplemented
NotImplemented

=========================
 Logs: st2workflowengine
2019-03-21 08:45:45,742 DEBUG [-] Using Python: 2.7.12 (/opt/stackstorm/st2/bin/python)
2019-03-21 08:45:45,742 DEBUG [-] Using config files: /etc/st2/st2.conf,/etc/st2/st2.docker.conf,/etc/st2/st2.user.conf
2019-03-21 08:45:45,743 DEBUG [-] Using logging config: /etc/st2/logging.workflowengine.conf
2019-03-21 08:45:45,748 INFO [-] Connecting to database "st2" @ "aspiring-ferret-mongodb-ha:27017" as user "None".
2019-03-21 08:45:45,774 INFO [-] Successfully connected to database "st2" @ "aspiring-ferret-mongodb-ha:27017" as user "None".
2019-03-21 08:45:46,633 ERROR [-] Traceback (most recent call last):
2019-03-21 08:45:46,633 ERROR [-] File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/workflow_engine.py", line 94, in main
2019-03-21 08:45:46,633 ERROR [-] setup()
2019-03-21 08:45:46,633 ERROR [-] File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/workflow_engine.py", line 65, in setup
2019-03-21 08:45:46,633 ERROR [-] capabilities=capabilities
2019-03-21 08:45:46,633 ERROR [-] File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 187, in setup
2019-03-21 08:45:46,633 ERROR [-] start_heart=True)
2019-03-21 08:45:46,633 ERROR [-] File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 224, in register_service_in_service_registry
2019-03-21 08:45:46,634 ERROR [-] coordinator.create_group(group_id).get()
2019-03-21 08:45:46,634 ERROR [-] File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/coordination.py", line 476, in create_group
2019-03-21 08:45:46,634 ERROR [-] raise tooz.NotImplemented
2019-03-21 08:45:46,634 ERROR [-] NotImplemented
2019-03-21 08:45:46,634 ERROR [-] (PID=1) Workflow engine quit due to exception.
Traceback (most recent call last):
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/workflow_engine.py", line 94, in main
setup()
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/cmd/workflow_engine.py", line 65, in setup
capabilities=capabilities
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 187, in setup
start_heart=True)
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/service_setup.py", line 224, in register_service_in_service_registry
coordinator.create_group(group_id).get()
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/coordination.py", line 476, in create_group
raise tooz.NotImplemented
NotImplemented

=========================

This was installed with command: helm install stackstorm/stackstorm-ha
I've used the same layout to deploy and test few days ago. There's no resources issue.

root@aspiring-ferret-st2client-849f88776f-p4ntd:/opt/stackstorm# st2 --version
st2 3.0dev (0b95862), on Python 2.7.12

**Comment by Kami** [comment]
@nagrigore Did you figure it out?

It looks like it's related to recent service registry changes I worked on. Which coordination backed do you have configured in st2.conf?

**Comment by Kami** [comment]
Edit: We are continuing here - https://github.com/StackStorm/stackstorm-ha/issues/57.
