### ISSUE TITLE
Error when installing staging unstable on CentOS 7

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2#4626]
##### SUMMARY

When installing on CentOS 7 (do NOT see the problem on Ubuntu16.04) with st2vagrant i'm getting the following error.

I haven't noticed any issues with the install, other than than seeing the error during install.

```
20190409T010012+0000 2019-04-09 01:00:12,544 ERROR [-] Conflict while trying to save in DB.
20190409T010012+0000 Traceback (most recent call last):
20190409T010012+0000   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/persistence/base.py", line 174, in add_or_update
20190409T010012+0000     model_object = cls._get_impl().add_or_update(model_object, validate=True)
20190409T010012+0000   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/__init__.py", line 452, in add_or_update
20190409T010013+0000     instance.save(validate=validate)
20190409T010013+0000   File "/opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/document.py", line 412, in save
20190409T010013+0000     raise NotUniqueError(message % six.text_type(err))
20190409T010013+0000 NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: st2.trigger_d_b index: uid_1 dup key: { : "trigger:core:st2.key_value_pair.update:99914b932bd37a50b983c5e7c90ae93b" })
20190409T010013+0000 2019-04-09 01:00:12,683 ERROR [-] Conflict while trying to save in DB.
20190409T010013+0000 Traceback (most recent call last):
20190409T010013+0000   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/persistence/base.py", line 174, in add_or_update
20190409T010013+0000     model_object = cls._get_impl().add_or_update(model_object, validate=True)
20190409T010013+0000   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/__init__.py", line 452, in add_or_update
20190409T010013+0000     instance.save(validate=validate)
20190409T010014+0000   File "/opt/stackstorm/st2/lib/python2.7/site-packages/mongoengine/document.py", line 412, in save
20190409T010014+0000     raise NotUniqueError(message % six.text_type(err))
20190409T010014+0000 NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: st2.trigger_type_d_b index: uid_1 dup key: { : "trigger_type:core:st2.key_value_pair.value_change" })
``` 

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
```shell
$ st2 --version
st2 3.0dev (44c4953), on Python 2.7.5
```

##### OS / ENVIRONMENT / INSTALL METHOD
```
$ cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 

# install method: st2vagrant with centos/7 box
```

##### STEPS TO REPRODUCE

```shell
git clone https://github.com/StackStorm/st2vagrant
cd st2vagrant
BOX=centos/7 vagrant up
```

##### ACTUAL RESULTS
Here's a full Gist of the install log: https://gist.github.com/nmaludy/875acebf3772d10384df5eccfc2605e9

The error is in lines: 846-900

**Comment by LindsayHill** [comment]
Seems similar to https://github.com/StackStorm/st2/issues/3933 - it's one I've seen pop up every now & then, but never figured out exactly what's going on.

**Comment by nmaludy** [comment]
Closing this in favor of #3933
