### ISSUE TITLE
Orquesta workflows hang when referencing first task in workflow

### ISSUE THREAD

**Issue by bishopbm1** [StackStorm/st2#4746]
## SUMMARY
When attempting to implement a retry loop in orquesta if the first task is called again for the retry, the workflow does not execute any tasks and just hangs on starting which causes the workflow to have to be cancelled manually.

### STACKSTORM VERSION

```
# st2 --version
st2 3.1.0, on Python 2.7.5
```

##### OS, environment, install method

```
# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
```
Install method is Puppet forge module

## Steps to reproduce the problem

Action file:
```
---
description: "testing retry"
enabled: true
entry_point: workflows/retry.yaml
name: retry
pack: testing
runner_type: orquesta
```

Workflow:
```
version: 1.0

description: testing retry

input:
  - attempt_count: 0
  - retry_count: 3

tasks:
  get_data:
    action: core.http
    input:
      method: "GET"
      url: "https://wwww.google.com"
    next:
      - when: "{{ failed() and ctx().attempt_count < ctx().retry_count }}"
        do: re_run_get_data

  re_run_get_data:
    action: core.noop
    next:
      - when: "{{ succeeded() }}"
        publish:
          - attempt_count: "{{ ctx().attempt_count + 1 }}"
        do: get_data
```

running action (will hang and need to be cancelled manually):
```
# st2 run testing.retry
...................................................................^CTraceback (most recent call last):
```

```
| 5d36133a49b3d243eb877cdc | testing.retry                    | test_user | canceled (157s elapsed)  | Mon, 22 Jul 2019 19:49:14 UTC | Mon, 22 Jul 2019 19:51:51 UTC |
```

logs from /var/log/st2/st2workflowengine.log:
```
2019-07-22 15:49:15,497 140340759341328 INFO workflows [-] [5d36133a49b3d243eb877cdc] Processing request for workflow execution.
2019-07-22 15:49:15,526 140340759341328 INFO workflows [-] [5d36133a49b3d243eb877cdc] Requesting conductor to start running workflow execution.
2019-07-22 15:49:15,527 140340759341328 INFO workflows [-] [5d36133a49b3d243eb877cdc] Identifying next set (0) of tasks for workflow execution in status "running".
2019-07-22 15:49:15,528 140340759341328 INFO workflows [-] [5d36133a49b3d243eb877cdc] No tasks identified to execute next.
2019-07-22 15:49:15,529 140340759341328 INFO workflows [-] [5d36133a49b3d243eb877cdc] Updating workflow execution from status "requested" to "running".
```

## Expected Results

If we change the workflow by just copy and pasting the first action with a slightly different name everything works as expected. It retries for the expected amount of times and exits.

Workflow:
```
version: 1.0

description: testing retry

input:
  - attempt_count: 0
  - retry_count: 3

tasks:
  get_data:
    action: core.http
    input:
      method: "GET"
      url: "https://wwww.google.com"
    next:
      - when: "{{ failed() and ctx().attempt_count < ctx().retry_count }}"
        do: re_run_get_data

  re_run_get_data:
    action: core.noop
    next:
      - when: "{{ succeeded() }}"
        publish:
          - attempt_count: "{{ ctx().attempt_count + 1 }}"
        do: re_get_data

  re_get_data:
    action: core.http
    input:
      method: "GET"
      url: "https://wwww.google.com"
    next:
      - when: "{{ failed() and ctx().attempt_count < ctx().retry_count }}"
        do: re_run_get_data
```

results:
```
# st2 run testing.retry
......
id: 5d3612d949b3d243eb877cd9
action.ref: testing.retry
parameters: None
status: failed
start_timestamp: Mon, 22 Jul 2019 19:47:37 UTC
end_timestamp: Mon, 22 Jul 2019 19:47:48 UTC
result: 
  errors:
  - message: Execution failed. See result for details.
    result:
      error: 'HTTPSConnectionPool(host=''wwww.google.com'', port=443): Max retries exceeded with url: / (Caused by NewConnectionError(''<urllib3.connection.VerifiedHTTPSConnection object at 0x7fafd97b2dd0>: Failed to establish a new connection: [Errno -2] No address found'',))'
      traceback: "  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py", line 127, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/http_runner/http_runner.py", line 101, in run
    result = client.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/http_runner/http_runner.py", line 229, in run
    verify=self.verify
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
"
    task_id: get_data
    type: error
  - message: Execution failed. See result for details.
    result:
      error: 'HTTPSConnectionPool(host=''wwww.google.com'', port=443): Max retries exceeded with url: / (Caused by NewConnectionError(''<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdbfbfeb250>: Failed to establish a new connection: [Errno -2] No address found'',))'
      traceback: "  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py", line 127, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/http_runner/http_runner.py", line 101, in run
    result = client.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/http_runner/http_runner.py", line 229, in run
    verify=self.verify
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
"
    task_id: re_get_data
    type: error
  - message: Execution failed. See result for details.
    result:
      error: 'HTTPSConnectionPool(host=''wwww.google.com'', port=443): Max retries exceeded with url: / (Caused by NewConnectionError(''<urllib3.connection.VerifiedHTTPSConnection object at 0x7f94be5dedd0>: Failed to establish a new connection: [Errno -2] No address found'',))'
      traceback: "  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py", line 127, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/http_runner/http_runner.py", line 101, in run
    result = client.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/http_runner/http_runner.py", line 229, in run
    verify=self.verify
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
"
    task_id: re_get_data
    type: error
  - message: Execution failed. See result for details.
    result:
      error: 'HTTPSConnectionPool(host=''wwww.google.com'', port=443): Max retries exceeded with url: / (Caused by NewConnectionError(''<urllib3.connection.VerifiedHTTPSConnection object at 0x7f52f79d7450>: Failed to establish a new connection: [Errno -2] No address found'',))'
      traceback: "  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py", line 127, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/http_runner/http_runner.py", line 101, in run
    result = client.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/http_runner/http_runner.py", line 229, in run
    verify=self.verify
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
"
    task_id: re_get_data
    type: error
  output: null
+--------------------------+------------------------+-----------------+-----------+-------------------------------+
| id                       | status                 | task            | action    | start_timestamp               |
+--------------------------+------------------------+-----------------+-----------+-------------------------------+
| 5d3612da49b3d205cdd70972 | failed (1s elapsed)    | get_data        | core.http | Mon, 22 Jul 2019 19:47:38 UTC |
| 5d3612db49b3d205cdd70975 | succeeded (1s elapsed) | re_run_get_data | core.noop | Mon, 22 Jul 2019 19:47:39 UTC |
| 5d3612dc49b3d205cdd70978 | failed (1s elapsed)    | re_get_data     | core.http | Mon, 22 Jul 2019 19:47:40 UTC |
| 5d3612de49b3d205cdd7097b | succeeded (0s elapsed) | re_run_get_data | core.noop | Mon, 22 Jul 2019 19:47:42 UTC |
| 5d3612df49b3d205cdd7097e | failed (1s elapsed)    | re_get_data     | core.http | Mon, 22 Jul 2019 19:47:43 UTC |
| 5d3612e149b3d205cdd70981 | succeeded (0s elapsed) | re_run_get_data | core.noop | Mon, 22 Jul 2019 19:47:45 UTC |
| 5d3612e249b3d205cdd70984 | failed (1s elapsed)    | re_get_data     | core.http | Mon, 22 Jul 2019 19:47:46 UTC |
+--------------------------+------------------------+-----------------+-----------+-------------------------------+
```

**Comment by m4dcoder** [comment]
When implementing a completely enclosed cycle or a self-looping task in orquesta, you will need an initiating task that tells orquesta where is the entry point. Please refer to this issue here https://github.com/StackStorm/orquesta/issues/84 for example and workaround.
