### ISSUE TITLE
 get_bgp_config is raising NotImplementedError

### ISSUE THREAD

**Issue by netwninja** [StackStorm/st2#4799]
I am trying to extract the bgp config for one of the Cisco IOS router using pack napalm and action as "napalm.get_bgp_config" and it's generating not Implemened error"

```
st2 run napalm.get_bgp_config hostname=r1

...
id: 5d9a5ed791b2773108984838
status: failed
parameters: 
  hostname: r1
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 333, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 192, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/napalm/actions/get_bgp_config.py", line 14, in run
    bgpconf = device.get_bgp_config()
  File "/opt/stackstorm/virtualenvs/napalm/lib/python2.7/site-packages/napalm/base/base.py", line 653, in get_bgp_config
    raise NotImplementedError
NotImplementedError
"
  stdout: ''
```

**Comment by netwninja** [comment]
Created by mistake. no action required.
