### ISSUE TITLE
st2 CLI hanging randomly

### ISSUE THREAD

**Issue by kedare** [StackStorm/st2#4893]
## SUMMARY

When running st2 CLI, locally or remotely, connecting directly to the API endpoints or thru a reverser proxy (it happens on both case), the CLI client would freeze for many seconds, not responding to SIGTERM either

### STACKSTORM VERSION

Paste the output of ``st2 --version``: `st2 3.1.0, on Python 3.6.9`

##### OS, environment, install method

Ubuntu 18.04.4 LTS

deb packages

## Steps to reproduce the problem

Install the basic setup following the documentation.
Then when trying to use the `st2` cli, it will randomly hang.
Note that after a command that froze, the immediate next command always work.

## Expected Results

`st2` to work smoothly

## Actual Results

Randomly (half the time?), `st2` would hang for many seconds, eventually continuing or not.
When trying to stop it with `CTRL+C`, it will stay frozen for many seconds before responding and giving the following stacktrace (that doesn't make sense as it's connecting locally without SSL)

```
$ st2 apikey create --help

^C^C^C^C

Traceback (most recent call last):
  File "/usr/bin/st2", line 6, in <module>
    from st2client.shell import main
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/shell.py", line 40, in <module>
    from st2client import models
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/models/__init__.py", line 17, in <module>
    from st2client.models.core import *         # noqa
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/models/core.py", line 25, in <module>
    import requests
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 48, in <module>
    from cryptography.hazmat.backends.openssl import backend as openssl_backend
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 2419, in <module>
    backend = Backend()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 119, in __init__
    self.activate_osrandom_engine()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 163, in activate_osrandom_engine
    with self._get_osurandom_engine() as e:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 146, in _get_osurandom_engine
    res = self._lib.ENGINE_init(e)
KeyboardInterrupt
```

Thanks!

**Comment by misterpah** [comment]
st2 have debug flag. you can get more information by running `st2 --debug apikey create --help` .

another thing is , it is possible that your rabbitMQ is having issue, thus unable to return response to your command.

for my setup, insufficient memory (for rabbitMQ) is the main culprit.

**Comment by kedare** [comment]
The server itself has plenty of free memory (It's using 8GB of the 16GB available).
I don't think there is any parameter in RabbitMQ that by default would prevent it from allocating more ?

**Comment by kedare** [comment]
I took a look at my RabbitMQ memory usage and it's only using a few megs (which is normal as it's a lab instance for now, we have almost nothing running on it)

**Comment by cognifloyd** [comment]
Are you still experiencing this issue with version 3.5? If you are, please comment and I can reopen.
Thanks!
