### ISSUE TITLE
Provide a logrotate configuration for st2notifier logs with mapping to the service as opposed to log file.

### ISSUE THREAD

**Issue by srimandaleeka01** [StackStorm/st2#4940]
## SUMMARY

Support engineer noticed excessive  amount st2notifier logs in our support bundle. There were thirteen thousand files to be precise.

We have log rotate setup for st2notifier but seems like it's applicable to a log file generated per st2 notifier process.

`## Notifiers
/var/log/st2/st2notifier*.log {
  size 10M
  rotate 5
  postrotate
    # Delete all files that haven't been modified in over 5 days
    # Clean up stale PID logs
    find /var/log/st2/ -type f -name "st2notifier*.log*" -mtime +5 -exec rm -f {} \;
    st2ctl reopen-log-files st2notifier > /dev/null
  endscript
}`

### STACKSTORM VERSION

st2 --version : st2 3.1.0, on Python 2.7.15

## OS, environment, install method
A Centos VM : centos-release-7-8.2003.0.el7.centos.x86_64

Install method: Custom install - rpm.

## Steps to reproduce the problem

Not sure what caused the issue, but here are the stack traces in the notifier.
`2020-02-05 20:48:06,598 139630704517840 INFO __init__ [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "None".
2020-02-05 20:48:06,604 139630704517840 INFO __init__ [-] Successfully connected to database "st2" @ "127.0.0.1:27017" as user "None".
2020-02-05 20:48:28,750 139630704517840 ERROR connection_retry_wrapper [-] Connections to RabbitMQ cannot be re-established: Server unexpectedly closed connection
Traceback (most recent call last):
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/st2common/transport/connection_retry_wrapper.py", line 161, in run
    errback=log_error_on_conn_failure)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/connection.py", line 422, in ensure_connection
    callback, timeout=timeout)
  File "/opt/plexxi/python/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/connection.py", line 436, in _reraise_as_library_errors
    sys.exc_info()[2])
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/connection.py", line 431, in _reraise_as_library_errors
    yield
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/connection.py", line 422, in ensure_connection
    callback, timeout=timeout)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/utils/functional.py", line 341, in retry_over_time
    return fun(*args, **kwargs)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/connection.py", line 275, in connect
    return self.connection
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/connection.py", line 823, in connection
    self._connection = self._establish_connection()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/connection.py", line 778, in _establish_connection
    conn = self.transport.establish_connection()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/amqp/connection.py", line 313, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/amqp/connection.py", line 500, in drain_events
    while not self.blocking_read(timeout):
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/amqp/connection.py", line 505, in blocking_read
    frame = self.transport.read_frame()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/amqp/transport.py", line 256, in read_frame
    frame_header = read(7, True)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/amqp/transport.py", line 448, in _read
    raise IOError('Server unexpectedly closed connection')
OperationalError: Server unexpectedly closed connection
2020-02-05 20:48:28,752 139630704517840 ERROR st2notifier [-] (PID=19545) Results tracker quit due to exception.
Traceback (most recent call last):
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/st2actions/cmd/st2notifier.py", line 61, in main
    _setup()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/st2actions/cmd/st2notifier.py", line 41, in _setup
    register_signal_handlers=True, service_registry=True, capabilities=capabilities)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/st2common/service_setup.py", line 163, in setup
    register_exchanges_with_retry()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/st2common/transport/bootstrap_utils.py", line 170, in register_exchanges_with_retry
    return retrying_obj.call(register_exchanges)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/st2common/transport/bootstrap_utils.py", line 152, in register_exchanges
    retry_wrapper.run(connection=conn, wrapped_callback=wrapped_register_exchanges)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/st2common/transport/connection_retry_wrapper.py", line 161, in run
    errback=log_error_on_conn_failure)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/connection.py", line 422, in ensure_connection
    callback, timeout=timeout)
  File "/opt/plexxi/python/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/connection.py", line 436, in _reraise_as_library_errors
    sys.exc_info()[2])
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/connection.py", line 431, in _reraise_as_library_errors
    yield
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/connection.py", line 422, in ensure_connection
    callback, timeout=timeout)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/utils/functional.py", line 341, in retry_over_time
    return fun(*args, **kwargs)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/connection.py", line 275, in connect
    return self.connection
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/connection.py", line 823, in connection
    self._connection = self._establish_connection()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/connection.py", line 778, in _establish_connection
    conn = self.transport.establish_connection()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/amqp/connection.py", line 313, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/amqp/connection.py", line 500, in drain_events
    while not self.blocking_read(timeout):
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/amqp/connection.py", line 505, in blocking_read
    frame = self.transport.read_frame()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/amqp/transport.py", line 256, in read_frame
    frame_header = read(7, True)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/amqp/transport.py", line 448, in _read
    raise IOError('Server unexpectedly closed connection')
OperationalError: Server unexpectedly closed connection`

## Expected Results

What did you expect to happen when running the steps above?
Find fewer st2notifier logs in case of exceptions.

## Actual Results

What happened? What output did you get?
[st2notifier.416.log](https://github.com/StackStorm/st2/files/4588650/st2notifier.416.log)
[st2notifier.417.log](https://github.com/StackStorm/st2/files/4588652/st2notifier.417.log)
[st2notifier.32767.log](https://github.com/StackStorm/st2/files/4588657/st2notifier.32767.log)

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by winem** [comment]
Hi, I took a look at the issue and have some questions. 

1) Were there any empty log files? 
2) In which time were these 13k files written? The modification date of the oldest and the latest log file would be great.
3) How many action runners do you have and are they often restarted or are all of them running for many days already?
4) How often do you trigger logrotate? Do you use the default and it's just triggered daily?
5) It looks like you made some modifications to /etc/logrotate.d/st2. So does `logrotate -d /etc/logrotate.conf` show any errors?

The exception in the log files is caused by connection issues (interruptions) when connecting to the RabbitMQ endpoint. The number of errors being logged increases with the number of connection attempts.

My current assumption is that st2 logged a whole bunch of errors when it lost the connectivity to the RabbitMQ server. This caused the logs to grow quite fast while your logrotate configuration says to rotate the log files if they are larger than 10MB. This would not make that much of a difference if logrotate is triggered just once a day but I assume it's done more often on your system. So the math would be `number of action runners * number of actionrunner restarts * invocations of logrotate with the logfiles being larger then 10MB`. I can imagine that this creates a real high number of logs even though you delete files that were not modified within the last 5 days. 

Cheers,
Marcel

**Comment by armab** [comment]
Thanks @winem for more questions to clarify this.

I'm closing the issue due to no response and no instructions to reproduce.
@srimandaleeka01 feel free to re-open and provide more details if it's still an actual issue for you.
