### ISSUE TITLE
ImportError: No module named st2common.util.shell when run linux.service

### ISSUE THREAD

**Issue by dove-young** [StackStorm/st2#5004]
## SUMMARY

Provide a quick summary of your bug report.

```
st2 run linux.service service=mongod act=restart hosts=agentavtone-worker1
...
id: 5f191803f06137c07014deb3
action.ref: linux.service
context.user: st2admin
parameters:
  act: restart
  hosts: agentavtone-worker1
  service: mongod
status: failed
start_timestamp: Thu, 23 Jul 2020 04:54:27 UTC
end_timestamp: Thu, 23 Jul 2020 04:54:33 UTC
result:
  agentavtone-worker1:
    failed: true
    return_code: 1
    stderr: "0: 2 windows (created Thu Jul  9 00:06:22 2020)
1: 1 windows (created Tue Jul 21 20:58:59 2020)
Traceback (most recent call last):
  File "/tmp/5f191803f06137c07014deb2/service.py", line 23, in <module>
    from st2common.util.shell import quote_unix
ImportError: No module named st2common.util.shell"
    stdout: ''
    succeeded: false

```

### STACKSTORM VERSION

Paste the output of ``st2 --version``:

st2 3.2.0, on Python 2.7.5

##### OS, environment, install method

Post what OS you are running this on, along with any other relevant information/

- e.g. Docker, Vagrant, Kubernetes, etc. Describe how you installed ST2
- e.g. one-line install, custom install, etc -->

one-line install 

## Steps to reproduce the problem

Show how to reproduce the problem, using a minimal test-case. Make sure to include any content
(pack content - workflows, actions, etc.) which are needed to reproduce the problem.

## Expected Results

What did you expect to happen when running the steps above?

## Actual Results

What happened? What output did you get?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by dove-young** [comment]
I've tried to create virtualenv for linux pack `st2 run packs.setup_virtualenv packs=linux`,  then I did these steps to debug

```
cd /opt/stackstorm/virtualenvs/linux
source bin/activate
python

>>> from st2common.util.shell import quote_unix
```

I found `oslo_config` is missing, then I installed it via 

```
source bin/activate
bin/pip install oslo_config
```

then import `st2common.util.shell` in python works

```
python

>>> from st2common.util.shell import quote_unix
```

Then I ran `st2ctl restart` and `st2ctl reload --register-all`, But `st2 run linux.service service=mongod act=restart hosts=agentavtone-worker1` still falied.

**Comment by winem** [comment]
Hi @dove-young, I ran into the same issue. 

Can you run the action again and set the `env` parameter to `{"PYTHONPATH":"/opt/stackstorm/st2/lib/python3.6/site-packages"}` and share the result? This fixes the error you mentioned but at least on CentOS8 and Ubuntu 18.04 with 3.6 I end up in another error :
```
Traceback (most recent call last):
  File "/tmp/5f52b36dfb971c6fc0ef9ca9/service.py", line 23, in <module>
    from st2common.util.shell import quote_unix
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/shell.py", line 30, in <module>
    subprocess = concurrency.get_subprocess_module()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/concurrency.py", line 72, in get_subprocess_module
    from eventlet.green import subprocess  # pylint: disable=import-error
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/eventlet/__init__.py", line 10, in <module>
    from eventlet import convenience
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/eventlet/convenience.py", line 4, in <module>
    from eventlet import greenpool
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/eventlet/greenpool.py", line 4, in <module>
    from eventlet import queue
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/eventlet/queue.py", line 49, in <module>
    from eventlet.event import Event
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/eventlet/event.py", line 3, in <module>
    from eventlet import hubs
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/eventlet/hubs/__init__.py", line 6, in <module>
    from eventlet import patcher
ImportError: cannot import name patcher
```

Would be interesting to know if it works for you if you use any other distribution. 

Cheers,
Marcel

**Comment by winem** [comment]
This will be fixed by #5035

**Comment by minsis** [comment]
I dont know if I should add to this or create a new bug but it seems maybe related.

Basically linux.service doesn't even work on the remote end (Oracle 7) because the tmp file it creates isn't found to execute for some reason. I also tried this with a specific directory with the same results. Not sure what other information I can provide here as far as debugging it goes.

![image](https://user-images.githubusercontent.com/11248197/107564682-56cec000-6ba8-11eb-979c-6a1644901ce7.png)

**Comment by blag** [comment]
I don't understand how `linux.service` was ever supposed to work in the first place.

It's a `remote-shell-script`, so the Python file gets copied to the target system and is then executed from there. But the `service.py` file contains this import:

```python
from st2common.util.shell import quote_unix
```

That import means that the only way that would ever work is if the target system is a StackStorm instance _and_ the script was copied over into the right place within the target's ST2 virtualenv and executed from there. And that seems like such a narrow use case that it will basically never be useful to anybody.

@Kami You authored #4675 which contains [this import](https://github.com/StackStorm/st2/pull/4675/files#diff-4a96aceee094fe269a0870ddc7a0bde7a955be247cdadb9c60f14b9c0c08e525R23), can you give us your thoughts on this?

Adding tests for `linux` pack actions is definitely something that would be a relatively easy-ish to contribute, and would provide an immediate benefit. I've added it to the [wiki page on easy contributions](https://github.com/StackStorm/st2/wiki/Easy-improvements-for-new-contributors), hopefully we can onboard somebody with that.

**Comment by Kami** [comment]
That's a good question.

It's been far too long so I forget the original reasoning and details (well, I remember the reasoning for the actual change - to prevent possible shell injections aka security fix), it could very well be, that it never worked or it was never executed outside the context of localhost (but as you said, even then I don't think it should work since that package would not be available in ``PYTHONPATH``).

Although I'm also like 80% that we definitely did use that action in multiple places in the past in our infra, etc.

**Comment by blag** [comment]
Yeah, I can definitely see that action being useful to us in the past.

I can't find any use of that in the current `master` branches of our [st2ci](https://github.com/StackStorm/st2ci) or [st2cd](https://github.com/StackStorm/st2cd) repos, so I don't think we use it anymore.

**Comment by minsis** [comment]
Looks liek [restart_component](https://github.com/StackStorm/st2/blob/master/contrib/packs/actions/restart_component.yaml) would be for restarting any st2 service, so not sure what came first.

Looking around I dont really see where linux.service is supposed to execute, locally or remotely. I'm still trying to get familiar with the project in general.
