### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get' in mask_secrets in rule.py

### ISSUE THREAD

**Issue by dove-young** [StackStorm/st2#5014]
## SUMMARY

Provide a quick summary of your bug report.

### STACKSTORM VERSION

Paste the output of ``st2 --version``:

st2 3.2.0, on Python 2.7.5

##### OS, environment, install method

Post what OS you are running this on, along with any other relevant information/

RHEL 7.6  one-line install

## Steps to reproduce the problem

Show how to reproduce the problem, using a minimal test-case. Make sure to include any content
(pack content - workflows, actions, etc.) which are needed to reproduce the problem.

- install slack pack and define a rule to trigger `slack.message` trigger. 
- found error messages in `st2rulesengine.log`

```
2020-08-05 19:58:53,324 139647545789008 ERROR traceback [-] Traceback (most recent call last):

2020-08-05 19:58:53,325 139647545789008 ERROR traceback [-]   File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit

2020-08-05 19:58:53,325 139647545789008 ERROR traceback [-]     msg = self.format(record)

2020-08-05 19:58:53,326 139647545789008 ERROR traceback [-]   File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format

2020-08-05 19:58:53,326 139647545789008 ERROR traceback [-]     return fmt.format(record)

2020-08-05 19:58:53,326 139647545789008 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 176, in format

2020-08-05 19:58:53,327 139647545789008 ERROR traceback [-]     attributes = self._format_extra_attributes(attributes=attributes)

2020-08-05 19:58:53,327 139647545789008 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 151, in _format_extra_attributes

2020-08-05 19:58:53,328 139647545789008 ERROR traceback [-]     value = serialize_object(obj=value)

2020-08-05 19:58:53,329 139647545789008 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/formatters.py", line 65, in serialize_object

2020-08-05 19:58:53,329 139647545789008 ERROR traceback [-]     value = obj.to_serializable_dict(mask_secrets=True)

2020-08-05 19:58:53,330 139647545789008 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/stormbase.py", line 105, in to_serializable_dict

2020-08-05 19:58:53,330 139647545789008 ERROR traceback [-]     serializable_dict = self.mask_secrets(value=serializable_dict)

2020-08-05 19:58:53,330 139647545789008 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/db/rule.py", line 137, in mask_secrets

2020-08-05 19:58:53,331 139647545789008 ERROR traceback [-]     action_ref = result.get('action', {}).get('ref', None)

2020-08-05 19:58:53,331 139647545789008 ERROR traceback [-] AttributeError: 'str' object has no attribute 'get'

2020-08-05 19:58:53,331 139647545789008 ERROR handlers [-] Logged from file filter.py, line 94
```
- add trace log in `rule.py`
```
       LOG.info('result in rule.py is %s - %s' % (type(result), result))
        LOG.info("result.get('action', {}) is %s = %s " % ( type(result.get('action', {})), result.get('action', {})))
```
- found that return value of `result.get('action', {})` is `str`

```
2020-08-05 19:53:08,139 140298075175504 INFO rule [-] result.get('action', {}) is <type 'str'> = ActionExecutionSpecDB@140298075004112(ref="slack.post_message", parameters="{u'debug': True, u'content_v
ersion': u'#test', u'message': u'test message to trigger', u'log_level': u'DEBUG', u'username': u'classic'}")
```

## Expected Results

What did you expect to happen when running the steps above?

## Actual Results

What happened? What output did you get?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by dove-young** [comment]
more trace log here

```
2020-08-05 19:53:08,121 140298075175504 DEBUG rules [-] Querying rules with trigger slack.message
2020-08-05 19:53:08,126 140298075175504 INFO engine [-] Found 1 rules defined for trigger slack.message

2020-08-05 19:53:08,128 140298075175504 INFO rule [-] result in rule.py is <type 'dict'> - {'description': None, 'tags': [], 'ref': u'slack.slack_messages', 'enabled': True, 'name': u'slack_messages',
'trigger': u'slack.message', 'metadata_file': u'', 'context': {u'user': u'st2admin'}, 'criteria': {u'trigger.channel': {u'pattern': u'"name": "hubot-test-icam"', u'type': u'contains'}}, 'action': 'Acti
onExecutionSpecDB@140298075004112(ref="slack.post_message", parameters="{u\'debug\': True, u\'content_version\': u\'#test\', u\'message\': u\'test message to trigger\', u\'log_level\': u\'DEBUG\', u\'u
sername\': u\'classic\'}")', 'pack': u'slack', 'type': 'RuleTypeSpecDB@140298075004368(ref="standard", parameters="{}")', 'id': '5f2ac642d8fdef7d62a355e2', 'uid': u'rule:slack:slack_messages'}
2020-08-05 19:53:08,129 140298075175504 INFO rule [-] result.get('action', {}) is <type 'str'> = ActionExecutionSpecDB@140298075004112(ref="slack.post_message", parameters="{u'debug': True, u'content_v
ersion': u'#test', u'message': u'test message to trigger', u'log_level': u'DEBUG', u'username': u'classic'}")

2020-08-05 19:53:08,138 140298075175504 INFO rule [-] result in rule.py is <type 'dict'> - {'description': None, 'tags': [], 'ref': u'slack.slack_messages', 'enabled': True, 'name': u'slack_messages',
'trigger': u'slack.message', 'metadata_file': u'', 'context': {u'user': u'st2admin'}, 'criteria': {u'trigger.channel': {u'pattern': u'"name": "hubot-test-icam"', u'type': u'contains'}}, 'action': 'Acti
onExecutionSpecDB@140298075004112(ref="slack.post_message", parameters="{u\'debug\': True, u\'content_version\': u\'#test\', u\'message\': u\'test message to trigger\', u\'log_level\': u\'DEBUG\', u\'u
sername\': u\'classic\'}")', 'pack': u'slack', 'type': 'RuleTypeSpecDB@140298075004368(ref="standard", parameters="{}")', 'id': '5f2ac642d8fdef7d62a355e2', 'uid': u'rule:slack:slack_messages'}

2020-08-05 19:53:08,139 140298075175504 INFO rule [-] result.get('action', {}) is <type 'str'> = ActionExecutionSpecDB@140298075004112(ref="slack.post_message", parameters="{u'debug': True, u'content_v
ersion': u'#test', u'message': u'test message to trigger', u'log_level': u'DEBUG', u'username': u'classic'}")

2020-08-05 19:53:08,127 140298075175504 INFO filter [-] Trigger payload type: <class 'st2common.models.db.trigger.TriggerInstanceDB'> (trigger_instance={'status': 'processing', 'occurrence_time': '2020
-08-06 02:53:08.079018+00:00', 'trigger': u'slack.message', 'id': '5f2b7094f7b6ca35b5733de6', 'payload': {u'timestamp': 1596682363, u'text': u'result.get(\u2018action\u2019, {})', u'user': {u'first_nam
e': u'David', u'last_name': u'Yang', u'is_owner': True, u'name': u'dove.young', u'is_bot': False, u'real_name': u'David Yang', u'is_admin': True, u'id': u'USF73Q1RV'}, u'channel': {u'topic': u'what is
a topic', u'is_group': False, u'id': u'CSDBKG7BP', u'name': u'hubot-test-icam'}, u'timestamp_raw': u'1596682363.013100'}},rule={'description': None, 'tags': [], 'type': 'RuleTypeSpecDB@140298075004368(
ref="standard", parameters="{}")', 'enabled': True, 'trigger': u'slack.message', 'metadata_file': u'', 'context': {u'user': u'st2admin'}, 'criteria': {u'trigger.channel': {u'pattern': u'"name": "hubot-
test-icam"', u'type': u'contains'}}, 'action': 'ActionExecutionSpecDB@140298075004112(ref="slack.post_message", parameters="{u\'debug\': True, u\'content_version\': u\'#test\', u\'message\': u\'test me
ssage to trigger\', u\'log_level\': u\'DEBUG\', u\'username\': u\'classic\'}")', 'uid': u'rule:slack:slack_messages', 'pack': u'slack', 'ref': u'slack.slack_messages', 'id': '5f2ac642d8fdef7d62a355e2',
 'name': u'slack_messages'},trigger={'description': None, 'parameters': {}, 'ref': u'slack.message', 'ref_count': 0, 'metadata_file': None, 'uid': u'trigger:slack:message:99914b932bd37a50b983c5e7c90ae9
3b', 'pack': u'slack', 'type': u'slack.message', 'id': '5f190dec714f1d963f514c99', 'name': u'message'})

2020-08-05 19:53:08,146 140298075175504 INFO rule [-] result in rule.py is <type 'dict'> - {'description': None, 'tags': [], 'ref': u'slack.slack_messages', 'enabled': True, 'name': u'slack_messages',
'trigger': u'slack.message', 'metadata_file': u'', 'context': {u'user': u'st2admin'}, 'criteria': {u'trigger.channel': {u'pattern': u'"name": "hubot-test-icam"', u'type': u'contains'}}, 'action': 'Acti
onExecutionSpecDB@140298075004112(ref="slack.post_message", parameters="{u\'debug\': True, u\'content_version\': u\'#test\', u\'message\': u\'test message to trigger\', u\'log_level\': u\'DEBUG\', u\'u
sername\': u\'classic\'}")', 'pack': u'slack', 'type': 'RuleTypeSpecDB@140298075004368(ref="standard", parameters="{}")', 'id': '5f2ac642d8fdef7d62a355e2', 'uid': u'rule:slack:slack_messages'}
2020-08-05 19:53:08,146 140298075175504 INFO rule [-] result.get('action', {}) is <type 'str'> = ActionExecutionSpecDB@140298075004112(ref="slack.post_message", parameters="{u'debug': True, u'content_v
ersion': u'#test', u'message': u'test message to trigger', u'log_level': u'DEBUG', u'username': u'classic'}")

```

**Comment by nmaludy** [comment]
@dove-young this has already been fixed in master here https://github.com/StackStorm/st2/pull/4952

Thanks for the report.
