### ISSUE TITLE
Rule log raises exception

### ISSUE THREAD

**Issue by nzlosh** [StackStorm/st2#5046]
## SUMMARY

Python exception is being raised when writing validation log entry.

### STACKSTORM VERSION

`st2 3.2.0, on Python 3.6.9`

##### OS, environment, install method

*one-liner installation*

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

mongo --version
MongoDB shell version v4.0.20
git version: e2416422da84a0b63cde2397d60b521758b56d1b
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1804
    distarch: x86_64
    target_arch: x86_64

{rabbit,"RabbitMQ","3.6.10"},
```

## Steps to reproduce the problem

Configure any rule and then send a trigger (a webhook rule and call it with curl or whatever)

## Expected Results

A log line entry should be produced, something along the lines of  `Validating rule rule.ref for trigger.name.`

## Actual Results

An exception is raised when attempting to create the log entry.

```
--- Logging error ---

Traceback (most recent call last):

File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/logging/formatters.py", line 176, in format
    attributes = self._format_extra_attributes(attributes=attributes)
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/logging/formatters.py", line 151, in _format_extra_attributes
    value = serialize_object(obj=value)
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/logging/formatters.py", line 65, in serialize_object
    value = obj.to_serializable_dict(mask_secrets=True)
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/models/db/stormbase.py", line 113, in to_serializable_dict
    serializable_dict = self.mask_secrets(value=serializable_dict)
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/models/db/rule.py", line 126, in mask_secrets
    action_ref = result.get('action', {}).get('ref', None)

AttributeError: 'str' object has no attribute 'get'


Call stack:

File "/opt/stackstorm/st2/lib/python3.6/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/transport/consumers.py", line 71, in _process_message
    self._handler.process(body)
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/rules/worker.py", line 88, in process
    self.rules_engine.handle_trigger_instance(trigger_instance)
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/rules/engine.py", line 33, in handle_trigger_instance
    matching_rules = self.get_matching_rules_for_trigger(trigger_instance)
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/rules/engine.py", line 64, in get_matching_rules_for_trigger
    matching_rules = matcher.get_matching_rules()
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/rules/matcher.py", line 38, in get_matching_rules
    matched_rules = [rule_filter.rule for rule_filter in rule_filters if rule_filter.filter()]
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/rules/matcher.py", line 38, in <listcomp>
    matched_rules = [rule_filter.rule for rule_filter in rule_filters if rule_filter.filter()]
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/rules/filter.py", line 72, in filter
    extra=self._base_logger_context)
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/log.py", line 105, in func_wrapper
    return func(*args, **kwargs)

Message: 'Validating rule %s for %s.'
Arguments: ('rule.ref', 'cdab03c8-66b0-4048-80d4-49447bb68e55')

0 rule(s) found to enforce for cdab03c8-66b0-4048-80d4-49447bb68e55.
Matched 0 rule(s) for trigger_instance 5f6cc7cb869f226c5124431c (trigger=core.cdab03c8-66b0-4048-80d4-49447bb68e55)
No matching rules found for trigger instance 5f6cc7cb869f226c5124431c.
```

I've done a bit of preliminary work to track down the error, the exception originates from here.
```
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/models/db/rule.py", line 126, in mask_secrets
    action_ref = result.get('action', {}).get('ref', None)

AttributeError: 'str' object has no attribute 'get'
```

After adding a debug state it appers the `result` variable is a dictionary that has an `action` key but the value of the key is a string.  Which explains the exception but I haven't been able to tell what the correct handling of this value should be.

```
[<class 'dict'>]
{
	'action': 'ActionExecutionSpecDB@139952368084816(ref="core.local", parameters="{\'cmd\': \'echo {{ payload.host }}\'}")',
	'context': {},
	'criteria': {
		'payload.state': {
			'type': 'equals',
			'pattern': 1.0
		},
		'payload.state_type': {
			'type': 'equals',
			'pattern': 0.0
		},
		'payload.vars_after.attempt': {
			'type': 'equals',
			'pattern': 1.0
		}
	},
	'description': 'Test rule.',
	'enabled': True,
	'id': '5e4d746538b7e5675d3e70ce',
	'metadata_file': 'rules/test_action.yaml',
	'name': 'test_action',
	'pack': 'test_pack',
	'ref': 'test_pack.test_action',
	'tags': [],
	'trigger': 'icinga2.event.state_change',
	'type': 'RuleTypeSpecDB@139952368085176(ref="standard", parameters="{}")',
	'uid': 'rule:test_pack:test_action'
}
```

**Comment by nmaludy** [comment]
@nzlosh fixed here: https://github.com/StackStorm/st2/pull/4952
