### ISSUE TITLE
st2web constant int convertion 

### ISSUE THREAD

**Issue by DavidMeu** [StackStorm/st2#5232]
I enter a number (as str) but in constantly converts it to int,
Why is that? Anyway to WA that?

```
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2api/controllers/v1/actionexecutions.py", line 141, in _handle_schedule_execution
    action_db=action_db)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2api/controllers/v1/actionexecutions.py", line 193, in _schedule_execution
    liveaction_db.context)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/param.py", line 312, in render_live_params
    live_params = _cast_params_from(params, context, [action_parameters, runner_parameters])
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/param.py", line 245, in _cast_params_from
    result[name] = _cast(context[name], param_schema)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/param.py", line 76, in _cast
    return cast(v)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/casts.py", line 72, in _cast_string
    raise ValueError(msg)
ValueError: Value "23423" must either be a string or None. Got "int".
```

**Comment by blag** [comment]
> Anyway to WA that?

What does "WA" mean?

What does your action alias look like?

What does the action that the alias is trying to call look like?

Please fill out the bug report template when reporting your issue. If you follow the template and answer all of those questions it will give us the information we need to help you. If you don't follow the template then we have to ask all of these questions to you, which slows the whole process down.

**Comment by DavidMeu** [comment]
> 'What does "WA" mean?'
WA means workaround.
As I can't fins a way to pass it as a 'pure str'.

> 'What does your action alias look like?'
Not sure what you mean by 'action alias'
action which gets a single str param (Though it doesn't even get's triggeres due to the exception I attached).

> 'Please fill out the bug report template when reporting your issue.'
I'm not sure this is a bug.

**Comment by blag** [comment]
> I'm not sure this is a bug.

It might be, it might not be. Please fill it out either way. It's okay to report something as a bug when you can't get it to work. We need the same information whether we are solving a bug or just helping you get things working, so filling out the issue template for a bug will guide you through the process to give us the information we need to help you.

> Not sure what you mean by 'action alias'

https://docs.stackstorm.com/chatops/aliases.html

What ChatOps alias are you running? Post that metadata YAML file here please.

What chat provider are you using (Slack, Mattermost, MS Teams, etc.)?

What action are you trying to run? Post it's metadata YAML file here please.

It's impossible to help you give the information you have supplied so far. Saying something doesn't work when you "put in" data doesn't tell us _what you are putting data into_. You need to post the files I've asked for in order for us to get enough context to help you.

**Comment by DavidMeu** [comment]
Probably the term **ChatOps** I;m refering to is not accurate.

The yaml:
```
---
pack: some pack
enabled: true
runner_type: orquesta
name: some_action_cli
description: Command line to run.
entry_point: workflows/_GEN_ some_action_cli.yaml
tags:
- name: command
  value: 'true'
parameters:
  metadata:
    type: object
    description: command metadata
    required: true
  some_id:
    type: string
    description: A single some id to run.
    required: true
    position: 1
```


Then trying to run that action cli like:
![image](https://user-images.githubusercontent.com/35102691/115137676-208e4080-a030-11eb-9fef-8ec863e0bc18.png)
Or:
![image](https://user-images.githubusercontent.com/35102691/115137699-3bf94b80-a030-11eb-89b2-804bd93fb736.png)

And recieving the err above.

**Comment by blag** [comment]
If you're running this via a chat provider, like Slack, Mattermost, or MS Teams, then that would be related to ChatOps.

If you're running this via the web interface, that wouldn't be related to ChatOps.

If you're running this in a terminal/command prompt somewhere, that likely wouldn't be related to ChatOps either. Are you using the built-in `st2` command or something else?

What version of StackStorm are you running? Run `st2 --version` in the CLI to find out and post the result here please.

**Comment by DavidMeu** [comment]
Probably web interface is the matching term.
![image](https://user-images.githubusercontent.com/35102691/115138363-59c8af80-a034-11eb-862f-5219c5a8e7cb.png)

**Comment by blag** [comment]
That's a really old version of StackStorm! We just released v3.4 in March, and all of the previous enterprise-only addons (LDAP, RBAC, EWC) are now free, open source, and installed by default. Please consider upgrading. We might have fixed your problem since then.

Can you post a screenshot of the values you're trying to pass to the action in the web interface? And post the full error log (but feel free to redact any sensitive information like passwords, API keys or tokens, secret data, etc.) if you can.

For the error log, you can use [GitHub Flavored Markdown](https://github.github.com/gfm/#example-89) to format the text that you paste instead of posting a screenshot of that.

**Comment by DavidMeu** [comment]
CLI cmd:
`/some_action_cli  --some_id='1'`

Full log:
```
2021-04-18 08:23:40,415 ERROR [-] Unable to execute action.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2api/controllers/v1/actionexecutions.py", line 141, in _handle_schedule_
execution
    action_db=action_db)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2api/controllers/v1/actionexecutions.py", line 193, in _schedule_executi
on
    liveaction_db.context)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/param.py", line 312, in render_live_params
    live_params = _cast_params_from(params, context, [action_parameters, runner_parameters])
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/param.py", line 245, in _cast_params_from
    result[name] = _cast(context[name], param_schema)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/param.py", line 76, in _cast
    return cast(v)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/casts.py", line 72, in _cast_string
    raise ValueError(msg)
ValueError: Value "1" must either be a string or None. Got "int".
2021-04-18 08:23:40,415 ERROR [-] Failed to call controller function "post" for operation "st2api.controllers.v1.actionexecutions:
action_executions_controller.post": Value "1" must either be a string or None. Got "int".
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2api/controllers/v1/actionexecutions.py", line 141, in _handle_schedule_
execution
    action_db=action_db)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2api/controllers/v1/actionexecutions.py", line 193, in _schedule_executi
on
    liveaction_db.context)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/param.py", line 312, in render_live_params
    live_params = _cast_params_from(params, context, [action_parameters, runner_parameters])
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/param.py", line 245, in _cast_params_from
    result[name] = _cast(context[name], param_schema)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/param.py", line 76, in _cast
    return cast(v)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/casts.py", line 72, in _cast_string
    raise ValueError(msg)
ValueError: Value "1" must either be a string or None. Got "int".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/router.py", line 515, in __call__
    resp = func(**kw)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2api/controllers/v1/actionexecutions.py", line 565, in post
    show_secrets=show_secrets)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2api/controllers/v1/actionexecutions.py", line 144, in _handle_schedule_
execution
    abort(http_client.BAD_REQUEST, six.text_type(e))
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/router.py", line 77, in abort
    raise exc.status_map[status_code](message)
webob.exc.HTTPBadRequest: Value "1" must either be a string or None. Got "int".
2021-04-18 08:23:40,416 INFO [-] f151e470-cbd7-46bb-87a5-9ac16def804c - 400 82 18.72ms (method='POST',path='/v1/executions',remote
_addr='10.244.2.95',status=400,runtime=18.72,content_length=82,request_id='f151e470-cbd7-46bb-87a5-9ac16def804c')
```

**Comment by DavidMeu** [comment]
Not an issue
