### ISSUE TITLE
Can't assign pattern in rule criteria from datastore

### ISSUE THREAD

**Issue by DavidMeu** [StackStorm/st2#5260]
## SUMMARY

While trying to assign a pattern to criteria:
i.e:
```
criteria:
  trigger.body.some_field:
    type: icontains
    pattern:  "{{ st2kv.system.some_ds_dict | decrypt_kv | st2kv.system.some_ds_dict.get('some_ds_dict_key') }}"
```
Also tried just:
` "{{ st2kv.system.some_str_from_ds }}" `

Docs example is'nt working as well:
```
criteria:
    trigger.payload.build_number:
        type: "equals"
        pattern : "{{ st2kv.system.current_build_number }}"
```

Recieved:
`Object of type 'KeyValueLookup' is not JSON serializable`
Full traceback:
```
2021-05-10 12:05:33,521 ERROR [-] Failed to render pattern value "{{ st2kv.system.name }}" for key "trigger.body.sour
ce"
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/rules/filter.py", line 128, in _check_criterion
    criteria_context=payload_lookup.context
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/rules/filter.py", line 206, in _render_criteria_pattern
    context=criteria_context
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/templating.py", line 72, in render_template_with_system_
context
    rendered = render_template(value=value, context=context)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/templating.py", line 47, in render_template
    rendered = template.render(context)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/expressions/functions/data.py", line 106, in to_complex
    return json.dumps(value)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'KeyValueLookup' is not JSON serializable
```
### STACKSTORM VERSION

`st2 3.1.0, on Python 3.6.9`

seems related to:
https://github.com/StackStorm/st2/issues/4043

@bigmstone 
Saw you are related to that issue, any hints on how to resolve that/any workaround?
(I now that in action params in rule it manages to fetch ds values with no issues so maybe it's good to take that as reference)

**Comment by amanda11** [comment]
StackStorm 3.4 release.

Investiated if same on 3.4. Same error when just set the key to a string value and with set_object with JSON objects.

**Comment by DavidMeu** [comment]
Found a WA for that:
In ds:
`st2 key set some_key '"some_str"'`
In rule pattern:
`"{{ st2kv.system.some_key | from_json_string }}"`

**Comment by Kami** [comment]
Did we ever support this notation for rule pattern attribute? If not, it's probably more of a feature request.

From a high level, implementing this feature shouldn't be too hard - we just need to ensure we use correct Jinja context where we render that value (+ tests, docs, etc.).

There are a couple of things we need to be careful with though - notably "user" scoped datastore items. We had discussions on this in the past (aka determining / inferring "user" for a specific trigger instance and rule invocation), but I don't remember if anything came out of it.

Worst case, every rule is just "scoped" to ``stanley`` user (which should be a good and a safe default, likely something which is already the case right now).

**Comment by DavidMeu** [comment]
Eventually this workaround helped:

> "When accessing numbers, integers, objects and arrays in an Action Definition file, utilizing the from_json_string filter is NOT necessary. For more information on accessing key-value pairs from Actions see: Referencing Key-Value Pairs in Action Definitions
> Accessing numbers, integers, objects and arrays in other places, such as workflows, utilizing from_json_string is still necessary."

https://docs.stackstorm.com/reference/jinja.html#referencing-datastore-keys-in-jinja

**Comment by skiedude** [comment]
For those who may find this issue at some later day, if the kv you're trying to pull from the datastore is a simple string, the default example in the docs will still fail. You can however get it to work by using the `string()` jinja filter.
```
criteria:
    trigger.payload.build_number:
        type: "equals"
        pattern : "{{ st2kv.system.current_build_name | string() }}"
```
