### ISSUE TITLE
login fail  ERROR: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by heruosong** [StackStorm/st2#5272]
#st2 --debug  login st2admin -p 'Ch@ngeMe'
# -------- begin 140218091069512 request ----------
curl -X POST -H  'User-Agent: python-requests/2.23.0' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'Connection: keep-alive' -H  'content-type: application/json' -H  'Content-Length: 2' -H  'Authorization: Basic c3QyYWRtaW46Q2hAbmdlTWU=' --data-binary '{}' http://127.0.0.1:9100/tokens
# -------- begin 140218091069512 response ----------
<html>
                        <head><title>Node Exporter</title></head>
                        <body>
                        <h1>Node Exporter</h1>
                        <p><a href="/metrics">Metrics</a></p>
                        </body>
                        </html>
# -------- end 140218091069512 response ------------

ERROR: Expecting value: line 1 column 1 (char 0)

CLI settings:
----------------
Config file path: /root/.st2/config
Client settings:
----------------
ST2_BASE_URL: http://127.0.0.1
ST2_AUTH_URL: http://127.0.0.1:9100
ST2_API_URL: http://127.0.0.1:9101/v1
ST2_STREAM_URL: http://127.0.0.1:9102/v1
ST2_AUTH_TOKEN: None

Proxy settings:
---------------
HTTP_PROXY:
HTTPS_PROXY:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/shell.py", line 408, in run
    func(args)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/commands/auth.py", line 154, in run_and_print
    self.run(args, **kwargs)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/commands/auth.py", line 125, in run
    manager = self.manager.create(instance, auth=(args.username, args.password), **kwargs)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/models/core.py", line 42, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/models/core.py", line 309, in create
    instance = self.resource.deserialize(response.json())
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by nzlosh** [comment]
You are running Prometheus node exporter on the same host as StackStorm.  Both of these programs use TCP/9100.  You will need to adjust the settings of one of them to stop using the same port.
