### ISSUE TITLE
two equals == is being interpreted as a key/value pair by the StackStorm API.

### ISSUE THREAD

**Issue by minifygb** [StackStorm/st2#5274]
## SUMMARY

Provide a quick summary of your bug report.

### STACKSTORM VERSION

latest using docker tag
##### OS, environment, install method

docker 
## Steps to reproduce the problem

Show how to reproduce the problem, using a minimal test-case. Make sure to include any content
(pack content - workflows, actions, etc.) which are needed to reproduce the problem.

## Expected Results

input string two or more equals not to be parsed as key/value, just string

## Actual Results

It seems the == is being interpreted as a key/value pair by the StackStorm API.

12:38 PM
!st2 licensing request json data 111==

12:38 PM
storm-trooper-bot-devAPP Additional properties are not allowed ('111' was unexpected)
Failed validating 'additionalProperties' in schema:
   {'additionalProperties': False,
    'description': 'Execute Composer Licensing actions chained flow',
    'properties': {'display_published': {'default': True,
                                         'description': 'Intermediate '
                                                        'published '
                                                        'variables will '
                                                        'be stored and '
                                                        'displayed.',
                                         'type': 'boolean'},
                   'request': {'description': 'Composer Licensing request',
                               'required': True,
                               'type': 'string'},
                   'skip_notify': {'default': ['get_user',
                                               'failure_get_user_msg',
                                               'composer_licensing_failure_msg',
                                               'composer_licensing_action_process'],
                                   'description': 'List of tasks to skip '
                                                  'notifications for.',
                                   'type': 'array'}},
    'title': 'composer_licensing',
    'type': 'object'}
On instance:
   {'111': '=',
    'display_published': True,
    'request': 'request json data',
    'skip_notify': ['get_user',
                    'failure_get_user_msg',
                    'composer_licensing_failure_msg',
                    'composer_licensing_action_process']}

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by nzlosh** [comment]
To be clear, this issue was encountered using err-stackstorm, but stems from StackStorm's action-alias processing.  Here is an example of the problem using st2client:

```
st2 --debug action-alias execute 'licensing base64string=='
# -------- begin 140444889842464 request ----------
curl -X POST -H  'User-Agent: python-requests/2.25.1' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'Connection: keep-alive' -H  'X-Auth-Token: c07e53483425401a
a3ac4a26cf1902cb' -H  'content-type: application/json' -H  'Content-Length: 76' --data-binary '{"command": "licensing base64string==", "user": "", "source_channel": "cli"}'
http://127.0.0.1:9101/v1/aliasexecution/match_and_execute
# -------- begin 140444889842464 response ----------
{"faultstring":"Additional properties are not allowed ('base64string' was unexpected)\n\nFailed validating 'additionalProperties' in schema:\n    {'additionalProperties': False,\n     'description': 'Double equals from chatops test',\n     'properties': {'display_published': {'default': True,\n                                          'description': 'Intermediate '\n                                                         'published '\n                                                         'variables will '\n                                                      'be stored and '\n                                                         'displayed.',\n             'type': 'boolean'},\n                    'opt1': {'default': 'opt1',\n                             'required': False,\n                             'type': 'string'},\n                    'opt2': {'default': 'opt2',\n                             'required': False,\n                             'type': 'string'},\n  'request': {'required': True, 'type': 'string'},\n                    'skip_notify': {'default': [],\n                                    'description': 'List of tasks toskip '\n                                                   'notifications for.',\n                                    'type': 'array'}},\n     'title': 'double_equals',\n  'type': 'object'}\n\nOn instance:\n    {'base64string': '=',\n     'display_published': True,\n     'opt1': 'opt1',\n     'opt2': 'opt2',\n     'request': 'help',\n     'skip_notify': []}"}
# -------- end 140444889842464 response ------------

ERROR: 400 Client Error: Bad Request
MESSAGE: Additional properties are not allowed ('base64string' was unexpected)

Failed validating 'additionalProperties' in schema:
    {'additionalProperties': False,
     'description': 'Double equals from chatops test',
     'properties': {'display_published': {'default': True,
                                          'description': 'Intermediate '
                                                         'published '
                                                         'variables will '
                                                         'be stored and '
                                                         'displayed.',
                                          'type': 'boolean'},
                    'opt1': {'default': 'opt1',
                             'required': False,
                             'type': 'string'},
                    'opt2': {'default': 'opt2',
                             'required': False,
                             'type': 'string'},
                    'request': {'required': True, 'type': 'string'},
                    'skip_notify': {'default': [],
                                    'description': 'List of tasks to skip '
                                                   'notifications for.',
                                    'type': 'array'}},
     'title': 'double_equals',
     'type': 'object'}

On instance:
    {'base64string': '=',
     'display_published': True,
     'opt1': 'opt1',
     'opt2': 'opt2',
     'request': 'help',
     'skip_notify': []} for url: http://127.0.0.1:9101/v1/aliasexecution/match_and_execute

CLI settings:
----------------
Config file path: /root/.st2/config
Client settings:
----------------
ST2_BASE_URL: http://127.0.0.1
ST2_AUTH_URL: http://127.0.0.1:9100
ST2_API_URL: http://127.0.0.1:9101/v1
ST2_STREAM_URL: http://127.0.0.1:9102/v1
ST2_AUTH_TOKEN: c07e53483425401aa3ac4a26cf1902cb

Proxy settings:
---------------
HTTP_PROXY:
HTTPS_PROXY:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/shell.py", line 473, in run
    func(args)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/commands/action_alias.py", line 170, in run_and_print
    execution = self.run(args, **kwargs)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/commands/resource.py", line 52, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/commands/action_alias.py", line 166, in run
    execution = alias_execution_mgr.match_and_execute(payload)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/models/core.py", line 42, in decorate
    return func(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/models/core.py", line 428, in match_and_execute
    self.handle_error(response)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/models/core.py", line 195, in handle_error
    response.raise_for_status()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request
MESSAGE: Additional properties are not allowed ('base64string' was unexpected)

Failed validating 'additionalProperties' in schema:
    {'additionalProperties': False,
     'description': 'Double equals from chatops test',
     'properties': {'display_published': {'default': True,
                                          'description': 'Intermediate '
                                                         'published '
                                                         'variables will '
                                                         'be stored and '
                                                         'displayed.',
                                          'type': 'boolean'},
                    'opt1': {'default': 'opt1',
                             'required': False,
                             'type': 'string'},
                    'opt2': {'default': 'opt2',
                             'required': False,
                             'type': 'string'},
                    'request': {'required': True, 'type': 'string'},
                    'skip_notify': {'default': [],
                                    'description': 'List of tasks to skip '
                                                   'notifications for.',
                                    'type': 'array'}},
     'title': 'double_equals',
     'type': 'object'}

On instance:
    {'base64string': '=',
     'display_published': True,
     'opt1': 'opt1',
     'opt2': 'opt2',
     'request': 'help',
     'skip_notify': []} for url: http://127.0.0.1:9101/v1/aliasexecution/match_and_execute
```
