### ISSUE TITLE
from lib import action   File "/opt/stackstorm/packs/aws/actions/lib/action.py", line 107     except Exception, e:                     ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by raghavendraDBA** [StackStorm/st2#5276]
## SUMMARY
st2 run command throwing syntax errors .

Provide a quick summary of your bug report.

### STACKSTORM VERSION

Paste the output of ``st2 --version``:

st2 --version
st2 3.4.1, on Python 3.6.13
##### OS, environment, install method

vagrant box
StackStorm v3.4.1 (Ubuntu 16.04 LTS GNU/Linux x86_64)
st2vagrant

## Steps to reproduce the problem

Show how to reproduce the problem, using a minimal test-case. Make sure to include any content
(pack content - workflows, actions, etc.) which are needed to reproduce the problem.

st2 pack install aws
updated aws.yml file with keys from IAM role

excuted st2 run aws.ec2_get_all_tags

## Expected Results

get list of ec2 tags

## Actual Results

st2 run aws.ec2_get_all_tags
.
id: 60b4be16a161a571fbd73de6
action.ref: aws.ec2_get_all_tags
context.user: st2admin
parameters: None
status: failed
start_timestamp: Mon, 31 May 2021 10:44:38 UTC
end_timestamp: Mon, 31 May 2021 10:44:39 UTC
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 238, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/loader.py", line 166, in register_plugin
    module = imp.load_source(module_name, plugin_abs_file_path)
  File "/opt/stackstorm/virtualenvs/aws/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/stackstorm/packs/aws/actions/run.py", line 1, in <module>
    from lib import action
  File "/opt/stackstorm/packs/aws/actions/lib/action.py", line 107
    except Exception, e:
                    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 334, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 192, in run
    action = self._get_action_instance()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 245, in _get_action_instance
    raise exc_cls(msg)
SyntaxError: Failed to load action class from file "/opt/stackstorm/packs/aws/actions/run.py" (action file most likely doesn't exist or contains invalid syntax): invalid syntax (action.py, line 107)

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 238, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/loader.py", line 166, in register_plugin
    module = imp.load_source(module_name, plugin_abs_file_path)
  File "/opt/stackstorm/virtualenvs/aws/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/stackstorm/packs/aws/actions/run.py", line 1, in <module>
    from lib import action
  File "/opt/stackstorm/packs/aws/actions/lib/action.py", line 107
    except Exception, e:
                    ^
SyntaxError: invalid syntax

"
  stdout: ''

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by nzlosh** [comment]
It appears you are using an old version of the aws pack that was written for Python2, but you are running the pack using Python3.  Python2 is no longer supported and all packs were updated for Python3.  You should upgrade your pack to the latest version (v2.0.0 at the time of writing).

As a side note: You should consider running StackStorm on a new version of Ubuntu as v3.5 of StackStorm will not be available on Ubuntu 16.04, only Ubuntu 18.04 and 20.04.

**Comment by raghavendraDBA** [comment]
`st2 pack install aws=2.0.0

        [ succeeded ] init_task
        [ succeeded ] download_pack
        [ succeeded ] make_a_prerun
        [ succeeded ] get_pack_dependencies
        [ succeeded ] check_dependency_and_conflict_list
        [ succeeded ] install_pack_requirements
        [ succeeded ] get_pack_warnings
        [ succeeded ] register_pack

+-------------+--------------------------------------------------------------+
| Property    | Value                                                        |
+-------------+--------------------------------------------------------------+
| ref         | aws                                                          |
| name        | aws                                                          |
| description | st2 content pack containing Amazon Web Services              |
|             | integrations.                                                |
| version     | 2.0.0                                                        |
| author      | StackStorm, Inc.                                             |
+-------------+--------------------------------------------------------------+`

able to clear that error 

st2 run aws.ec2_get_all_tags
.
id: 60b4e185a161a571fbd74c18
action.ref: aws.ec2_get_all_tags
context.user: st2admin
parameters: None
status: failed
start_timestamp: Mon, 31 May 2021 13:15:49 UTC
end_timestamp: Mon, 31 May 2021 13:15:51 UTC
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/runners/utils.py", line 134, in get_action_class_instance
    action_instance = action_cls(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'action_service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 334, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 192, in run
    action = self._get_action_instance()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 261, in _get_action_instance
    action_service=action_service)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/runners/utils.py", line 143, in get_action_class_instance
    action_instance = action_cls(**kwargs)
  File "/opt/stackstorm/packs/aws/actions/lib/action.py", line 67, in __init__
    self.account_id = self.session.client('sts').get_caller_identity().get('Account')
  File "/opt/stackstorm/virtualenvs/aws/lib/python3.6/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/stackstorm/virtualenvs/aws/lib/python3.6/site-packages/botocore/client.py", line 526, in _make_api_call
    operation_model, request_dict)
  File "/opt/stackstorm/virtualenvs/aws/lib/python3.6/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/stackstorm/virtualenvs/aws/lib/python3.6/site-packages/botocore/endpoint.py", line 166, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/opt/stackstorm/virtualenvs/aws/lib/python3.6/site-packages/botocore/endpoint.py", line 150, in create_request
    operation_name=operation_model.name)
  File "/opt/stackstorm/virtualenvs/aws/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/opt/stackstorm/virtualenvs/aws/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/opt/stackstorm/virtualenvs/aws/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/opt/stackstorm/virtualenvs/aws/lib/python3.6/site-packages/botocore/signers.py", line 147, in sign
    auth.add_auth(request)
  File "/opt/stackstorm/virtualenvs/aws/lib/python3.6/site-packages/botocore/auth.py", line 316, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
"
  stdout: ''

Unable to locate credentials is the location expected opt/stackstorm/aws/aws.yml not able to pick from there
