### ISSUE TITLE
please support redis + tls (rediss)

### ISSUE THREAD

**Issue by bkk-bcd** [StackStorm/st2#5352]
## SUMMARY

Redis with TLS not supported (rediss)

### STACKSTORM VERSION

Paste the output of ``st2 --version``:

```
$ st2 --version
st2 3.4.1, on Python 3.6.14
```

##### OS, environment, install method

Post what OS you are running this on, along with any other relevant information/

- e.g. Docker, Vagrant, Kubernetes, etc. Describe how you installed ST2
- e.g. one-line install, custom install, etc -->
Custom/Ansible

```
uname -a
Linux xxx 5.8.0-1042-aws #44~20.04.1-Ubuntu SMP Mon Aug 2 11:25:34 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

## Steps to reproduce the problem

add the following to `st2.conf`:

```
[coordination]
#local redis without tls enabled works fine...
#url = redis://127.0.0.1
url = rediss://:someredispassword@myredishost:6379
```

## Expected Results

What did you expect to happen when running the steps above?

`rediss` should work (ie TLS)

## Actual Results

What happened? What output did you get?

```
2021-09-05 17:38:46,483 140159477849888 WARNING named [-] Could not load rediss
2021-09-05 17:38:46,484 140159477849888 ERROR scheduler [-] (PID=1236037) Scheduler quit due to exception.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2actions/cmd/scheduler.py", line 126, in main
    return _run_scheduler()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2actions/cmd/scheduler.py", line 68, in _run_scheduler
    handler = scheduler_handler.get_handler()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2actions/scheduler/handler.py", line 469, in get_handler
    return ActionExecutionSchedulingQueueHandler()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2actions/scheduler/handler.py", line 66, in __init__
    self._coordinator = coordination_service.get_coordinator(start_heart=True)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/services/coordination.py", line 227, in get_coordinator
    COORDINATOR = coordinator_setup(start_heart=start_heart)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/services/coordination.py", line 192, in coordinator_setup
    coordinator = coordination.get_coordinator(url, member_id, lock_timeout=lock_timeout)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/tooz/coordination.py", line 802, in get_coordinator
    invoke_args=(member_id, parsed_url, options)).driver
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/stevedore/driver.py", line 61, in __init__
    warn_on_missing_entrypoint=warn_on_missing_entrypoint
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/stevedore/named.py", line 89, in __init__
    self._init_plugins(extensions)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/stevedore/driver.py", line 113, in _init_plugins
    (self.namespace, name))
stevedore.exception.NoMatches: No 'tooz.backends' driver found, looking for 'rediss'
```
Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by nzlosh** [comment]
From what I can tell, TLS is already support with the tooz redis backend.

There is no protocol `rediss`, which is why you're getting the above error.  To enable TLS with the tooz redis driver you can pass redis client arguments as part of URL query string.

The available client arguments are documented in [CLIENT_ARGS](https://docs.openstack.org/tooz/latest/reference/index.html#tooz.drivers.redis.RedisDriver.CLIENT_ARGS).

```
[coordination]
url = redis://127.0.0.1:6379?ssl=true&ssl_certfile=<url_encoded_path_to_cert_file>&ssl_keyfile=<url_encoded_path_to_key_file>
```

**Comment by bkk-bcd** [comment]
@nzlosh thanks! Some drivers use `rediss` to signify TLS so I assumed that was a standard. Thanks for the clarification! /cc
