### ISSUE TITLE
Connection to rabbitmq with SSL doesn't work

### ISSUE THREAD

**Issue by yypptest** [StackStorm/st2#5446]
## SUMMARY

We have stackstorm v3.2.0 on openshift and the connection to rabbitmq with SSL worked normally. Now we would like to upgrade stackstorm to v3.5.0, but the connection to the rabbitmq with SSL seems not work. 

##  STACKSTORM VERSION

st2: 3.5.0

##  OS, environment, install method

**OCP**: 4.8.13
**Docker image OS**: redhat 8.5
**Certificate**: self signed certificate
**Rabbitmq version**: 3.8.4
**Rabbitmq listener**:
```
Interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
Interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Interface: [::], port: 5671, protocol: amqp/ssl, purpose: AMQP 0-9-1 and AMQP 1.0 over TLS
Interface: [::], port: 15672, protocol: http, purpose: HTTP API
```

**Rabbitmq config**:
```
    listeners.ssl.default             = 5671
    ssl_options.cacertfile            = /etc/cert/cacert.pem
    ssl_options.certfile              = /etc/cert/cert.pem
    ssl_options.keyfile               = /etc/cert/key.pem
    ssl_options.verify                = verify_peer
    ssl_options.fail_if_no_peer_cert  = false
```
**st2.conf**:
```
    url = amqp://user:pwd@chatops-rabbitmq-ha-discovery:5671
    ssl = True
    ssl_keyfile = /etc/cert/rabbitmq/key.pem
    ssl_certfile = /etc/cert/rabbitmq/cert.pem
    ssl_cert_reqs = optional 
    ssl_ca_certs = /etc/cert/rabbitmq/cacert.pem
    login_method = PLAIN
```
## Steps to reproduce the problem
stackstorm v3.2.0 on openshift connected to rabbitmq with SSL normally,  when upgrade stackstorm to v3.5.0, the connection to the same rabbitmq with SSL does not work. Without SSL, stackstorm v3.5.0 can connect to rabbitmq normally.

## Expected Results

The stackstorm should be able to connect to rabbitmq with SSL normally. Here's the connection successfully log from  stackstorm v3.2.0:
```
2021-11-17 03:30:29,698 DEBUG [-] Using SSL context for RabbitMQ connection: {'keyfile': '/etc/cert/rabbitmq/key.pem', 'certfile': '/etc/cert/rabbitmq/cert.pem', 'cert_reqs': <VerifyMode.CERT_OPTIONAL: 1>, 'ca_certs': '/etc/cert/rabbitmq/cacert.pem'}
2021-11-17 03:30:29,698 INFO [-] Starting ActionExecutionDispatcher...
2021-11-17 03:30:29,724 DEBUG [-] Start from server, version: 0.9, properties: {'capabilities': {'publisher_confirms': True, 'exchange_exchange_bindings': True, 'basic.nack': True, 'consumer_cancel_notify': True, 'connection.blocked': True, 'consumer_priorities': True, 'authentication_failure_close': True, 'per_consumer_qos': True, 'direct_reply_to': True}, 'cluster_name': 'rabbit@chatops-rabbitmq-ha-1.chatops-rabbitmq-ha-discovery.stackstorm.svc.cluster.local', 'copyright': 'Copyright (c) 2007-2020 VMware, Inc. or its affiliates.', 'information': 'Licensed under the MPL 1.1. Website: https://rabbitmq.com', 'platform': 'Erlang/OTP 23.0.1', 'product': 'RabbitMQ', 'version': '3.8.4'}, mechanisms: [b'AMQPLAIN', b'PLAIN'], locales: ['en_US']
2021-11-17 03:30:29,728 INFO [-] Connected to amqp://admin:**@chatops-rabbitmq-ha-discovery:5671//
2021-11-17 03:30:29,729 DEBUG [-] using channel_id: 1
2021-11-17 03:30:29,730 DEBUG [-] Channel open
```

## Actual Results

Stackstorm connection to rabbitmq with SSL failed, most pods show CrashLoopBackOff with below log:
```
2021-11-17 01:37:45,290 DEBUG [-] Registering exchanges...
2021-11-17 01:37:45,290 DEBUG [-] Using SSL context for RabbitMQ connection: {'keyfile': '/etc/cert/rabbitmq/key.pem', 'certfile': '/etc/cert/rabbitmq/cert.pem', 'cert_reqs': <VerifyMode.CERT_OPTIONAL: 1>, 'ca_certs': '/etc/cert/rabbitmq/cacert.pem'}
2021-11-17 01:37:47,367 DEBUG [-] Received RabbitMQ server error, sleeping for 10 seconds before retrying: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)
2021-11-17 01:37:57,415 DEBUG [-] Failed to re-establish connection to RabbitMQ server, retrying in 2.0 seconds: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)
2021-11-17 01:37:59,436 DEBUG [-] Failed to re-establish connection to RabbitMQ server, retrying in 4.0 seconds: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)
2021-11-17 01:38:03,497 DEBUG [-] Failed to re-establish connection to RabbitMQ server, retrying in 6.0 seconds: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)
2021-11-17 01:38:09,588 ERROR [-] Connections to RabbitMQ cannot be re-established: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/transport/connection_retry_wrapper.py", line 131, in run
    channel = connection.channel()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/kombu/connection.py", line 283, in channel
    chan = self.transport.create_channel(self.connection)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/kombu/connection.py", line 859, in connection
    max_retries=1, reraise_as_library_errors=False
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/kombu/connection.py", line 439, in _ensure_connection
    callback, timeout=timeout
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/kombu/utils/functional.py", line 325, in retry_over_time
    return fun(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/kombu/connection.py", line 866, in _connection_factory
    self._connection = self._establish_connection()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/kombu/connection.py", line 801, in _establish_connection
    conn = self.transport.establish_connection()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 128, in establish_connection
    conn.connect()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/amqp/connection.py", line 323, in connect
    self.transport.connect()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/amqp/transport.py", line 115, in connect
    self.socket_settings, self.read_timeout, self.write_timeout,
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/amqp/transport.py", line 225, in _init_socket
    self._setup_transport()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/amqp/transport.py", line 405, in _setup_transport
    self.sock.do_handshake()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/eventlet/green/ssl.py", line 313, in do_handshake
    super(GreenSSLSocket, self).do_handshake)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/eventlet/green/ssl.py", line 162, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib64/python3.6/ssl.py", line 1036, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)
```

**Comment by amanda11** [comment]
It looks like a certificate problem

You could try and connect over SSL but remove some of the verify steps, to help identify where the problem is, e.g.

1. If your rabbitMQ uses verify_none instead of verify_peer can your StackStorm instance connect? 
2. If your ST2 doesn't verify the certificate from rabbitMQ can you connect (ssl_cert_reqs = None in st2.conf)

I'd also double check that the certificates are correct in case of any problems there. 

Can you connect from one of the ST2 3.5.0 pods to RabbitMQ using openSSL and passing the certificates you passed in the ST2.conf (see https://www.rabbitmq.com/troubleshooting-ssl.html#openssl-tools for help)?

**Comment by yypptest** [comment]
@amanda11, thanks your suggestions.

I re-generated the certificate files, but the stackstorm still can not connect to rabbitmq. 

I tried to connect to Rabbitmq using openSSL client with the command below, and it can connect normally with verify return code 0
`openssl s_client -connect 172.30.93.200:5671 -cert cert.pem -key key.pem -CAfile cacert.pem  -tls1_2 -cipher ALL`

Then I tried to set the rabbitMQ uses verify_none, this time the Stackstorm instances can connect successfully.

**Comment by amanda11** [comment]
Is RabbitMQ configured to trust the signing authority of the certificate that StackSotmr is sending?

**Comment by yypptest** [comment]
The rabbbitmq is configured as below, what's the configuration you mean to trust the signing authority of the certificate that StackStorm?
```    
    listeners.ssl.default             = 5671
    ssl_options.cacertfile            = /etc/cert/cacert.pem
    ssl_options.certfile              = /etc/cert/cert.pem
    ssl_options.keyfile               = /etc/cert/key.pem
    ssl_options.verify                = verify_peer
    ssl_options.fail_if_no_peer_cert  = false
```

**Comment by amanda11** [comment]
So StackStorm will send a client certificate which will be signed by a certificate authority. That certificate authority needs to be trusted by RabbitMQ. The ssl_options.cacertfile is the trusted CA bundle path - so needs to include the certificate authority that signed the certificate that StackStorm sent.
See: https://www.rabbitmq.com/ssl.html#peer-verification-how-it-works

**Comment by yypptest** [comment]
The provided cacertfile `/etc/cert/cacert.pem` is the file with certificate authority, and has been configured and provided to RabbitMQ for authentication.

**Comment by yypptest** [comment]
@amanda11, could you pls have a look at above comment? what's the tls protocal available from StackStorm side? Any thoughts for the error message from you?

**Comment by amanda11** [comment]
I don't think we specify the tls version, so I think it is dependant on your O/S. I had a good look around and I think its just up to the python version on your distribution. I believe with RH8  then that's tls v1.2 and v1.3. (I think the exception trace is not related to the version - the name of the exception class doesn't change between tls versions).

I would suspect though that if you managed to connect successfully when rabbitMQ verify_peer was none, that it wasn't a version problem. (But I have known that the errors can be sometimes confusing...)

If you can put on extra debug on the rabbitMQ side then that might help, as I think the error needs to be investigated from the rabbitMQ side as to why it is failing to verify the peer connection.

According to https://www.rabbitmq.com/ssl.html#peer-verification then if the problem is with the certificate that StackStorm is sending to RAbbitMQ then on the rabbitMQ logs you should get errors indicating if its that it's unknown CA, or certificate expired. 

It appears to me that StackStorm is just reporting that RabbitMQ rejected the connection, so the key to resolve is to look at the RabbitMQ logs to see why its being rejected.

**Comment by jamesdreid** [comment]
The error message seems to imply that the client is trying to connect using SSLv3 and the RabbitMQ server no longer supports SSLv3 as it is now considered "Insecure" and it use has been discouraged since the POODLE attacks compromised it.  You could try forcing the SSL Version to TLS 1.2 by adding the following to the config along with the other config options set above:
`ssl_version=ssl.PROTOCOL_TLSv1_2`
