### ISSUE TITLE
validate raise error jsonschema.exceptions.ValidationError: 'triggers' is a required property

### ISSUE THREAD

**Issue by Anz14** [StackStorm/st2#5633]
I did the stackstorm Installation in Ubuntu VM with the one line installation. I'm integrating this with the prometheus. So from prometheus the alert is sent to alertmanager and from there its posting to stackstorm webhook. When the alert triggers, its able to push the data to stackstorm and the webhook instance is getting triggered, however the rule is not getting executed. Please find below the Rules and Action I have defined.

Rules:

---
    name: "prometheus_integration_rule"
    pack: "demo"
    description: "Prometheus-stackstorm event handler."
    enabled: true

    trigger:
        parameters:
            url: "demo"
        type: "core.st2.webhook"

    criteria:
        trigger.body.alerts[0].labels.alertname:
            type: "startswith"
            pattern : "Disk_usage_kafka"
    action:
        ref: "demo.kafka_demo_disk_action"
        parameters:
            payload: "{{trigger}}"

Action:

---
name: "kafka_demo_disk_action"
pack: "demo"
runner_type: "python-script"
description: "On receiving a trigger, ssh into the problematic hosts and perform some action."
enabled: true
entry_point: "kafka_demo_disk_action.py"
parameters:
    triggers:
        type: "string"
        description: "Trigger received"
        required: true
output_schema:
    result:
        type: "string"

Error:

2022-04-27 11:52:43,616 140280774680416 INFO engine [-] Matched 1 rule(s) for trigger_instance 62692e8b1d6eaae1be11a657 (trigger=core.c42c4075-9658-424d-98ef-6ed54e940464)
2022-04-27 11:52:43,624 140280774680416 INFO enforcer [-] Invoking action demo.kafka_demo_disk_action for trigger_instance 62692e8b1d6eaae1be11a657 with params {"payload": "{{trigger}}"}.
2022-04-27 11:52:43,652 140280774680416 ERROR enforcer [-] Failed kicking off execution for rule RuleDB(action=ActionExecutionSpecDB@140280777529600(ref="demo.kafka_demo_disk_action", parameters="{'payload': '{{trigger}}'}"), context={'user': 'st2admin'}, criteria={'trigger.body.alerts[0].labels.alertname': {'type': 'startswith', 'pattern': 'Disk_usage_kafka'}}, description="Prometheus-stackstorm event handler.", enabled=True, id=626915a705b773ddee8e2c6c, metadata_file="", name="prometheus_integration_rule", pack="demo", ref="demo.prometheus_integration_rule", tags=[], trigger="core.c42c4075-9658-424d-98ef-6ed54e940464", type=RuleTypeSpecDB@140280777529824(ref="standard", parameters="{}"), uid="rule:demo:prometheus_integration_rule").
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2reactor/rules/enforcer.py", line 100, in enforce
    execution_db = self._do_enforce()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2reactor/rules/enforcer.py", line 165, in _do_enforce
    return self._invoke_action(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2reactor/rules/enforcer.py", line 258, in _invoke_action
    liveaction_db, execution_db = action_service.request(liveaction_db)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/services/action.py", line 210, in request
    liveaction, execution = create_request(liveaction)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/services/action.py", line 117, in create_request
    util_schema.validate(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/util/schema/__init__.py", line 350, in validate
    jsonschema.validate(instance=instance, schema=schema, cls=cls, *args, **kwargs)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
**jsonschema.exceptions.ValidationError: 'triggers' is a required property
Failed validating 'required' in schema['properties']['triggers']:**

**Comment by amanda11** [comment]
You have specified in your action definition that you want a parameter called triggers to be passed to it:
```
name: "kafka_demo_disk_action"
pack: "demo"
runner_type: "python-script"
description: "On receiving a trigger, ssh into the problematic hosts and perform some action."
enabled: true
entry_point: "kafka_demo_disk_action.py"
parameters:
triggers:
type: "string"
description: "Trigger received"
required: true
output_schema:
result:
type: "string"
```

 But when you call your action from your rule you don't pass a parameter called triggers to it, you are passing a parameter called payload to it:
 ```
 action:
    ref: "demo.kafka_demo_disk_action"
    parameters:
        payload: "{{trigger}}"
 ```
 
 So you need to make sure you use the same parameter name in your action definition and the name of the parameter you are passing to the action.

**Comment by Anz14** [comment]
Thanks @amanda11 It worked

**Comment by doing007** [comment]
I am currently planning to use p rometheus as well, can you share your best practices with me? @Anz14
