### ISSUE TITLE
Icons for pack content not loading

### ISSUE THREAD

**Issue by datapanda91** [StackStorm/st2#5663]
## SUMMARY

Icons for packs content is not loading. Icon wants to get loaded over the api but gets an unauthorized error. E.g. /api/v1/packs/views/file/rabbitmq/icon.png with result {"faultstring":"Unauthorized - One of Token or API key required."}.

### STACKSTORM VERSION

st2 3.7.0, on Python 3.8.10

##### OS, environment, install method

Docker installation

## Steps to reproduce the problem

Browse any custom pack content in the UI and check the icon.

## Expected Results

An icon.

## Actual Results

Icon not loading.
{"faultstring":"Unauthorized - One of Token or API key required."}.

**Comment by armab** [comment]
Someone interested in looking into this can spin-up a quick Vagrant image with stackstorm (https://docs.stackstorm.com/install/vagrant.html) and check if that's an issue in a VM as well.

If it's Docker-only, I'd look in the direction of the file permissions first. Another thing, for st2api to return the content of the icon it needs to be accessible to the st2api service/process. Could be something with how pack content is shared with the containers.

**Comment by kylehartigan-idea11** [comment]
I actually have this issue as well. I am moving to k8s and I have deployed a test environment using the stackstorm helm templates and I cannot see a cause for this issue.

![image](https://github.com/StackStorm/st2/assets/67616937/7660b873-3946-4942-9d3f-2a2c8070447e)

There has been no customisation to the docker images and i am not using a shared storage solutions as i am mounting st2packs using custom images

**Comment by kylehartigan-idea11** [comment]
I have been trouble shooting this one further and I have managed to get some additional log information from turning on debug mode in the st2 conf file. I hope this helps narrowing down where the bug could be or at least point out whats missing.

```
2023-10-12 12:34:38,035 DEBUG [-] Match path: /v1/packs/views/file/core/icon.png
2023-10-12 12:34:38,035 DEBUG [-] Parsed endpoint: {'operationId': 'st2api.controllers.v1.packs:packs_controller.views.file.get_one', 'x-requirements': {'file_path': '.*'}, 'x-log-result': False, 'x-submit-metrics': False, 'description': 'Get information about an installed pack.', 'parameters': [{'name': 'ref_or_id', 'in': 'path', 'description': 'Reference of the pack.', 'type': 'string', 'required': True}, {'name': 'file_path', 'in': 'path', 'description': 'Path to the file.', 'type': 'string', 'required': True}, {'name': 'if-none-match', 'in': 'header', 'x-as': 'if_none_match', 'description': 'ETag to compare to.', 'type': 'string'}, {'name': 'if-modified-since', 'in': 'header', 'x-as': 'if_modified_since', 'description': 'Date of last known modification.', 'type': 'string'}], 'x-parameters': [{'name': 'user', 'in': 'context', 'x-as': 'requester_user', 'description': 'User performing the operation.'}], 'responses': {'200': {'description': 'Content of the file.'}, '304': {'description': 'File has not been modified.'}, 'default': {'description': 'Unexpected error', 'schema': {'$ref': '#/definitions/Error'}}}}
2023-10-12 12:34:38,035 DEBUG [-] Parsed path_vars: {'ref_or_id': 'core', 'file_path': 'icon.png'}
2023-10-12 12:34:38,036 ERROR [-] One of Token or API key required.
2023-10-12 12:34:38,036 DEBUG [-] API call failed: Unauthorized - One of Token or API key required. (exception_class='HTTPUnauthorized',exception_message='Unauthorized - One of Token or API key required.',exception_data={'_status': '401 Unauthorized', '_headers': None, '_headerlist': [('Content-Type', 'text/html; charset=UTF-8'), ('Content-Length', '0')], 'conditional_response': False, '_app_iter': [b''], 'detail': 'Unauthorized - One of Token or API key required.', 'comment': 'Unauthorized - One of Token or API key required.'})
2023-10-12 12:34:38,037 DEBUG [-] Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/router.py", line 407, in __call__
    raise auth_exc.NoAuthSourceProvidedError(
st2common.exceptions.auth.NoAuthSourceProvidedError: One of Token or API key required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/middleware/error_handling.py", line 49, in __call__
    return self.app(environ, start_response)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/middleware/streaming.py", line 46, in __call__
    return self.app(environ, start_response)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/router.py", line 746, in as_wsgi
    resp = self(req)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/router.py", line 415, in __call__
    return abort_unauthorized(six.text_type(e))
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/router.py", line 82, in abort_unauthorized
    raise exc.HTTPUnauthorized("Unauthorized - %s" % msg if msg else "Unauthorized")
webob.exc.HTTPUnauthorized: Unauthorized - One of Token or API key required.
```

**Comment by kylehartigan-idea11** [comment]
so I decided to deploy st2 using docker-compose on my local workstation, enabled debug logging, and compared the logs to the one in my AWS EKS cluster. to my surprise, the local version had one additional header `Cookie: auth-token=RandomString`.

so I tried a different browser (with better developer tools) and found that auth-token cookie was not being sent as it was HTTP 
![image](https://github.com/StackStorm/st2/assets/67616937/0e13c154-2e8e-4cbe-9ee3-278bf8df120e)

I went and reconfigured the AWS ALB to accept HTTPS only and put a cert on it and it all started working as expected

<img width="727" alt="image" src="https://github.com/StackStorm/st2/assets/67616937/4b42f512-804a-41e3-88cd-bf39163cc6b0">

@armab I would suggest the issue can be closed as I suspect that @datapanda91 hit the same issue with the cookie not being passed to the API service

**Comment by armab** [comment]
Thanks @kylehartigan-idea11 for your research and findings, - very helpful!
