### ISSUE TITLE
Is it possible to setup the ssh runner to use diffie-hellman-group-exchange-sha256

### ISSUE THREAD

**Issue by philipphomberger** [StackStorm/st2#5876]
## SUMMARY

Hello All I get a error that Incompatible ssh server (no acceptable ciphers). 

Provide a quick summary of your bug report.
[eco_adm@cg3d383c911-groot-s301 ~]$ st2 run core.remote cmd=whoami hosts=127.0.0.1
.
id: 63d7d15083ba996bbaefa4d8
action.ref: core.remote
context.user: hombergerp
parameters:
  cmd: whoami
  hosts: 127.0.0.1
status: failed
start_timestamp: Mon, 30 Jan 2023 14:16:48 UTC
end_timestamp: Mon, 30 Jan 2023 14:16:48 UTC
result:
  error: "Unable to connect to any one of the hosts: ['127.0.0.1'].

 connect_errors={
  "127.0.0.1": {
    "failed": true,
    "succeeded": false,
    "timeout": false,
    "return_code": 255,
    "stdout": "",
    "stderr": "",
    "error": "Connection error. Error connecting to host 127.0.0.1 with connection parameters {'hostname': '127.0.0.1', 'allow_agent': False, 'look_for_keys': False, 'timeout': 60, 'username': 'stanley', 'port': 22, 'key_filename': '/home/stanley/.ssh/stanley_rsa'}.Paramiko error: Incompatible ssh server (no acceptable ciphers).",
    "traceback": "Traceback (most recent call last):\
  File \\"/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/runners/paramiko_ssh.py\\", line 787, in _connect\
    client.connect(**conninfo)\
  File \\"/opt/stackstorm/st2/lib/python3.8/site-packages/paramiko/client.py\\", line 406, in connect\
    t.start_client(timeout=timeout)\
  File \\"/opt/stackstorm/st2/lib/python3.8/site-packages/paramiko/transport.py\\", line 698, in start_client\
    raise e\
  File \\"/opt/stackstorm/st2/lib/python3.8/site-packages/paramiko/transport.py\\", line 2137, in run\
    self._handler_table[ptype](self, m)\
  File \\"/opt/stackstorm/st2/lib/python3.8/site-packages/paramiko/transport.py\\", line 2257, in _negotiate_keys\
    self._parse_kex_init(m)\
  File \\"/opt/stackstorm/st2/lib/python3.8/site-packages/paramiko/transport.py\\", line 2510, in _parse_kex_init\
    raise IncompatiblePeer(\
paramiko.ssh_exception.IncompatiblePeer: Incompatible ssh server (no acceptable ciphers)\
\
During handling of the above exception, another exception occurred:\
\
Traceback (most recent call last):\
  File \\"/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/runners/parallel_ssh.py\\", line 278, in _connect\
    client.connect()\
  File \\"/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/runners/paramiko_ssh.py\\", line 171, in connect\
    self.client = self._connect(host=self.hostname, socket=self.bastion_socket)\
  File \\"/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/runners/paramiko_ssh.py\\", line 799, in _connect\
    raise SSHException(msg)\
paramiko.ssh_exception.SSHException: Error connecting to host 127.0.0.1 with connection parameters {'hostname': '127.0.0.1', 'allow_agent': False, 'look_for_keys': False, 'timeout': 60, 'username': 'stanley', 'port': 22, 'key_filename': '/home/stanley/.ssh/stanley_rsa'}.Paramiko error: Incompatible ssh server (no acceptable ciphers).\
"
  }
}"
  traceback: "  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2actions/container/base.py", line 117, in _do_run
    runner.pre_run()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/runners/paramiko_ssh_runner.py", line 206, in pre_run
    self._parallel_ssh_client = ParallelSSHClient(**client_kwargs)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/runners/parallel_ssh.py", line 90, in __init__
    connect_results = self.connect(raise_on_any_error=raise_on_any_error)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/runners/parallel_ssh.py", line 131, in connect
    raise NoHostsConnectedToException(msg)
"
[eco_adm@cg3d383c911-groot-s301 ~]$

I see that paramiko it self can it:

https://github.com/ktbyers/netmiko/issues/1742

But I have no idea how deal with it in Stackstorm.

Thank you for your advice :)

**Comment by philipphomberger** [comment]
I have now use this code to read out the the ciphers and kex from the paramiko libary: 
import paramiko
import socket

opts = paramiko.transport.Transport(socket.socket()).get_security_options()
print(opts.ciphers)
print(opts.kex)
ciphers:
('aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-cbc', 'aes192-cbc', 'aes256-cbc', '3des-cbc')
kex:
('curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group16-sha512', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha256', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1')

From my point of view that looks good. But not working.

**Comment by philipphomberger** [comment]
The Problem is that the SSHD Server Service only allow openssh chippers. So now problem on Stackstorm seite.
