### ISSUE TITLE
pip_opts does't work

### ISSUE THREAD

**Issue by zhenglisai** [StackStorm/st2#5910]
### STACKSTORM VERSION
3.8.0

Paste the output of ``st2 --version``:

##### OS, environment, install method
docker-compose

## Steps to reproduce the problem

configfile:

[actionrunner]
pip_opts = -i https://pypi.tuna.tsinghua.edu.cn/simple,--no-cache-dir,--disable-pip-version-check,--trusted-host=pypi.tuna.tsinghua.edu.cn

## Actual Results

id: 63f4899229d1c02d754501d2
action.ref: packs.setup_virtualenv
context.user: st2admin
parameters: 
  packs:
  - k8s
status: failed
start_timestamp: Tue, 21 Feb 2023 09:06:26 UTC
end_timestamp: Tue, 21 Feb 2023 09:06:29 UTC
result: 
  exit_code: 1
  result: None
  stderr: "st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Setting up virtualenv for pack "k8s" (/opt/stackstorm/packs/k8s)
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Removing virtualenv in "/opt/stackstorm/virtualenvs/k8s"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Virtualenv successfully removed.
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv for pack "k8s" in "/opt/stackstorm/virtualenvs/k8s"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv in "/opt/stackstorm/virtualenvs/k8s" using Python binary "/opt/stackstorm/st2/bin/python"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Running command "/opt/stackstorm/st2/bin/virtualenv -p /opt/stackstorm/st2/bin/python --always-copy --verbose --no-download /opt/stackstorm/virtualenvs/k8s" to create virtualenv.
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing base requirements
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing requirement six>=1.9.0,<2.0 with command /opt/stackstorm/virtualenvs/k8s/bin/pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir --disable-pip-version-check --trusted-host=pypi.tuna.tsinghua.edu.cn six>=1.9.0,<2.0.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 395, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 214, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/setup_virtualenv.py", line 93, in run
    setup_pack_virtualenv(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/util/virtualenvs.py", line 118, in setup_pack_virtualenv
    install_requirement(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/util/virtualenvs.py", line 348, in install_requirement
    raise Exception(
Exception: Failed to install requirement "six>=1.9.0,<2.0": Looking in indexes:  https://pypi.tuna.tsinghua.edu.cn/simple

"
  stdout: ''

**the pip doesn't install six success, but i can install it manuely**

root@262d1f9b9e43:/opt/stackstorm# /opt/stackstorm/virtualenvs/k8s/bin/pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir --disable-pip-version-check --trusted-host=pypi.tuna.tsinghua.edu.cn 'six>=1.9.0,<2.0'
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting six<2.0,>=1.9.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six
Successfully installed six-1.16.0

**Comment by zhenglisai** [comment]
i resolved this problem.

1, modify 
/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/constants/pack.py
from
BASE_PACK_REQUIREMENTS = ["six>=1.9.0,<2.0"]
to
BASE_PACK_REQUIREMENTS = ["'six>=1.9.0,<2.0'"]

2, modify
/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/util/shell.py
FROM
def run_command(
    cmd,
    stdin=None,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    shell=False,
    cwd=None,
    env=None,
    close_fds=None,
):
TO
def run_command(
    cmd,
    stdin=None,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    shell=True,
    cwd=None,
    env=None,
    close_fds=None,
):
    cmd = " ".join(cmd)


this is the good result

st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing requirement 'six>=1.9.0,<2.0' with command /opt/stackstorm/virtualenvs/k8s/bin/pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir --disable-pip-version-check --trusted-host=pypi.tuna.tsinghua.edu.cn 'six>=1.9.0,<2.0'.
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    
pip stdout=
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting six<2.0,>=1.9.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six
Successfully installed six-1.16.0

st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing pack specific requirements from "/opt/stackstorm/packs/k8s/requirements.txt"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing requirements from file /opt/stackstorm/packs/k8s/requirements.txt with command /opt/stackstorm/virtualenvs/k8s/bin/pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir --disable-pip-version-check --trusted-host=pypi.tuna.tsinghua.edu.cn -U -r /opt/stackstorm/packs/k8s/requirements.txt.
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Virtualenv for pack "k8s" successfully created in "/opt/stackstorm/virtualenvs/k8s"
"
  stdout: ''




i think the problem is ths pack six<2.0,>=1.9.0,
pip install this pack in shell must with ''
pip install 'six<2.0,>=1.9.0'

i found a =1.9.0 file in stackstorm home path 
![图片](https://user-images.githubusercontent.com/32353492/220320401-32632c5d-2ad1-40fa-984f-2ca0451c440f.png)

**Comment by zhenglisai** [comment]
sorry， my bad, this is not a bug, my st2.conf is wrong

this is wrong
[actionrunner]
pip_opts = -i https://pypi.tuna.tsinghua.edu.cn/simple,--no-cache-dir,--disable-pip-version-check,--trusted-host=pypi.tuna.tsinghua.edu.cn

correct is 
[actionrunner]
pip_opts = -i,https://pypi.tuna.tsinghua.edu.cn/simple,--no-cache-dir,--disable-pip-version-check,--trusted-host=pypi.tuna.tsinghua.edu.cn

in pip_opts, every blank space should be replaced with ,
