### ISSUE TITLE
Failed to register action from pack "aws": found duplicate key "headers"

### ISSUE THREAD

**Issue by lordpengwin** [StackStorm/st2#5918]
## SUMMARY

Register content job failing (stackstorm/stackstorm-job-st2-register-content-xxxxx) when run from Helm chart

### STACKSTORM VERSION

This occurs with both v0.100.0 and v0.110.0 of the helm chart

##### OS, environment, install method

EKS Kubernetes using helm chart from https://github.com/StackStorm/stackstorm-k8s

## Steps to reproduce the problem

This fails while bringing up the system for the first time. It seems to be a job called st2-register-content

## Expected Results

Should not fail

## Actual Results

```
st2-register-content 2023-03-02 15:30:34,381 WARNING [-] Failed to register actions: Failed to register action "/opt/stackstorm/packs/aws/actions/apigateway_test_invoke_authorizer.yaml" from pack "aws": found duplicate key "headers"
st2-register-content Traceback (most recent call last):
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/actionsregistrar.py", line 233, in _register_actions_from_pack
st2-register-content     altered = self._register_action(pack=pack, action=action)
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/actionsregistrar.py", line 132, in _register_action
st2-register-content     content = self._meta_loader.load(action)
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/loader.py", line 253, in load
st2-register-content     result = self._load(PARSER_FUNCS[file_ext], file_path)
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/loader.py", line 265, in _load
st2-register-content     return parser_func(fd)
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/constants/meta.py", line 53, in yaml_safe_load
st2-register-content     return yaml.load(stream, Loader=YamlSafeLoader)
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
st2-register-content     return loader.get_single_data()
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
st2-register-content     return self.construct_document(node)
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/yaml/constructor.py", line 55, in construct_document
st2-register-content     data = self.construct_object(node)
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
st2-register-content     data = constructor(self, node)
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/orquesta/utils/yml.py", line 52, in construct_mapping
st2-register-content     value = self.construct_object(value_node, deep=deep)
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
st2-register-content     data = constructor(self, node)
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/orquesta/utils/yml.py", line 51, in construct_mapping
st2-register-content     raise constructor.ConstructorError('found duplicate key "%s"' % key_node.value)
st2-register-content yaml.constructor.ConstructorError: found duplicate key "headers"
st2-register-content
st2-register-content During handling of the above exception, another exception occurred:
st2-register-content
st2-register-content Traceback (most recent call last):
st2-register-content   File "/usr/bin/st2-register-content", line 22, in <module>
st2-register-content     sys.exit(content_loader.main(sys.argv[1:]))
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/bootstrap.py", line 458, in main
st2-register-content     register_content()
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/bootstrap.py", line 400, in register_content
st2-register-content     register_actions()
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/bootstrap.py", line 267, in register_actions
st2-register-content     raise e
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/bootstrap.py", line 257, in register_actions
st2-register-content     registered_count, overridden_count = actions_registrar.register_actions(
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/actionsregistrar.py", line 279, in register_actions
st2-register-content     result = registrar.register_from_packs(base_dirs=packs_base_paths)
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/actionsregistrar.py", line 74, in register_from_packs
st2-register-content     raise e
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/actionsregistrar.py", line 67, in register_from_packs
st2-register-content     count, overridden = self._register_actions_from_pack(
st2-register-content   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/actionsregistrar.py", line 243, in _register_actions_from_pack
st2-register-content     raise ValueError(msg)
st2-register-content ValueError: Failed to register action "/opt/stackstorm/packs/aws/actions/apigateway_test_invoke_authorizer.yaml" from pack "aws": found duplicate key "headers"
```

**Comment by amanda11** [comment]
What version of the AWS pack are you installing? This is a bug in the AWS pack that was fixed by this pull request: https://github.com/StackStorm-Exchange/stackstorm-aws/pull/115

In old versions of ST2 duplicate fields were not detected, but duplication detection was added a few releases ago, and so any packs that had duplicate headers had to be fixed.

**Comment by lordpengwin** [comment]
Yes it turns out that the version of the aws pack I had included in my custom pack was out of date. I rebuilt everything and the problem went away.
