### ISSUE TITLE
After MongoDB upgrade from 4.0 to 4.4 - pymongo 'IndexOptionsConflict' "Index with name: l v_ac_id already exists with a different name"

### ISSUE THREAD

**Issue by slohse** [StackStorm/st2#5968]
## SUMMARY

We have an old StackStorm installation that we are currently trying to get from 3.2 to 3.8. This also meant taking MongoDB from 3.4 to 4.4. But when we try to go beyond MongoDB 4.0, StackStorm will not start, with this in the logs:

```
pymongo.errors.OperationFailure: Index with name: lv_ac_id already exists with a different name, full error: {'ok': 0.0, 'errmsg': 'Index with name: lv_ac_id already exists with a different name', 'code': 85, 'codeName': 'IndexOptionsConflict'}
```

Something to note may be that we needed to migrate the database from the old MMAPv1 storage engine to wiredTiger. We followed the [instructions given by MongoDB](https://www.mongodb.com/docs/manual/tutorial/change-standalone-wiredtiger/)

### STACKSTORM VERSION

`st2 3.8.0, on Python 3.8.10`, but also observed with 3.5.0

##### OS, environment, install method

Ubuntu 20.04, upgraded in LTS-steps from 16.04 (and, some years ago, from 14.04).
Install-method: ansible-st2
MongoDB: No problems with 4.0, but the issue appears with 4.2 and does not go away with 4.4.

## Steps to reproduce the problem

`st2ctl start`

## Expected Results

ST2 runs and responds to commands like `st2 execution list`

## Actual Results

```
# st2ctl start
Failed to start st2chatops.service: Unit st2chatops.service not found.
##### st2 components status #####
st2actionrunner PID: 1515724
st2actionrunner PID: 1515727
st2actionrunner PID: 1515729
st2actionrunner PID: 1515731
st2actionrunner PID: 1515736
st2actionrunner PID: 1515745
st2actionrunner PID: 1515747
st2actionrunner PID: 1515749
st2actionrunner PID: 1515751
st2actionrunner PID: 1515753
st2api PID: 1515757
st2stream PID: 1515761
st2auth PID: 1515765
st2garbagecollector PID: 1515769
st2notifier PID: 1515777
st2rulesengine PID: 1515780
st2sensorcontainer PID: 1515788
st2chatops is not running.
st2timersengine PID: 1515793
st2workflowengine PID: 1515796
st2scheduler PID: 1515799

# [wait a few seconds]
# st2ctl status
##### st2 components status #####
st2actionrunner is not running.
st2api is not running.
st2stream is not running.
st2auth is not running.
st2garbagecollector is not running.
st2notifier is not running.
st2rulesengine is not running.
st2sensorcontainer is not running.
st2chatops is not running.
st2timersengine is not running.
st2workflowengine is not running.
st2scheduler is not running.

# st2 execution list                                                                                                                           
ERROR: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))                                                                                                                            
```

Excerpt from `/var/log/st2/st2workflowengine.log`:

```
2023-04-27 20:07:25,266 139884456315184 INFO __init__ [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "None".
2023-04-27 20:07:25,273 139884456315184 INFO __init__ [-] Successfully connected to database "st2" @ "127.0.0.1:27017" as user "None".
2023-04-27 20:07:25,353 139884456315184 ERROR traceback [-] Traceback (most recent call last):

2023-04-27 20:07:25,353 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,354 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2actions/cmd/workflow_engine.py", line 88, in main
    setup()

2023-04-27 20:07:25,354 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,354 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2actions/cmd/workflow_engine.py", line 54, in setup
    common_setup(

2023-04-27 20:07:25,355 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,355 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/service_setup.py", line 252, in setup
    db_setup()

2023-04-27 20:07:25,355 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,355 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/database_setup.py", line 55, in db_setup
    connection = db_init.db_setup_with_retry(**db_cfg)

2023-04-27 20:07:25,356 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,356 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/persistence/db_init.py", line 79, in db_setup_with_retry
    return db_func_with_retry(

2023-04-27 20:07:25,356 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,357 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/persistence/db_init.py", line 58, in db_func_with_retry
    return retrying_obj.call(db_func, *args, **kwargs)

2023-04-27 20:07:25,357 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,357 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)

2023-04-27 20:07:25,358 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,358 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])

2023-04-27 20:07:25,358 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,358 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/six.py", line 696, in reraise
    raise value

2023-04-27 20:07:25,359 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,359 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)

2023-04-27 20:07:25,359 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,360 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/models/db/__init__.py", line 261, in db_setup
    db_ensure_indexes()

2023-04-27 20:07:25,360 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,360 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/models/db/__init__.py", line 302, in db_ensure_indexes
    raise e

2023-04-27 20:07:25,360 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,361 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/models/db/__init__.py", line 291, in db_ensure_indexes
    model_class.ensure_indexes()

2023-04-27 20:07:25,361 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,361 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/mongoengine/document.py", line 867, in ensure_indexes
    collection = cls._get_collection()

2023-04-27 20:07:25,362 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,362 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/mongoengine/document.py", line 215, in _get_collection
    cls.ensure_indexes()

2023-04-27 20:07:25,362 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,362 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/mongoengine/document.py", line 894, in ensure_indexes
    collection.create_index(fields, background=background, **opts)

2023-04-27 20:07:25,363 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,363 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/collection.py", line 2059, in create_index
    return self.__create_indexes([index], session, **cmd_options)[0]

2023-04-27 20:07:25,363 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,363 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/collection.py", line 1949, in __create_indexes
    self._command(

2023-04-27 20:07:25,363 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,363 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/collection.py", line 238, in _command
    return sock_info.command(

2023-04-27 20:07:25,364 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,364 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/pool.py", line 683, in command
    return command(self, dbname, spec, slave_ok,

2023-04-27 20:07:25,364 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,364 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/network.py", line 159, in command
    helpers._check_command_response(

2023-04-27 20:07:25,364 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,364 139884456315184 ERROR traceback [-]   File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/helpers.py", line 164, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)

2023-04-27 20:07:25,364 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,364 139884456315184 ERROR traceback [-] pymongo.errors.OperationFailure: Index with name: lv_ac_id already exists with a different name, full error: {'ok': 0.0, 'errmsg': 'Index with name: lv_ac_id already exists with a different name', 'code': 85, 'codeName': 'IndexOptionsConflict'}

2023-04-27 20:07:25,365 139884456315184 ERROR traceback [-] 
2023-04-27 20:07:25,365 139884456315184 ERROR workflow_engine [-] (PID=1515796) Workflow engine quit due to exception.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2actions/cmd/workflow_engine.py", line 88, in main
    setup()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2actions/cmd/workflow_engine.py", line 54, in setup
    common_setup(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/service_setup.py", line 252, in setup
    db_setup()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/database_setup.py", line 55, in db_setup
    connection = db_init.db_setup_with_retry(**db_cfg)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/persistence/db_init.py", line 79, in db_setup_with_retry
    return db_func_with_retry(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/persistence/db_init.py", line 58, in db_func_with_retry
    return retrying_obj.call(db_func, *args, **kwargs)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/six.py", line 696, in reraise
    raise value
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/models/db/__init__.py", line 261, in db_setup
    db_ensure_indexes()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/models/db/__init__.py", line 302, in db_ensure_indexes
    raise e
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/models/db/__init__.py", line 291, in db_ensure_indexes
    model_class.ensure_indexes()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/mongoengine/document.py", line 867, in ensure_indexes
    collection = cls._get_collection()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/mongoengine/document.py", line 215, in _get_collection
    cls.ensure_indexes()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/mongoengine/document.py", line 894, in ensure_indexes
    collection.create_index(fields, background=background, **opts)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/collection.py", line 2059, in create_index
    return self.__create_indexes([index], session, **cmd_options)[0]
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/collection.py", line 1949, in __create_indexes
    self._command(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/collection.py", line 238, in _command
    return sock_info.command(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/pool.py", line 683, in command
    return command(self, dbname, spec, slave_ok,
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/network.py", line 159, in command
    helpers._check_command_response(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/helpers.py", line 164, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Index with name: lv_ac_id already exists with a different name, full error: {'ok': 0.0, 'errmsg': 'Index with name: lv_ac_id already exists with a different name', 'code': 85, 'codeName': 'IndexOptionsConflict'}
```

**Comment by fdrab** [comment]
Per the installation documentation the supported version of MongoDB is 4.0.

**Comment by slohse** [comment]
I was under the impression that for Ubuntu 20.04, MongoDB 4.4 was to be installed.
Both the [installation instructions](https://docs.stackstorm.com/install/u20.html), and [ansible-st2](https://github.com/StackStorm/ansible-st2/blob/master/roles/StackStorm.mongodb/defaults/main.yml#L3) indicate that.

**Comment by nzlosh** [comment]
mongo 4.x is supported. 4.0/4.2/4.4 have been confirmed as compatible.  I've not seen this sort of error before, but do see there are mongo related upgrade notes, have you been following these? https://docs.stackstorm.com/upgrade_notes.html

**Comment by slohse** [comment]
We followed the notes at StackStorm 3.3 to get to MongoDB 4.0 and that worked fine. The only database related note I can see on later versions is the thing at 3.5 with `st2-migrate-db-dict-field-values`. That we did not do, as it was declared optional and we didn't want to risk data integrity.

**Comment by nzlosh** [comment]
Has this issue been resolved?  The indexes on the database are for performance purposes, not data integrity, so they can be dropped without risk of loosing information.

I suspect this bug comes from this change https://github.com/StackStorm/st2/pull/4690.  Try to identify the collection with the index containing the old field name `liveaction_id` and then drop the index for that collection. Stackstorm will recreate the index on new entries when restarted.

**Comment by slohse** [comment]
We 'solved' it by starting from a fresh database and keeping a VM with the old installation around, in case we need to refer back to something. But thanks for the help and maybe your tip about dropping the index is of use for other people running into this.

**Comment by nzlosh** [comment]
Good to know you managed to work around the problem.  :+1:
