### ISSUE TITLE
 Failed to register rule duplicate key "criteria"

### ISSUE THREAD

**Issue by doing007** [StackStorm/st2#5987]
my webhook file is 
```yaml
---
name: "sample_rule_with_webhook"
pack: "examples"
description: "Sample rule dumping webhook payload to a file."
enabled: true
trigger:
  type: "core.st2.webhook"
  parameters:
    url: "sample2"
criteria:
  trigger.body.alerts[0].labels.alertname:
    pattern: "service_down"
    type: "equals"
action:
  ref: "core.local"
  parameters:
    cmd: "echo \"{{trigger.body}}\" >> ~/st2.webhook_sample.out ; sync"
criteria:
  trigger.body.alerts[0].labels.alertname:
    pattern: "site_down"
    type: "equals"
action:
  ref: "core.remote"
  parameters:
    cmd: 'ls -l'
    hosts: '10.0.0.0.1'
    username: 'root'
    port: 22
```

```bash
2023-06-13 06:26:59,762 WARNING [-] Failed to register rules: Failed to register rule "/opt/stackstorm/packs/examples/rules/restart_server_with_webhook.yaml" from pack "examples": found duplicate key "criteria"
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/rulesregistrar.py", line 121, in _register_rules_from_pack
    content = self._meta_loader.load(rule)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/loader.py", line 253, in load
    result = self._load(PARSER_FUNCS[file_ext], file_path)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/loader.py", line 265, in _load
    return parser_func(fd)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/constants/meta.py", line 53, in yaml_safe_load
    return yaml.load(stream, Loader=YamlSafeLoader)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/orquesta/utils/yml.py", line 51, in construct_mapping
    raise constructor.ConstructorError('found duplicate key "%s"' % key_node.value)
yaml.constructor.ConstructorError: found duplicate key "criteria"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/st2-register-content", line 22, in <module>
    sys.exit(content_loader.main(sys.argv[1:]))
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/bootstrap.py", line 458, in main
    register_content()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/bootstrap.py", line 401, in register_content
    register_rules()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/bootstrap.py", line 300, in register_rules
    raise e
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/bootstrap.py", line 292, in register_rules
    registered_count, overridden_count = rules_registrar.register_rules(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/rulesregistrar.py", line 236, in register_rules
    result = registrar.register_from_packs(base_dirs=packs_base_paths)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/rulesregistrar.py", line 68, in register_from_packs
    raise e
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/rulesregistrar.py", line 63, in register_from_packs
    count, override = self._register_rules_from_pack(pack, rules)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/rulesregistrar.py", line 205, in _register_rules_from_pack
    raise ValueError(msg)
ValueError: Failed to register rule "/opt/stackstorm/packs/examples/rules/restart_server_with_webhook.yaml" from pack "examples": found duplicate key "criteria"
##### st2 components status #####
```

how to register two criteria in a webhook ?

**Comment by doing007** [comment]
I have split this file into two files

```bash
---
name: "sample_rule_with_webhook"
pack: "examples"
description: "Sample rule dumping webhook payload to a file."
enabled: true
trigger:
  type: "core.st2.webhook"
  parameters:
    url: "sample2"
criteria:
  trigger.body.alerts[0].labels.alertname:
    pattern: "site_down"
    type: "equals"
action:
  ref: "core.remote"
  parameters:
    cmd: 'ls -l'
    hosts: '10.0.0.0.1'
    username: 'root'
    port: 22
```

```bash
---
name: "sample_rule_with_webhook"
pack: "examples"
description: "Sample rule dumping webhook payload to a file."
enabled: true
trigger:
  type: "core.st2.webhook"
  parameters:
    url: "sample2"
criteria:
  trigger.body.alerts[0].labels.alertname:
    pattern: "service_down"
    type: "equals"
action:
  ref: "core.local"
  parameters:
    cmd: "echo \"{{trigger.body}}\" >> ~/st2.webhook_sample.out ; sync"
```

after execute cmd
 ```bash
st2ctl reload --register-all
```

But only one file takes effect！！

**Comment by nzlosh** [comment]
The rule name must be unique.  Using the same name will cause an error or race condition as one rule over-writes the other.  The pack name and rule name can be thought of as the unique key when writing to the database.

As you discovered, it is not possible provide the same key multiple times in the rule file, splitting the rules into separate file is the right thing to do.

From a security point of view, you should never pass user input to be directly executed by workflow/action as this opens you to being attacked via injection.
