### ISSUE TITLE
stackstorm start problem

### ISSUE THREAD

**Issue by simonli866** [StackStorm/st2#6009]
hi , I got a problem.
system: Ubuntu 20.04
`Traceback (most recent call last):
  File "/home/simon/st2/st2common/st2common/metrics/base.py", line 228, in metrics_initialize
    METRICS = get_plugin_instance(PLUGIN_NAMESPACE, cfg.CONF.metrics.driver)
  File "/home/simon/st2/st2common/st2common/util/loader.py", line 222, in get_plugin_instance
    manager = DriverManager(
  File "/home/simon/st2/virtualenv/lib/python3.8/site-packages/stevedore/driver.py", line 53, in __init__
    super(DriverManager, self).__init__(
  File "/home/simon/st2/virtualenv/lib/python3.8/site-packages/stevedore/named.py", line 89, in __init__
    self._init_plugins(extensions)
  File "/home/simon/st2/virtualenv/lib/python3.8/site-packages/stevedore/driver.py", line 112, in _init_plugins
    raise NoMatches('No %r driver found, looking for %r' %
stevedore.exception.NoMatches: No 'st2common.metrics.driver' driver found, looking for 'noop'`
  how can I resolve it?

**Comment by nzlosh** [comment]
Installing StackStorm into an arbitrary virtualenv is not supported.  There are multiple ways to install StackStorm correctly by following the official documentation https://docs.stackstorm.com/install/u20.html
