### ISSUE TITLE
Command Error: st2-run-pack-tests -c

### ISSUE THREAD

**Issue by xu-y-50** [StackStorm/st2#6109]
## SUMMARY
Can not output the coverage report when unit test the stackstorm packs

### STACKSTORM VERSION
st2 3.8.0, on Python 3.8.10

**output of ``t2-run-pack-tests -c``:**
TEST RESULT OUTPUT:

Traceback (most recent call last):
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/sqlitedb.py", line 109, in _execute
    return self.con.execute(sql, parameters)    # type: ignore[arg-type]
sqlite3.OperationalError: no such table: coverage_schema

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/sqlitedb.py", line 114, in _execute
    return self.con.execute(sql, parameters)    # type: ignore[arg-type]
sqlite3.OperationalError: no such table: coverage_schema

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/sqldata.py", line 293, in _read_db
    row = db.execute_one("select version from coverage_schema")
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/sqlitedb.py", line 181, in execute_one
    with self.execute(sql, parameters) as cur:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/sqlitedb.py", line 144, in execute
    cur = self._execute(sql, parameters)
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/sqlitedb.py", line 132, in _execute
    raise DataError(f"Couldn't use data file {self.filename!r}: {msg}") from exc
coverage.exceptions.DataError: Couldn't use data file '/opt/stackstorm/packs/pgcloud/.coverage': no such table: coverage_schema

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/usr/lib/python3.8/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/nose/core.py", line 66, in run
    result.printErrors()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/rednose.py", line 442, in printErrors
    self.config.plugins.report(self.stream)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/nose/plugins/cover.py", line 183, in report
    self.coverInstance.stop()
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/control.py", line 831, in combine
    self.get_data()
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/control.py", line 862, in get_data
    if self._collector.flush_data():
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/collector.py", line 521, in flush_data
    self.covdata.add_lines(self.mapped_file_dict(line_data))
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/sqldata.py", line 124, in _wrapped
    return method(self, *args, **kwargs)
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/sqldata.py", line 495, in add_lines
    self._choose_lines_or_arcs(lines=True)
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/sqldata.py", line 564, in _choose_lines_or_arcs
    with self._connect() as con:
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/sqldata.py", line 344, in _connect
    self._open_db()
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/sqldata.py", line 287, in _open_db
    self._read_db()
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/sqldata.py", line 297, in _read_db
    self._init_db(db)
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/sqldata.py", line 326, in _init_db
    db.executescript(SCHEMA)
  File "/tmp/st2-pack-tests-virtualenvs/pgcloud/lib/python3.8/site-packages/coverage/sqlitedb.py", line 220, in executescript
    self.con.executescript(script).close()
sqlite3.OperationalError: database is locked
Deactivating virtualenv /tmp/st2-pack-tests-virtualenvs
##### OS, environment, install method
StackStorm on Kubernetes
 
Thanks!

**Comment by guzzijones** [comment]
The error tells you what the problem is.
