### ISSUE TITLE
Unable to install packs that has .git file in it

### ISSUE THREAD

**Issue by anshul-axl** [StackStorm/st2#6219]
I was trying to install the packs that are there on the github, but on installing it is showing me this error:
result:
  errors:
  - message: Execution failed. See result for details.
    result:
      exit_code: 1
      result: None
      stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 395, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 214, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 94, in run
    pack_result = download_pack(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/util/pack_management.py", line 161, in download_pack
    clone_repo(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/util/pack_management.py", line 205, in clone_repo
    repo = Repo.clone_from(repo_url, temp_dir)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/git/repo/base.py", line 1328, in clone_from
    return cls._clone(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/git/repo/base.py", line 1237, in _clone
    finalize_process(proc, stderr=stderr)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/git/util.py", line 437, in finalize_process
    proc.wait(**kwargs)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/git/cmd.py", line 602, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- git@github.com:exampleuser/stackstorm-examplepack.git /root/.st2packs/006re5b146af7979431fc9e001da0d79f3
  stderr: 'Cloning into '/root/.st2packs/0065b146af7979431fc9e001dase0d79f3'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
'
"
      stdout: ''
    task_id: download_pack
    type: error
  output:
    conflict_list: null
    message: ''
    packs_list: null
    warning_list: null

**Comment by anshul-axl** [comment]
Thank you so much that helped me!
