### ISSUE TITLE
Errors while configuring proxy for ST2 interaction with JIRA

### ISSUE THREAD

**Issue by zsmanjot** [StackStorm/st2#6281]
Hi Team,

We have a scenario where in our environment JIRA could not be directly accessible from ST2 but has to first go through proxy.

But when we configure the proxy settings as per below , it does not help and gives error.

<img width="715" alt="image" src="https://github.com/user-attachments/assets/9ab955d4-0273-44d9-b153-43780adb1407">

`[root@stackstorm3 ~]# st2 run jira.create_issue summary="TEST" project="OPS" type="ops-sopframework"
.
id: 66c8881a97a284d989cfbfb2
action.ref: jira.create_issue
context.user: st2admin
parameters:
  project: OPS
  summary: TEST
  type: ops-sopframework
status: failed
start_timestamp: Fri, 23 Aug 2024 13:01:14 UTC
end_timestamp: Fri, 23 Aug 2024 13:01:15 UTC
result:
  exit_code: 1
  result: None
  stderr: "/opt/stackstorm/virtualenvs/jira/lib/python3.8/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cops-bc-proxy1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/opt/stackstorm/virtualenvs/jira/lib/python3.8/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cops-bc-proxy1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 395, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 214, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/jira/actions/create_issue.py", line 26, in run
    issue = self._client.create_issue(fields=data)
  File "/opt/stackstorm/virtualenvs/jira/lib/python3.8/site-packages/jira/client.py", line 1858, in create_issue
    r = self._session.post(url, data=json.dumps(data))
  File "/opt/stackstorm/virtualenvs/jira/lib/python3.8/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/opt/stackstorm/virtualenvs/jira/lib/python3.8/site-packages/jira/resilientsession.py", line 247, in request
    elif raise_on_error(response, **processed_kwargs):
  File "/opt/stackstorm/virtualenvs/jira/lib/python3.8/site-packages/jira/resilientsession.py", line 72, in raise_on_error
    raise JIRAError(
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://jira.**********.com/rest/api/2/issue
\t
\tresponse headers = {'Date': 'Fri, 23 Aug 2024 13:01:15 GMT', xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
\tresponse text = {"errorMessages":[],"errors":{"summary":"Field 'summary' cannot be set. It is not on the appropriate screen, or unknown."}}
"
  stdout: ''
[root@stackstorm3 ~]#`

Could anyone help here?
Normal curl does work.

**Comment by fdrab** [comment]
You probably need to clone the Jira pack and update the JiraBaseAction in lib folder to accept proxies. The Jira library that this pack uses does allow for that, it's just not done in the pack (for some reason).

**Comment by zsmanjot** [comment]
Hi @fdrab 

Yes i did those changes as well but no luck.. defined proxy to be used but still the same error

**Comment by nzlosh** [comment]
It appears to me that you're asking for proxy support in the jira pack, not StackStorm.  If this is the case you, should open an issue against the jira pack for assistance https://github.com/StackStorm-Exchange/stackstorm-jira as the pack installation behind a proxy documentation is specific to st2 core and not the jira pack.

**Comment by zsmanjot** [comment]
Noted @nzlosh But even on our end we tried making some changes in base package of JIRA to include proxy configuration but it appears stackstorm is not taking them . 
For example:
In /opt/stackstorm/packs/jira/config.schema.yaml: Did the following addition:
<img width="620" alt="image" src="https://github.com/user-attachments/assets/de7a088b-f1ed-430e-8f39-6b3fc9f30575">

In /opt/stackstorm/packs/jira/actions/lib/base.py:
<img width="682" alt="image" src="https://github.com/user-attachments/assets/c9528c7a-d7a5-42e7-87bc-b2f60a3091ff">

If you say i might open an issue under https://github.com/StackStorm-Exchange/stackstorm-jira

**Comment by zsmanjot** [comment]
Thanks @floatingstatic 

I have opened an issue under stackstorm-jira/issues --> https://github.com/StackStorm-Exchange/stackstorm-jira/issues/81

I have mentioned all the settings that we have done in order to communicate with JIRA from ST2 box.

**Comment by nzlosh** [comment]
Thanks for stepping in @floatingstatic.  :+1: Closed this issue since it is now tracked at the jira pack repository.
